web/src/main/java/org/springframework/security/web/context/HttpSessionSecurityContextRepository.java
I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.
I've added this log as when you have some session management issues (I had the case with Jetty), so you can check that sessions are the same between requests.
=> Trivial logging fix in saveContext method in HttpSessionSecurityContextRepository

config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java
The HttpSecurity#headers() Javadoc did not accurately reflect changes made to the
HeadersConfigurer in Spring Security 4.x.
=> SEC-3159: Fix Javadoc

web/src/main/java/org/springframework/security/web/context/SaveContextOnUpdateOrErrorResponseWrapper.java, web/src/main/java/org/springframework/security/web/header/HeaderWriterFilter.java, web/src/main/java/org/springframework/security/web/header/writers/CacheControlHeadersWriter.java, web/src/main/java/org/springframework/security/web/util/OnCommittedResponseWrapper.java, web/src/test/java/org/springframework/security/web/header/HeaderWriterFilterTests.java, web/src/test/java/org/springframework/security/web/header/writers/CacheControlHeadersWriterTests.java, web/src/test/java/org/springframework/security/web/util/OnCommittedResponseWrapperTests.java
Previously Spring Security always wrote cache control headers and relied on
the application to override the values. This can cause problems with cache
control. For example, applications may only set cache control if the header
is not already set. Additionally, setting of Cache-Control should disable
writing of Pragma.
This commit delays writing headers until just before the response is
committed and only writes the Cache Control headers if they do not exist.
Fixes gh-2953
=> Cache Control only written if not set

docs/manual/src/docs/asciidoc/index.adoc
Includes a reference to the https://report-uri.io/ service in the CSP and HPKP documentation.
Fixes gh-3772
=> Includes reference to https://report-uri.io/ in CSP and HPKP docs

test/src/main/java/org/springframework/security/test/web/servlet/response/SecurityMockMvcResultMatchers.java, test/src/test/java/org/springframework/security/test/web/servlet/response/SecurityMockWithAuthoritiesMvcResultMatchersTests.java
Support Collection<? extends GrantedAuthority> for SecurityMockMvcResultMatchers.withAuthorities
See gh-3791
=> SecurityMockMvcResultMatchers.withAuthorities(Collection<? extends GrantedAuthority>)

config/src/main/java/org/springframework/security/config/annotation/web/socket/AbstractSecurityWebSocketMessageBrokerConfigurer.java
I noticed there is a small typo. However, I'm not sure the fix is correct like this.
=> Fix typo in setMessageExpessionHandler

config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java
Removed error provoking extra logout() from example code in documentation for HttpSecurity.java
=> Update HttpSecurity.java logout() sample code

crypto/src/main/java/org/springframework/security/crypto/encrypt/BouncyCastleAesBytesEncryptor.java, crypto/src/main/java/org/springframework/security/crypto/encrypt/BouncyCastleAesCbcBytesEncryptor.java, crypto/src/main/java/org/springframework/security/crypto/encrypt/BouncyCastleAesGcmBytesEncryptor.java, crypto/src/test/java/org/springframework/security/crypto/encrypt/BouncyCastleAesBytesEncryptorEquivalencyTest.java, crypto/src/test/java/org/springframework/security/crypto/encrypt/BouncyCastleAesBytesEncryptorTest.java
Fixes #2917 
I ran a very cursory JMH benchmark on encrypt/decrypt of a 1 MB byte array of random bytes and this implementation is 3x slower than JCE, and for a 1 kB byte array this is 4.7x slower.
=> BouncyCastle implementation of "AES/CBC/PKCS5Padding"

crypto/crypto.gradle, crypto/src/test/java/org/springframework/security/crypto/encrypt/BouncyCastleAesBytesEncryptorEquivalencyTest.java, crypto/src/test/java/org/springframework/security/crypto/encrypt/CryptoAssumptions.java, crypto/src/test/java/org/springframework/security/crypto/encrypt/EncryptorsTests.java
Apply assumptions directly to test methods instead of checking for key
length in crypto.gradle.
=> Refactor test assumptions about JCE to common class.

web/src/main/java/org/springframework/security/web/header/writers/HpkpHeaderWriter.java
#3792 New pull request after confirming patch works.
=> Fix javadoc code formatting.

web/src/main/java/org/springframework/security/web/header/HeaderWriterFilter.java
HeaderWriterFilter is there for adding headers to the response, not the request.
=> HeaderWriterFilter: Fix Javadoc.

crypto/src/main/java/org/springframework/security/crypto/encrypt/BouncyCastleAesBytesEncryptor.java, crypto/src/main/java/org/springframework/security/crypto/encrypt/BouncyCastleAesCbcBytesEncryptor.java, crypto/src/main/java/org/springframework/security/crypto/encrypt/BouncyCastleAesGcmBytesEncryptor.java, crypto/src/test/java/org/springframework/security/crypto/encrypt/BouncyCastleAesBytesEncryptorEquivalencyTest.java
- [] I have signed the CLA
This forces us to avoid using CipherOutputStream, and instead use the
BlockCiphers directly. As an extra measure for correctness, test the
equivalence of the BC implementations against data sizes from 1 to 2048
bytes.
Fixes gh-2917
=> Only use methods present in Bouncy Castle 1.47.

config/src/test/groovy/org/springframework/security/config/http/InterceptUrlConfigTests.groovy, config/src/test/java/org/springframework/security/config/annotation/web/configurers/AuthorizeRequestsTests.java, web/src/main/java/org/springframework/security/web/access/expression/AbstractVariableEvaluationContextPostProcessor.java, web/src/main/java/org/springframework/security/web/access/expression/DelegatingEvaluationContext.java, web/src/main/java/org/springframework/security/web/access/expression/ExpressionBasedFilterInvocationSecurityMetadataSource.java, web/src/main/java/org/springframework/security/web/util/matcher/AntPathRequestMatcher.java, web/src/test/java/org/springframework/security/web/access/expression/AbstractVariableEvaluationContextPostProcessorTests.java, web/src/test/java/org/springframework/security/web/access/expression/DelegatingEvaluationContextTests.java, web/src/test/java/org/springframework/security/web/util/matcher/AntPathRequestMatcherTests.java
Perviously there were issues with case insenstive patterns and URI
variables that contained upper case characters. For example, the pattern
"/user/{userId}" could not resolve the variable #userId Instead it was
forced to lowercase and #userid was used.
Now if the pattern is case insensitive then so is the variable. This means
that #userId will work as will #userid.
Fixes gh-3786
=> Support Camel case URI variables

config/src/main/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/ExpressionUrlAuthorizationConfigurer.java, config/src/test/groovy/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfigurationTests.groovy, config/src/test/groovy/org/springframework/security/config/annotation/method/configuration/MethodSecurityService.groovy, config/src/test/groovy/org/springframework/security/config/annotation/method/configuration/MethodSecurityServiceImpl.groovy, config/src/test/java/org/springframework/security/config/annotation/web/configurers/AuthorizeRequestsTests.java
Migrated from [SEC-3189](https://jira.spring.io/browse/SEC-3189?redirect=false)
=> SEC-3189: By default use any RoleHierarchy Bean for SecurityExpressionHandler

config/src/main/java/org/springframework/security/config/annotation/web/socket/AbstractSecurityWebSocketMessageBrokerConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/web/socket/AbstractSecurityWebSocketMessageBrokerConfigurerTests.java
Previously the SecurityExpressionHandler for message based configuration
did not have a beanResolver set.
This commit post processes the default message SecurityExpressionHandler
to ensure the beanResolver is set.
Fixes gh-3797
=> Message SecurityExpressionHandler is post processed

web/src/main/java/org/springframework/security/web/util/OnCommittedResponseWrapper.java, web/src/test/java/org/springframework/security/web/util/OnCommittedResponseWrapperTests.java
OnCommittedResponseWrapper trackContentLength will throw a
NullPointerException when the content length passed in is null.
This commit properly tracks the null value as a length of 4.
Fixes gh-3823
=> Fix NPE in OnCommittedResponseWrapper trackContentLength

test/src/main/java/org/springframework/security/test/web/servlet/response/SecurityMockMvcResultMatchers.java, test/src/test/java/org/springframework/security/test/web/servlet/response/Gh3409Tests.java, test/src/test/java/org/springframework/security/test/web/servlet/response/SecurityMockMvcResultMatchersTests.java
Previously if unauthenticated() experienced an AnonymousAuthenticationToken
it would not match.
This commit ensures that if the user is anonymous (not just null)
unauthenticated() works.
Fixes gh-3409
=> Fix unauthenitcated() and AnonymousAuthenticationToken

docs/manual/src/docs/asciidoc/index.adoc
In the documentation, there was a reference to a class called CsrfTokenResolver
and it should CsrfTokenArgumentResolver
Fixes #3890
=> Fix wrong class name reference in the docs

docs/manual/src/docs/asciidoc/index.adoc
Add a suggestion to retrieve a fresh csrf token right before the
form submission in order to avoid problems with invalid csrf tokens
due session timeouts.
Fixes gh-3925
=> Improve csrf login caveats

CONTRIBUTING.md
Direct changes to XSD schemas will be overwritten by the build, it is necessary that the developer updates the RELAX NG schema instead.
See discussion on commit e297706e8bfda38117a99fd06dace74c5a8cc5f1.
=> Document schema changes in CONTRIBUTING.md

config/src/test/java/org/springframework/security/config/annotation/web/configurers/HttpSecurityRequestMatchersTests.java, web/src/main/java/org/springframework/security/web/FilterInvocation.java
To support MvcRequestMatcher DummyRequest needs to support
`getCharacterEncoding()` and `getAttribute(String)`. Otherwise the following exception is thrown:
```
java.lang.UnsupportedOperationException: public abstract java.lang.Object javax.servlet.ServletRequest.getAttribute(java.lang.String) is not supported
at org.springframework.security.web.UnsupportedOperationExceptionInvocationHandler.invoke(FilterInvocation.java:227)
at com.sun.proxy.$Proxy66.getAttribute(Unknown Source)
at javax.servlet.ServletRequestWrapper.getAttribute(ServletRequestWrapper.java:120)
at javax.servlet.ServletRequestWrapper.getAttribute(ServletRequestWrapper.java:120)
at org.springframework.web.util.UrlPathHelper.getContextPath(UrlPathHelper.java:323)
at …
```
=> DummyRequest supports methods for MvcRequestMatcher

config/src/main/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.java, config/src/test/java/org/springframework/security/config/method/configuration/Gh4020GlobalMethodSecurityConfigurationTests.java
Previously if a Bean for GlobalMethodSecurityConfiguration's
defaultMethodExpressionHandler was found on a Configuration that also
@Autowired a Bean that enabled method security, the Bean that was
@Autowired would not have security enabled.
This fixes the issue by delaying the lookup of Beans populated on
GlobalMethodSecurityConfiguration's defaultMethodExpressionHandler.
Fixes gh-4020
=> Fix defaultMethodExpressionHandler autowiring

config/src/main/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.java
Fixes a misleading message that warns about PermissionEvaluator when MethodSecurityExpressionHandler should be mentioned instead.
Fixes #3402
=> Fix typo in autowiring warning

web/src/main/java/org/springframework/security/web/csrf/CookieCsrfTokenRepository.java
This PR simply fixes typo in Javadoc.
=> Fix typo in Javadoc

crypto/src/main/java/org/springframework/security/crypto/bcrypt/BCrypt.java, crypto/src/test/java/org/springframework/security/crypto/bcrypt/BCryptTests.java
This PR introduces a simple null check within BCrypt.hashpw(String password, String salt) to properly handle null-value salts in a consistent way and prevent NPEs. 
Fixes #4147
=> Prevent BCrypt NPE

web/src/main/java/org/springframework/security/web/savedrequest/HttpSessionRequestCache.java, web/src/test/java/org/springframework/security/web/savedrequest/HttpSessionRequestCacheTests.java
This commit allows to customize the session attribute name. Default is
SPRING_SECURITY_SAVED_REQUEST.
Fixes gh-4130
=> Add HttpSessionRequestCache sessionAttrName property

config/src/main/java/org/springframework/security/config/http/FilterInvocationSecurityMetadataSourceParser.java
Obvious Fix:
The class `ExpressionFilterInvocationSecurityMetadataSource` does not exist.
The `ExpressionBasedFilterInvocationSecurityMetadataSource` should be mentioned instead.
=> Fix class name in comment

docs/manual/src/docs/asciidoc/index.adoc
"... after the use has authenticated ..." -> "... after the user has authenticated"
=> Fix index.adoc typo

core/src/main/java/org/springframework/security/core/context/SecurityContextHolder.java
Refactor class `SecurityContextHolder` to use utility method `StringUtils#hasText(String)` to handle blank text.
=> Update SecurityContextHolder.java - Use StringUtils#hasText(String)

core/src/test/java/org/springframework/security/access/hierarchicalroles/HierarchicalRolesTestHelper.java, docs/manual/src/docs/asciidoc/_includes/faq.adoc, docs/manual/src/docs/asciidoc/index.adoc
Fixes gh-4162.
Please, see GitHub issue #4162 for the motivation.
=> Refer to SimpleGrantedAuthority instead of GrantedAuthorityImpl

config/src/main/java/org/springframework/security/config/annotation/web/configurers/FormLoginConfigurer.java
Typo. Replace `he` by `the` in Javadoc.
=> Fix JavaDoc for FormLoginConfigurer

web/src/main/java/org/springframework/security/web/session/SessionInformationExpiredStrategy.java
Removed Unicode character from a parameter name that caused compilation errors on Windows.
Fixes #4428
=> Removed Unicode Character from Parameter Name

config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java
Javadoc for `HttpSecurity.authorizeRequests` uses consistently username `admin` in code sample and javadoc text.
Fix for #4620
=> Fixed typo in HttpSecurity.authorizeRequests javadoc

crypto/src/main/java/org/springframework/security/crypto/factory/PasswordEncoderFactories.java
See gh-4666
Probably, Javadoc is wrong. In the current implementation, the `BCryptPasswordEncoder` is used for encoding a password. 
Is wrong implementation?
=> Fix Javadoc of PasswordEncoderFactories#createDelegatingPasswordEncoder

docs/manual/src/docs/asciidoc/index.adoc
Fixes #4420 by correcting a small typo in the reference docs.
`KeyGenerators` class is a Factory that can return a `BytesKeyGenerator` or `StringKeyGenerator`.
The example code in the docs calls `KeyGenerators.secureRandom()` which returns a `BytesKeyGenerator` not a `KeyGenerator`
=> Fix Typo in Reference Docs

core/src/main/java/org/springframework/security/jackson2/UnmodifiableSetDeserializer.java, core/src/main/java/org/springframework/security/jackson2/UsernamePasswordAuthenticationTokenDeserializer.java, core/src/test/java/org/springframework/security/jackson2/UsernamePasswordAuthenticationTokenMixinTests.java, web/src/main/java/org/springframework/security/web/jackson2/PreAuthenticatedAuthenticationTokenDeserializer.java
The pull-request addresses 2 issues:
- Incorrect use of the Jackson API, by using `JsonNode.toString()` to serialize a sub-tree before deserializing it using an `ObjectMapper`.
- Forced deserialization of the principal as `User`.
This fixes #4252.
=> Improved Jackson support for Spring Session

config/src/test/groovy/org/springframework/security/config/annotation/web/configurers/ExpressionUrlAuthorizationsTests.groovy, core/src/main/java/org/springframework/security/access/expression/AbstractSecurityExpressionHandler.java
Configure WebSecurity's default WebSecurityExpressionHandler to use the ApplicationContext's PermissionEvaluator and RoleHierarchy by default, the same way that GlobalMethodSecurityConfiguration does for its default MethodSecurityExpressionHandler.
Issue gh-4077
=> Configure permissionEvaluator and roleHierarchy by default

config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/HttpBasicConfigurer.java, config/src/main/java/org/springframework/security/config/http/AuthenticationConfigBuilder.java, config/src/main/resources/org/springframework/security/config/spring-security-4.2.rnc, config/src/main/resources/org/springframework/security/config/spring-security-4.2.xsd, config/src/test/java/org/springframework/security/config/http/NamespaceHttpBasicTests.java
Change a default realm name of Basic Authentication for XML namespace to 'Realm'.
Fixes gh-4220
=> Change a default realm name to 'Realm'

core/src/main/java/org/springframework/security/core/session/SessionRegistryImpl.java
As of now spring security allows single session per user which is working out of box for single node application. This feature won't work in clustered environment as each node has it's separate session count in SessionRegistry. In order to overcome this limitation we can store principals, and sessionIds map in a data grid(synchronized Cache).
As principals and sessionIds are set in class itself so one can't share user session count across nodes(Cluster). Using constructor for setting principals and sessionIds we can pass Cache map to constructor which can enable common session count in cluster otherwise user would be allowed to logged in with multiple sessions.
=> Enabling spring security to handle single session per user in clustered environment.

core/src/main/java/org/springframework/security/jackson2/UnmodifiableSetDeserializer.java, core/src/main/java/org/springframework/security/jackson2/UsernamePasswordAuthenticationTokenDeserializer.java, core/src/test/java/org/springframework/security/jackson2/UsernamePasswordAuthenticationTokenMixinTests.java, web/src/main/java/org/springframework/security/web/jackson2/PreAuthenticatedAuthenticationTokenDeserializer.java
This is #4253 reported on `4.2.x` to fix #4252 on that branch as well, for people that won't be able to upgrade to `5.0` right away.
=> Replace improper JsonNode.toString() in Jackson support

docs/guides/spring-security-docs-guides.gradle
This PR removes duplicate `eruby` option in `asciidoctor` task.
=> Remove duplicate eruby option in asciidoctor task

config/src/main/java/org/springframework/security/config/oauth2/client/CommonOAuth2Provider.java, config/src/test/java/org/springframework/security/config/http/NamespaceHttpBasicTests.java, config/src/test/java/org/springframework/security/config/oauth2/client/CommonOAuth2ProviderTests.java, core/src/main/java/org/springframework/security/core/AuthenticatedPrincipal.java, core/src/test/java/org/springframework/security/core/userdetails/UserDetailsTest.java, samples/boot/oauth2login/src/integration-test/java/org/springframework/security/samples/OAuth2LoginApplicationTests.java, web/src/test/java/org/springframework/security/web/csrf/CookieCsrfTokenRepositoryTests.java
This PR fixes wrong copyright start years.
See gh-4655
See gh-4725
=> Fix copyright start years

CONTRIBUTING.md
When trying to install the requirements needed to start contributing to the project, I realized that the last version of Groovy Eclipse plugin isn't available at Eclipse Marketplace. So, to install newer versions I propose the tip added to `CONTRIBUTING.md` file to help other developers.
- Add a tip on `CONTRIBUTING.md` file within the section __Importing into IDE__
=> Add tip to install Groovy Eclipse plugin on newer STS versions

crypto/src/main/java/org/springframework/security/crypto/password/DelegatingPasswordEncoder.java
=> Fix: Typo in DelegatingPasswordEncoder's Javadoc

core/spring-security-core.gradle
Instead of copying classes to the compile output, we now add them directly to the JAR. This allows JavaCompile to be cached, since there are no overlapping outputs anymore.
=> Allow spring-security-core:compileJava to be cached

build.gradle
When using Gradle's build cache (`--build-cache`) the `Test` tasks are not loaded from cache because of a JaCoCo issue with caching:
https://discuss.gradle.org/t/do-not-cache-if-condition-matched-jacoco-agent-configured-with-append-true-satisfied/23504
This PR applies the recommended workaround to disable JaCoCo when a report is not explicitly requested.
=> Enable caching for Test tasks

docs/manual/src/docs/asciidoc/index.adoc
1) for more on information on how the Spring Security `AuthenticationManager` is -> for more information on how the Spring Security `AuthenticationManager` is
2) all the sames things -> all the same things
=> fix typo in documentation: index.adoc

gradle/dependency-management.gradle
This upgrades Nimbus OAuth + OIDC SDK from `5.54` to `5.56`.
`5.55` fixes compatibility issue with Nimbus JOSE + JWT `5.5` onward, while `5.56` brings a number of improvements including removal of dependency on Apache Commons Lang and Apache Commons Collections 4.
This should go in `master` and `5.0.x`.
=> Upgrade Nimbus OAuth + OIDC SDK to 5.56

cas/src/test/java/org/springframework/security/cas/web/CasAuthenticationFilterTests.java, core/src/main/java/org/springframework/security/authentication/TestingAuthenticationToken.java, core/src/test/java/org/springframework/security/authentication/TestingAuthenticationTokenTests.java
In other extensions of `AbstractAuthenticationToken`, the constructors
that include `authorities` call `setAuthenticated(true)`. This includes
`PreAuthenticated`-, `UsernamePassword`-, and
`RememberMeAuthenticationToken`.
This change brings `TestingAuthenticationToken` in line with that
convention.
Note that this was done once already to one of the constructors
(ee13be4) in `TestingAuthenticationToken` that takes an arity of
`authorities`. It was not propagated to the constructor that takes a
collection, which is what this commit remedies.
Fixes: gh-5073
=> Authorities authenticate TestingAuthenticationToken

.editorconfig
This PR adds several improvements to EditorConfig file:
- separated properties by file types
- apply common properties (i.e. EOL, trailing whitespace, final newline, line length) to all file types
- apply others (i.e. indentation, charset) for specific file type
- added `continuation_indent_size` to have continuous indentation work as expected in IntelliJ (see [spring-projects/spring-boot#8497 (comment)](https://github.com/spring-projects/spring-boot/issues/8497#issuecomment-294172853))
- added `max_line_length` with value of 120 to match [contribution guidelines](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#mind-the-whitespace)
=> Improve EditorConfig file

test/src/main/java/org/springframework/security/test/context/support/ReactorContextTestExecutionListener.java, test/src/test/java/org/springframework/security/test/context/support/ReactorContextTestExecutionListenerTests.java, test/src/test/java/org/springframework/security/test/web/reactive/server/AbstractMockServerConfigurersTests.java, test/src/test/java/org/springframework/security/test/web/reactive/server/SecurityMockServerConfigurersAnnotatedTests.java
During some playing around testing of an application, especially during verification of WebSocket API, I have found that `@WithMockUser` annotation does not work as it expected.
Since we do not have something similar to `TestWebClient` but for verification of the WebSocket API, we need to use `WebSocketClient` (for now). It means that we need to run spring boot app with `@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)` configuration. In turn, it means that execution of the method annotated with, for instance, JUnit's annotation `@Test` will be in a slightly different thread than the execution of `WebSocketHandler`, which will be, for example for Netty, in `reactor-http-nio-blah-blah-blah`.
Since `TestSecurityContextHolder` is based on thread local, it means …
=> ReactorContextTestExecutionListener should obtain SecurityContext on TestExecutionListenerThread

web/src/main/java/org/springframework/security/web/firewall/StrictHttpFirewall.java
4.2.x branch has been fixed in 1159c9f302080f7e91c8a806c957a1c63f5882e4 but master hasn’t.
See #5006
=> Fix @since for StrictHttpFirewall

web/src/main/java/org/springframework/security/web/util/matcher/AntPathRequestMatcher.java
When a request fails to match `AntPathRequestMatcher.matches` logs the actual and expected requests. The quoted expected request is missing the trailing quote. This PR fixes that.
=> Close quoted expected path in log when matching

docs/manual/src/docs/asciidoc/_includes/preface/java-configuration.adoc
This paragraph was originally there to explain why Spring Security was
moving from the old default URLs and parameters to new ones.
Now that the defaults are the same in XML and well as Java Config, the
explanation is now no longer relevant.
Fixes: gh-5242
=> Remove Default URLs and Parameters Commentary

core/src/main/java/org/springframework/security/core/userdetails/jdbc/JdbcDaoImpl.java
I've fixed an incorrect explanation on the `JdbcDaoImpl`.
Probably, we should be mapped back to same column **positions** rather than same column names as in the default query when a custom query will be use.
=> Fix incorrect explanation for customizing query on JdbcDaoImpl

ldap/src/main/java/org/springframework/security/ldap/authentication/ad/ActiveDirectoryLdapAuthenticationProvider.java, ldap/src/test/java/org/springframework/security/ldap/authentication/ad/ActiveDirectoryLdapAuthenticationProviderTests.java
Allows the username only (without domain) to be used in custom search filter like "sAMAccountName={1}",
in eg. situations where the userPrincipalName has a different suffix than domain.
Thanks to contributors in issue.
fixes gh-2448
(cherry picked from commit 8d717c62afd5d98b0aba467035389d3011434b51)
=> Pass username as second parameter for search filter.

docs/guides/spring-security-docs-guides.gradle
Build this project shows the following warning:
```
Configure project :spring-security-docs-guides 
Attributes found in options. Existing attributes will be replaced due to assignment. Please use 'attributes' method instead as current behaviour will be removed in future
```
This PR fixes the warning by applying the suggested way in the warning message.
See https://github.com/asciidoctor/asciidoctor-gradle-plugin#options-attributes
=> Fix 'attributes' deprecation warning in spring-security-docs-guides

web/src/main/java/org/springframework/security/web/authentication/ui/DefaultLoginPageGeneratingFilter.java, web/src/test/java/org/springframework/security/web/authentication/DefaultLoginPageGeneratingFilterTests.java
Such as
view source:
Resubmit and including the content of the unit test.
=> DefaultLoginPageGeneratingFilter should calculate ContentLength using UTF-8

CONTRIBUTING.md, config/src/test/java/org/springframework/security/config/annotation/authentication/AuthenticationManagerBuilderTests.java, config/src/test/java/org/springframework/security/config/annotation/issue50/Issue50Tests.java, config/src/test/java/org/springframework/security/config/annotation/web/builders/HttpConfigurationTests.java, docs/guides/spring-security-docs-guides.gradle, docs/guides/src/docs/asciidoc/Guardfile
This PR changes "SpringSource" to "spring-projects" as it looks a previous one.
=> Use spring-projects for organization in GitHub URLs

crypto/src/main/java/org/springframework/security/crypto/encrypt/BouncyCastleAesCbcBytesEncryptor.java, crypto/src/main/java/org/springframework/security/crypto/encrypt/BouncyCastleAesGcmBytesEncryptor.java, crypto/src/main/java/org/springframework/security/crypto/factory/PasswordEncoderFactories.java, crypto/src/test/java/org/springframework/security/crypto/codec/Base64Tests.java, crypto/src/test/java/org/springframework/security/crypto/password/LdapShaPasswordEncoderTests.java, crypto/src/test/java/org/springframework/security/crypto/password/Md4PasswordEncoderTests.java, crypto/src/test/java/org/springframework/security/crypto/password/MessageDigestPasswordEncoderTests.java, crypto/src/test/java/org/springframework/security/crypto/password/StandardPasswordEncoderTests.java
This PR suppresses deprecation warnings in `spring-security-crypto`.
=> Suppress deprecation warnings in spring-security-crypto

web/src/main/java/org/springframework/security/web/server/csrf/CookieServerCsrfTokenRepository.java, web/src/test/java/org/springframework/security/web/server/csrf/CookieServerCsrfTokenRepositoryTests.java
The CookieServerCsrfTokenRepository fails with an IllegalArgumentException
when a cookie is present but the value is null or empty.
Fixes gh-5315
=> CookieServerCsrfTokenRepository fails when cookie is null/empty

docs/manual/src/docs/asciidoc/_includes/appendix/database-schema.adoc, docs/manual/src/docs/asciidoc/_includes/web/csrf.adoc
This pull request fixes two minor documentation typos, fixing #5204 and #4792.
=> Documentation typo fixes

config/src/test/java/org/springframework/security/config/MockEventListener.java
`MockEventListener` looks added since 5.0.2.RELEASE although it can be removed as it's a class for internal tests.
See 49e5b15ce28440fc8b9135217ba0c435a25ff543
=> Fix @since for MockEventListener

web/src/main/java/org/springframework/security/web/server/authentication/HttpStatusServerEntryPoint.java, web/src/test/java/org/springframework/security/web/server/authentication/HttpStatusServerEntryPointTests.java
An `HttpStatusServerEntryPoint` is missing on the reactive side - essentially the reactive equivalent of HttpStatusEntryPoint.
Fixes gh-5082
=> Add HttpStatusServerEntryPoint

web/src/main/java/org/springframework/security/web/server/authentication/logout/HttpStatusReturningServerLogoutSuccessHandler.java, web/src/test/java/org/springframework/security/web/server/authentication/logout/HttpStatusReturningServerLogoutSuccessHandlerTests.java
An HttpStatusReturningServerLogoutSuccessHandler is missing on the reactive side - essentially the reactive equivalent of HttpStatusReturningLogoutSuccessHandler.
Fixes gh-5081
=> Add HttpStatusReturningServerLogoutSuccessHandler

config/spring-security-config.gradle, config/src/main/java/org/springframework/security/config/oauth2/client/OidcConfigurationProvider.java, config/src/test/java/org/springframework/security/config/oauth2/client/OidcConfigurationProviderTests.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistration.java
With this user's can now create a ClientRegistration using something like this:
```java
@Bean
ReactiveClientRegistrationRepository clientRegistrationRepository() {
ClientRegistration registration = OidcConfigurationProvider.issuer("https://accounts.google.com")
.clientId("client-id")
.clientSecret("client-secret")
.build();
return new InMemoryReactiveClientRegistrationRepository(registration);
}
```
Fixes: gh-4413
=> Add ClientRegistration from OpenID Connect Discovery

web/src/main/java/org/springframework/security/web/server/authentication/logout/DelegatingServerLogoutHandler.java, web/src/test/java/org/springframework/security/web/server/authentication/logout/DelegatingServerLogoutHandlerTests.java
Create a `DelegatingServerLogoutHandler` which delegates to a group of `ServerLogoutHandler` implementations.
Fixes gh-4839
=> DelegatingServerLogoutHandler

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderJwkSupport.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderJwkSupportTests.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoderTests.java
This commit captures and remaps the exception that Nimbus throws
when a PlainJWT is presented to it.
While the surrounding classes are likely only used today by the
oauth2Login flow, since they are public, we'll patch them at this
point for anyone who may be using them directly.
Fixes: gh-5457
=> Close Nimbus Information Leak

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java
This PR polishes Javadoc in `ServerHttpSecurity`, focused on `@return`.
=> Polish Javadoc in ServerHttpSecurity

config/src/main/java/org/springframework/security/config/annotation/web/configuration/EnableWebSecurity.java
The actual method signature look this this:
```java
protected void configure(AuthenticationManagerBuilder auth) throws Exception
```
This PR aims at aligning the javadoc for this annotation with the actual method signature.
=> Fix a missing "throws Exception" for @EnableWebSecurity

docs/manual/src/docs/asciidoc/_includes/data/index.adoc
This PR adds a mention on `org.springframework.security:spring-security-data` dependency for Spring Data in the reference doc.
Closes #5556
=> Mention spring-security-data dependency for Spring Data in doc

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/AuthorizationRequestRepository.java
This PR adds `@Deprecation` on `AuthorizationRequestRepository.removeAuthorizationRequest() ` as `@deprecated` tag was added in its Javadoc but `@Deprecation` annotation looks missed in 2c1c2c78c363978fce4297b5de8e929bb8344e52.
=> Add @Deprecation on removeAuthorizationRequest()

docs/manual/src/docs/asciidoc/_includes/web/websocket.adoc
Changeset 46bb855 (#4094) removed websocket chat
sample in favor of spring-session one. This commit
updates spring-security documentation link to
point to the up-to-date sample location
=> Fix the broken link in the WebSocket documentation

config/src/main/java/org/springframework/security/config/annotation/web/configurers/HeadersConfigurer.java, config/src/main/java/org/springframework/security/config/http/HeadersBeanDefinitionParser.java, config/src/main/resources/org/springframework/security/config/spring-security-5.1.rnc, config/src/main/resources/org/springframework/security/config/spring-security-5.1.xsd, config/src/test/groovy/org/springframework/security/config/annotation/web/configurers/HeadersConfigurerTests.groovy, docs/manual/src/docs/asciidoc/_includes/appendix/namespace.adoc, docs/manual/src/docs/asciidoc/_includes/web/headers.adoc, web/src/main/java/org/springframework/security/web/header/writers/FeaturePolicyHeaderWriter.java, web/src/test/java/org/springframework/security/web/header/writers/FeaturePolicyHeaderWriterTests.java
See the following resources:
- https://wicg.github.io/feature-policy/
- https://scotthelme.co.uk/a-new-security-header-feature-policy/
- https://developers.google.com/web/updates/2018/06/feature-policy
Although the Feature Policy RFC is not finalized yet, there is already [browser adoption](https://caniuse.com/#search=feature%20policy) and the configuration of `Feature-Policy` header is (similarly to `Content-Security-Policy`) fairly simple and based on a set of directives that we configure as a `String`.
Also note that https://securityheaders.com/ already supports this header in their report.
=> Add support for Feature-Policy security header

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoder.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoderTests.java
This allows a user to customize the Jwt validation steps that
NimbusReactiveJwtDecoder will take for each Jwt.
Fixes: gh-5650
=> Reactive Jwt Validation

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoder.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/ReactiveJwtDecoders.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoderTests.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/ReactiveJwtDecodersTests.java
A reactive static builder for constructing and configuring a
ReactiveJwtDecoder via an issuer that supports the OIDC Provider
Configuration spec.
Fixes: gh-5649
=>  ReactiveJwtDecoder via OIDC Provider Configuration

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2ResourceServerSpecTests.java
This makes requests identified as bearer token requests skip the csrf
filter.
Fixes: gh-5710
=> Reactive Resource Server Csrf Bypass

ldap/src/test/java/org/springframework/security/ldap/authentication/ad/ActiveDirectoryLdapAuthenticationProviderTests.java
This PR polishes `ActiveDirectoryLdapAuthenticationProviderTests.contextEnvironmentPropertiesUsed()` by:
- Adding `fail()` to prevent from going through an unexpected path.
- Asserting that the root cause is an instance of `ClassNotFoundException` as the current code doesn't seem to right unless I'm missing something.
=> Polish ActiveDirectoryLdapAuthenticationProviderTests

Jenkinsfile
This PR leverages newly introduced (see spring-gradle-plugins/spring-build-conventions#35) feature of `spring-build-conventions` that allows forcing of dependency resolution repository. By default, the repository was deduced was deduced from current project version.
Related #5738.
=> Force snapshot repo in snapshot stage build

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2ResourceServerSpecTests.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/access/server/BearerTokenServerAccessDeniedHandler.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/web/access/server/BearerTokenServerAccessDeniedHandlerTests.java, web/src/main/java/org/springframework/security/web/server/authorization/ServerWebExchangeDelegatingServerAccessDeniedHandler.java, web/src/test/java/org/springframework/security/web/server/authorization/ServerWebExchangeDelegatingServerAccessDeniedHandlerTests.java
This introduces an implementation of ServerAccessDeniedHandler that is
compliant with the OAuth 2.0 spec for insufficent_scope errors.
Fixes: gh-5705
=> Reactive insufficient_scope support

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/MappedJwtClaimSetConverter.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderJwkSupport.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/MappedJwtClaimSetConverterTests.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderJwkSupportTests.java
This introduces a hook for users to customize standard Jwt Claim
values in cases where the JWT issuer isn't spec compliant.
Fixes: gh-5223
=> Jwt Claim Mapping

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/HeaderSpecTests.java
Support for Referrer-Policy security header that was originally added in #5703 had required a clumsy construct in config if one wanted to use a non-default policy:
```java
http
.referrerPolicy()
.referrerPolicy(ReferrerPolicy.NO_REFERRER_WHEN_DOWNGRADE);
```
This was improved in 54d07b6 which made the nested `#referrerPolicy` method redundant.
This PR polishes header config by removing the redundant method, and adding a missing unit test.
=> Polish WebFlux Referrer-Policy header config

core/src/main/java/org/springframework/security/access/annotation/Secured.java
This PR adds a missing space in the `Secured.value()` signature.
=> Add a missing space in Secured.value() signature

samples/xml/contacts/src/main/java/sample/contact/AddDeleteContactController.java
The method name for handling `/secure/del.htm` was `handleRequest()`, but it should be `delContact()` (similar to `addContact()`).
=> Fix method name in the Contact sample code

docs/manual/src/docs/asciidoc/_includes/servlet/authorization/secure-objects.adoc
Fixes a minor typo in *secure-objects.adoc* (`in` &rarr; `is`).
=> Fix minor typo in secure-objects.adoc

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2ResourceServerSpecTests.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtReactiveAuthenticationManager.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/ReactiveJwtAuthenticationConverterAdapter.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/ReactiveJwtAuthenticationConverterAdapterTests.java
=> Reactive Jwt Authentication Converter Support

docs/manual/src/docs/asciidoc/_includes/servlet/additional-topics/x509.adoc, web/src/main/java/org/springframework/security/web/authentication/preauth/x509/SubjectDnX509PrincipalExtractor.java
=> Fixing X509 Principal Extractor regex examples #5770

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurer.java
Updated message to include `http.oauth2ResourceServer()`
=> Fixing IllegalStateException message in OAuth2ResourceServerConfigurer

acl/src/main/java/org/springframework/security/acls/jdbc/AclClassIdUtils.java, acl/src/main/java/org/springframework/security/acls/jdbc/BasicLookupStrategy.java, acl/src/main/java/org/springframework/security/acls/jdbc/JdbcAclService.java, acl/src/test/java/org/springframework/security/acls/jdbc/BasicLookupStrategyWithAclClassTypeTests.java, acl/src/test/resources/jdbcMutableAclServiceTestsWithAclClass-context.xml
AclClassIdUtils was added in #4424 but should be made public so can be instantiated via Java Config.
Fixes #4814
=> AclClassIdUtils should be public

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2ResourceServerSpecTests.java
Users can specify a custom access denied handler and authentication
entry point for reactive resource servers.
Fixes: gh-6052
=> Add Reactive Custom Bearer Token Error Handling Support

config/src/main/resources/org/springframework/security/config/spring-security-4.2.rnc, config/src/main/resources/org/springframework/security/config/spring-security-4.2.xsd, config/src/main/resources/org/springframework/security/config/spring-security-5.0.rnc, config/src/main/resources/org/springframework/security/config/spring-security-5.0.xsd, config/src/main/resources/org/springframework/security/config/spring-security-5.1.rnc, config/src/main/resources/org/springframework/security/config/spring-security-5.1.xsd
The documentation of the `token-repository-ref attribute` of the `csrf``  element in the schema has been updated to make clear the default repository is lazy.
Fixes #6037.
I wasn't sure which versions should be targeted, so I chose 4.2, 5.0 and 5.1. If this is incorrect, I'll update this PR.
=> Fix csrf:token-repository-ref XSD documentation

docs/manual/src/docs/asciidoc/_includes/preface/getting-spring-security.adoc
resolves https://github.com/spring-projects/spring-security/issues/6065
Should this possibly be back-ported?
=> Docs: Fix Maven Property example `spring-security.version`

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoder.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoderTests.java
Exposes setClaimSetConverter on NimbusReactiveJwtDecoder, lining it up
with the same support on NimbusJwtDecoder.
Fixes: gh-6015
=> Reactive Jwt Claim Set Converter Support

gradle/dependency-management.gradle
This PR upgrades to neko-htmlunit 2.33 as it doesn't seem to be upgraded fully in 4f80b9d73786bdd04eaaabf8a83c4c9ba92cadce.
=> Upgrade to neko-htmlunit 2.33

docs/guides/src/docs/asciidoc/_hello-includes/secure-the-application-boot.asc, docs/guides/src/docs/asciidoc/helloworld-boot.asc, gradle.properties, samples/boot/helloworld/spring-security-samples-boot-helloworld.gradle, samples/boot/helloworld/src/main/resources/templates/index.html, samples/boot/oauth2login-webflux/spring-security-samples-boot-oauth2login-webflux.gradle, samples/boot/oauth2login/spring-security-samples-boot-oauth2login.gradle, samples/boot/oauth2login/src/main/resources/templates/index.html, samples/boot/oauth2webclient-webflux/spring-security-samples-boot-oauth2webclient-webflux.gradle, samples/boot/oauth2webclient-webflux/src/main/resources/templates/index.html, samples/boot/oauth2webclient/spring-security-samples-boot-oauth2webclient.gradle, samples/boot/oauth2webclient/src/main/resources/templates/index.html
From `https://github.com/spring-projects/spring-security/issues/6082`
=> Updated Spring Boot version from 2.1.0.M4 to 2.1.0.RELEASE

config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/AuthenticationConfiguration.java, config/src/test/java/org/springframework/security/config/annotation/authentication/configuration/AuthenticationConfigurationTests.java
Resolves #3912 . 
I know that @shazin created #4136 as well, however it is now nearly two years old and full of conflicts.
=> #3912 lazyBean method respects @Primary annotation

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/oidc/authentication/OidcAuthorizationCodeAuthenticationProvider.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtDecoder.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtDecoders.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtProcessors.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderJwkSupport.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/JwtProcessorsTest.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderJwkSupportTests.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderTests.java
Introduces a JwtDecoder which takes a raw Nimbus JWTProcessor
configuration.
Fixes: gh-5648
=> Add NimbusJwtDecoder

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/InMemoryClientRegistrationRepository.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/InMemoryReactiveClientRegistrationRepository.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/registration/InMemoryClientRegistrationRepositoryTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/registration/InMemoryReactiveClientRegistrationRepositoryTests.java
Fix inconsistencies for class constuctors:
- InMemoryReactiveClientRegistrationRepository
- InMemoryClientRegistrationRepository
The ConcurrentHashMap is not needed because of [this](https://stackoverflow.com/a/5951203/4796021).
=> Make InMemory*ClientRegistrationRepository Consistent

buildSrc/src/main/groovy/aspectj/AspectJPlugin.groovy
This commit ensures that the method Task.deleteAllActions is not used
Fixes: gh-6128
=> Replace deprecated Gradle Task method in AspectJPlugin.groovy

Jenkinsfile
This commit ensures that jacocoTestReport task is called when running the Sonar stage.
Additionally, a variable is passed instructing Sonar where to find the test result data.
Fixes: gh-6092
=> Enable Code Coverage Reports in Sonar

web/src/main/java/org/springframework/security/web/authentication/logout/CookieClearingLogoutHandler.java, web/src/test/java/org/springframework/security/web/authentication/logout/CookieClearingLogoutHandlerTests.java
Enabled the ability to pass in an array of Cookies to support clearing cookies on a different path other than the default context path
Issue: gh-6078
Issue #6078 
cc: @rwinch
=> CookieClearingLogoutHandler enhancement

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveClientCredentialsTokenResponseClient.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveClientCredentialsTokenResponseClientTests.java
Added the ability to specify a custom WebClient in
WebClientReactiveClientCredentialsTokenResponseClient.
Also added testing to ensure the custom WebClient is not null and is
used.
Fixes: gh-6051
=> Add WebClientReactiveClientCredentialsTokenResponseClient setWebClient

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/DefaultBearerTokenResolver.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/web/DefaultBearerTokenResolverTests.java
According to [RFC 6750 item 3](https://tools.ietf.org/html/rfc6750#page-7), the "WWW-Authenticate" header field uses the framework defined by HTTP/1.1 [RFC2617](https://tools.ietf.org/html/rfc2617#page-3). 
There item 1.2 states that the auth-scheme (i.e, the "Bearer" keyword) is case insensitive.
Hope this helps,
=> According to RFC 2617 #1.2, the "Bearer" keyword should be case-insensitive

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2ResourceServerSpecTests.java
=> OAuth2ResourceServerSpec should allow its ServerAuthenticationConverter to be configurable

web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationFilter.java, web/src/main/java/org/springframework/security/web/server/ServerHttpBasicAuthenticationConverter.java
Updated BasicAuthenticationFilter and ServerHttpBasicAuthenticationConverter to fix #6183
=> Use SpringUtils to check scheme

test/src/main/java/org/springframework/security/test/context/support/ReactorContextTestExecutionListener.java, test/src/test/java/org/springframework/security/test/context/support/ReactorContextTestExecutionListenerTests.java
=> ReactorContextTestExecutionListener should use named hooks

CONTRIBUTING.md
=> Fixed Git SCM book link

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/server/ServerBearerTokenAuthenticationConverter.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/web/server/ServerBearerTokenAuthenticationConverterTests.java
The Authorization header was matched for OAuth2
against the "Bearer" keyword in a case sensitive
fashion.
According to RFC 2617, it should be case insensitive
and some oauth clients (including some earlier
versions of spring-security) expect it so.
This is the reactive counterpart to commit
63f2b6094f59cc9ded6a83ac3def4a1726890a8b .
Fixes gh-6195
=> Accept a case-insensitive "Bearer" keyword

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/ServerHttpSecurityTests.java
Addition of two new methods addFilterBefore and addFilterAfter in
ServerHttpSecurity to allow addition of WebFilter before and after of
specified order
Pull request for github issue #6138
=> Added methods to add filter relatively in ServerHttpSecurity

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveAuthorizationCodeTokenResponseClient.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveAuthorizationCodeTokenResponseClientTests.java
Add WebClientReactiveAuthorizationCodeTokenResponseClient.setWebClient
Fixes #6182
=> Add WebClientReactiveAuthorizationCodeTokenResponseClient.setWebClient

config/src/main/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.java, config/src/test/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfigurationTests.java
RoleVoter Configuration Defaults Prefix Using GrantedAuthorityDefauts
Fixes: gh-4876
=> RoleVoter Configuration Defaults Prefix Using GrantedAuthorityDefauts

core/src/main/java/org/springframework/security/authentication/UserDetailsRepositoryReactiveAuthenticationManager.java, core/src/test/java/org/springframework/security/authentication/UserDetailsRepositoryReactiveAuthenticationManagerTests.java
Integrate UserDetailsChecker into ReactiveAuthenticationManager and
OAuth2 resource server authentication converters.
Fixes gh-6219
=> Add Reactive Support for UserDetailsChecker

config/src/main/java/org/springframework/security/config/authentication/AbstractUserDetailsServiceBeanDefinitionParser.java, config/src/main/java/org/springframework/security/config/http/UserDetailsServiceFactoryBean.java, config/src/test/java/org/springframework/security/config/authentication/JdbcUserServiceBeanDefinitionParserTests.java, core/src/main/java/org/springframework/security/authentication/CachingUserDetailsService.java
- changed default to public constructor in CachingUserDetailsService
Changed based on the comments in this thread https://github.com/spring-projects/spring-security/issues/4139
=> Make CachingUserDetailsService Public

core/src/main/java/org/springframework/security/authorization/AuthenticatedReactiveAuthorizationManager.java, core/src/test/java/org/springframework/security/authorization/AuthenticatedReactiveAuthorizationManagerTests.java
=> Add Anonymous Support to AuthenticatedReactiveAuthorizationManager

config/src/main/java/org/springframework/security/config/web/server/SecurityWebFiltersOrder.java, config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/ServerHttpSecurityTests.java, web/src/main/java/org/springframework/security/web/server/authentication/AnonymousAuthenticationWebFilter.java, web/src/test/java/org/springframework/security/test/web/reactive/server/WebTestClientBuilder.java, web/src/test/java/org/springframework/security/web/server/authentication/AnonymousAuthenticationWebFilterTests.java
1. Created new WebFilter AnonymousAuthenticationWebFilter to
for anonymous authentication
2. Created class AnonymousSpec, method anonymous to configure
anonymous authentication in ServerHttpSecurity
3. Added ANONYMOUS_AUTHENTICATION order after AUTHENTICATION for
anonymous authentication in SecurityWebFiltersOrder
Pull request for github issue:
https://github.com/spring-projects/spring-security/issues/5934
=> Added support for Anonymous Authentication

web/src/main/java/org/springframework/security/web/csrf/CookieCsrfTokenRepository.java, web/src/test/java/org/springframework/security/web/csrf/CookieCsrfTokenRepositoryTests.java
Add cookieDomain to CookieCsrfTokenRepository
Fixes: gh-4315
=> Add cookieDomain to CookieCsrfTokenRepository

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistration.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/registration/ClientRegistrationTests.java
=> Validate Scopes in ClientRegistration.Builder

acl/src/main/java/org/springframework/security/acls/jdbc/JdbcAclService.java, acl/src/main/java/org/springframework/security/acls/jdbc/JdbcMutableAclService.java, acl/src/test/java/org/springframework/security/acls/jdbc/JdbcAclServiceTests.java, acl/src/test/resources/db/sql/test_data_hierarchy.sql
When trying to use Spring Security ACL, I am facing the error: org.postgresql.util.PSQLException: ERROR: operator does not exist: bigint = character varying.
As recommended in the [Spring.io documentation](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#postgresql) i've setup the acl tables in my PostgreSQL database, with column `acl_object_identity.object_id_identity` of type `varchar(36)`.
IMHO the `object_id_identity` in the `jdbcTemplate` method calls MUST always be passed as a character sequence.
This relates to issue:
#5508
=> Fix issue with PostgreSQL: org.postgresql.util.PSQLException

web/src/main/java/org/springframework/security/web/authentication/ui/DefaultLoginPageGeneratingFilter.java
Fix DefaultLoginPageGeneratingFilter Markup
the `</h3>` should be `</h2>`.
=> Fix DefaultLoginPageGeneratingFilter Markup

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/ServerHttpSecurityTests.java
1. Added method realmName in ServerHttpSecurity to allow
specifying realm name.
2. Added test in ServerHttpSecurityTests to check if
specified realm name is returned.
Pull request for issue: https://github.com/spring-projects/spring-security/issues/6270
=> Allow setting realm for Http Basic

core/src/main/java/org/springframework/security/scheduling/DelegatingSecurityContextTaskScheduler.java, core/src/test/java/org/springframework/security/scheduling/DelegatingSecurityContextTaskSchedulerTests.java, docs/manual/src/docs/asciidoc/_includes/servlet/additional-topics/concurrency.adoc
Spring Security provides a TaskScheduler variant or the documentation routes users to expose a TaskScheduler bean rather than exposing a ScheduledExecutorService bean.
New file: DelegatingSecurityContextTaskScheduler which is a DelegatingSecurityContextAsyncTaskExecutor thant implements TaskScheduler.
ExplicitSecurityContextSchedulingTaskSchedulerTests and AbstractSecurityContextTaskSchedulerTests for testing.
=> Add DelegatingSecurityContextTaskScheduler

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationConverter.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtGrantedAuthoritiesConverter.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/ReactiveJwtAuthenticationConverter.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/ReactiveJwtGrantedAuthoritiesConverterAdapter.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtGrantedAuthoritiesConverterTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/ReactiveJwtAuthenticationConverterTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/ReactiveJwtGrantedAuthoritiesConverterAdapterTests.java
Introduce an equivalent to `JwtAuthenticationConverter` on the reactive stack that users can override if they so choose.
Fixes gh-6273
=> Introduce ReactiveJwtAuthenticationConverter

core/src/main/java/org/springframework/security/jackson2/SecurityJackson2Modules.java, web/src/main/java/org/springframework/security/web/jackson2/CookieMixin.java, web/src/main/java/org/springframework/security/web/jackson2/DefaultSavedRequestMixin.java, web/src/main/java/org/springframework/security/web/jackson2/SavedCookieMixin.java, web/src/main/java/org/springframework/security/web/jackson2/WebAuthenticationDetailsMixin.java, web/src/main/java/org/springframework/security/web/jackson2/WebServletJackson2Module.java
=> Add conditionally servlet based support for spring security web jackson module

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, core/src/main/java/org/springframework/security/authorization/AuthorityReactiveAuthorizationManager.java, core/src/test/java/org/springframework/security/authorization/AuthorityReactiveAuthorizationManagerTests.java
Fixes gh-6306
Add hasAnyAuthority() and hasAnyRole() in reactive API
=> Add hasAnyAuthority() and hasAnyRole() in AuthorizeExchangeSpec

core/src/main/java/org/springframework/security/jackson2/SecurityJackson2Modules.java, web/src/main/java/org/springframework/security/web/server/jackson2/DefaultCsrfServerTokenMixin.java, web/src/main/java/org/springframework/security/web/server/jackson2/WebServerJackson2Module.java, web/src/test/java/org/springframework/security/web/server/jackson2/DefaultCsrfServerTokenMixinTests.java
=> Add WebFlux support for spring security web jackson module.

core/src/main/java/org/springframework/security/core/userdetails/jdbc/JdbcDaoImpl.java, core/src/main/java/org/springframework/security/provisioning/JdbcUserDetailsManager.java, core/src/test/java/org/springframework/security/provisioning/JdbcUserDetailsManagerTests.java
Check `ResutSetMetaData` to see if extra columns are present in order to also handle the `UserDetails` attributes: `accountNonExpired`, `accountNonLocked` and `credentialsNonExpired`.
Fixes gh-4399
=> JdbcUserDetailsManager handles extra UserDetails attributes

config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2ClientConfigurerTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/DefaultOAuth2AuthorizationRequestResolverTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/OAuth2AuthorizationRequestRedirectFilterTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/server/DefaultServerOAuth2AuthorizationRequestResolverTests.java, oauth2/oauth2-core/spring-security-oauth2-core.gradle, oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/endpoint/OAuth2AuthorizationRequest.java, oauth2/oauth2-core/src/test/java/org/springframework/security/oauth2/core/endpoint/OAuth2AuthorizationRequestTests.java
=> authorization_uri Supports Query Parameters

config/src/main/resources/org/springframework/security/config/spring-security-3.2.rnc, config/src/main/resources/org/springframework/security/config/spring-security-3.2.xsd, config/src/main/resources/org/springframework/security/config/spring-security-4.0.rnc, config/src/main/resources/org/springframework/security/config/spring-security-4.0.xsd, config/src/main/resources/org/springframework/security/config/spring-security-4.1.rnc, config/src/main/resources/org/springframework/security/config/spring-security-4.1.xsd, config/src/main/resources/org/springframework/security/config/spring-security-4.2.rnc, config/src/main/resources/org/springframework/security/config/spring-security-4.2.xsd, config/src/main/resources/org/springframework/security/config/spring-security-5.0.rnc, config/src/main/resources/org/springframework/security/config/spring-security-5.0.xsd, config/src/main/resources/org/springframework/security/config/spring-security-5.1.rnc, config/src/main/resources/org/springframework/security/config/spring-security-5.1.xsd
1. Fixes type ammount to amount in *.rnc files
2. Regenerates *.xsd files from *.rnc files
Fixes: gh-6325
=> Fixes typo in x,rnc files

web/src/main/java/org/springframework/security/web/csrf/LazyCsrfTokenRepository.java
This PR fixes a typo in the `LazyCsrfTokenRepository` javadoc.
This is an Obvious Fix
=> Fix LazyCsrfTokenRepository Javadoc Typo

config/src/test/java/org/springframework/security/config/InvalidConfigurationTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/registration/ClientRegistrationsTest.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/JwtDecodersTests.java, web/src/test/java/org/springframework/security/web/authentication/rememberme/AbstractRememberMeServicesTests.java
=> Polish tests

core/src/main/java/org/springframework/security/access/expression/method/MethodSecurityEvaluationContext.java, core/src/test/java/org/springframework/security/access/expression/method/MethodSecurityEvaluationContextTests.java
=> fixes setting paramName only when it is not null

web/src/main/java/org/springframework/security/web/firewall/StrictHttpFirewall.java, web/src/test/java/org/springframework/security/web/firewall/StrictHttpFirewallTests.java
#6292 
1. add customization support for double forwardslash in StrickHttpFirewall
2. add getEncodedUrlBlacklist() and getDecodedUrlBlacklist() method in StrickHttpFirewall
=> customization support for StrictHttpFirewall

web/src/main/java/org/springframework/security/web/server/savedrequest/WebSessionServerRequestCache.java, web/src/test/java/org/springframework/security/web/server/savedrequest/WebSessionServerRequestCacheTests.java
Previously, URL query parameters were lost when saving a request in `WebSessionServerRequestCache`. Now it is properly saved and restored.
Fixes #6421
=> Save query parameters in WebSessionServerRequestCache

config/src/main/java/org/springframework/security/config/annotation/web/configurers/HeadersConfigurer.java, config/src/main/java/org/springframework/security/config/http/HeadersBeanDefinitionParser.java, config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/main/resources/org/springframework/security/config/spring-security-5.2.rnc, config/src/main/resources/org/springframework/security/config/spring-security-5.2.xsd, config/src/test/groovy/org/springframework/security/config/annotation/web/configurers/HeadersConfigurerTests.groovy, config/src/test/java/org/springframework/security/config/doc/XsdDocumentedTests.java, config/src/test/java/org/springframework/security/config/web/server/HeaderSpecTests.java, docs/manual/src/docs/asciidoc/_includes/reactive/headers.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/appendix/namespace.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/web/headers.adoc, web/src/main/java/org/springframework/security/web/header/writers/HstsHeaderWriter.java, web/src/main/java/org/springframework/security/web/server/header/StrictTransportSecurityServerHttpHeadersWriter.java
1. Preload support in Servlet Security
2. Preload support in Reactive Security
3. Test for preload support in Servlet Security
4. Test for preload support in Reactive Security
Fixes: gh-6312
=> Add preload support to Strict-Transport-Security

docs/manual/src/docs/asciidoc/_includes/reactive/webclient.adoc
There was a missing space after a closing ` character which was messing up the formatting. This PR adds the space to correct the formatting.
=> Fix formatting in Implicit OAuth2AuthorizedClient section

config/src/test/groovy/org/springframework/security/config/annotation/web/configurers/DefaultLoginPageConfigurerTests.groovy, config/src/test/java/org/springframework/security/config/http/FormLoginBeanDefinitionParserTests.java, web/src/main/java/org/springframework/security/web/authentication/ui/DefaultLoginPageGeneratingFilter.java
Ending div moved  out of condition.
Fies: gh-6417
=> HTML markup fixed in DefaultLoginPageGeneratingFilter

config/src/main/java/org/springframework/security/config/http/CsrfBeanDefinitionParser.java, config/src/test/java/org/springframework/security/config/http/CsrfBeanDefinitionParserTests.java, config/src/test/resources/org/springframework/security/config/http/CsrfBeanDefinitionParserTests-RegisterDataValueProcessorOnyIfNotRegistered.xml
CsrfBeanDefinitionParser registers requestDataValueProcessor
if not already registered
Fixes: gh-6423
=> Improve CsrfBeanDefinitionParser xml parsing

docs/manual/src/docs/asciidoc/_includes/reactive/oauth2/resource-server.adoc
Debugging an issue today because our jwk properties where not working and discovered that the doc [here](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#oauth2resourceserver-jwkseturi) should be `spring.security.oauth2.resourceserver.jwt.jwk-set-uri` to align with the spring boot autoconfiguration [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/reactive/ReactiveOAuth2ResourceServerJwkConfiguration.java#L46)
=> Missing spring: prefix on jwk-set-uri example

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/server/OAuth2AuthorizationRequestRedirectWebFilter.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/server/OAuth2AuthorizationRequestRedirectWebFilterTests.java
When we used the oauth2Client directive and requested an endpoint that
required client authorization on the authorization server, the
SPRING_SECURITY_SAVED_REQUEST was not persisted, and therefore after
creating the authorized client we were redirected to the root page ("/").
Now we are storing the session attribute and getting redirected back to
the original URI as expected.
Note that the attribute is stored only when a
ClientAuthorizationRequiredException is thrown in the chain, we don't
want to store it as a response to the
/oauth2/authorization/{registrationId} endpoint, since we would end
up in an infinite loop
Fixes related Issue: #6341
=> Save original request on oauth2Client filter

config/src/main/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistry.java, config/src/test/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistryAnyMatcherTests.java
Don't allow any type of RequestMatchers
after any request by throwing IllegalStateException
Fixes: gh-6359
=> No RequestMatcher After AnyRequest

samples/boot/oauth2authorizationserver/src/main/java/sample/JwkSetConfiguration.java
parameter 'pricipal' is never used
=> parameter 'pricipal' is never used

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java, oauth2/oauth2-resource-server/spring-security-oauth2-resource-server.gradle, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/AbstractOAuth2TokenAuthenticationToken.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionAuthenticationProvider.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionAuthenticationToken.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionClaimNames.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionAuthenticationProviderTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionAuthenticationTokenTests.java, samples/boot/oauth2authorizationserver/src/main/java/sample/AuthorizationServerConfiguration.java, samples/boot/oauth2authorizationserver/src/main/resources/application.yml, samples/boot/oauth2resourceserver-opaque/README.adoc, samples/boot/oauth2resourceserver-opaque/spring-security-samples-boot-oauth2resourceserver-opaque.gradle, samples/boot/oauth2resourceserver-opaque/src/integration-test/java/sample/OAuth2ResourceServerApplicationITests.java, samples/boot/oauth2resourceserver-opaque/src/main/java/org/springframework/boot/env/MockWebServerEnvironmentPostProcessor.java, samples/boot/oauth2resourceserver-opaque/src/main/java/org/springframework/boot/env/MockWebServerPropertySource.java, samples/boot/oauth2resourceserver-opaque/src/main/java/org/springframework/boot/env/package-info.java, samples/boot/oauth2resourceserver-opaque/src/main/java/sample/OAuth2ResourceServerApplication.java, samples/boot/oauth2resourceserver-opaque/src/main/java/sample/OAuth2ResourceServerController.java, samples/boot/oauth2resourceserver-opaque/src/main/java/sample/OAuth2ResourceServerSecurityConfiguration.java, samples/boot/oauth2resourceserver-opaque/src/main/resources/META-INF/spring.factories, samples/boot/oauth2resourceserver-opaque/src/main/resources/application.yml
=> Add Support for Opaque OAuth2 Tokens to Resource Server

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2ResourceServerSpecTests.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionReactiveAuthenticationManager.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionReactiveAuthenticationManagerTests.java
=> Reactive Opaque Token Support

config/src/main/java/org/springframework/security/config/http/HeadersBeanDefinitionParser.java, config/src/main/resources/META-INF/spring.schemas, config/src/main/resources/org/springframework/security/config/spring-security-5.2.rnc, config/src/main/resources/org/springframework/security/config/spring-security-5.2.xsd, config/src/test/java/org/springframework/security/config/http/HttpHeadersConfigTests.java, config/src/test/resources/org/springframework/security/config/http/HttpHeadersConfigTests-DefaultsDisabledWithPlaceholder.xml, config/src/test/resources/org/springframework/security/config/http/HttpHeadersConfigTests-DisabledWithPlaceholder.xml
Fixes gh-6547
Two points
- Is it alright to update all the `.rnc` files starting from `4.2` upto `5.2`? The reason I did that is because in one of the test's xml, I changed `spring-security.xsd` to `spring-security-5.2.xsd` (or 5.2) and it failed with error message complaining about schema not matching and changing to `4.2.xsd` did not fail. This was before the change the `schema.handlers`.
- I am curious to whether I should include a check such as `if (element.getAttribute(attributeName).indexOf("${") !== -1)` in the `resolveAttribute` of `HeadersBeanDefinitionParser`. It might be expensive to run `resolve` even when it's not a property. I wonder if there are any edge cases with this if-check 🤔  
In order to succeed in running the unit tests locally, I had to setup a local `http` server …
=> Introduced placeholder support for headers tag attributes

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurer.java, core/src/main/java/org/springframework/security/authentication/AuthenticationManagerResolver.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationProvider.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/BearerTokenAuthenticationFilter.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/web/BearerTokenAuthenticationFilterTests.java, samples/boot/oauth2resourceserver-multitenancy/README.adoc, samples/boot/oauth2resourceserver-multitenancy/spring-security-samples-boot-oauth2resourceserver-multitenancy.gradle, samples/boot/oauth2resourceserver-multitenancy/src/integration-test/java/sample/OAuth2ResourceServerApplicationITests.java, samples/boot/oauth2resourceserver-multitenancy/src/main/java/org/springframework/boot/env/MockWebServerEnvironmentPostProcessor.java, samples/boot/oauth2resourceserver-multitenancy/src/main/java/org/springframework/boot/env/MockWebServerPropertySource.java, samples/boot/oauth2resourceserver-multitenancy/src/main/java/org/springframework/boot/env/package-info.java, samples/boot/oauth2resourceserver-multitenancy/src/main/java/sample/OAuth2ResourceServerApplication.java, samples/boot/oauth2resourceserver-multitenancy/src/main/java/sample/OAuth2ResourceServerController.java, samples/boot/oauth2resourceserver-multitenancy/src/main/java/sample/OAuth2ResourceServerSecurityConfiguration.java, samples/boot/oauth2resourceserver-multitenancy/src/main/resources/META-INF/spring.factories, samples/boot/oauth2resourceserver-multitenancy/src/main/resources/application.yml
=> Multi tenancy for Resource Server

config/src/main/resources/org/springframework/security/config/spring-security-5.2.rnc, config/src/main/resources/org/springframework/security/config/spring-security-5.2.xsd, docs/manual/src/docs/asciidoc/_includes/preface/samples.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/appendix/namespace.adoc
- #5553: Documentation on \<intercept-url filters="..."\> is outdated
- #6602: Spring Security 5 docs references distribution zip, which does not exist
=> documentation: remove out-of-date

config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebMvcSecurityConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/web/reactive/ServerHttpSecurityConfiguration.java, core/src/main/java/org/springframework/security/core/annotation/CurrentSecurityContext.java, web/src/main/java/org/springframework/security/web/bind/support/CurrentSecurityContextArgumentResolver.java, web/src/main/java/org/springframework/security/web/reactive/result/method/annotation/CurrentSecurityContextArgumentResolver.java, web/src/test/java/org/springframework/security/web/bind/support/CurrentSecurityContextArgumentResolverTests.java, web/src/test/java/org/springframework/security/web/reactive/result/method/annotation/CurrentSecurityContextArgumentResolverTests.java
it can both support with spring web mvc and reactive web, user can retrieve `SecurityContext` in controller easily, such as
```java
import org.springframework.security.core.Authentication;
import org.springframework.security.core.annotation.CurrentSecurityContext;
import org.springframework.security.core.context.SecurityContext;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
@Controller
public class MySecurityController {
@RequestMapping("/security-context")
public String securityContext(@CurrentSecurityContext SecurityContext context) {
Authentication auth = context.getAuthentication();
//do with security context and related authentication
return "security-context";
}
}
```
#6546
=> Introduce @CurrentSecurityContext for method arguments

core/src/main/java/org/springframework/security/core/authority/AuthorityUtils.java
> https://github.com/spring-projects/spring-security/issues/6773#issue-432523187
=> Fix no check if the parameter is null.

web/src/main/java/org/springframework/security/web/server/authentication/logout/HeaderWriterServerLogoutHandler.java, web/src/main/java/org/springframework/security/web/server/header/ClearSiteDataServerHttpHeadersWriter.java, web/src/test/java/org/springframework/security/web/server/authentication/logout/HeaderWriterServerLogoutHandlerTests.java, web/src/test/java/org/springframework/security/web/server/header/ClearSiteDataServerHttpHeadersWriterTests.java
1. A new implementation of ServerHttpHeadersWriter has been created to add Clear-Site-Data header support.
2. A new implementation of ServerLogoutHandler has been created which can be configured to write response headers during logout.
3. Added unit tests for both implementations.
=> Add Reactive Clear-Site-Data Support

config/src/main/java/org/springframework/security/config/annotation/web/reactive/ServerHttpSecurityConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/web/reactive/WebFluxSecurityConfiguration.java
=> Expose bean setters in @Configuration used by @EnableWebFluxSecurity

docs/manual/src/docs/asciidoc/_includes/servlet/additional-topics/webclient.adoc
Currently, ["13. WebClient for Servlet Environments"](https://docs.spring.io/spring-security/site/docs/5.2.0.BUILD-SNAPSHOT/reference/htmlsingle/#servlet-webclient
) is not aligned with rest of the items on ["additional-topics"](https://github.com/spring-projects/spring-security/tree/master/docs/manual/src/docs/asciidoc/_includes/servlet/additional-topics) section. As a consequence, "13.5 JSP Tag Libraries" to "13.12 Spring MVC Integration" became children of chapter 13 instead of children of chapter 12.
This PR fixes the leveling of the webclient documentation.
=> Align webclient section level in documentation

core/src/main/java/org/springframework/security/access/expression/method/ExpressionBasedPreInvocationAdvice.java, core/src/test/java/org/springframework/security/access/expression/method/ExpressionBasedPreInvocationAdviceTests.java, core/src/test/java/org/springframework/security/access/intercept/method/MockMethodInvocation.java
Getting NPE if @PreFilter argument filterType is not provided
and method accept more then one argument.
Add related exception message.
fixes gh-6803
=> Fix NPE ExpressionBasedPreInvocationAdviceTests

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurer.java, config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java, config/src/test/resources/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests-Active.json, config/src/test/resources/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests-ActiveNoScopes.json, config/src/test/resources/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests-Inactive.json, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionAuthenticationProvider.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionAuthenticationToken.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionReactiveAuthenticationManager.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/NimbusOAuth2TokenIntrospectionClient.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/NimbusReactiveOAuth2TokenIntrospectionClient.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/OAuth2IntrospectionClaimNames.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/OAuth2IntrospectionException.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/OAuth2TokenIntrospectionClient.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/ReactiveOAuth2TokenIntrospectionClient.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/package-info.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionAuthenticationProviderTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionAuthenticationTokenTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionReactiveAuthenticationManagerTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/introspection/NimbusOAuth2TokenIntrospectionClientTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/introspection/NimbusReactiveOAuth2TokenIntrospectionClientTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/introspection/TestOAuth2TokenIntrospectionClientResponses.java, samples/boot/oauth2resourceserver-multitenancy/src/main/java/sample/OAuth2ResourceServerSecurityConfiguration.java
Introducing OAuth2TokenIntrospectionClient and also
ReactiveOAuth2TokenIntrospectionClient as configuration points.
The DSL looks in the application context for these types in the same
way it looks for JwtDecoder and ReactiveJwtDecoder, and exposes
similar configuration methods.
Fixes: gh-6632
=> Opaque Token Intermediate Type

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/HeaderBearerTokenResolver.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/web/HeaderBearerTokenResolverTests.java
The new `HeaderBearerTokenResolver` extracts the bearer token (most likely JWT) from the application-defined HTTP request header.
This allows Spring Security Resource Server to understand, for example, [Google Cloud IAP proxy authentication](https://cloud.google.com/iap/docs/signed-headers-howto), which places JWT tokens in a `x-goog-iap-jwt-assertion` header.
=> Extract bearer token from arbitrary header

web/src/main/java/org/springframework/security/web/authentication/HttpStatusEntryPoint.java
Just fixes a typo in a javadoc. (Obvious Fix)
=> Fix javadoc typo

core/src/main/java/org/springframework/security/authentication/AccountStatusUserDetailsChecker.java
=> AccountStatusUserDetailsChecker implements MessageSourceAware

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoder.java
Reactive JwkSource Builder Parameter Type
Changed the parameter type from JWT to SignedJWT
Fixes: gh-6771
=> Reactive JwkSource Builder Parameter Type  Changed the parameter type from JWT to SignedJWT  Fixes: gh-6771

config/src/main/java/org/springframework/security/config/annotation/method/configuration/ReactiveMethodSecurityConfiguration.java, config/src/test/java/org/springframework/security/config/annotation/method/configuration/ReactiveMethodSecurityConfigurationTests.java
Currently, `GrantedAuthorityDefaults` is not considered in
`ReactiveMethodSecurityConfiguration`.
This commit updates the configuration to be aware of
`GrantedAuthorityDefaults` and update `rolePrefix` when the bean is
available.
Also, use the same instance of `DefaultMethodSecurityExpressionHandler`
when constructing `ExpressionBasedAnnotationAttributeFactory`.
=> Set "rolePrefix" in ReactiveMethodSecurityConfiguration

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/NimbusOAuth2TokenIntrospectionClient.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/introspection/NimbusOAuth2TokenIntrospectionClientTests.java
Added support for providing custom parameters to an OAuth 2.0 token introspection request. This is done by explicitly instantiating a NimbusOAuth2TokenIntrospectionClient instance and then setting a custom Converter implementation.
=> Add custom parameters to token introspection requests

docs/manual/src/docs/asciidoc/_includes/preface/getting-spring-security.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/preface/java-configuration.adoc
=> Documentation fixes

config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionAuthenticationToken.java
fixes gh-6829
As discussed here https://github.com/spring-projects/spring-security/pull/6841, I submitted the PR. 
CLA already signed.
=> Add @transient to OAuth2IntrospectionAuthenticationToken

core/src/main/java/org/springframework/security/authentication/jaas/JaasGrantedAuthority.java, core/src/test/java/org/springframework/security/authentication/jaas/JaasGrantedAuthorityTests.java, web/src/main/java/org/springframework/security/web/access/intercept/RequestKey.java, web/src/main/java/org/springframework/security/web/authentication/switchuser/SwitchUserGrantedAuthority.java, web/src/test/java/org/springframework/security/web/access/intercept/RequestKeyTests.java, web/src/test/java/org/springframework/security/web/authentication/switchuser/SwitchUserGrantedAuthorityTests.java
RequestKey, JaasGrantedAuthority, and SwitchUserGrantedAuthority
assume certain final members are non-null.
Issue: gh-6892
=> Added null checks and tests to constructors

gradle/dependency-management.gradle, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/registration/InMemoryClientRegistrationRepositoryTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/registration/InMemoryReactiveClientRegistrationRepositoryTests.java
Update the AssertJ dependency to version 3.12.2. Additionally fix
some tests not compiling due to API changes of AssertJ.
Fixes #6786
=> Update AssertJ to version 3.12.2

config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/AuthenticationConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/web/reactive/ServerHttpSecurityConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/web/socket/AbstractSecurityWebSocketMessageBrokerConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/authentication/configuration/AuthenticationConfigurationTests.java, config/src/test/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfigurationTests.java, config/src/test/java/org/springframework/security/config/annotation/method/configuration/NamespaceGlobalMethodSecurityTests.java, config/src/test/java/org/springframework/security/config/annotation/method/configuration/ReactiveMethodSecurityConfigurationTests.java, config/src/test/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurationTests.java, config/src/test/java/org/springframework/security/config/annotation/web/reactive/ServerHttpSecurityConfigurationTest.java, config/src/test/java/org/springframework/security/config/annotation/web/reactive/WebFluxSecurityConfigurationTests.java, config/src/test/java/org/springframework/security/config/annotation/web/socket/AbstractSecurityWebSocketMessageBrokerConfigurerTests.java
This is so that our configuration classes do not rely on CGLIB to proxy bean methods.
Fixes gh-6818
=> Replace bean method calls with injection

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/DefaultOAuth2AuthorizationRequestResolver.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/server/DefaultServerOAuth2AuthorizationRequestResolver.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/DefaultOAuth2AuthorizationRequestResolverTests.java
Fixes #6239
Provided baseScheme, baseHost, basePort and basePath variables that comprise the baseUrl variable.
To avoid errors during templating, I've added all variables with empty string default.
=> Finer variables for OAuth2 redirectUriTemplate expansion

config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2ResourceServerSpecTests.java
As per #6516, `OAuth2ResourceConfiguration#extractAuthorities` was deprecated
This PR updates `OAuth2ResourceServerConfigurerTests` and `OAuth2ResourceServerSpecTests` to use `setJwtGrantedAuthoritiesConverter` instead of `extractAuthorities`
=> Updates OAuth2ResourceServer configuration tests

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/ReactiveJwtAuthenticationConverterAdapter.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/ReactiveJwtAuthenticationConverterAdapterTests.java
Currently, `ReactiveJwtAuthenticationConverterAdapter` takes `JwtAuthenticationConverter` as its constructor argument. However, this limits the usage of this adapter.
In this commit, widen the constructor to take `Converter<Jwt, AbstractAuthenticationToken>` and allow this adapter to be used by generic converters.
=> Accept Converter in ReactiveJwtAuthenticationConverterAdapter

docs/manual/src/docs/asciidoc/_includes/reactive/oauth2/resource-server.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/preface/java-configuration.adoc
Use correct method names for creating JwtDecoder like described in gh-6925
Obvious Fix
=> Fix typo in OAuth2TokenValidator doc

config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/AuthenticationConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/configuration/ObjectPostProcessorConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/method/configuration/Jsr250MetadataSourceConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/method/configuration/ReactiveMethodSecurityConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/web/configuration/OAuth2ClientConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/web/reactive/ReactiveOAuth2ClientImportSelector.java, config/src/main/java/org/springframework/security/config/annotation/web/reactive/ServerHttpSecurityConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/web/reactive/WebFluxSecurityConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/web/servlet/configuration/WebMvcSecurityConfiguration.java, config/src/test/java/org/springframework/security/config/annotation/authentication/configuration/AuthenticationConfigurationTests.java, config/src/test/java/org/springframework/security/config/annotation/authentication/configuration/EnableGlobalAuthenticationTests.java, config/src/test/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfigurationTests.java, config/src/test/java/org/springframework/security/config/annotation/method/configuration/ReactiveMethodSecurityConfigurationTests.java, config/src/test/java/org/springframework/security/config/annotation/web/configuration/EnableWebSecurityTests.java, config/src/test/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurationTests.java, config/src/test/java/org/springframework/security/config/annotation/web/reactive/EnableWebFluxSecurityTests.java, config/src/test/java/org/springframework/security/config/annotation/web/reactive/ServerHttpSecurityConfigurationTest.java, config/src/test/java/org/springframework/security/config/annotation/web/reactive/WebFluxSecurityConfigurationTests.java
=> Disable bean proxying in configuration classes

core/src/main/java/org/springframework/security/authentication/ReactiveAuthenticationManagerAdapter.java, core/src/test/java/org/springframework/security/authentication/ReactiveAuthenticationManagerAdapterTests.java
Currently, authentication logic will be performed on hardcoded elastic scheduler in `ReactiveAuthenticationManagerAdapter`.
This needs to be configurable in order to perform the authentication logic in dedicated scheduler.
Also, once authentication is performed, rest of the logic(Controller/Service) also be performed on the published scheduler.
To allow the rest of the logic after authentication to run on different scheduler, adding another optional scheduler to publish on.
This PR is based on the usecase I have described here: https://github.com/reactor/reactor-core/pull/1644#issuecomment-490701518
=> Make scheduler configurable on ReactiveAuthenticationManagerAdapter

test/src/main/java/org/springframework/security/test/web/servlet/request/SecurityMockMvcRequestPostProcessors.java, test/src/test/java/org/springframework/security/test/web/servlet/request/SecurityMockMvcRequestPostProcessorsJwtTests.java
This is the first PR to address extension of testing API as described in https://github.com/spring-projects/spring-security/issues/6896
=> Extended testing api for tests

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2ResourceServerSpecTests.java, core/src/main/java/org/springframework/security/authentication/ReactiveAuthenticationManagerResolver.java, web/src/main/java/org/springframework/security/web/server/authentication/AuthenticationWebFilter.java, web/src/test/java/org/springframework/security/web/server/authentication/AuthenticationWebFilterTests.java
=> Add Multi-tenancy support for Reactive Resource Server

core/src/main/java/org/springframework/security/core/session/SessionRegistryImpl.java
Moved a log statement in `SessionRegistryImpl#registerNewSession` after `removeSessionInformation()` is called for comprehensible output to the logger.
The log statements are now printed in the same order as the logic is executed. Before the change, this could be confusing when debugging an application, since it seemed that the registered session was immediately removed when only looking at the logs.
Before:
```
> Registering session 500B7FEE4F10F1CFD5C69561FB40C2EC, for principal examplePrincipal
> Removing session 500B7FEE4F10F1CFD5C69561FB40C2EC from principal's set of registered sessions
> Removing principal examplePrincipal from registry
```
After:
```
> Removing session E40C41AD72989210A64B1CA2436D7A54 from principal's set of registered sessions
> Removing principal examplePrincipal …
```
=> Move log statement in SessionRegistryImpl

test/src/main/java/org/springframework/security/test/web/reactive/server/SecurityMockServerConfigurers.java, test/src/test/java/org/springframework/security/test/web/reactive/server/SecurityMockServerConfigurersJwtTests.java
Added new implementation of jwt() method that
makes it possible to directly provide a previously
prepared JWT token to WebTestClient mutator.
Fixes: spring-projectsgh-6896
=> Added jwt injection for reactive test mocks

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/OAuth2LoginAuthenticationFilter.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/OAuth2LoginAuthenticationFilterTests.java
[GH-6866] OAuth2LoginAuthenticationFilter should set AuthenticationDetails
=> OAuth2LoginAuthenticationFilter sets AuthenticationDetails

acl/src/main/java/org/springframework/security/acls/domain/ObjectIdentityImpl.java, core/src/main/java/org/springframework/security/authentication/jaas/JaasGrantedAuthority.java, web/src/main/java/org/springframework/security/web/access/intercept/RequestKey.java, web/src/main/java/org/springframework/security/web/authentication/switchuser/SwitchUserGrantedAuthority.java, web/src/main/java/org/springframework/security/web/util/matcher/AntPathRequestMatcher.java
XORing with 31 in these methods seems suspicious as it doesn't affect collision rate, it just flips the last 5 bits. And using bitwise XOR here just feels weird in general.
These are all unlikely to cause collisions but I would replace them with generated ones just in case.
All additions in this commit are generated by Eclipse.
=> Replace strange hashCode() implementations

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/server/ServerBearerTokenAuthenticationConverter.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/web/server/ServerBearerTokenAuthenticationConverterTests.java
ServerBearerTokenAuthenticationConverter Handles Empty Tokens
Previously ServerBearerTokenAuthenticationConverter would throw an
IllegalArgumentException when the access token in a URI was empty String.
It also incorrectly provided HttpStatus.BAD_REQUEST for an empty String
access token in the headers.
This changes ServerBearerTokenAuthenticationConverter to consistently
throw a OAuth2AuthenticationException with an HttpStatus.UNAUTHORIZED
Fixes gh-7011
=> ServerBearerTokenAuthenticationConverter Handles Empty Tokens

samples/boot/oauth2resourceserver-multitenancy/src/main/java/sample/OAuth2ResourceServerSecurityConfiguration.java, web/src/main/java/org/springframework/security/web/authentication/MultiTenantAuthenticationManagerResolver.java, web/src/test/java/org/springframework/security/web/authentication/MultiTenantAuthenticationManagerResolverTests.java
A class with a number of handy request-based implementations of
AuthenticationManager Resolver
Fixes; gh-6976
=> Add MultiTenantAuthenticationManagerResolver

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/FormLoginTests.java, config/src/test/java/org/springframework/security/config/web/server/ServerHttpSecurityTests.java
I just stumbled upon this issue(#5660), so fixing it.
----
Prior to this change, `HttpBasicSpec#authenticationManager` and
`FormLoginSpec#authenticationManager` were always overridden by
`ServerHttpSecurity#authenticationManager`.
This commit makes sure override only happens when custom authentication
manager was not specified.
Fixes: gh-5660
=> Allow custom ReactiveAuthenticationManager for basic and form auth

docs/manual/src/docs/asciidoc/_includes/servlet/architecture/technical-overview.adoc
These four items, not three items, constitute the auth process:
. A user is prompted to log in with a username and password.
. The system (successfully) verifies that the password is correct for the username.
. The context information for that user is obtained (their list of roles and so on).
. A security context is established for the user
=> Fix typo in documentation

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoder.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/SingleKeyJWSKeySelector.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jose/TestKeys.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderTests.java
=> Single-key Key Selector

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/BearerTokenAuthenticationFilter.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/web/BearerTokenAuthenticationFilterTests.java
Make BearerTokenAuthenticationFilter expose an AuthenticationFailureHandler which, by default, invokes the AuthenticationEntryPoint set in the filter.
Fixes gh-7009
=> BearerTokenAuthenticationFilter exposes AuthenticationFailureHandler

config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java, oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/OAuth2TokenAttributes.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionAuthenticationProvider.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionAuthenticationToken.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionReactiveAuthenticationManager.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionAuthenticationProviderTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionAuthenticationTokenTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionReactiveAuthenticationManagerTests.java, samples/boot/oauth2resourceserver-opaque/src/main/java/sample/OAuth2ResourceServerController.java
To simplify access to OAuth 2.0 token attributes
Fixes gh-6498
=> Added OAuth2TokenAttributes to wrap attributes

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistration.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/registration/ClientRegistrationTests.java
ClientRegistration.Builder defaulted to validating as an
authorization code registration, though a custom grant type could be in
use. The actual grant type is now verified for every case.
- Fixed validation in ClientRegistration.Builder
- New test that fails unless the issue is fixed.
Also made OAuth2AuthorizationGrantRequestEntityUtils public to help
implementing custom token response clients.
Fixes #7040
=> Fixed validation in ClientRegistration.Builder

config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/access/BearerTokenAccessDeniedHandler.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/access/server/BearerTokenServerAccessDeniedHandler.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/web/access/BearerTokenAccessDeniedHandlerTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/web/access/server/BearerTokenServerAccessDeniedHandlerTests.java
Fixes #gh-7089. It was found that current implementations of `BearerTokenAccessDeniedHandler` include information in their error responses about the scopes granted to the rejected OAuth2 token, whereas the OAuth RFCs states that these messages should describe the *required* scopes. This fix removes any mention of the scopes in these messages, as computing the required scopes within the `AccessDeniedHandler` looks impossible.
=> Removal of scope in WWW-Authenticate header on OAuth2 insufficient_scope error responses

web/src/main/java/org/springframework/security/web/util/matcher/IpAddressMatcher.java, web/src/test/java/org/springframework/security/web/util/matcher/IpAddressMatcherTests.java
Originally, `matches(String address)` would first call `parse` on an address, when I believe the correct behavior is to first check for the validity of the subnet mask (an invalid mask for an IP address is invalid regardless of what method it's a part of). This is why invalid masks could be passed into the constructor but then throw exceptions on valid calls to `matches`. So I changed both the constructor and the `matches` method to first validate that the mask in the IP address passed in is not too long.
Draft b/c I'm not sure if my assumption fully holds for all cases.
Fixes gh-2790
=> Throws exception when passed IP address with too long mask

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/AuthorizeExchangeSpecTests.java, config/src/test/java/org/springframework/security/config/web/server/CorsSpecTests.java, config/src/test/java/org/springframework/security/config/web/server/ExceptionHandlingSpecTests.java, config/src/test/java/org/springframework/security/config/web/server/FormLoginTests.java, config/src/test/java/org/springframework/security/config/web/server/HeaderSpecTests.java, config/src/test/java/org/springframework/security/config/web/server/HttpsRedirectSpecTests.java, config/src/test/java/org/springframework/security/config/web/server/LogoutSpecTests.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2ClientSpecTests.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2LoginTests.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2ResourceServerSpecTests.java, config/src/test/java/org/springframework/security/config/web/server/RequestCacheTests.java, config/src/test/java/org/springframework/security/config/web/server/ServerHttpSecurityTests.java, docs/manual/src/docs/asciidoc/_includes/reactive/cors.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/headers.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/method.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/oauth2/access-token.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/oauth2/login.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/oauth2/resource-server.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/redirect-https.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/webflux.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/x509.adoc, samples/boot/hellowebflux-method/src/main/java/sample/SecurityConfig.java, samples/boot/oauth2resourceserver-webflux/src/main/java/sample/SecurityConfig.java, samples/boot/oauth2webclient-webflux/src/main/java/sample/config/SecurityConfig.java, samples/boot/webflux-form/src/main/java/sample/WebfluxFormSecurityConfig.java, samples/boot/webflux-x509/src/main/java/sample/WebfluxX509Application.java
=> Support nested builder in DSL for reactive apps

core/src/main/java/org/springframework/security/access/hierarchicalroles/RoleHierarchyImpl.java, core/src/test/java/org/springframework/security/access/hierarchicalroles/RoleHierarchyImplTests.java
This PR resolves issue with infinite loop in role hierarchy resolving. 
The original issue has been resolved in first two commits (`2d36062`, `d3eaef6`). Last commit (`be0ad67`) simplifies the implementation in general meaning and removes unnecessary logic (logic related to the comparison of custom `GrantedAuthority` implementations). We are convinced that the readability of the component is much more better, but it is not necessary to merge this commit as well.
Fixes gh-7035
=> Fix infinite loop in role hierarchy resolving

web/src/main/java/org/springframework/security/web/authentication/AuthenticationConverter.java, web/src/main/java/org/springframework/security/web/authentication/AuthenticationEntryPointFailureHandler.java, web/src/main/java/org/springframework/security/web/authentication/AuthenticationFilter.java, web/src/main/java/org/springframework/security/web/authentication/AuthenticationSuccessHandler.java, web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationConverter.java, web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationFilter.java, web/src/test/java/org/springframework/security/web/authentication/AbstractAuthenticationProcessingFilterTests.java, web/src/test/java/org/springframework/security/web/authentication/AuthenticationFilterTests.java, web/src/test/java/org/springframework/security/web/authentication/www/BasicAuthenticationConverterTests.java
Fixes #6506 
This PR contains `AuthenticationWebFilter` concept implementation for regular Spring Security Filter Chain:
- `AuthenticationConverter` interface (aligned to `ServerAuthenticationConverter`)
- `GenericAuthenticationFilter` implementation (aligned to `AuthenticationWebFilter`)
- `BasicAuthenticationConverter` implementation (aligned to `ServerHttpBasicAuthenticationConverter`)
@rwinch the `AbstractAuthenticationProcessingFilter.requiresAuthentication()` method modified here to throw exceptions because these exceptions declared for `AbstractAuthenticationProcessingFilter.unsuccessfulAuthentication` method, which need to be called within `GenericAuthenticationFilter.requiresAuthentication` in case of `AuthenticationConverter.convert` decides to throw the …
=> Add AuthenticationConverter

config/src/main/java/org/springframework/security/config/annotation/web/configurers/CsrfConfigurer.java
Bump `@since` version on methods for configurable CSRF session authentication strategy.
Fixes #7083
=> Fix CSRF session authentication strategy since version

web/src/main/java/org/springframework/security/web/authentication/AuthenticationFilter.java
=> Downgrade modifier from public to protected

web/src/main/java/org/springframework/security/web/FilterInvocation.java, web/src/main/java/org/springframework/security/web/firewall/StrictHttpFirewall.java, web/src/test/java/org/springframework/security/web/firewall/StrictHttpFirewallTests.java
Introduce a new method `setAllowedHostnames` which perform the validation
against untrusted hostnames.
Fixes gh-4310
=> Add support for allowedHostnames in StrictHttpFirewall

crypto/src/main/java/org/springframework/security/crypto/argon2/Argon2EncodingUtils.java, crypto/src/main/java/org/springframework/security/crypto/argon2/Argon2PasswordEncoder.java, crypto/src/main/java/org/springframework/security/crypto/factory/PasswordEncoderFactories.java, crypto/src/test/java/org/springframework/security/crypto/argon2/Argon2EncodingUtilsTests.java, crypto/src/test/java/org/springframework/security/crypto/argon2/Argon2PasswordEncoderTests.java, crypto/src/test/java/org/springframework/security/crypto/factory/PasswordEncoderFactoriesTests.java, docs/manual/src/docs/asciidoc/_includes/servlet/architecture/password-encoder.adoc
Add PasswordEncoder for the Argon2 hashing algorithm (Password Hashing
Competition (PHC) winner).
This implementation uses the BouncyCastle-implementation of Argon2.
Fixes gh-5354
=> Add Argon2PasswordEncoder

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2LoginTests.java, oauth2/oauth2-core/src/test/java/org/springframework/security/oauth2/core/endpoint/TestOAuth2AuthorizationExchanges.java
Allow to customize the failure handler.
Fixes gh-7051
=> Add authenticationFailureHandler method in OAuth2LoginSpec

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/DefaultOAuth2AuthorizationRequestResolver.java, web/src/main/java/org/springframework/security/web/access/expression/ExpressionBasedFilterInvocationSecurityMetadataSource.java, web/src/main/java/org/springframework/security/web/servlet/util/matcher/MvcRequestMatcher.java, web/src/main/java/org/springframework/security/web/util/matcher/AntPathRequestMatcher.java, web/src/main/java/org/springframework/security/web/util/matcher/RequestMatcher.java, web/src/main/java/org/springframework/security/web/util/matcher/RequestVariablesExtractor.java, web/src/test/java/org/springframework/security/web/servlet/util/matcher/MvcRequestMatcherTests.java
Addresses: https://github.com/spring-projects/spring-security/issues/7148
Incorporates Commit from: https://github.com/spring-projects/spring-security/pull/7150
=> Enhancement to RequestMatcher

docs/manual/src/docs/asciidoc/_includes/servlet/preface/java-configuration.adoc
Change the name of class in docs WebSecurityConfigurationAdapter to WebSecurityConfigurerAdapter.
gh-7026
=> Fix docs typo WebSecurityConfigurationAdapter->WebSecurityConfigurerAdapter

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2LoginTests.java
Following discussion at #7222 , `OAuth2LoginSpec#securityContextRepository` was added.
=> Add OAuth2LoginSpec#securityContextRepository

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtGrantedAuthoritiesConverter.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtGrantedAuthoritiesConverterTests.java
Fixes gh-7101
Prior to this change mapped authorities are always prefixed
with default value 'SCOPE_'. To change this default behaviour the
converter had to be replaced completely with a custom one.
This commit adds an additional setter to configure a custom
authority prefix like e.g. 'ROLE_'. Without specifying a custom prefix
the default prefix still remains 'SCOPE_'.
This way existing authorization checks using the standard 'ROLE_'
prefix can be reused without lots of effort.
Required CLA has been submitted as well
=> Add setter for authority prefix in JwtGrantedAuthoritiesConverter

config/src/main/java/org/springframework/security/config/annotation/web/configurers/RequestCacheConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/RequestCacheConfigurerTests.java
references: https://github.com/spring-projects/spring-security/issues/7060
=> ignore Multipart requests in HttpSessionRequestCache.requestMatcher

web/src/main/java/org/springframework/security/web/authentication/session/ConcurrentSessionControlAuthenticationStrategy.java, web/src/test/java/org/springframework/security/web/authentication/session/ConcurrentSessionControlAuthenticationStrategyTests.java
=> Expire as many sessions as exceed maximum allowed

docs/manual/src/docs/asciidoc/_includes/servlet/web/basic.adoc
I fixed typo `DigestAuthenticatonEntryPoint` to `DigestAuthenticationEntryPoint`.
=> Fix typo in docs

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtGrantedAuthoritiesConverter.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtGrantedAuthoritiesConverterTests.java
Fixes gh-7100
Prior to this change authorities are always mapped using well known
claim names ('scp' or 'scope'). To change this default behaviour the
converter had to be replaced completely with a custom one.
This commit adds an additional setter to configure a custom
claim name like for example 'roles' to map authorities.
Without specifying a custom claim name
the default claims to be used still remains to
the well known ones ('scp' and 'scope').
=> Add setter for authorities claim name in JwtGrantedAuthoritiesConverter

web/src/main/java/org/springframework/security/web/util/OnCommittedResponseWrapper.java, web/src/test/java/org/springframework/security/web/util/OnCommittedResponseWrapperTests.java
Fixes gh-#7261
Trivial implementation.
=> Add setContentLengthLong detection to OnCommittedResponseWrapper.

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JWSAlgorithmMapJWSKeySelector.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoder.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderTests.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoderTests.java
=> Multiple JWS Algorithms

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/InMemoryReactiveClientRegistrationRepository.java
Since InMemoryReactiveClientRegistrationRepository is intended to be persistent, it should instead use ConcurrentHashMap.
Fixes gh-7299
=> Use ConcurrentHashMap in InMemoryReactiveClientRegistrationRepository

docs/manual/src/docs/asciidoc/_includes/servlet/architecture/technical-overview.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/preface/namespace.adoc
This PR adresses several markup errors in online documentation, concerning footnotes.
Fixes #3180
=> fix footnotes markup

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/reactive/function/client/ServletOAuth2AuthorizedClientExchangeFilterFunction.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/reactive/function/client/ServletOAuth2AuthorizedClientExchangeFilterFunctionTests.java
RequestContextSubscriber could cause NPE if Mono/Flux.subscribe
was invoked outside of Web Context.
In addition it replaced source Context with its own without respect
to old data.
Now Request Context Data is Propagated within holder class and
it is added to existing reactor Context
Fixes gh-7228
=> Fix NPE in RequestContextSubscriber

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/ServletBearerExchangeFilterFunction.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/server/ServerBearerExchangeFilterFunction.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/web/MockExchangeFunction.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/web/ServletBearerExchangeFilterFunctionTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/web/server/ServerBearerExchangeFilterFunctionTests.java
=> Add Servlet and ServerBearerExchangeFilterFunction

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/oidc/userinfo/OidcReactiveOAuth2UserService.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/oidc/userinfo/OidcUserService.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/userinfo/DefaultOAuth2UserService.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/userinfo/DefaultReactiveOAuth2UserService.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/oidc/userinfo/OidcReactiveOAuth2UserServiceTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/oidc/userinfo/OidcUserServiceTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/userinfo/DefaultOAuth2UserServiceTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/userinfo/DefaultReactiveOAuth2UserServiceTests.java, oauth2/oauth2-core/src/test/java/org/springframework/security/oauth2/core/oidc/TestOidcIdTokens.java
=> Grant Individual Authorities From Claims

oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/userinfo/CustomUserTypesOAuth2UserServiceTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/userinfo/DefaultOAuth2UserServiceTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/userinfo/DefaultReactiveOAuth2UserServiceTests.java, oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/user/DefaultOAuth2User.java, oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/user/OAuth2User.java
=> Make OAuth2User extends OAuth2AuthenticatedPrincipal

docs/manual/src/docs/asciidoc/_includes/servlet/architecture/technical-overview.adoc
Fixes gh-7440
The reference documentation still referred to Java 5.0 as minimum
runtime version which is wrong.
This commit changes this to the correct
- Java 8 runtime version as required minimum version.
- In addition it corrects a fuzzy wording regarding stripping down the
`spring-security-core` jar.
=> Fix wrong java runtime version mentioned in reference doc

saml2/saml2-service-provider/spring-security-saml2-service-provider.gradle, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationProvider.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2AuthenticationException.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2Error.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2ErrorCodes.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/credentials/Saml2X509CredentialTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationProviderTests.java, samples/boot/saml2login/src/integration-test/java/org/springframework/security/samples/Saml2LoginIntegrationTests.java
SAML Assertion validation should propagate errors: #7375
=> Propagate saml authentication exception gh-7375

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationProvider.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationRequestFactory.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlImplementation.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2AuthenticationException.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2AuthenticationRequestFactory.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2Error.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2ErrorCodes.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/credentials/Saml2X509CredentialTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationProviderTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/Saml2CryptoTestSupport.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/TestSaml2AuthenticationObjects.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/TestSaml2X509Credentials.java, samples/boot/saml2login/src/integration-test/java/org/springframework/security/samples/Saml2LoginIntegrationTests.java
PowerMock removed as a test dependency. Testing converted using real data.
Fixes gh-7375
=> propagate saml authentication exception #7375

config/src/main/java/org/springframework/security/config/annotation/rsocket/RSocketSecurity.java, config/src/test/java/org/springframework/security/config/annotation/rsocket/RSocketMessageHandlerConnectionITests.java
=> Add hasAuthority method to RSocketSecurity

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationProvider.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistrationRepository.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationProviderTests.java, samples/boot/saml2login/src/integration-test/java/org/springframework/security/samples/Saml2LoginIntegrationTests.java
Fixes gh-7490
https://github.com/spring-projects/spring-security/issues/7490
=> Always validate saml2 signatures

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationRequestFactory.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2AuthenticationRequest.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationRequestFilter.java, samples/boot/saml2login/src/integration-test/java/org/springframework/security/samples/Saml2LoginIntegrationTests.java
=> Correctly populate the AuthNRequest attributes

config/src/main/java/org/springframework/security/config/annotation/rsocket/RSocketSecurity.java, config/src/test/java/org/springframework/security/config/annotation/rsocket/RSocketMessageHandlerConnectionITests.java
See gh-7437
Co-authored-by: Eddú Meléndez <eddu.melendez@gmail.com>
=> Add denyAll method in AuthorizePayloadsSpec.Access

config/src/main/java/org/springframework/security/config/annotation/rsocket/RSocketSecurity.java, config/src/test/java/org/springframework/security/config/annotation/rsocket/RSocketMessageHandlerConnectionITests.java
See [gh-7437](https://github.com/spring-projects/spring-security/issues/7437)
=> add hasAnyRole method in AuthorizePayloadsSpec.Access

config/src/main/java/org/springframework/security/config/annotation/rsocket/RSocketSecurity.java, config/src/test/java/org/springframework/security/config/annotation/rsocket/RSocketMessageHandlerConnectionITests.java
=> Add hasAnyAuthority method in AuthorizePayloadsSpec.Access

core/src/main/java/org/springframework/security/authentication/AbstractUserDetailsReactiveAuthenticationManager.java, core/src/test/java/org/springframework/security/authentication/ReactiveUserDetailsServiceAuthenticationManagerTests.java
AbstractUserDetailsReactiveAuthenticationManager creates parallel `Scheduler` with `daemon=false` `Thread`s. It is recommended to dispose such Schedulers to be able exit the VM
Fixes gh-7492
=> Dispose default Scheduler

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationRequestFactory.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationRequestFactoryTests.java
Fixes gh-7513.
Note: This is not intended as the final solution, but as a starting point for discussion.  I believe a better solution may be to add `protocolBinding` to `Saml2AuthenticationRequest` and `RelyingPartyRegistration`.  But I'd like to hear feedback on that approach before submitting any code.
@fhanik FYI.
=> Support configuration of protocol binding for authentication requests

docs/manual/src/docs/asciidoc/_includes/reactive/webflux.adoc
The documentation of webflux integration sample projects was pointing to the `javaconfig` folder instead of `boot` sample folder.
=> fix webflux samples documentation path

core/src/main/java/org/springframework/security/core/authority/AuthorityUtils.java
Changed parameter name to authorities
Added JavaDoc
Fixes gh-4805
Co-authored-by: Everett Irwin <everettirwin77@gmail.com>
=> Polish AuthorityUtils

acl/src/main/java/org/springframework/security/acls/domain/DefaultPermissionGrantingStrategy.java, acl/src/test/java/org/springframework/security/acls/domain/AclImplTests.java
**SEC-2342**
Extracts the mask comparison in DefaultPermissionGrantingStrategy into a protected method.
This allows overriding the default behavior in a subclass without having to copy the whole isGranted() method.
As discussed in the above issue (and others like [SEC-1140](https://github.com/spring-projects/spring-security/issues/1388)), users can choose to implement a different strategy, e.g. do a bitwise mask comparison instead of the integer comparison.
=> extract permission mask comparison for subclasses to override

ldap/src/integration-test/java/org/springframework/security/ldap/userdetails/DefaultLdapAuthoritiesPopulatorTests.java, ldap/src/main/java/org/springframework/security/ldap/userdetails/DefaultLdapAuthoritiesPopulator.java
As discussed in #5929 this adds an implementation of `LdapAuthoritiesPopulator` which uses `LdapAuthority` instead or the generic `SimpleGrantedAuthority`.
The new implementation shares the same code as the original so that the old one can be deprecated and then removed.
Keep in mind that `NestedLdapAuthoritiesProvider` still extends `DefaultLdapAuthoritiesProvider`.
Change `DefaultLdapAuthoritiesPopulator` implementation to use `LdapAuthority` instead of `SimpleGrantedAuthority`: this would be a "breaking" change if and only if an existing logic is based on the fact that authorities from the populator are instances of `SimpleGrantedAuthority` and I can't figure out any case where this would make sense. Of course this will wait a next major, but would not introduce an additional …
=> Use more specific GrantedAuthority for mapped roles

web/src/main/java/org/springframework/security/web/authentication/preauth/AbstractPreAuthenticatedProcessingFilter.java, web/src/test/java/org/springframework/security/web/authentication/preauth/AbstractPreAuthenticatedProcessingFilterTests.java
Hi,
I'd like to add more precheck logic on `AbstractPreAuthenticatedProcessingFilter#requiresAuthentication`. (Currently, it is a private method)
Similar class `AbstractAuthenticationProcessingFilter` has `requiresAuthentication` as a protected method.
Making the method protected allows sub-classes to extend the precondition check.
Thanks,
=> Allow override AbstractPreAuthenticatedProcessingFilter#requiresAuthentication

web/src/main/java/org/springframework/security/web/DefaultRedirectStrategy.java, web/src/test/java/org/springframework/security/web/DefaultRedirectStrategyTests.java
Hello,
When defining a redirect strategy, after a logout for example, you can force the redirection to be context relative, by ``setContextRelative(true)``.
If by mistake (or not), you want the redirect target to be an absolute url completely outside of your context-path (eg: http://www.google.com), this url obviously does not contain your context-path.
This lead to ``DefaultRedirectStrategy#calculateRedirectUrl`` silently calculating a completely wrong URL if ``contextRelative`` is ``true``
This PR  checks is the URL contains the context-path. If not, it early returns the untouched url.
Another possibility would be to throw an ``IllegalArgumentException`` if ``contextRelative`` is true BUT url is absolute AND does not contain the context-path.
=> DefaultRedirectStrategy should not calculate relative url if it does not contain the context-path

web/src/main/java/org/springframework/security/web/authentication/preauth/AbstractPreAuthenticatedProcessingFilter.java
=> Align javadoc of continueFilterChainOnUnsuccessfulAuthentication with actual behaviour

config/src/main/java/org/springframework/security/config/annotation/web/configurers/ExceptionHandlingConfigurer.java
Just a typo fix in javadoc for `authenticationEntryPoint` method. Nothing fancy here.
=> Fix typo 'is' -> 'if' in javadoc

test/src/main/java/org/springframework/security/test/web/servlet/request/SecurityMockMvcRequestBuilders.java, test/src/test/java/org/springframework/security/test/web/servlet/request/SecurityMockMvcRequestBuildersFormLoginTests.java, test/src/test/java/org/springframework/security/test/web/servlet/request/SecurityMockMvcRequestBuildersFormLogoutTests.java
Allows URI variables in `formLogin` and `logout` requests of `MockMvc`
login example:
```
mockMvc.perform(formLogin("{basePath}/admin/login", "/api")
.user("username")
.password("password"))
.andExpect(authenticated()
...
.andExpect(status().isOk())
.andExpect(...);
```
yields `/api/admin/login` as the `formLogin` URL.
logout example:
```
mockMvc.perform(logout("{basePath}/admin/logout", "/api"))
.andExpect(unauthenticated()
.andExpect(status().isOk())
.andExpect(...);
```
yields `/api/admin/logout` as the `logout` URL.
=> Support URI vars in formLogin and logout MockMvc requests

samples/boot/hellorsocket/src/integration-test/java/sample/HelloRSocketApplicationITests.java
* Make use of @LocalRSocketServerPort
* Improve saml2login and hellorsocket sampless
=> Upgrade spring-boot version to latest snapshot

docs/manual/src/docs/asciidoc/_includes/servlet/authorization/expression-based.adoc
A valid `@PreAuthorize` expression with `hasAnyRole` looks like this:
```@PreAuthorize("hasAnyRole('USER', 'ADMIN')")```
However, this was not quite clear to me from the documentation. It states
`hasAnyRole([role1,role2])`. I initially thought that I had to add brackets around the complete list of roles e.g. `@PreAuthorize("hasAnyRole(['USER', 'ADMIN'])")`.
This leads to an exception though:
```Caused by: org.springframework.expression.spel.SpelParseException: Expression [hasAnyRole(['USER', 'ADMIN'])] @18: EL1043E: Unexpected token. Expected 'rsquare(])' but was 'comma(,)'```
which makes it clear that the brackets are wrong.
I think it would be clearer if the documentation would use this expression: `hasAnyRole([role1],[role2])`.
=> Clarify usage of hasAnyRole and hasAnyAuthority

core/src/main/java/org/springframework/security/access/expression/SecurityExpressionRoot.java
Code:
private Set<String> getAuthoritySet() {
if (roles == null) {
roles = new HashSet<>();
Collection<? extends GrantedAuthority> userAuthorities = authentication
.getAuthorities();
if (roleHierarchy != null) {
userAuthorities = roleHierarchy
.getReachableGrantedAuthorities(userAuthorities);
}
roles = AuthorityUtils.authorityListToSet(userAuthorities);
}
return roles;
}
The "roles = new HashSet<>();" is  unnecessary and inefficiency.
Hope it can be modified.
=> Remove unnecessary and inefficiency code

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistrations.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/registration/ClientRegistrationsTest.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtDecoderProviderConfigurationUtils.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/JwtDecodersTests.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/ReactiveJwtDecodersTests.java
Relating to https://github.com/spring-projects/spring-security/issues/7512
=> Make jwks_uri optional for RFC 8414 and required for OpenID Connect

config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeUserDetailsBeanManagerConfigurer.java
When the AuthenticationConfiguration sets the UserDetailsBeanConfigurer it creates a DaoAuthenticationProvider without the capabilities of setting an ApplicationContext registered UserCache bean.
Fixes gh-7556
=> Adds UserCache to the DaoAuthenticationprovider through AuthenticationConfiguration

config/src/main/java/org/springframework/security/config/method/GlobalMethodSecurityBeanDefinitionParser.java
Fix a simple typo in a log message. See issue https://github.com/spring-projects/spring-security/issues/7658
=> Fix typo in log message in GlobalMethodSecurityBeanDefinitionParser.java.

config/src/test/java/org/springframework/security/config/annotation/rsocket/RSocketMessageHandlerITests.java
This commit fixes the tests failures when using spring version `5.2.2.BUILD-SNAPSHOT`.
This [Spring Framework issue](https://github.com/spring-projects/spring-framework/issues/23999), 
> refines each @MessageMapping to match only the RSocket interaction type it fits based on the input and output cardinality of the handler method.
After the commit that fixes the above issue, the test `retrieveFluxWhenDataStringAndPublicThenGranted ` is invalid because the destination `"retrieve-flux"` does not support `REQUEST_STREAM`, and only support `REQUEST_CHANNEL`, since the input cardinality is 2. 
Additionally, the destination `"send"` was not being used in the test `sendWhenPublicThenGranted` because it the provided input of cardinality 1 did not match the expect `Flux` input of cardinality 2.
=> Update @MessageMapping to match input/output cardinality

docs/manual/src/docs/asciidoc/_includes/about/exploits/csrf.adoc, docs/manual/src/docs/asciidoc/_includes/about/getting-spring-security.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/exploits/headers.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/exploits/headers.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/saml2/saml2-login.adoc
=> fix typo: require require

docs/manual/src/docs/asciidoc/_includes/servlet/java-configuration/index.adoc
=> Fix minor typo.

web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationFilter.java
Was having some problems when my implementations were throwing some runtime exceptions. Which lead to `InternalAuthenticationServiceException` being thrown. However, the log didn't have any stacktrace. With this change it would be possible to see the stacktrace when such exception occurs.
=> Log full failed authentication exception in BasicAuthenticationFilter

config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeAuthenticationProviderBeanManagerConfigurer.java, config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeUserDetailsBeanManagerConfigurer.java
Currently the javadoc of class `InitializeAuthenticationProviderBeanManagerConfigurer` is copy-pasted from `InitializeUserDetailsBeanManagerConfigurer`. This PR just fixes the Javadoc and removes an unnecessary import.
This also fixes copy-pasted class and variable names in `InitializeAuthenticationProviderBeanManagerConfigurer` class and also fixes variable name in `InitializeUserDetailsBeanManagerConfigurer`: `userDetailsBeanNames` -> `beanNames` as the names returned for bean type that depends on method parameter and they are not always `UserDetailsService` type (the method `getBeanOrNull` is called several times with different 'type' argument actually).
=> Fix InitializeAuthenticationProviderBeanManagerConfigurer Javadoc

web/src/main/java/org/springframework/security/web/reactive/result/method/annotation/AuthenticationPrincipalArgumentResolver.java, web/src/test/java/org/springframework/security/web/reactive/result/method/annotation/AuthenticationPrincipalArgumentResolverTests.java
Implementation for #6598 as noted by @eleftherias 
Replacing `exchange.getPrincipal()` with `ReactiveSecurityContextHolder.getContext().map(SecurityContext::getAuthentication)` in `AuthenticationPrincipalArgumentResolver`.
Other implementations of `AuthenticationPrincipalArgumentResolver` are already doing that (messaging).
One thing I noticed was, the logic for `AuthenticationPrincipalArgumentResolver` exists multiple times (like 2-3 duplicates), maybe it's time to refactor the logic out into an abstract base class.
=> switches web authentication principal resolver to use reactive context (#6598)

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationProvider.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2AuthenticatedPrincipal.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/SimpleSaml2AuthenticatedPrincipal.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationProviderTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/SimpleSaml2AuthenticatedPrincipalTests.java
Fix https://github.com/spring-projects/spring-security/issues/7681
=> fix: make Saml2Authentication serializable

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/ServerHttpSecurityTests.java
Fixes gh-7721
Test case provided
=> Use the custom ServerRequestCache for Oauth2LoginSpec

core/src/main/java/org/springframework/security/jackson2/UsernamePasswordAuthenticationTokenDeserializer.java, core/src/test/java/org/springframework/security/jackson2/UsernamePasswordAuthenticationTokenMixinTests.java
Before this commit, the details field was set to a JsonNode, but now it is deserialized correctly.
Fixes gh-7482
=> Deserialize details field in UsernamePasswordAuthenticationToken

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/ServerHttpSecurityTests.java
on for the default authentication entry point and authentication
success handler
Fixes gh-7751
Backport of gh-7721
https://github.com/spring-projects/spring-security/issues/7721
=> Use the custom ServerRequestCache that the user configures

web/src/main/java/org/springframework/security/web/authentication/rememberme/AbstractRememberMeServices.java, web/src/test/java/org/springframework/security/web/authentication/rememberme/AbstractRememberMeServicesTests.java
AbstractRememberMeServices is setting remember-me cookie with checking request is secure or secure usage is independently set to a fixed flag.
But when cancelling a cookie, cookie is not being marked secure or not. It produces an inconsistency when using secure flag as a part to identity of cookie. This commit intended to fix this situation.
=> Fix remember-me cookie set/cancel inconsistency:

core/src/main/java/org/springframework/security/jackson2/SecurityJackson2Modules.java
The Jackson 2 `JavaType` is unnecessarily resolved twice when a class is whitelisted. This should be the most likely case. The delegate doing this may be a `ClassNameIdResolver` whose operations seem rather complex, so it would be a good idea to avoid a call.
JavaTypes are resolved twice for a whitelisted class.
JavaTypes are resolved only once for a whitelisted class.
=> Resolve JavaType only once for whitelisted class

docs/manual/src/docs/asciidoc/_includes/reactive/oauth2/resource-server.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/oauth2/oauth2-resourceserver.adoc
The unchecked exception if fixed by casting to `Collection<?>` instead of `Collection<String>` and casting each item with `Object::toString` prior the `SimpleGrantedAuthority` instantiation.
The possible NPE is fixed by returning `Collections.emptyList()` if the custom claim is missing in the JWT.
=> Fix unchecked assignment and possible NPE

docs/manual/src/docs/asciidoc/_includes/servlet/architecture/core-services.adoc
It does not offer decoding passwords. Only encoding and matching encoded passwords
=> Fixed desc of PasswordEncoder

config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java, docs/manual/src/docs/asciidoc/_includes/servlet/oauth2/oauth2-resourceserver.adoc, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerAuthenticationManagerResolver.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerAuthenticationManagerResolverTests.java
=> Add JwtIssuerAuthenticationManagerResolver

web/src/main/java/org/springframework/security/web/authentication/logout/CookieClearingLogoutHandler.java, web/src/test/java/org/springframework/security/web/authentication/logout/CookieClearingLogoutHandlerTests.java
It is better to mark cookie secure flag with request.isSecure() to ensure cookie identity is same
=> Set secure on cookie when logging out

config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurerAdapter.java, config/src/test/java/org/springframework/security/config/annotation/web/WebSecurityConfigurerAdapterTests.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java
This PR addresses two main circumstances where Spring Security allows for an `AuthenticationEventPublisher`:
1. When published as a bean
```java
@Bean 
public AuthenticationEventPublisher eventPublisher(ApplicationEventPublisher eventPublisher) {
return new DefaultAuthenticationEventPublisher(eventPublisher);
}
```
2. When specified via the DSL
```
protected configure(AuthenticationManagerBuilder auth) {
auth.authenticationEventPublisher(fooEventPublisher);
}
```
=> AuthenticationEventPublisher Lookup

config/src/main/java/org/springframework/security/config/annotation/web/configurers/RequestCacheConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/RequestCacheConfigurerTests.java
The eventstream requests is typically not directly invoked by the browser.
And even more unfortunately the browser api for `Eventsource` doesn't allow the set additional headers as `X-Requested-With: XMLHttpRequest`..
=> Don't cache requests with `Accept: text/event-stream` by default.

core/src/main/java/org/springframework/security/authentication/ProviderManager.java, core/src/test/java/org/springframework/security/authentication/ProviderManagerTests.java
- Added varargs constructor to ProviderManager.
- Updated ProviderManagerTests to use the new syntax and fix the check for empty list.
Fixes gh-7713
=> ProviderManager should have a varargs constructor

docs/manual/src/docs/asciidoc/_includes/reactive/oauth2/resource-server.adoc, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerReactiveAuthenticationManagerResolver.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerReactiveAuthenticationManagerResolverTests.java
=> Add JwtIssuerReactiveAuthenticationManagerResolver

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/AbstractSaml2AuthenticationRequest.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationRequestFactory.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlImplementation.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2AuthenticationRequest.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2AuthenticationRequestContext.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2AuthenticationRequestFactory.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2PostAuthenticationRequest.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2RedirectAuthenticationRequest.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2Utils.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/Saml2MessageBinding.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2ServletUtils.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationFilter.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationRequestFilter.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationRequestFactoryTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlImplementationTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/Saml2AuthenticationRequestFactoryTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2UtilsTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationRequestFilterTests.java, samples/boot/saml2login/src/integration-test/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlActionTestingSupport.java, samples/boot/saml2login/src/integration-test/java/org/springframework/security/saml2/provider/service/authentication/Saml2LoginIntegrationTests.java
Simple fix for gh-7711 that changes the way the AuthNRequest is signed and 
Has been tested with
- Keycloak
- SSOCircle
- Okta
- SimpleSAMLPhp
Further configuration options (POST vs REDIRECT) that build on top of this PR can be found in:
https://github.com/spring-projects/spring-security/pull/7759
=> SAML AuthNRequest Signatures - Step 1

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/DefaultOAuth2AuthorizationRequestResolver.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/server/DefaultServerOAuth2AuthorizationRequestResolver.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/jackson2/OAuth2AuthorizationRequestMixinTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/DefaultOAuth2AuthorizationRequestResolverTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/server/DefaultServerOAuth2AuthorizationRequestResolverTests.java, oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/endpoint/OAuth2AuthorizationRequest.java, oauth2/oauth2-core/src/test/java/org/springframework/security/oauth2/core/endpoint/OAuth2AuthorizationRequestTests.java
The `OAuth2AuthorizationRequestResolver` provides the ability to customize the Authorization Request using a [delegation-based strategy](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#customizing-the-authorization-request).
Although this strategy could fulfill most (if not all) use cases, it does require some extra configuration that may not be as convenient compared to directly _"hooking"_ into the `OAuth2AuthorizationRequest.Builder` for customizations.
This PR addresses this by introducing a `Consumer<OAuth2AuthorizationRequest.Builder>` in `DefaultOAuth2AuthorizationRequestResolver`.
Fixes gh-7696
Related #7714
=> Simplify customizing OAuth2AuthorizationRequest

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerReactiveAuthenticationManagerResolver.java
Add lazy Exception instantiation and reduce amount of
reactor operators to reduce allocations
Fixes gh-7995
=> Instantiate exceptions lazily

docs/manual/src/docs/asciidoc/_includes/servlet/index.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/kotlin-configuration/index.adoc
=> Add Kotlin Configuration section to docs

crypto/src/test/java/org/springframework/security/crypto/encrypt/BouncyCastleAesBytesEncryptorEquivalencyTest.java
=> Update test to have comment about secure salt length

web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationConverter.java, web/src/test/java/org/springframework/security/web/authentication/www/BasicAuthenticationConverterTests.java, web/src/test/java/org/springframework/security/web/authentication/www/BasicAuthenticationFilterTests.java
=> Fix exception from empty basic auth header token

config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java
`HttpSecurity#csrf()` returns a `CsrfConfigurer`, while the Javadoc states that it returns the `ServletApiConfigurer`. This was probably copied from the method above.
=> Fix typo in Javadoc of HttpSecurity#csrf()

docs/manual/src/docs/asciidoc/_includes/servlet/oauth2/oauth2-login.adoc
I found and fixed some broken links related `ClientRegistration` in "oauth2-login.adoc".
Closes https://github.com/spring-projects/spring-security/issues/8213
=> Fix links in oauth2 doc

core/src/main/java/org/springframework/security/access/expression/method/DefaultMethodSecurityExpressionHandler.java, core/src/test/java/org/springframework/security/access/expression/method/DefaultMethodSecurityExpressionHandlerTests.java, docs/manual/src/docs/asciidoc/_includes/servlet/authorization/expression-based.adoc
This pull requests adds support for Maps to DefaultMethodSecurityExpressionHandler.
Notes:
- Not sure if `permissionCacheOptimizer.cachePermissionsFor` can be used with Maps.
=> Adding Map support to DefaultMethodSecurityExpressionHandler

crypto/src/main/java/org/springframework/security/crypto/bcrypt/BCryptPasswordEncoder.java, crypto/src/test/java/org/springframework/security/crypto/bcrypt/BCryptPasswordEncoderTests.java
Issue #8317 - made BCryptPasswordEncoder#encode() and BCryptPasswordEncoder#matches() null-safe
=> BCryptPasswordEncoder rawPassword cannot be null

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationConverter.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationConverterTests.java
=> Added setPrincipalClaimName to JwtAuthenticationConverter

config/src/main/kotlin/org/springframework/security/config/web/server/AuthorizeExchangeDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerAnonymousDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerCorsDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerCsrfDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerExceptionHandlingDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerFormLoginDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerHeadersDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerHttpBasicDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerHttpSecurityDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerHttpsRedirectDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerLogoutDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerOAuth2ClientDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerOAuth2LoginDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerOAuth2ResourceServerDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerRequestCacheDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerSecurityMarker.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerX509Dsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/headers/ServerCacheControlDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/headers/ServerContentSecurityPolicyDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/headers/ServerContentTypeOptionsDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/headers/ServerFrameOptionsDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/headers/ServerHttpStrictTransportSecurityDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/headers/ServerReferrerPolicyDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/headers/ServerXssProtectionDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/oauth2/resourceserver/ServerJwtDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/oauth2/resourceserver/ServerOpaqueTokenDsl.kt
Add marker on web server security configuration
to make Kotlin DSL type safe.
Issue gh-8366
=> Add marker to make Kotlin DSL type safe

README.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/oauth2/resource-server.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/oauth2/oauth2-resourceserver.adoc
As discussed in #8391, extended the documentation for the opaque Resource Server in order to clearly state which dependencies are required in order for the minimal deployment to work.
=> Documented dependencies for opaque Resource Server

CONTRIBUTING.adoc
In CONTRIBUTING.adoc, we have:
>Latin-1 (ISO-8859-1) encoding for Java sources; use native2ascii to convert if necessary
In .editorconfig, we have:
```
charset = utf-8
```
Both files were in sync, but apparently this [commit](https://github.com/spring-projects/spring-security/commit/a8b438587b129d455f4c2c93f556fd6c080a19aa#diff-6a3371457528722a734f3c51d9238c13) which converted Contribution.md to Contributing.adoc, did not use the latest version and some modifications have been lost.
=> Fix mismatch between CONTRIBUTING.adoc and .editorconfig

docs/manual/src/docs/asciidoc/_includes/servlet/authentication/unpwd/basic.adoc
Only a small modification on the documentation, which fixes gh-8119.
I have submitted the CLA.
=> Document description error gh-8119

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtGrantedAuthoritiesConverter.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtGrantedAuthoritiesConverterTests.java
- docs stated that empty authorityPrefix are allowed but implementation denied to use `""`
- commit removes the `hasText`-limitation but restricts to `notNull`
Fixes gh-8421
=> Enables empty authorityPrefix in JwtGrantedAuthoritisConverter

config/src/main/kotlin/org/springframework/security/config/web/servlet/AbstractRequestMatcherDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/servlet/AuthorizeRequestsDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/servlet/RequiresChannelDsl.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/AuthorizeRequestsDslTests.kt
Attempted an implementation for #8307, which adds an implementation of `authorize()` for `AuthorizeRequestsDsl`, so that we can write code like this:
```kotlin
http {
authorizeRequests {
authorize(GET, "/path", permitAll)
authorize(PUT, "/path", denyAll)
}
}
```
=> Add authorize() DSL method that accepts HttpMethod

test/src/main/java/org/springframework/security/test/web/servlet/setup/SecurityMockMvcConfigurer.java
This commit adds null-checks in relevant methods, so instead of NPE an IllegalStateException will be thrown with additional details.
Fixes gh-7745
=> SecurityMockMvcConfigurer$DelegateFilter is not null-safe

docs/manual/src/docs/asciidoc/_includes/servlet/oauth2/oauth2-resourceserver.adoc
Improve the documentation to show how to re-use the Opaquetoken properties of `OAuth2ResourceServerProperties` to set up basic auth in the configured `RestTemplate`.
=> Use Opaquetoken properties to configure timeouts

web/src/main/java/org/springframework/security/web/server/DefaultServerRedirectStrategy.java, web/src/main/java/org/springframework/security/web/server/DelegatingServerAuthenticationEntryPoint.java, web/src/main/java/org/springframework/security/web/server/authentication/AnonymousAuthenticationWebFilter.java, web/src/main/java/org/springframework/security/web/server/authentication/AuthenticationWebFilter.java, web/src/main/java/org/springframework/security/web/server/authentication/logout/LogoutWebFilter.java, web/src/main/java/org/springframework/security/web/server/authorization/AuthorizationWebFilter.java, web/src/main/java/org/springframework/security/web/server/authorization/DelegatingReactiveAuthorizationManager.java, web/src/main/java/org/springframework/security/web/server/context/WebSessionServerSecurityContextRepository.java, web/src/main/java/org/springframework/security/web/server/savedrequest/CookieServerRequestCache.java, web/src/main/java/org/springframework/security/web/server/savedrequest/WebSessionServerRequestCache.java, web/src/main/java/org/springframework/security/web/server/util/matcher/AndServerWebExchangeMatcher.java, web/src/main/java/org/springframework/security/web/server/util/matcher/NegatedServerWebExchangeMatcher.java, web/src/main/java/org/springframework/security/web/server/util/matcher/OrServerWebExchangeMatcher.java, web/src/main/java/org/springframework/security/web/server/util/matcher/PathPatternParserServerWebExchangeMatcher.java
Goal is to provide insight to devs on:
- Authentication & Authorization success/failures
- WebSession & SecurityContext
- Request matchers, cache & authn/authz flow
Fixes gh-5758
Please feel free to suggest better log messages (they mostly come from the servlet side)!
=> Add debug logging to Reactive Web

crypto/src/main/java/org/springframework/security/crypto/password/NoOpPasswordEncoder.java
This commit adds extension to deprecation notice.
Fixes gh-8506
=> Document NoOpPasswordEncoder will not be removed

web/src/main/java/org/springframework/security/web/server/csrf/WebSessionServerCsrfTokenRepository.java
The CSRF token is created with a call to UUID.randomUUID which is blocking.
This change ensures this blocking call is done on the bounded elastic scheduler which supports blocking calls.
Fixes gh-8128
=> Create the CSRF token on the bounded elactic scheduler

web/src/main/java/org/springframework/security/web/DefaultRedirectStrategy.java, web/src/test/java/org/springframework/security/web/DefaultRedirectStrategyTests.java
* Spring 5.2.3
* Spring Security 5.2.1
* Tomcat 9.0.7.B
https://github.com/spring-projects/spring-security/pull/4142
`DefaultRedirectStrategy` send redirect to `""` if redirect argument `url` not contains application context path.
But on Tomcat, it may not redirect to the context root as intended.
When `HttpServletResponse#sendRedirect("")`, Tomcat response with empty Location header.
If the request url is `/context-root/login` and response empty Location header:
| Browser | Redierct url | ? |
|---|---|---|
| Chrome | `/context-root/login` | NG |
| Firefox | `/context-root/login` | NG |
| IE 11 | `/context-root` | OK |
https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpServletResponse.html#sendRedirect-java.lang.String-
> If the location is relative without a leading '/' …
=> Throw exception if URL does not include context path when context relative

docs/manual/src/docs/asciidoc/_includes/servlet/authentication/unpwd/jdbc.adoc
* Correct documented default schema to match default schema exposed as classpath resource.
A varchar of size 50 is not large enough for the encoded password.
* Fix Java example of adding users to JdbcUserDetailsManager.
=> Polish JDBC Authentication documentation

docs/manual/src/docs/asciidoc/_includes/about/authentication/password-storage.adoc
Hi, 
As mentioned in the Spring security doc on `BCryptPasswordEncoder`
> The strength of   BCryptPasswordEncoder should be tuned to take about 1 second to verify a password on your system.
However, the default implementation of `BCryptPasswordEncoder` uses a **default strength of 10**. 
On my system (Intel Core i5 CPU-1.60Hz 8 GM RAM), I found that the default implementation takes around **220~250 ms** to verify a password which is clearly way less than 1 second lower limit. 
I think it should be worth **mentioning the default strength of BCryptPasswordEncoder** since all of the Spring projects I have worked with developers tend not to change the default strength which according to the Spring security doc is not secure.  
This can make the developers using the default strength of …
=> Security issue: mentioning the default strength of `BCryptPasswordEncoder`

crypto/src/main/java/org/springframework/security/crypto/password/Md4PasswordEncoder.java
`private Digester digester;`  defined in Md4PasswordEncoder is never used. So remove it.
=> Remove unused field 'digester' in Md4PasswordEncoder

config/src/main/java/org/springframework/security/config/annotation/web/configurers/SessionManagementConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/SessionManagementConfigurerTests.java
If a SessionRegistry is necessary, check for one in the ApplicationContext before creating one.
See https://github.com/spring-projects/spring-session/issues/1629
=> Configuration defaults to SessionRegistry bean

docs/manual/src/docs/asciidoc/_includes/about/authentication/password-storage.adoc
=> Fix typos in BCryptPasswordEncoder documentation

docs/manual/src/docs/asciidoc/_includes/servlet/integrations/websocket.adoc
=> Fix broken link in spring security reference document

.github/workflows/pr-build-workflow.yml
We want to migrate our build pipelines to Github Actions for consistency and ease of use.
Created Github Actions build pipeline for PR requests. This is includes setting up the appropriate JDK, caching Gradle dependencies, and running a Gradle clean build. I've confirmed that the pipeline runs correctly against my forked version of spring-security.
=> Set up Github Actions pipeline for PRs

web/src/main/java/org/springframework/security/web/firewall/StrictHttpFirewall.java, web/src/test/java/org/springframework/security/web/firewall/StrictHttpFirewallTests.java
* Adds `setAllowNull`
* By default, denies null in paths
=> Reject the NULL character in paths in StrictHttpFirewall

web/src/main/java/org/springframework/security/web/FilterInvocation.java, web/src/main/java/org/springframework/security/web/firewall/StrictHttpFirewall.java, web/src/test/java/org/springframework/security/web/firewall/StrictHttpFirewallTests.java
Improvements to StrictHttpFirewall:
* Headers names values should never contain [ISO control characters](https://docs.oracle.com/javase/8/docs/api/java/lang/Character.html#isISOControl-int-) such as NUL, CR, and LF.
* Similarly, parameter names should never contain ISO control characters either. Parameter values can (imagine a multiline text input - that can and should submit CR/LF in its value)
=> StrictHttpFirewall: Validate headers and parameters

web/src/main/java/org/springframework/security/web/csrf/CookieCsrfTokenRepository.java, web/src/test/java/org/springframework/security/web/csrf/CookieCsrfTokenRepositoryTests.java
While using the request's "isSecure" flag is a reasonable default, when webapps sit behind firewalls, sometimes the firewall does the SSL, and the traffic between the firewall and the app is plain HTTP (not HTTPS). In this case the "isSecure" flag on the request is always false, but we still want th XSRF-TOKEN cookie to be secure (the firewall forwards all cookies to the app, and the browser sends the secure cookie to the firewall).
It would be nice if we could configure the desired value for the secure flag of the cookie, just like we can configure the value for the httpOnly flag of the cookie.
=> Add Configurable secure flag in CookieCsrfTokenRepository

acl/src/main/java/org/springframework/security/acls/jdbc/JdbcAclService.java
We don't need array-based `Arrays.asList()` as we always have only one instance `ObjectIdentity` at call site.
=> Use memory-saving Collections.singletonList in JdbcAclService.readAclById()

config/src/main/kotlin/org/springframework/security/config/web/servlet/HttpSecurityDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/servlet/oauth2/login/UserInfoEndpointDsl.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/HttpSecurityDslTests.kt
=> Add reified function variants to security DSL

web/src/main/java/org/springframework/security/web/savedrequest/CookieRequestCache.java, web/src/test/java/org/springframework/security/web/savedrequest/CookieRequestCacheTests.java, web/src/test/java/org/springframework/security/web/savedrequest/RequestCacheAwareFilterTests.java
=> Adds cookie based RequestCache

core/src/main/java/org/springframework/security/authentication/ProviderManager.java
On lines 240 and 257 of the ProviderManager class, the comments may have some problems.
The original note was: If the parent AuthenticationManager was attempted and successful than it will publish an AuthenticationSuccessEvent
The correct one should be: If the parent AuthenticationManager was attempted and successful then it will publish an AuthenticationSuccessEvent
Replace the word than with then.
=> Fix ProviderManager Javadoc typo

web/src/main/java/org/springframework/security/web/savedrequest/SimpleSavedRequest.java, web/src/test/java/org/springframework/security/web/savedrequest/SimpleSavedRequestTests.java
Before:
1. SimpleSavedRequest#getMethod returned null
2. SimpleSavedRequest(SavedRequest request) constructor did not set the method field from the request
After:
1. SimpleSavedRequest#getMethod returns method property value
2. SimpleSavedRequest(SavedRequest request) constructor sets the method field from request
Closes gh-8675
I have submitted the CLA
=> Updated SimpleSavedRequest#getMethod

docs/manual/src/docs/asciidoc/_includes/about/exploits/csrf.adoc, docs/manual/src/docs/asciidoc/_includes/about/exploits/headers.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/appendix/namespace.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/architecture/security-context-holder.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/cas.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/session-management.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/integrations/concurrency.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/integrations/mvc.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/saml2/saml2-login.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/test/method.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/test/mockmvc.adoc
=> Wording changes

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, web/src/main/java/org/springframework/security/web/server/authentication/AuthenticationConverterServerWebExchangeMatcher.java, web/src/test/java/org/springframework/security/web/server/authentication/AuthenticationConverterServerWebExchangeMatcherTests.java
AuthenticationConverterServerWebExchangeMatcher is ServerWebExchangeMatcher implementation based on AuthenticationConverter which matches if ServerWebExchange can be converted to Authentication.
It can be used as a matcher where SecurityFilterChain should be matched based on used authentication method.
BearerTokenServerWebExchangeMatcher was replaced by this matcher.
Closes gh-8824
=> Introduce AuthenticationConverterServerWebExchangeMatcher

config/src/main/kotlin/org/springframework/security/config/web/server/ServerHttpSecurityDsl.kt, config/src/test/kotlin/org/springframework/security/config/web/server/ServerHttpSecurityDslTests.kt
=> Support custom filter in Server Kotlin DSL

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/DefaultSaml2AuthenticatedPrincipal.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationProvider.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/DefaultSaml2AuthenticatedPrincipalTests.java
Rename it to DefaultSaml2AuthenticatedPrincipal to be more in line with
the respective class in the OAuth2 module.
Also make the class public to be able to whitelist the SAML2 auth classes
in Jackson object mappers for deserialization in e.g. Spring Session MongoDB.
Closes gh-8852
=> Update SimpleSaml2AuthenticatedPrincipal class name

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/server/ServerBearerTokenAuthenticationConverter.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/web/server/ServerBearerTokenAuthenticationConverterTests.java
Bearer token was resolved immediately after calling method convert. In situations when malformed token was provided or authorization header and access token query param were present in request exception was thrown instead of signalling error.
After this change Bearer token is resolved on subscription and invalid states are handled by signaling error to subscriber.
Closes gh-8865
=> Resolve Bearer token after subscribing to publisher

config/src/main/java/org/springframework/security/config/annotation/web/WebSecurityConfigurer.java, config/src/main/java/org/springframework/security/config/annotation/web/builders/WebSecurity.java, config/src/main/java/org/springframework/security/config/annotation/web/configuration/EnableWebSecurity.java, config/src/main/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.java, config/src/test/java/org/springframework/security/config/annotation/web/configuration/EnableWebSecurityTests.java, config/src/test/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfigurationTests.java, config/src/test/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurationTests.java
=> Remove need for WebSecurityConfigurerAdapter

config/src/main/kotlin/org/springframework/security/config/web/servlet/AuthorizeRequestsDsl.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/AuthorizeRequestsDslTests.kt
=> Add hasAnyRole and hasAnyAuthority to authorizeRequests in Kotlin DSL

ldap/src/main/java/org/springframework/security/ldap/authentication/BindAuthenticator.java
That code syntax doesn't fit the Java convention.
So, I added whitespace
=> Refactor - apply java code convention

config/src/main/java/org/springframework/security/config/annotation/web/builders/WebSecurity.java, config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityCustomizer.java, config/src/test/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurationTests.java
=> Customizer for WebSecurity

web/src/main/java/org/springframework/security/web/server/csrf/CookieServerCsrfTokenRepository.java
The CSRF token is generated by UUID.randomUUID() which is I/O blocking operation.
This commit changes the subscriber thread to the bounded elactic scheduler.
Fix gh-9018
=> Use Schedulers.boundedElastic for UUID.randomUUID

web/src/main/java/org/springframework/security/web/server/csrf/WebSessionServerCsrfTokenRepository.java
This commit restore broken Mono chain in WebSessionServerCsrfTokenRepository.generateToken(ServerWebExchange).
Closes gh-9017
=> Fix broken Mono chain

crypto/src/main/java/org/springframework/security/crypto/password/DelegatingPasswordEncoder.java
Dear all,
I'm pushing a quick fix for the javadoc of the class `UnmappedIdPasswordEncoder` in `DelegatingPasswordEncoder.java`, which appeared incomplete. It looks like if some text got missing at some point, maybe a typing mistake.
I didn't feel this minor detail required opening an issue.
Please feel free to accept or reject the PR as you see fit.
=> Quick javadoc fix for DelegatingPasswordEncoder

docs/manual/src/docs/asciidoc/_includes/servlet/authentication/x509.adoc
I suggest SSL setup guide link from tomcat6 to tomcat10.
Tomcat 6 document for ssl (SSL is changed by SSL/TLS in tomcat 7,8,9,10 server document) is old.
So, I create pull request.
Also, I think it would better add xsd format in .ignore, So I suggest this file. 
Regards.
=> Replace Tomcat6 URL for SSL Guide to Tomcat 10

config/src/main/java/org/springframework/security/config/annotation/web/configurers/HeadersConfigurer.java
Javadoc for `org.springframework.security.config.annotation.web.configurers.HeadersConfigurer` class contained MSDN blog link that expired in March, 2016 and is not usable since. I decided to replace it with latest possible web archive copy of that blog post (from February, 2016). I didn't create issue for such a minor change, hope it's OK.
=> Replace expired msdn link with latest web archive copy

.github/workflows/pr-build-workflow.yml, build.gradle, settings.gradle
This PR adds build scans to PR builds, making it easier for developers to see their error output at the end of a run.
=> Add build scans to PR builds

CONTRIBUTING.adoc, docs/manual/src/docs/asciidoc/_includes/about/community.adoc
Changes in `CONTRIBUTING.adoc`:
- Syntax corrected
- Links updated
- Improved wording of some paragraphs and fixed typos
- Restored some parts that got lost during conversion to `adoc` format (see: a8b438587b129d455f4c2c93f556fd6c080a19aa)
Changes in `community.adoc`:
- Updated link to `CONTRIBUTING.adoc` (no longer `.md`)
- Corrected name of _Stack Overflow_ according to their [trademark guidelines](https://stackoverflow.com/legal/trademark-guidance) (two words, capital letters)
=> Fixes in documentation

.github/workflows/pr-build-workflow.yml
An issue was raised in Spring Session (https://github.com/spring-projects/spring-session/issues/1678) detailing how builds were running on forked versions of the repo. I fixed the issue in https://github.com/spring-projects/spring-security/pull/8698, this PR adds similar logic to the Spring Security repo to ensure builds don't run on forks.
More detail:
Github Actions doesn't currently have an elegant way to prevent builds on forks. Following the suggestion outlined here, I added checks for each job to ensure it only runs on spring-projects/spring-session.
I opened a PR on my forked version and confirmed that no builds steps ran. See https://github.com/elliedori/spring-security/pull/6/checks?check_run_id=1062839692 for more.
=> Prevent PR builds from running on forks

web/src/main/java/org/springframework/security/web/authentication/session/ConcurrentSessionControlAuthenticationStrategy.java
Check of allowed user sessions count moved to head for avoid unnecessary fetching all user sessions.
Fixes gh-9152
=> Change guard expressions order

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtIssuerValidator.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/JwtIssuerValidatorTests.java
- NimbusJwtDecoder uses claim set converters: issuer claim is converted to an URL object
- JwtIssuerValidator (created by JwtValidators.createDefaultWithIssuer(String)) wraps a JwtClaimValidator<String>
- because of different data types, equal() is always false
This change allows both Strings and URLs as values of the issuer
Issue gh-9136
=> JwtIssuerValidator handles issuer (iss) claim values as Strings and URLs

docs/manual/src/docs/asciidoc/_includes/servlet/appendix/index.adoc
@pivotal-issuemaster This is an Obvious Fix
=> Closes gh-8196 appendix indentation

docs/manual/src/docs/asciidoc/_includes/servlet/appendix/faq.adoc
`ofother ...`
https://docs.spring.io/spring-security/site/docs/current/reference/html5/#appendix-faq-concurrent-session-same-browser
`of other ...`
Generated PDF.
=> [docs]Add white space before strong notation.

crypto/src/main/java/org/springframework/security/crypto/password/Pbkdf2PasswordEncoder.java, crypto/src/test/java/org/springframework/security/crypto/password/Pbkdf2PasswordEncoderTests.java
Add constructors with a salt length input parameter.
Default salt length is still 8-byte long like before when
saltGenerator was initialized with call to
KeyGenerators#secureRandom() which use
SecureRandomBytesKeyGenerator#DEFAULT_KEY_LENGTH.
Closes gh-4372
---
This PR is related to #4372 to make salt length configurable in Pbkdf2PasswordEncoder.
Like mention in the #4372 issue, [NIST Special Publication 800-132](https://csrc.nist.gov/publications/detail/sp/800-132/final) section 5.1 said that salt length shall be at least 128 bits (16 bytes). Current [`Pbkdf2PasswordEncoder`](crypto/src/main/java/org/springframework/security/crypto/password/Pbkdf2PasswordEncoder.java) use a 8-byte (64-bit) random salt with no possibility to configure its length.
Users that want to conform to NIST Special …
=> Make salt length configurable in Pbkdf2PasswordEncoder

web/src/main/java/org/springframework/security/web/context/support/SecurityWebApplicationContextUtils.java
Change to cleanup SecurityWebApplicationContextUtils. Based on the recommendation in the tagged issue. 
> We no longer need to support versions of Spring Framework that old, so we should now call WebApplicationContextUtils.findWebApplicationContext
Closes gh-8868
=> SecurityWebApplicationContextUtils cleanup gh-8868

crypto/src/main/java/org/springframework/security/crypto/password/Pbkdf2PasswordEncoder.java
Fix javadoc in Pbkdf2PasswordEncoder
- Add `@author Loïc Guibert`
- Add `@since 5.5` to new constructors
See PR gh-9147
=> Fix javadoc in Pbkdf2PasswordEncoder

web/src/main/java/org/springframework/security/web/csrf/CookieCsrfTokenRepository.java, web/src/test/java/org/springframework/security/web/csrf/CookieCsrfTokenRepositoryTests.java
Allows maxAge of the generated cookie by CookieCsrfTokenRepository
to be configurable.
Prior to this commit, maximum age was set with a value of -1.
After this commit, it will be configured by the user with an either
positive or negative value. If the user does not provide a value,
it will be set -1.
An IllegalArgumentException will be thrown when
this value is set to zero.
Closes gh-9195
=> Allow maximum age of csrf cookie to be configured

config/src/main/java/org/springframework/security/config/annotation/web/configurers/HeadersConfigurer.java, config/src/main/java/org/springframework/security/config/http/HeadersBeanDefinitionParser.java, config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/main/kotlin/org/springframework/security/config/web/server/ServerHeadersDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerPermissionsPolicyDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/servlet/HeadersDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/servlet/headers/PermissionsPolicyDsl.kt, config/src/main/resources/org/springframework/security/config/spring-security-5.5.rnc, config/src/main/resources/org/springframework/security/config/spring-security-5.5.xsd, config/src/test/java/org/springframework/security/config/annotation/web/configurers/HeadersConfigurerTests.java, config/src/test/java/org/springframework/security/config/http/HttpHeadersConfigTests.java, config/src/test/kotlin/org/springframework/security/config/web/server/ServerPermissionsPolicyDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/HeadersDslTests.kt, config/src/test/resources/org/springframework/security/config/http/HttpHeadersConfigTests-DefaultsDisabledWithPermissionsPolicy.xml, docs/manual/src/docs/asciidoc/_includes/about/exploits/headers.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/exploits/headers.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/exploits/headers.adoc, web/src/main/java/org/springframework/security/web/header/writers/PermissionsPolicyHeaderWriter.java, web/src/main/java/org/springframework/security/web/server/header/PermissionsPolicyServerHttpHeadersWriter.java, web/src/test/java/org/springframework/security/web/header/writers/PermissionsPolicyHeaderWriterTests.java, web/src/test/java/org/springframework/security/web/server/header/PermissionsPolicyServerHttpHeadersWriterTests.java
=> Add permissionsPolicy http header

config/src/main/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistry.java, config/src/test/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistryTests.java, web/src/main/java/org/springframework/security/web/util/matcher/AntPathRequestMatcher.java, web/src/main/java/org/springframework/security/web/util/matcher/DispatcherTypeRequestMatcher.java, web/src/main/java/org/springframework/security/web/util/matcher/RegexRequestMatcher.java, web/src/test/java/org/springframework/security/web/util/matcher/DispatcherTypeRequestMatcherTests.java
Created a DispatcherTypeRequestMatcher and corresponding methods
for configuring an HttpSecurity object. This enables filtering of
security rules based on the dispatcher type of the incoming servlet
request.
Additionally, removed duplicative code for parsing HttpMethod objects
from the AntPathRequestMatcher and RegexRequestMatcher.
Closes gh-9205
=> Introduced DispatcherType request matcher

config/src/main/java/org/springframework/security/config/annotation/web/builders/FilterComparator.java, config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurerTests.java, core/src/main/java/org/springframework/security/authorization/AuthenticatedAuthorizationManager.java, core/src/main/java/org/springframework/security/authorization/AuthorityAuthorizationManager.java, core/src/main/java/org/springframework/security/authorization/AuthorizationManager.java, core/src/test/java/org/springframework/security/authorization/AuthenticatedAuthorizationManagerTests.java, core/src/test/java/org/springframework/security/authorization/AuthorityAuthorizationManagerTests.java, core/src/test/java/org/springframework/security/authorization/AuthorizationManagerTests.java, web/src/main/java/org/springframework/security/web/access/intercept/AuthorizationFilter.java, web/src/main/java/org/springframework/security/web/access/intercept/DelegatingAuthorizationManager.java, web/src/main/java/org/springframework/security/web/access/intercept/RequestAuthorizationContext.java, web/src/test/java/org/springframework/security/web/access/intercept/AuthorizationFilterTests.java, web/src/test/java/org/springframework/security/web/access/intercept/DelegatingAuthorizationManagerTests.java
=> Add AuthorizationManager

config/src/main/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfiguration.java, config/src/test/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurationTests.java
There is no need to autowire the `AuthenticationManager` since we later get it from `this.authenticationConfiguration.getAuthenticationManager()`.
https://github.com/spring-projects/spring-security/blob/7dde7cffda9b03859c954eb06cfb09baa3bbb54f/config/src/main/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfiguration.java#L104-L107
=> Fix bug with multiple AuthenticationManager beans

config/src/test/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurerTests.java, web/src/main/java/org/springframework/security/web/servlet/util/matcher/MvcRequestMatcher.java, web/src/test/java/org/springframework/security/web/servlet/util/matcher/MvcRequestMatcherTests.java
=> Consider Aligning MvcRequestMatcher's matching methods

config/src/main/kotlin/org/springframework/security/config/web/servlet/CorsDsl.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/CorsDslTests.kt
=> Extend CorsDsl with CorsConfigurationSource property

web/src/main/java/org/springframework/security/web/util/matcher/AntPathRequestMatcher.java, web/src/test/java/org/springframework/security/web/util/matcher/AntPathRequestMatcherTests.java
=> Reconsider AntPathRequestMatcher matching logic

config/src/main/kotlin/org/springframework/security/config/web/servlet/HttpSecurityDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/servlet/RememberMeDsl.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/RememberMeDslTests.kt
=> Add RememberMeDsl

core/src/main/java/org/springframework/security/core/ComparableVersion.java
Update ComparableVersion to be a copy of the class in Maven 3.6.3.
Among other improvements, this includes two problems of potential interest:
* https://github.com/apache/maven/commit/3ac9718f8267b2fb9636f1a58acc6bb53356c329 "[MNG-6655] Add support for "release" qualifier "
* https://github.com/apache/maven/commit/445421051c5d364839d3bcdf2fa35e3ecd06e9bc "potential NPE"
I discovered that this class was out of date when I ran a static analysis tool which identified the NPE issue.
=> Update ComparableVersion to version from Maven 3.6.3

crypto/src/main/java/org/springframework/security/crypto/encrypt/AesBytesEncryptor.java
Closes gh-9361
Signed-off-by: Manousos Mathioudakis <manoumathioudakis@yahoo.gr>
=> Add javadoc at constructors.

crypto/src/main/java/org/springframework/security/crypto/encrypt/Encryptors.java
Fix 'See Also' section link issue in Encryptors.standard method.
=> Fix javadoc in crypto/encrypt/Encryptors.java

crypto/src/main/java/org/springframework/security/crypto/encrypt/AesBytesEncryptor.java
Update AesBytesEncryptor constructors' javadoc to:
1. mention default IV length and encryption mode,
2. provide links to appropriate constructors that allow users to specify custom IV and encryption mode.
Related to gh-3879 and gh-9361
=> Update javadoc for AesBytesEncryptor constructors

buildSrc/src/main/groovy/io/spring/gradle/convention/JavadocApiPlugin.groovy
=> Add package-list

config/spring-security-config.gradle, config/src/test/java/org/springframework/security/config/annotation/method/configuration/EnableReactiveMethodSecurityTests.java, config/src/test/kotlin/org/springframework/security/config/annotation/method/configuration/KotlinEnableReactiveMethodSecurityTests.kt, config/src/test/kotlin/org/springframework/security/config/annotation/method/configuration/KotlinReactiveMessageService.kt, config/src/test/kotlin/org/springframework/security/config/annotation/method/configuration/KotlinReactiveMessageServiceImpl.kt, core/spring-security-core.gradle, core/src/main/java/org/springframework/security/access/prepost/PrePostAdviceReactiveMethodInterceptor.java, dependencies/spring-security-dependencies.gradle, docs/manual/src/docs/asciidoc/_includes/reactive/method.adoc
=> Add coroutine support to pre/post authorize

web/src/main/java/org/springframework/security/web/session/SimpleRedirectInvalidSessionStrategy.java
The log message involves string concatenation, the cost of which should only be incurred if debug logging is enabled
=> Add guard around logger.debug statement

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtDecoderProviderConfigurationUtils.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/JwtDecoderProviderConfigurationUtilsTests.java
Fix for https://github.com/spring-projects/spring-security/issues/9651
=> Fix ClassCastException in JwtDecoders fromIssuerLocation

web/src/main/java/org/springframework/security/web/server/csrf/CookieServerCsrfTokenRepository.java, web/src/test/java/org/springframework/security/web/server/csrf/CookieServerCsrfTokenRepositoryTests.java
Make the XSRF-TOKEN cookie secure flag configurable in CookieServerCsrfTokenRepository.
Closes gh-9678
=> Make Csrf cookie secure flag configurable (WebFlux)

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/NimbusOpaqueTokenIntrospector.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/NimbusReactiveOpaqueTokenIntrospector.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/introspection/NimbusReactiveOpaqueTokenIntrospectorTests.java
Update NimbusOpaqueTokenIntrospector and NimbusReactiveOpaqueTokenIntrospector to use MediaType.APPLICATION_JSON instead of the deprecated MediaType.APPLICATION_JSON_UTF8
Closes gh-9353
=>  Update Deprecated Property in Opaque Token Introspectors 

.github/workflows/continuous-integration-workflow.yml
- Add slack integration for error reporting
- Rename from `check_windows` to `build_windows`
- Change the build command to match the one in `build_jdk_11`
- Add `build_windows` to the `needs` of deployment and failure check jobs
Issue gh-9727
=> Update Check Windows CI Workflow

.github/workflows/continuous-integration-workflow.yml
Set environment variables via `env` job property
Fix the name of access key variable
Closes gh-9761, gh-9790
=> Fix Build Scan not being published in Build Windows Job

ldap/src/integration-test/java/org/springframework/security/ldap/DefaultSpringSecurityContextSourceTests.java, ldap/src/integration-test/java/org/springframework/security/ldap/search/FilterBasedLdapUserSearchWithSpacesTests.java, ldap/src/integration-test/resources/test-server-with-spaces.ldif, ldap/src/main/java/org/springframework/security/ldap/DefaultSpringSecurityContextSource.java
Fixes an issue where provider URLs passed to the constructor of the
DefaultSpringSecurityContextSource can be URL encoded, resulting in
an invalid base dn.
Closes gh-9742
=> Handle encoded spaces in the root dn

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/http/OAuth2ErrorResponseErrorHandler.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/http/OAuth2ErrorResponseErrorHandlerTests.java
Fixes an issue where custom status codes in the error response cause an
IllegalArgumentException to be thrown when resolving an HttpStatus.
Closes gh-9741
=> Handle custom status codes in OAuth2ErrorResponseErrorHandler

web/src/main/java/org/springframework/security/web/session/RequestedUrlRedirectInvalidSessionStrategy.java, web/src/test/java/org/springframework/security/web/session/SessionManagementFilterTests.java
Performs a redirect to the original request URL when an invalid requested session is detected.
In effect, when a user's session times out, the user is redirected to URL they originally requested instead of some fixed URL.
I have a number of projects using this implementation, so I suspect it's useful to the wide Spring Security world.
I'm hoping you can give a quick review of this idea. If it seems like it will be acceptable to Spring Security, I'll update this PR with tests.
=> Add RequestedUrlRedirectInvalidSessionStrategy implemention of InvalidSessionStrategy

web/src/main/java/org/springframework/security/web/server/authorization/ExceptionTranslationWebFilter.java, web/src/test/java/org/springframework/security/web/server/authorization/ExceptionTranslationWebFilterTests.java
The ExceptionTranslationWebFilter does not support correctly when
anonymous authentication is enabled. With this enabled provoked always
the execution of the access denied handler, and with this fix it
behaves like the ExceptionTranslationFilter (servlet), executing the
access denied handler only if the principal is not empty and neither
anonymous.
Closes gh-9130
=> Anonymous in ExceptionTranslationWebFilter

web/src/main/java/org/springframework/security/web/context/HttpSessionSecurityContextRepository.java, web/src/test/java/org/springframework/security/web/context/HttpSessionSecurityContextRepositoryTests.java
Ensure that `HttpSessionSecurityContextRepository#isTransientAuthentication` reuses the same authentication object from `SaveToSessionResponseWrapper#saveContext`
Closes gh-8947
=> Adjust createNewSessionIfAllowed to prevent NPE

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/AbstractWebClientReactiveOAuth2AccessTokenResponseClient.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/OAuth2AuthorizationGrantRequestEntityUtils.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/OAuth2ClientCredentialsGrantRequestEntityConverterTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveClientCredentialsTokenResponseClientTests.java
=> URL encode client credentials

oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/endpoint/DefaultMapOAuth2AccessTokenResponseConverter.java, oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/endpoint/DefaultOAuth2AccessTokenResponseMapConverter.java, oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/endpoint/MapOAuth2AccessTokenResponseConverter.java, oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/endpoint/OAuth2AccessTokenResponseMapConverter.java, oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/http/converter/OAuth2AccessTokenResponseHttpMessageConverter.java, oauth2/oauth2-core/src/test/java/org/springframework/security/oauth2/core/endpoint/DefaultMapOAuth2AccessTokenResponseConverterTests.java, oauth2/oauth2-core/src/test/java/org/springframework/security/oauth2/core/endpoint/DefaultOAuth2AccessTokenResponseMapConverterTests.java, oauth2/oauth2-core/src/test/java/org/springframework/security/oauth2/core/http/converter/OAuth2AccessTokenResponseHttpMessageConverterTests.java
Changed the converter used to convert a map into an OAuth2AccessTokenResponse to
support any object as the value, including json numbers and nested objects. Also
deprecated old setters/constructors and added new setters/factory methods.
Closes gh-9685
=> Access Token Response supports any data type

gradle.properties
=> Remove hard dependency on Kotlin

config/src/main/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.java
This PR adds the infrastructure role to the methodSecurityMetadataSource bean.
As there is another bean that is logged as non eligible for post processing this is only a partial fix for https://github.com/spring-projects/spring-security/issues/9845. Unfortunately I have not yet found a way to fix this. I will continue the discussion about the missing bean in the issue.
=> Mark methodSecurityMetadataSource as infrastructure bean

config/src/main/java/org/springframework/security/config/annotation/web/builders/FilterOrderRegistration.java, config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java, config/src/test/java/org/springframework/security/config/annotation/web/builders/FilterOrderRegistrationTests.java, config/src/test/java/org/springframework/security/config/annotation/web/builders/HttpSecurityAddFilterTest.java
- Prevent already defined filter's positions to be overriden
Closes gh-9787
=> Fix Adding Filter Relative to Custom Filter

core/src/main/resources/org/springframework/security/messages_zh_CN.properties, core/src/main/resources/org/springframework/security/messages_zh_TW.properties
Partially fix gh-9315
Add chinese translation missing for ExceptionTranslationFilter.insufficientAuthentication in messages_zh_CN.properties and messages_zh_TW.properties
=> Add insufficient authentication message for Simplified Chinese and Traditional Chinese

core/src/main/resources/org/springframework/security/messages_fr.properties
Partially fix gh-9315
This PR add french translation missing for ExceptionTranslationFilter.insufficientAuthentication in messages_fr.properties
=> Add insufficient authentication message for French

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/server/WebSessionOAuth2ServerAuthorizationRequestRepository.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/server/WebSessionOAuth2ServerAuthorizationRequestRepositoryAllowMultipleAuthorizationRequestsTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/server/WebSessionOAuth2ServerAuthorizationRequestRepositoryDoNotAllowMultipleAuthorizationRequestsTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/server/WebSessionOAuth2ServerAuthorizationRequestRepositoryTests.java
WebFlux version of gh-9649. Additionally aligns `WebSessionOAuth2ServerAuthorizationRequestRepository` with `HttpSessionOAuth2AuthorizationRequestRepository` in terms of internal class structure.
=> Store one request by default in WebSessionOAuth2ServerAuthorizationRequestRepository

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2ResourceServerSpecTests.java
When a bean of type ReactiveJwtAuthenticationConverter is defined,
the OAuth2 Resource Server configuration will use it automatically
when no other converter is defined through the DSL.
Closes gh-9698
=> Load ReactiveJwtAuthenticationConverter bean in OAuth2 Resource Server config

test/src/main/java/org/springframework/security/test/web/reactive/server/SecurityMockServerConfigurers.java
SecurityMockServerConfigurers.java previously used the StringUtils from
the optional oauth2-oidc-sdk dependency. Replacing this with the
StringUtils from the spring framework this should not force adding the
dependency in cases where it is not actually used.
Closes gh-9923
@pivotal-cla This is an Obvious Fix
=> Replace StringUtils from oauth2-oidc-sdk

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistrations.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/registration/ClientRegistrationsTests.java
=> Support additional client authentication methods

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/OAuth2AuthorizationRequestRedirectFilter.java
=> fix typo preventing full exception to be  displayed in log

config/src/main/java/org/springframework/security/config/authentication/AuthenticationManagerBeanDefinitionParser.java, config/src/test/java/org/springframework/security/config/authentication/AuthenticationManagerBeanDefinitionParserTests.java
The DefaultAuthenticationEventPublisher is now an inner bean of the ProviderManager.
I would advise to avoid publishing multiple copies of generated inner beans to the global scope, rather either publish a singleton once or generate inner beans which are not visible to others
Note: I haven't pushed any test (yet), and also could not run unit tests in local IDE. Probably some bot here will run anti regression tests.
For the tests, I have taken a look at AuthenticationManagerBuilderTests.
Here are some ideas:
- Test that no more AuthenticationEventPublisher beans are in the Spring context
Before implementing the change: executing the Builder resulted in both a bean of type ProviderManager and a bean of type AuthenticationEventPublisher to be visible in Spring scope. After implementation …
=> XML Exposes Only Single AuthenticationEventPublisher Bean

docs/manual/src/docs/asciidoc/_includes/servlet/saml2/saml2-login.adoc, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistrations.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistrationsTests.java
Update SAML2 Login reference documentation to reflect the changes
Closes gh-9558
=> Allow Creating RelyingPartyRegistration from Metadata InputStream

docs/manual/src/docs/asciidoc/_includes/servlet/saml2/saml2-login.adoc, saml2/saml2-service-provider/src/opensaml4Main/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml4AuthenticationProvider.java, saml2/saml2-service-provider/src/opensaml4Test/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml4AuthenticationProviderTests.java
Add a setter method into OpenSaml4AuthenticationProvider that allows defining a custom ResponseValidator
Closes gh-9721
=> Allow Defining Custom SAML Response Validator

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationRequestFilter.java
Fix (maybe copy-paste?) error in Saml2WebSsoAuthenticationRequestFilter. It responds to requests on `/saml2/authenticate/{registrationId}`.
=> Fix Saml2WebSsoAuthenticationRequestFilter javadoc

core/src/main/java/org/springframework/security/provisioning/InMemoryUserDetailsManager.java, core/src/test/java/org/springframework/security/provisioning/InMemoryUserDetailsManagerTests.java
Check if the UserAttribute is null when instantiating the InMemoryUserDetailsManager using the Properties argument's constructor
Closes gh-3403
=> Improve Error Message for Invalid Properties in InMemoryUserDetailsManager 

config/src/main/java/org/springframework/security/config/Elements.java, config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/PasswordManagementConfigurer.java, config/src/main/java/org/springframework/security/config/http/HttpConfigurationBuilder.java, config/src/main/java/org/springframework/security/config/http/SecurityFilters.java, config/src/main/java/org/springframework/security/config/http/WellKnownChangePasswordBeanDefinitionParser.java, config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/main/kotlin/org/springframework/security/config/web/server/ServerHttpSecurityDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/server/ServerPasswordManagementDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/servlet/HttpSecurityDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/servlet/PasswordManagementDsl.kt, config/src/main/resources/org/springframework/security/config/spring-security-5.6.rnc, config/src/main/resources/org/springframework/security/config/spring-security-5.6.xsd, config/src/test/java/org/springframework/security/config/annotation/web/configurers/PasswordManagementConfigurerTests.java, config/src/test/java/org/springframework/security/config/http/WellKnownChangePasswordBeanDefinitionParserTests.java, config/src/test/java/org/springframework/security/config/web/server/PasswordManagementSpecTests.java, config/src/test/kotlin/org/springframework/security/config/web/server/ServerPasswordManagementDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/PasswordManagementDslTests.kt, config/src/test/resources/org/springframework/security/config/http/WellKnownChangePasswordBeanDefinitionParserTests-CustomChangePasswordPage.xml, config/src/test/resources/org/springframework/security/config/http/WellKnownChangePasswordBeanDefinitionParserTests-DefaultChangePasswordPage.xml, docs/manual/src/docs/asciidoc/_includes/servlet/appendix/namespace.adoc, web/src/main/java/org/springframework/security/web/RequestMatcherRedirectFilter.java, web/src/main/java/org/springframework/security/web/server/ExchangeMatcherRedirectWebFilter.java, web/src/test/java/org/springframework/security/web/RequestMatcherRedirectFilterTests.java, web/src/test/java/org/springframework/security/web/server/ExchangeMatcherRedirectWebFilterTests.java
=> Support A Well-Known URL for Changing Passwords

docs/manual/src/docs/asciidoc/_includes/servlet/oauth2/oauth2-resourceserver.adoc
If I'm looking at the correct class (in nimbus-jose-7.8.1), there needs to be an extra 's' in the name of the classes here. I was searching for the name copied from the IDE and wasn't finding any matches.
=> Fix a typo in some class names in the oauth documentation

core/src/main/java/org/springframework/security/converter/RsaKeyConverters.java, core/src/test/java/org/springframework/security/converter/RsaKeyConvertersTests.java
Support for X509 Certificate in RsaKeyConverters
=> Support for X509 Certificate in RsaKeyConverters #9736

docs/manual/src/docs/asciidoc/_includes/servlet/authentication/events.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/oauth2/oauth2-resourceserver.adoc
This PR fixes https://github.com/spring-projects/spring-security/issues/10062
1. Replaces references to AuthenticationFailureEvent, which does exist, with AbstractAuthenticationFailureEvent. in file docs/manual/src/docs/asciidoc/_includes/servlet/authentication/events.adoc
2. Replace reference to AuthenticationFailureEvent, which does not exist, with AuthenticationFailureBadCredentialsEvent(matches Kotlin version) in file docs/manual/src/docs/asciidoc/_includes/servlet/oauth2/oauth2-resourceserver.adoc
=> Fixes references to AuthenticationFailureEvent, which does not exist

.github/workflows/continuous-integration-workflow.yml, build.gradle, buildSrc/src/main/groovy/io/spring/gradle/IncludeRepoTask.groovy, buildSrc/src/main/groovy/io/spring/gradle/convention/IncludeCheckRemotePlugin.groovy, buildSrc/src/main/resources/META-INF/gradle-plugins/io.spring.convention.include-check-remote.properties, buildSrc/src/test/java/io/spring/gradle/convention/IncludeCheckRemotePluginTest.java
Creates a new Gradle task named `checkSamples` which clones and performs a `./gradlew check` on the Samples project.
Adds a new job in the CI workflow which runs the new `checkSamples` task.
Closes gh-9846
=> Verify Samples in Build

config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LoginConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LoginConfigurerTests.java, docs/manual/src/docs/asciidoc/_includes/servlet/saml2/saml2-login.adoc, saml2/saml2-service-provider/spring-security-saml2-service-provider.gradle, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2AuthenticationToken.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/servlet/HttpSessionSaml2AuthenticationRequestRepository.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/servlet/Saml2AuthenticationRequestRepository.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationFilter.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationRequestFilter.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/Saml2AuthenticationTokenConverter.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/TestSaml2AuthenticationTokens.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/servlet/HttpSessionSaml2AuthenticationRequestRepositoryTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationFilterTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationRequestFilterTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/Saml2AuthenticationTokenConverterTests.java
=> Add Saml2AuthenticationRequestRepository

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/OAuth2LoginAuthenticationFilter.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/OAuth2LoginAuthenticationFilterTests.java
=> Add converter for authentication result in OAuth2LoginAuthenticationFilter

etc/checkstyle/checkstyle-suppressions.xml, oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/OAuth2TokenIntrospectionClaimAccessor.java, oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/OAuth2TokenIntrospectionClaimNames.java, oauth2/oauth2-core/src/test/java/org/springframework/security/oauth2/core/OAuth2TokenIntrospectionClaimAccessorTests.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/OpaqueTokenAuthenticationProvider.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/OpaqueTokenReactiveAuthenticationManager.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/NimbusOpaqueTokenIntrospector.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/NimbusReactiveOpaqueTokenIntrospector.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/OAuth2IntrospectionClaimAccessor.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/core/TestOAuth2AuthenticatedPrincipals.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/BearerTokenAuthenticationTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/OpaqueTokenAuthenticationProviderTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/OpaqueTokenReactiveAuthenticationManagerTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/introspection/NimbusOpaqueTokenIntrospectorTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/introspection/NimbusReactiveOpaqueTokenIntrospectorTests.java, test/src/main/java/org/springframework/security/test/web/reactive/server/SecurityMockServerConfigurers.java, test/src/main/java/org/springframework/security/test/web/servlet/request/SecurityMockMvcRequestPostProcessors.java, test/src/test/java/org/springframework/security/test/web/reactive/server/SecurityMockServerConfigurerOpaqueTokenTests.java
Introduced OAuth2TokenIntrospectionClaimAccessor and OAuth2TokenIntrospectionClaimNames
with copied implementation from OAuth2IntrospectionClaimAccessor/Names.
OAuth2IntrospectionClaimAccessor and OAuth2IntrospectionClaimNames are
now deprecated.
Also method getScopes() returning list of scopes was introduced
and getScope() is now deprecated. Intention is to change return type of
getScope() from String to List<String> and then deprecate getScopes()
method.
Closes gh-9647
=> Move and rename OAuth2IntrospectionClaimAccessor/Names

web/src/main/java/org/springframework/security/web/server/authentication/logout/WebSessionServerLogoutHandler.java, web/src/test/java/org/springframework/security/web/server/authentication/logout/WebSessionServerLogoutHandlerTests.java
As discussed in #8971, this PR is introducing `WebSessionServerLogoutHandler` and closes #4838.
=> Introducing WebSessionServerLogoutHandler

config/src/main/java/org/springframework/security/config/annotation/web/configurers/ExpressionUrlAuthorizationConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/ExpressionUrlAuthorizationConfigurerTests.java
=> Replace static "ROLE_" with customized role prefix

config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LoginConfigurer.java
Fix the return type of Saml2LoginConfigurer.relyingPartyRegistrationRepository so that further spring security configuration can be done with the and() method.
gh-10245
=> Fix return type to allow further security config

core/src/main/java/org/springframework/security/core/context/GlobalSecurityContextHolderStrategy.java, core/src/main/java/org/springframework/security/core/context/InheritableThreadLocalSecurityContextHolderStrategy.java, core/src/main/java/org/springframework/security/core/context/ListeningSecurityContextHolderStrategy.java, core/src/main/java/org/springframework/security/core/context/SecurityContextHolder.java, core/src/main/java/org/springframework/security/core/context/ThreadLocalSecurityContextHolderStrategy.java, core/src/test/java/org/springframework/security/core/context/ListeningSecurityContextHolderStrategyTests.java, core/src/test/java/org/springframework/security/core/context/SecurityContextHolderTests.java
=> Replace SecurityContextHolder#addListener

docs/manual/src/docs/asciidoc/_includes/reactive/test.adoc
This PR updates the references to `SecurityMockServerConfigurers` to use the correct method names.  It also adds documentation for `mockJwt()` and includes the reference to `SecurityMockServerConfigurers`.
Closes #10254
=> Updated the Reactive Test Support Documentation references for `SecurityMockServerConfigurers`

docs/manual/src/docs/asciidoc/_includes/about/authentication/password-storage.adoc, docs/manual/src/docs/asciidoc/_includes/about/exploits/csrf.adoc, docs/manual/src/docs/asciidoc/_includes/about/exploits/headers.adoc, docs/manual/src/docs/asciidoc/_includes/about/exploits/http.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/oauth2/resource-server.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/webflux.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/architecture/delegating-filter-proxy.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/architecture/exception-translation-filter.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/anonymous.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/architecture/authentication.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/architecture/security-context-holder.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/cas.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/index.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/jaas.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/logout.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/rememberme.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/runas.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/session-management.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/unpwd/basic.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/unpwd/form.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/unpwd/in-memory.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authorization/acls.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authorization/architecture.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authorization/expression-based.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authorization/secure-objects.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/exploits/firewall.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/java-configuration/index.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/oauth2/oauth2-resourceserver.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/saml2/saml2-login.adoc
Feel free to drop any changes you don't like.
@pivotal-cla This is an Obvious Fix
=> Minor documentation fixes

config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LoginConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LoginConfigurerTests.java
=> Update Saml2LoginConfigurer to pick up Saml2AuthenticationTokenConverter bean

docs/manual/src/docs/asciidoc/_includes/servlet/test/mockmvc.adoc, etc/checkstyle/checkstyle.xml, test/src/main/java/org/springframework/security/test/web/servlet/response/SecurityMockMvcResultHandlers.java, test/src/test/java/org/springframework/security/test/web/servlet/response/SecurityMockMvcResultHandlersTest.java
Create SecurityMockMvcResultHandlers to define security related MockMvc ResultHandlers
Create a method to allow copying the SecurityContext from the TestSecurityContextHolder to SecurityContextHolder
Closes gh-9565
=> Propagate TestSecurityContextHolder to SecurityContextHolder

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtDecoderInitializationException.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/SupplierJwtDecoder.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/SupplierReactiveJwtDecoder.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/SupplierJwtDecoderTests.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/SupplierReactiveJwtDecoderTests.java
Closes gh-9991
**UPDATE** - @rwinch and I chatted, and we'll leave gh-10309 out for now to keep the review smaller.
To use, you can publish a `JwtDecoder` like so:
```java
@Bean 
JwtDecoder jwtDecoder() {
Supplier<JwtDecoder> supplier = () -> JwtDecoder.withIssuerLocation("http://issuer/location");
return new SupplierJwtDecoder(supplier);
}
```
Spring Boot could publish a `SupplierJwtDecoder` instead of a `NimbusJwtDecoder`.
=> Add Supplier JwtDecoders

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationFilter.java, saml2/saml2-service-provider/src/opensaml4Main/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml4AuthenticationProvider.java, saml2/saml2-service-provider/src/opensaml4Test/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml4AuthenticationProviderTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationFilterTests.java
=> Saml2WebSsoAuthenticationFilter adds authentication details

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/server/ServerBearerTokenAuthenticationConverter.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/web/server/ServerBearerTokenAuthenticationConverterTests.java
Check for multiple access tokens on the ServerHttpRequest rather than get get first. If multiples are found throw a OAuth2AuthenticationException.
Closes gh-5708
=> Check for multiple access tokens per rfc 6750

config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LoginConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LoginConfigurerTests.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationFilter.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationFilterTests.java
Fixes an issue with the `Saml2WebSsoAuthenticationFilter` where it was not possible to register a `loginProcessingUrl` without the `registrationId` path variable.
Closes gh-10176
=> Allow SAML 2.0 `loginProcessingUrl` without `registrationId` path variable

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/JwtBearerReactiveOAuth2AuthorizedClientProvider.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveJwtBearerTokenResponseClient.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/JwtBearerReactiveOAuth2AuthorizedClientProviderTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveJwtBearerTokenResponseClientTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/reactive/function/client/ServerOAuth2AuthorizedClientExchangeFilterFunctionTests.java
=> Implement reactive support for JWT as an Authorization Grant

docs/modules/ROOT/pages/reactive/oauth2/access-token.adoc, docs/modules/ROOT/pages/reactive/oauth2/resource-server.adoc, docs/modules/ROOT/pages/servlet/configuration/java.adoc, docs/modules/ROOT/pages/servlet/oauth2/oauth2-resourceserver.adoc, docs/modules/ROOT/pages/servlet/saml2/index.adoc, docs/modules/ROOT/pages/servlet/saml2/saml2-login.adoc, docs/modules/ROOT/pages/servlet/test/mockmvc.adoc
Also using AsciiDoc style listings instead of Markdown style listings, and using explicit section IDs on all cross-references.
**Background:** I'm maintaining the IntelliJ AsciiDoc plugin that also supports Antora. When I publish new releases, I sometimes pick some public AsciiDoc/Antora documentation and run the plugin's validations. 
Some minor left-overs of the conversion showed up, and I submitted a PR. 
Thanks for providing this this project including its docs!
=> Fix Antora cross-references that lead to other pages.

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/AbstractWebClientReactiveOAuth2AccessTokenResponseClient.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveAuthorizationCodeTokenResponseClientTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveClientCredentialsTokenResponseClientTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveJwtBearerTokenResponseClientTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/WebClientReactivePasswordTokenResponseClientTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveRefreshTokenTokenResponseClientTests.java
This adds support for configuring NimbusJwtClientAuthenticationParametersConverter to any AbstractWebClientReactiveOAuth2AccessTokenResponseClient as an additional parameters converter, which in turns adds reactive support for jwt client authentication.
Closes gh-10146
=> Add parameters converter support to AbstractWebClientReactiveOAuth2AccessTokenResponseClient

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/reactive/oauth2/index.adoc, docs/modules/ROOT/pages/reactive/oauth2/login.adoc, docs/modules/ROOT/pages/reactive/oauth2/login/advanced.adoc, docs/modules/ROOT/pages/reactive/oauth2/login/core.adoc, docs/modules/ROOT/pages/reactive/oauth2/login/index.adoc, docs/modules/ROOT/pages/servlet/oauth2/login/advanced.adoc
=> Revamp Reactive OAuth 2.0 Login documentation

config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.java
While I was working with Native, I've noticed that the injection point metadata is changed by a SpEL expression that I found confusing. If the `@Value` does not apply, the regular behaviour of framework is to inject all bean of that types it knows about.
This commit removes the use of SpEL expression and replaces it with an explicit call to the underlying method. This has the effect of not exposing an additional bean. Additionally, we could move that logic in the configuration class itself.
=> Avoid using SpEL to change the meaning of the injection point

buildSrc/build.gradle, buildSrc/src/main/groovy/io/spring/gradle/convention/DocsPlugin.groovy, buildSrc/src/main/groovy/io/spring/gradle/convention/RepositoryConventionPlugin.groovy, buildSrc/src/test/java/io/spring/gradle/convention/RepositoryConventionPluginTests.java, settings.gradle
This fixes the deprecation warnings emitted by Gradle 7.2:
```
enableFeaturePreview('VERSION_ORDERING_V2') has been deprecated. This is scheduled to be removed in Gradle 8.0. The feature flag is no longer relevant, please remove it from your settings file. See https://docs.gradle.org/7.2/userguide/feature_lifecycle.html#feature_preview for more details.
at settings_dfhlxatnqhe7e8c2fo902wxnx.run(/Users/larsgrefer/git/spring-projects/spring-security/settings.gradle:13)
(Run with --stacktrace to get the full stack trace of this deprecation warning.)
> Configure project :buildSrc
The RepositoryHandler.jcenter() method has been deprecated. This is scheduled to be removed in Gradle 8.0. JFrog announced JCenter's sunset in February 2021. Use mavenCentral() instead. Consult the upgrading guide …
```
=> Fix Gradle Deprecation Warnings

docs/modules/ROOT/pages/features/authentication/password-storage.adoc
Fixes the return type of the bean factory method for a `NoOpPasswordEncoder` in the reference documentation.
The return type must be `PasswordEncoder` as that is the return type of `NoOpPasswordEncoder::getInstance`. The code snippet for Kotlin is correct.
=> Fix return type for NoOpPasswordEncoder bean in documentation

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtClaimValidator.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/JwtClaimValidatorTests.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/JwtTimestampValidatorTests.java
Previously JWTValidator could return any OAuth2Error like invalid_request. But validators were only allowed
to return invalid_token errors. Therefore Validators are now enforced to return invalid_token errors
by introducing the OAuth2InvalidTokenError class.
Closes gh-10337
=> Fix JwtClaimValidator error type

config/src/main/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurer.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/PermitAllSupport.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/PermitAllSupportTests.java, web/src/main/java/org/springframework/security/web/access/intercept/RequestMatcherDelegatingAuthorizationManager.java, web/src/test/java/org/springframework/security/web/access/intercept/RequestMatcherDelegatingAuthorizationManagerTests.java
PermitAllSupport supports either an ExpressionUrlAuthorizationConfigurer or an AuthorizeHttpRequestsConfigurer. If none or both are configured an error message is thrown.
Closes gh-10482
CLA was submitted.
=> PermitAllSupport supports AuthorizeHttpRequestsConfigurer

web/src/main/java/org/springframework/security/web/server/header/StaticServerHttpHeadersWriter.java, web/src/test/java/org/springframework/security/web/server/header/StaticServerHttpHeadersWriterTests.java
=> Fix case sensitive headers comparison

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/main/kotlin/org/springframework/security/config/web/server/AuthorizeExchangeDsl.kt, config/src/test/kotlin/org/springframework/security/config/web/server/AuthorizeExchangeDslTests.kt
=> Add hasIpAddress to Reactive Kotlin DSL

config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java, config/src/test/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfigurationTests.java
=> Prevent using both `authorizeRequests` and `authorizeHttpRequests`

core/src/main/java/org/springframework/security/authorization/AuthorityAuthorizationManager.java, core/src/main/java/org/springframework/security/authorization/AuthorityReactiveAuthorizationManager.java, core/src/test/java/org/springframework/security/authorization/AuthorityAuthorizationManagerTests.java, core/src/test/java/org/springframework/security/authorization/AuthorityReactiveAuthorizationManagerTests.java
=> Fix the bug that the custom GrantedAuthority comparison fails

config/src/main/java/org/springframework/security/config/annotation/web/builders/WebSecurity.java, config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.java, config/src/test/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurationTests.java, web/src/main/java/org/springframework/security/web/access/AuthorizationManagerWebInvocationPrivilegeEvaluator.java, web/src/main/java/org/springframework/security/web/access/RequestMatcherDelegatingWebInvocationPrivilegeEvaluator.java, web/src/main/java/org/springframework/security/web/access/intercept/AuthorizationFilter.java, web/src/main/java/org/springframework/security/web/debug/DebugFilter.java, web/src/main/java/org/springframework/security/web/util/matcher/RequestMatcherEntry.java, web/src/test/java/org/springframework/security/web/access/AuthorizationManagerWebInvocationPrivilegeEvaluatorTests.java, web/src/test/java/org/springframework/security/web/access/RequestMatcherDelegatingWebInvocationPrivilegeEvaluatorTests.java, web/src/test/java/org/springframework/security/web/access/TestWebInvocationPrivilegeEvaluator.java, web/src/test/java/org/springframework/security/web/access/intercept/AuthorizationFilterTests.java, web/src/test/java/org/springframework/security/web/util/matcher/RequestMatcherEntryTests.java
=> Configure WebInvocationPrivilegeEvaluator for multiple `SecurityFilterChain`s
