spring-projects/spring-security

build.gradle
buildSrc/build.gradle
buildSrc/src/main/java/org/springframework/gradle/github/RepositoryRef.java
buildSrc/src/main/java/org/springframework/gradle/github/changelog/GitHubChangelogPlugin.java
buildSrc/src/main/java/org/springframework/gradle/github/milestones/GitHubMilestoneApi.java
buildSrc/src/main/java/org/springframework/gradle/github/milestones/GitHubMilestoneHasNoOpenIssuesTask.java
buildSrc/src/main/java/org/springframework/gradle/github/milestones/GitHubMilestonePlugin.java
buildSrc/src/main/java/org/springframework/gradle/github/release/CreateGitHubReleaseTask.java
buildSrc/src/main/java/org/springframework/gradle/github/release/GitHubReleaseApi.java
buildSrc/src/main/java/org/springframework/gradle/github/release/GitHubReleasePlugin.java
buildSrc/src/main/java/org/springframework/gradle/github/release/Release.java
buildSrc/src/test/java/io/spring/gradle/github/milestones/GitHubMilestoneApiTests.java
buildSrc/src/test/java/org/springframework/gradle/github/milestones/GitHubMilestoneApiTests.java
buildSrc/src/test/java/org/springframework/gradle/github/release/GitHubReleaseApiTests.java

Add GitHubReleasePlugin with createGitHubRelease task

---

config/spring-security-config.gradle
config/src/integration-test/java/org/springframework/security/config/ldap/EmbeddedLdapServerContextSourceFactoryBeanITests.java
config/src/integration-test/java/org/springframework/security/config/ldap/LdapBindAuthenticationManagerFactoryITests.java
config/src/integration-test/java/org/springframework/security/config/ldap/LdapPasswordComparisonAuthenticationManagerFactoryITests.java
config/src/main/java/org/springframework/security/config/ldap/AbstractLdapAuthenticationManagerFactory.java
config/src/main/java/org/springframework/security/config/ldap/EmbeddedLdapServerContextSourceFactoryBean.java
config/src/main/java/org/springframework/security/config/ldap/LdapBindAuthenticationManagerFactory.java
config/src/main/java/org/springframework/security/config/ldap/LdapPasswordComparisonAuthenticationManagerFactory.java
itest/ldap/embedded-ldap-mode-unboundid/src/integration-test/resources/users.ldif
ldap/src/main/java/org/springframework/security/ldap/server/ApacheDSContainer.java
ldap/src/main/java/org/springframework/security/ldap/server/EmbeddedLdapServerContainer.java
ldap/src/main/java/org/springframework/security/ldap/server/UnboundIdContainer.java

This PR introduces a `LdapAuthenticationManagerFactoryBean` and `LdapContextSourceFactoryBean` which can be used to create an `AuthenticationManager` that can perform LDAP authentication.
This is an example usage
```java
@Bean
public EmbeddedLdapServerContextSourceFactoryBean contextSourceFactoryBean() {
EmbeddedLdapServerContextSourceFactoryBean contextSourceFactoryBean =
EmbeddedLdapServerContextSourceFactoryBean.fromEmbeddedLdapServer();
contextSourceFactoryBean.setPort(0);
return contextSourceFactoryBean;
}
@Bean
AuthenticationManager authenticationManager(BaseLdapPathContextSource contextSource) {
LdapBindAuthenticationManagerFactory factory = new LdapBindAuthenticationManagerFactory(contextSource);
factory.setUserDnPatterns("uid={0},ou=people"); …
```

Add LDAP AuthenticationManager factory

---

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/AbstractSaml2AuthenticationRequest.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/Saml2PostAuthenticationRequestTests.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/Saml2RedirectAuthenticationRequestTests.java

Make Saml2AuthenticationRequests serializable

---

web/src/main/java/org/springframework/security/web/authentication/RequestMatcherDelegatingAuthenticationManagerResolver.java
web/src/main/java/org/springframework/security/web/server/authentication/ServerWebExchangeDelegatingReactiveAuthenticationManagerResolver.java
web/src/test/java/org/springframework/security/web/authentication/RequestMatcherDelegatingAuthenticationManagerResolverTests.java
web/src/test/java/org/springframework/security/web/server/authentication/ServerWebExchangeDelegatingReactiveAuthenticationManagerResolverTests.java

Add Request AuthenticationManagerResolvers

---

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/DefaultSaml2AuthenticatedPrincipal.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2AuthenticatedPrincipal.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSamlLogoutRequestResolver.java
saml2/saml2-service-provider/src/opensaml4Main/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml4AuthenticationProvider.java
saml2/saml2-service-provider/src/opensaml4Test/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml4AuthenticationProviderTests.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/TestOpenSamlObjects.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSamlLogoutRequestResolverTests.java

Add Session Index Support

---

docs/modules/ROOT/pages/servlet/saml2/login/index.adoc

Fix this link to point to 
https://github.com/spring-projects/spring-security-samples/tree/5.6.x/servlet/spring-boot/java/saml2/login 
instead of 
https://github.com/spring-projects/spring-security-samples/tree/5.6.x/servlet/spring-boot/java/saml2-login

Fix broken link to SAML2 login example

---

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/OpenSamlAssertingPartyDetails.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/OpenSamlMetadataAssertingPartyDetailsConverter.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/OpenSamlRelyingPartyRegistrationBuilderHttpMessageConverter.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistration.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistrations.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/registration/OpenSamlMetadataAssertingPartyDetailsConverterTests.java

Add OpenSamlAssertingPartyDetails

---

config/src/main/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfiguration.java
config/src/test/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfigurationTests.java

Apply configurers from spring.factories to HttpSecurity bean

---

web/src/main/java/org/springframework/security/web/authentication/WebAuthenticationDetails.java
web/src/test/java/org/springframework/security/web/jackson2/WebAuthenticationDetailsMixinTests.java

Make WebAuthenticationDetails constructor public

---

docs/modules/ROOT/pages/reactive/oauth2/client/client-authentication.adoc
docs/modules/ROOT/pages/servlet/oauth2/client/client-authentication.adoc
oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/NimbusJwtClientAuthenticationParametersConverter.java
oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/NimbusJwtClientAuthenticationParametersConverterTests.java

Add support for customizing claims in JWT Client Assertion

---

.github/workflows/continuous-integration-workflow.yml
.github/workflows/release-next-version.yml

Update CI pipeline to push next snapshot version after release

---

dependencies/spring-security-dependencies.gradle

Update spring-data-bom to 2022.0.0-M2

---

config/src/main/kotlin/org/springframework/security/config/annotation/web/AbstractRequestMatcherDsl.kt
config/src/main/kotlin/org/springframework/security/config/annotation/web/AuthorizeHttpRequestsDsl.kt
config/src/main/kotlin/org/springframework/security/config/annotation/web/AuthorizeRequestsDsl.kt
config/src/main/kotlin/org/springframework/security/config/annotation/web/HttpSecurityDsl.kt
config/src/test/kotlin/org/springframework/security/config/annotation/web/AuthorizeHttpRequestsDslTests.kt
config/src/test/kotlin/org/springframework/security/config/annotation/web/HttpSecurityDslTests.kt

Closes gh-10481
Comparing to `AuthorizeRequestsDslTests`, the newly added `AuthorizeHttpRequestsDslTests` does not include the following test:
```
@Test
fun `request when secured by mvc path variables then responds based on path variable value`() {
this.spring.register(MvcMatcherPathVariablesConfig::class.java).autowire()
this.mockMvc.get("/user/user")
.andExpect {
status { isOk() }
}
this.mockMvc.get("/user/deny")
.andExpect {
status { isForbidden() }
}
}
@EnableWebSecurity
@EnableWebMvc
open class MvcMatcherPathVariablesConfig {
@Bean
open fun securityFilterChain(http: HttpSecurity): SecurityFilterChain {
http {
authorizeHttpRequests {
authorize("/user/{userName}", "#userName == 'user'")
}
}
return http.build()
}
@RestController
internal class PathController { …
```

Add authorizeHttpRequests to Kotlin DSL

---

docs/modules/ROOT/pages/servlet/saml2/login/authentication-requests.adoc

looks like `ping` is some registration id used in the past.

Fix saml2 authentication-requests documentation

---

build.gradle
buildSrc/src/test/java/io/spring/gradle/convention/sagan/SaganApiTests.java

This PR does the following:
- Updated `saganCreateRelease` task with the new `referenceDocUrl` for reference documentation
- Updated `sagan` plugin unit tests
Issue gh-11016

Update saganCreateRelease property referenceDocUrl

---

crypto/src/main/java/org/springframework/security/crypto/password/DelegatingPasswordEncoder.java
crypto/src/test/java/org/springframework/security/crypto/password/DelegatingPasswordEncoderTests.java

You can inject prefix and suffix when calling the constructor of `DelegatingPasswordEncoder`. And you can also inject the **"same"** prefix and suffix. In this case the instantiation of `DelegatingPasswordEncoder` works fine, but calling the `matches(CharSequence, String)` method throws an exception. There is a bug in the methods `extractId(String)` and `extractEncodedPassword(String)`.

Make the `DelegatingPasswordEncoder` work correctly, even if the prefix and suffix are the same

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurer.java
docs/modules/ROOT/pages/servlet/authorization/authorize-http-requests.adoc
web/src/main/java/org/springframework/security/web/access/intercept/AuthorizationFilter.java
web/src/test/java/org/springframework/security/web/access/intercept/AuthorizationFilterTests.java

Add Option to Filter All Dispatcher Types

---

core/src/main/java/org/springframework/security/authorization/method/AbstractAuthorizationManagerRegistry.java
core/src/main/java/org/springframework/security/authorization/method/AbstractExpressionAttributeRegistry.java
core/src/test/java/org/springframework/security/authorization/method/PreAuthorizeAuthorizationManagerTests.java
core/src/test/java/org/springframework/security/authorization/method/SecuredAuthorizationManagerTests.java

@EnableMethodSecurity doesn't resolve annotations on interfaces through a Proxy
Removed proxy unwrapping in case of resolving Method Security annotations,
this cause an issue when interfaces which are implemented by the proxy was skipped,
resulting in a missing security checks on those methods.
Closes gh-11175

@EnableMethodSecurity doesn't resolve annotations on interfaces through a Proxy

---

config/src/test/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurerTests.java
web/src/main/java/org/springframework/security/web/access/expression/DefaultHttpSecurityExpressionHandler.java
web/src/main/java/org/springframework/security/web/access/expression/ExpressionAuthorizationDecision.java
web/src/main/java/org/springframework/security/web/access/expression/WebExpressionAuthorizationManager.java
web/src/main/java/org/springframework/security/web/access/expression/WebSecurityExpressionRoot.java
web/src/test/java/org/springframework/security/web/access/expression/WebExpressionAuthorizationManagerTests.java

Add AuthorizationManager that uses ExpressionHandler

---

core/src/main/java/org/springframework/security/access/expression/AbstractSecurityExpressionHandler.java
core/src/main/java/org/springframework/security/access/expression/SecurityExpressionHandler.java
core/src/main/java/org/springframework/security/access/expression/SecurityExpressionRoot.java
core/src/main/java/org/springframework/security/access/expression/method/DefaultMethodSecurityExpressionHandler.java
core/src/main/java/org/springframework/security/access/expression/method/MethodSecurityEvaluationContext.java
core/src/main/java/org/springframework/security/access/expression/method/MethodSecurityExpressionRoot.java
core/src/main/java/org/springframework/security/authorization/method/PostAuthorizeAuthorizationManager.java
core/src/main/java/org/springframework/security/authorization/method/PostFilterAuthorizationMethodInterceptor.java
core/src/main/java/org/springframework/security/authorization/method/PreAuthorizeAuthorizationManager.java
core/src/main/java/org/springframework/security/authorization/method/PreFilterAuthorizationMethodInterceptor.java
core/src/test/java/org/springframework/security/access/expression/method/DefaultMethodSecurityExpressionHandlerTests.java
messaging/src/main/java/org/springframework/security/messaging/access/expression/DefaultMessageSecurityExpressionHandler.java
messaging/src/main/java/org/springframework/security/messaging/access/expression/MessageSecurityExpressionRoot.java
messaging/src/test/java/org/springframework/security/messaging/access/expression/DefaultMessageSecurityExpressionHandlerTests.java
web/src/main/java/org/springframework/security/web/access/expression/DefaultHttpSecurityExpressionHandler.java
web/src/main/java/org/springframework/security/web/access/expression/WebExpressionAuthorizationManager.java
web/src/main/java/org/springframework/security/web/access/expression/WebSecurityExpressionRoot.java
web/src/test/java/org/springframework/security/web/access/expression/DefaultHttpSecurityExpressionHandlerTests.java

`createEvaluationContext` should defer lookup of `Authentication`
- Added `createEvaluationContext` method that accepts `Supplier<Authentication>`
- Refactored classes that use `EvaluationContext` to use lazy initialization of `Authentication`
Closes gh-9667

createEvaluationContext should defer lookup of Authentication

---

config/src/test/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LoginConfigurerTests.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2Utils.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/logout/Saml2Utils.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/Saml2Utils.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/Saml2Utils.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/core/Saml2Utils.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/Saml2AuthenticationTokenConverterTests.java

Saml2 message BASE64-encode results will not have line wrapped. 
gh-11262

Use Base64 encoder with no CRLF in output for SAML 2.0 messages

---

data/src/main/java/org/springframework/security/data/repository/query/SecurityEvaluationContextExtension.java
data/src/test/java/org/springframework/security/data/repository/query/SecurityEvaluationContextExtensionTests.java

Added `trustResolver`, `roleHierarchy`, `permissionEvaluator`, `defaultRolePrefix`
fields to `SecurityEvaluationContextExtension` along with setter methods to override defaults.
Closes gh-11196

Some Security Expressions cause NPE when used within @Query

---

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/metadata/OpenSamlMetadataResolver.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/metadata/OpenSamlMetadataResolverTests.java

Create the EntityDescriptor object with `EntityDescriptor.DEFAULT_ELEMENT_NAME` instead of `EntityDescriptor.ELEMENT_QNAME`. That ensures the EntityDescriptor tag is marshalled to xml with the `md:` prefix, consistent with all other metadata tag elements.
I have signed the CLA.
Closes #11283

Use 'md:' prefix with EntityDescriptor tag in the metadata xml

---

build.gradle
config/spring-security-config.gradle
config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LoginConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LogoutConfigurer.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/NamespaceHttpX509Tests.java
core/src/test/java/org/springframework/security/core/SpringSecurityCoreVersionTests.java
core/src/test/java/org/springframework/security/core/StaticFinalReflectionUtils.java
saml2/saml2-service-provider/spring-security-saml2-service-provider.gradle

This PR does the following:
- Revert the commit https://github.com/spring-projects/spring-security/commit/60ed3602f6281d1a34c643484dfcb3440e2243d5 that was used as a workaround;
- Fix https://github.com/spring-projects/spring-security/issues/10695 by creating a `static` method to initialize the handlers;
- Use Java 8 for all modules but OpenSAML4;
- Because the `Saml2Login/LogoutConfigurerTests` are using some OpenSAML4 classes, these tests have to be compiled using Java 11. For this, those tests were removed from the `compileTestJava` task and a new Gradle task `compileSaml2TestJava` is being used to compile them;
- Another task `saml2Tests` is being used to run the tests compiled by `compileSaml2TestJava`.
- Instead of using the `ModuleDescriptor` to retrieve the OpenSAML version, now …

Build modules using Java 8

---

build.gradle
dependencies/spring-security-dependencies.gradle
messaging/spring-security-messaging.gradle
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/Saml2AuthenticationTokenConverter.java
web/spring-security-web.gradle
web/src/test/java/org/springframework/security/test/web/CodecTestUtils.java
web/src/test/java/org/springframework/security/web/authentication/rememberme/TokenBasedRememberMeServicesTests.java
web/src/test/java/org/springframework/security/web/authentication/www/BasicAuthenticationConverterTests.java
web/src/test/java/org/springframework/security/web/authentication/www/BasicAuthenticationFilterTests.java
web/src/test/java/org/springframework/security/web/authentication/www/DigestAuthenticationEntryPointTests.java
web/src/test/java/org/springframework/security/web/authentication/www/DigestAuthenticationFilterTests.java

see gh-11318
First commit removes  test usages  of Base64 and some other minor commons-codec functions.

Remove dependency on conmmons-codec by using java.util.Base64

---

build.gradle
dependencies/spring-security-dependencies.gradle
messaging/spring-security-messaging.gradle
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/Saml2AuthenticationTokenConverter.java
web/spring-security-web.gradle
web/src/test/java/org/springframework/security/test/web/CodecTestUtils.java
web/src/test/java/org/springframework/security/web/authentication/rememberme/TokenBasedRememberMeServicesTests.java
web/src/test/java/org/springframework/security/web/authentication/www/BasicAuthenticationConverterTests.java
web/src/test/java/org/springframework/security/web/authentication/www/BasicAuthenticationFilterTests.java
web/src/test/java/org/springframework/security/web/authentication/www/DigestAuthenticationEntryPointTests.java
web/src/test/java/org/springframework/security/web/authentication/www/DigestAuthenticationFilterTests.java

gh-11318
Replace commons-codec Base64 with `java.util.Base64`

Remove dependency on commons-codec by using java.util.Base64 (for 5.8.x)

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LogoutConfigurer.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/metadata/OpenSamlMetadataResolver.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistration.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSamlLogoutResponseResolver.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/Saml2LogoutRequestFilter.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/Saml2LogoutResponseFilter.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/Saml2MessageBindingUtils.java

Support multiple SingleLogoutService bindings.

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2LoginConfigurer.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2LoginConfigurerTests.java

Allow form login when single OAuth2 Provider is configured

---

web/src/main/java/org/springframework/security/web/server/csrf/CookieServerCsrfTokenRepository.java
web/src/test/java/org/springframework/security/web/server/csrf/CookieServerCsrfTokenRepositoryTests.java

Ability to set cookie maxAge in CookieServerCsrfTokenRepository
Closes gh-11432

Ability to set cookie maxAge in CookieServerCsrfTokenRepository

---

config/src/test/java/org/springframework/security/config/annotation/web/builders/WebSecurityTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/AuthorizeRequestsTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/HttpSecurityRequestMatchersTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/UrlAuthorizationConfigurerTests.java
config/src/test/java/org/springframework/security/htmlunit/server/WebTestClientHtmlUnitDriverBuilderTests.java
config/src/test/kotlin/org/springframework/security/config/annotation/web/AuthorizeHttpRequestsDslTests.kt
config/src/test/kotlin/org/springframework/security/config/annotation/web/AuthorizeRequestsDslTests.kt
config/src/test/kotlin/org/springframework/security/config/web/server/ServerJwtDslTests.kt
config/src/test/resources/org/springframework/security/config/http/InterceptUrlConfigTests-MvcMatchers.xml
config/src/test/resources/org/springframework/security/config/http/InterceptUrlConfigTests-MvcMatchersServletPath.xml
test/src/test/java/org/springframework/security/test/web/servlet/request/SecurityMockMvcRequestPostProcessorsAuthenticationStatelessTests.java
test/src/test/java/org/springframework/security/test/web/servlet/request/SecurityMockMvcRequestPostProcessorsTestSecurityContextStatelessTests.java

The Spring MVC changed the default behavior for trailing slash match
with https://github.com/spring-projects/spring-framework/issues/28552.
This causes failures in Spring Security's tests.
Setting the `useTrailingSlashMatch` to `true` ensures that Spring
Security will work for users who have modified the default configuration.
Specifing the request mapper with trailing slash path ensures that the tests
are successful when default behavior is used.
Closes gh-11451

Set the useTrailingSlashMatch to true for tests

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurer.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurerTests.java
core/src/main/java/org/springframework/security/authorization/AuthenticatedAuthorizationManager.java
core/src/test/java/org/springframework/security/authorization/AuthenticatedAuthorizationManagerTests.java

Add remaining methods from ExpressionUrlAuthorizationConfigurer to AuthorizeHttpRequestsConfigurer
- Added fullyAuthenticated
- Added rememberMe
- Added anonymous
Closes gh-11360

Add remaining methods from ExpressionUrlAuthorizationConfigurer to AuthorizeHttpRequestsConfigurer

---

docs/modules/ROOT/pages/servlet/authentication/rememberme.adoc
web/src/main/java/org/springframework/security/web/authentication/rememberme/TokenBasedRememberMeServices.java
web/src/test/java/org/springframework/security/test/web/CodecTestUtils.java
web/src/test/java/org/springframework/security/web/authentication/rememberme/TokenBasedRememberMeServicesTests.java

Add SHA256 as an algorithm option for Remember Me token hashing

---

docs/modules/ROOT/pages/reactive/test/web/setup.adoc

Closes gh-9998
basicAuthentication() is deprecated, so updated to basicAuthentication("user", "password")

Add Kotlin example for WebTestClient setup docs

---

docs/modules/ROOT/pages/reactive/configuration/webflux.adoc

Remove `@Configuration` from Webflux Security Configuration to be consistent with other examples.
#11626

Remove @Configuration from webflux config examples

---

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/jackson2/Saml2PostAuthenticationRequestMixin.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/jackson2/Saml2RedirectAuthenticationRequestMixin.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/AbstractSaml2AuthenticationRequest.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2PostAuthenticationRequest.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2RedirectAuthenticationRequest.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/OpenSamlAuthenticationRequestResolver.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/jackson2/Saml2PostAuthenticationRequestMixinTests.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/jackson2/TestSaml2JsonPayloads.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/authentication/OpenSamlAuthenticationRequestResolverTests.java

Add ID to Saml2 Post and Redirect Requests

---

web/src/main/java/org/springframework/security/web/FilterChainProxy.java
web/src/test/java/org/springframework/security/web/FilterChainProxyTests.java

Consistently handle RequestRejectedException if it is wrapped

---

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationRequestFilter.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/Saml2LogoutRequestFilter.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/Saml2RelyingPartyInitiatedLogoutSuccessHandler.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationRequestFilterTests.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/authentication/logout/Saml2LogoutRequestFilterTests.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/authentication/logout/Saml2RelyingPartyInitiatedLogoutSuccessHandlerTests.java

To avoid relying on HTML event handlers and adding unsafe-* rules to CSP, the javascript is moved to a <script> tag. This also allows a better browser compatibility.
Tested on Chrome Version 104.0.5112.79 (Official Build) (x86_64), Firefox 100.0 Build 20220428192727 and Safari Version 15.5 (17613.2.7.1.8)
Closes gh-11676

Move SAML Post inline javascript to script tag

---

web/src/main/java/org/springframework/security/web/util/matcher/IpAddressMatcher.java

There is no whitespace between error message and IP address value  `IpAddressMatcher#parseAddress()`
If IP value is wrong, then error text looks like `Failed to parse addressi.am.ip`.
There should be some separator between those two text tokens.
Also wrapped the address value with single quotes.
Will this add any confusion for the caller?
Or colon and `"Failed to parse address: $value` looks better?

Fix IP address parse error message in IpAddressMatcher#parseAddress()

---

config/src/main/kotlin/org/springframework/security/config/annotation/web/AuthorizeRequestsDsl.kt

Closes gh-10957
The test below shows the issue with "authenticated" access as a default parameter.
After fix the test is not relevant as the problem is solved at the compilation phase.
This is a breaking change, for example, when a user has `authorize("/path")` instead of `authorize("/path", authenticated)` in config.
```
@Test
fun `request when authorize with servletPath and default access`() {
this.spring.register(ServletPathAndDefaultAccessConfig::class.java).autowire()
this.mockMvc.perform(MockMvcRequestBuilders.get("/servletPath/path")
.with { request ->
request.servletPath = "/servletPath"
request
})
.andExpect(status().isUnauthorized)
this.mockMvc.perform(MockMvcRequestBuilders.get("/servletPath/path")
.with(httpBasic("user", "password"))
.with { request ->
request.servletPath = …
```

Remove default value for access parameter

---

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java
oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderTests.java

Refresh remote JWK when unknown KID error occurs

---

aspects/src/main/java/org/springframework/security/authorization/method/aspectj/AbstractMethodInterceptorAspect.aj
aspects/src/main/java/org/springframework/security/authorization/method/aspectj/JoinPointMethodInvocation.aj
aspects/src/main/java/org/springframework/security/authorization/method/aspectj/PostAuthorizeAspect.aj
aspects/src/main/java/org/springframework/security/authorization/method/aspectj/PostFilterAspect.aj
aspects/src/main/java/org/springframework/security/authorization/method/aspectj/PreAuthorizeAspect.aj
aspects/src/main/java/org/springframework/security/authorization/method/aspectj/PreFilterAspect.aj
aspects/src/main/java/org/springframework/security/authorization/method/aspectj/SecuredAspect.aj
aspects/src/test/java/org/springframework/security/authorization/method/aspectj/PostAuthorizeAspectTests.java
aspects/src/test/java/org/springframework/security/authorization/method/aspectj/PostFilterAspectTests.java
aspects/src/test/java/org/springframework/security/authorization/method/aspectj/PreAuthorizeAspectTests.java
aspects/src/test/java/org/springframework/security/authorization/method/aspectj/PreFilterAspectTests.java
aspects/src/test/java/org/springframework/security/authorization/method/aspectj/SecuredAspectTests.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/MethodSecurityAspectJAutoProxyRegistrar.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/MethodSecuritySelector.java
config/src/main/java/org/springframework/security/config/method/MethodSecurityBeanDefinitionParser.java
config/src/main/resources/org/springframework/security/config/spring-security-5.8.rnc
config/src/main/resources/org/springframework/security/config/spring-security-5.8.xsd
config/src/test/java/org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfigurationTests.java
config/src/test/java/org/springframework/security/config/method/MethodSecurityBeanDefinitionParserTests.java
config/src/test/resources/org/springframework/security/config/method/MethodSecurityBeanDefinitionParserTests-AspectJMethodSecurityServiceEnabled.xml
core/src/main/java/org/springframework/security/access/intercept/aspectj/AspectJCallback.java
core/src/main/java/org/springframework/security/access/intercept/aspectj/AspectJMethodSecurityInterceptor.java
docs/modules/ROOT/pages/servlet/appendix/namespace/method-security.adoc

Support for `@EnableMethodSecurity(mode=ASPECTJ)` and `<method-security mode="aspectj"/>`.
For `@EnableMethodSecurity`, see the AspectJ sample on [this `spring-security-samples` branch](https://github.com/jzheaux/spring-security-samples/commit/7d077ea90484946504562c6f8f45971370d5abfe).

AspectJ Method Security support

---

config/src/main/resources/org/springframework/security/config/spring-security-6.0.xsd

Fix missing xsd update after gh-11762

xsd document security-context-explicit-save defaults to true

---

antora-playbook-with-worktrees.yml
antora-playbook.yml
lib/antora/extensions/inject-collector-config.js
package.json

- add and register Antora Collector (see https://gitlab.com/antora/antora-collector-extension)
- configure Antora Collection at runtime using another extension
By using an extension to inject the configuration for Antora Collector, it's not necessary to update the content sources to add the configuration and thus allows it to be centrally controlled.

Add Antora Collector to eliminate the dependency on the generated-docs repository

---

README.adoc

The README covers:
* how to build the docs for a software branch (single version)
* how to build the docs for the whole project (the production docs site)

add a README that documents how to build the docs

---

config/src/main/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfiguration.java
config/src/test/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfigurationTests.java

Configure ContentNegotiationStrategy in HttpSecurityConfiguration

---

docs/antora.yml
docs/local-antora-playbook.yml
docs/spring-security-docs.gradle

The purpose of this PR is to remove the hard-coded version in the docs component descriptor (docs/antora.yml). This variation does so using Antora Collector. This approach does not rely on temporary changes to the component descriptor.

automatically manage docs version (with collector)

---

config/src/main/java/org/springframework/security/config/http/AuthorizationFilterParser.java
config/src/main/resources/org/springframework/security/config/spring-security-5.8.rnc
config/src/main/resources/org/springframework/security/config/spring-security-5.8.xsd
config/src/test/java/org/springframework/security/config/http/InterceptUrlConfigTests.java
config/src/test/resources/org/springframework/security/config/http/InterceptUrlConfigTests-AuthorizationManagerFilterAllDispatcherTypes.xml
docs/modules/ROOT/pages/servlet/appendix/namespace/http.adoc

Add XML support for shouldFilterAllDispatcherTypes

---

docs/modules/ROOT/pages/servlet/authorization/authorize-http-requests.adoc
etc/checkstyle/checkstyle.xml
web/src/main/java/org/springframework/security/web/util/matcher/AntPathRequestMatcher.java
web/src/main/java/org/springframework/security/web/util/matcher/RegexRequestMatcher.java
web/src/test/java/org/springframework/security/web/util/matcher/AntPathRequestMatcherTests.java
web/src/test/java/org/springframework/security/web/util/matcher/RegexRequestMatcherTests.java

Add static factory method to AntPathRequestMather and RegexRequestMather

---

crypto/src/main/java/org/springframework/security/crypto/argon2/Argon2PasswordEncoder.java
crypto/src/main/java/org/springframework/security/crypto/factory/PasswordEncoderFactories.java
crypto/src/main/java/org/springframework/security/crypto/password/Pbkdf2PasswordEncoder.java
crypto/src/main/java/org/springframework/security/crypto/scrypt/SCryptPasswordEncoder.java
crypto/src/test/java/org/springframework/security/crypto/argon2/Argon2PasswordEncoderTests.java
crypto/src/test/java/org/springframework/security/crypto/factory/PasswordEncoderFactoriesTests.java
crypto/src/test/java/org/springframework/security/crypto/password/Pbkdf2PasswordEncoderTests.java
crypto/src/test/java/org/springframework/security/crypto/scrypt/SCryptPasswordEncoderTests.java

Update default configuration for `Argon2PasswordEncoder`, `SCryptPasswordEncoder` and `Pbkdf2PasswordEncoder`, as per recommended minimums outlined in [OWASP Cheat Sheet Series ](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html).
**Recommendation:**
Use Argon2id with a minimum configuration of 15 MiB of memory, an iteration count of 2, and 1 degree of parallelism.
**Previous default configuration:**
memory=4, iterations=3, parallelism=1
**New default configuration:**
memory=16, iterations=2, parallelism=1
**Recommendation:**
Use scrypt with a minimum CPU/memory cost parameter of (2^16), a minimum block size of 8 (1024 bytes), and a parallelization parameter of 1.
**Previous default configuration:**
cpuCost=16384, memoryCost=8, parallelism=1
**New default …

Update default configuration for PasswordEncoders

---

local-antora-playbook.yml

When the production playbook was updated to use the new release line extension, the local playbook was not updated. This PR brings in up to date.

sync local-antora-playbook.yml with antora-playbook.yml

---

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtGrantedAuthoritiesConverter.java
oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtGrantedAuthoritiesConverterTests.java

This PR adds the ability to split the authorities claim on a configurable regex, which was previously set ot a hardcoded regex " ". The IAM solution I used provided the authorities separated by another character than ' ' and I realized that with the JwtGrantedAuthoritiesConverter I was not able to set a custom regex. The solution in this PR makes the JwtGrantedAuthoritiesConverter more flexible by supporting this use case while keeping the previous default behaviour.
I signed the individual CLA to provide this PR.

Add configurable authorities split regex

---

docs/modules/ROOT/pages/migration.adoc

Document how to use the new requestMatchers and securityMatchers

---

docs/modules/ROOT/pages/servlet/configuration/java.adoc

This is a change based on 6.0.0-RC1 release documentation.
`http.antMatcher()` is not longer available and was replaced with `http.securityMatcher()`, so use this in the Java Config Multiple HttpSecurity Instances example, too.
That part of documentation was missing in https://github.com/spring-projects/spring-security/issues/11939

Remove antMatcher usage from Multiple HttpSecurity docs

---

.github/actions/publish-docs.sh
.github/workflows/deploy-docs.yml
antora-playbook.yml
build.gradle
lib/antora/extensions/autoconfig-partial-build.js

- upgrade to Antora 3.2.0-alpha.2
- upgrade release-line-extension to 1.0.0-alpha.2
- add atlas-extension
- add local autoconfig-partial-build extension to activate partial build
- configure deploy-docs.yml workflow to detect and set up partial build
- configure publish-docs.sh script to sync partial build
The deploy-docs workflow now accepts an input which will activate a partial build. The input is the refname that you want to build. You can test this using the following `gh` call:
```
gh workflow --repo spring-projects/spring-security run deploy-docs.yml --ref docs-build -f build-refname=5.7.x
```
(the `--repo` is optional if the current directory is inside a clone of the repository)
As of now, the partial build will not be published. The sync script is configured to do a dry run in …

configure Antora and CI workflow to support partial build

---

.github/actions/publish-docs.sh

This PR fully activates the partial docs build.

remove dry-run on sync script; replace with -c for partial build

---

.github/workflows/deploy-docs.yml

- don't use environment variable reference in checkout action

fix deploy docs workflow (5.8.x)

---

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/logout/OpenSamlLogoutRequestValidator.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/Saml2LogoutResponseFilter.java

Fixes SAML logout log messages incorrectly referring to logout response instead of logout request and vice versa.
Closes gh-12129
@pivotal-cla This is an Obvious Fix

Fix SAML logout log messages

---

docs/modules/ROOT/pages/whats-new.adoc
web/src/main/java/org/springframework/security/web/context/AbstractSecurityWebApplicationInitializer.java
web/src/test/java/org/springframework/security/web/context/AbstractSecurityWebApplicationInitializerTests.java

Register FilterChainProxy for all dispatcher types

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/migration/servlet/cas.adoc

Migration guide for CAS support removal

---

docs/modules/ROOT/pages/migration/servlet/config.adoc

`http.securityMatcher(antMatcher("/api/**"), antMatcher("/app/**"))` is not possible at the moment. There is no `public HttpSecurity securityMatcher(RequestMatcher... requestMatcher)` method only a `public HttpSecurity securityMatcher(RequestMatcher requestMatcher)` method (no varargs) is available. The correct alternative is `http.securityMatchers().requestMatchers(antMatcher("/api/**"), antMatcher("/app/**"))`
Fixes gh-12296

Fix securityMatchers code sample

---

antora-playbook.yml
build.gradle
local-antora-playbook.yml

This pull request updates the production build to use the following extensions / behaviors:
* Asciidoctor Tabs
* automated / runtime migration from Spring Tabs to Asciidoctor Tabs
* code chomping (active, but not current used)
* code folding
There are still some improvements we're working on in Asciidoctor Tabs and the Spring.io Asciidoctor extensions, so I'd like to hold off adding these changes to the software branches until we are comfortable with how it works in production.
Once we submit the PR to add these extensions to the software branches, it will be possible to save the result of the tabs migration and commit it to the branch. After that point, the tabs migration will continue to run indefinitely on tags.

add Asciidoctor Tabs, tabs migration, code chomping & code folding to prod

---

docs/modules/ROOT/pages/servlet/test/mockmvc/oauth2.adoc

The `RequestPostProcessor` that takes no arguments is `oauth2Login`, which is what this paragraph describes.
This should be forward-ported up to 6.0.x.

Fix typo in OAuth 2.0 testing docs

---

.github/workflows/deploy-docs.yml

This change makes it possible to see which refname is being built by the Deploy Docs workflow from the GitHub Actions screen.

show build-refname value in Deploy Docs workflow name

---

web/src/main/java/org/springframework/security/web/server/csrf/CsrfWebFilter.java

Adjusts setRequestHandler method javadoc in CsrfWebFilter class to reflect changes in 6.0.
In 6.0, the default ServerCsrfTokenRequestHandler changed to XorServerCsrfTokenRequestAttributeHandler, however, the javadoc for the setRequestHandler method still said it was ServerCsrfTokenRequestAttributeHandler.
This change adjusts the information to make it more accurate, because, although XorServerCsrfTokenRequestAttributeHandler is a subclass of ServerCsrfTokenRequestAttributeHandler, the behavior is quite different.
Closes gh-12465

Adjusts setRequestHandler javadoc in CsrfWebFilter

---

docs/modules/ROOT/pages/features/authentication/password-storage.adoc

The words "The default implementation" are duplicated

Duplicate words.

---

core/src/main/java/org/springframework/security/authorization/AuthorityAuthorizationManager.java
core/src/main/java/org/springframework/security/authorization/method/SecuredAuthorizationManager.java
core/src/test/java/org/springframework/security/authorization/AuthoritiesAuthorizationManagerTests.java

SecuredAuthorizationManager should cache annotation's value

---

oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderTests.java

Two different methods are used for accessing the cache and only one of them is correctly mocked. This means the cache will always refresh unrelated to the unknown KID. https://github.com/spring-projects/spring-security/blob/main/oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java#L415
The `RemoteJWKSet` will never actually find a missing KID and do the update because of this. The code seems to be correct though and the test succeeds with the fixed mock.
Relates to this issue https://github.com/spring-projects/spring-security/issues/11621

NimbusJwtDecoder unknown KID scenario is not correctly tested

---

.github/workflows/deploy-docs.yml

This need is already filled by the push trigger. When a commit is pushed to a branch, the workflow automatically kicks off a partial build for that branch/version. A full build of the site occurs when a release is made or on demand. There's no reason to run this workflow otherwise.

turn off scheduler for Deploy Docs workflow

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurer.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurerTests.java

AuthorizeHttpRequestsConfigurer.AuthorizedUrl.hasRole should look up for a RoleHierarchy bean in the context
Closes gh-12473

AuthorizeHttpRequestsConfigurer.AuthorizedUrl.hasRole should look up for a RoleHierarchy bean in the context

---

core/src/main/java/org/springframework/security/authorization/method/SecuredAuthorizationManager.java
core/src/test/java/org/springframework/security/authorization/method/SecuredAuthorizationManagerTests.java

SecuredAuthorizationManager should allow customizing underlying authorization manager
Closes gh-12233

SecuredAuthorizationManager should allow customizing underlying authorization manager

---

build.gradle
lib/antora/templates/per-branch-antora-playbook.yml

* add packages (dependencies) to playbook template in docs-build branch
* upgrade Gradle Antora plugin and extension packages
* use map syntax for Antora CLI options

add packages (dependencies) to playbook template in docs-build branch

---

.github/actions/docsearch-config.json.hbs
lib/antora/extensions/publish-docsearch-config.js

This change should drastically reduce the number of search records and get the rollout of the search enhancements moving again.

only index pages from the latest version in each release line

---

docs/spring-security-docs.gradle

This will allow Antora to retrieve updates to the UI when Gradle is permitted access to the internet.

enable fetch option in Antora unless Gradle is running in offline mode

---

docs/modules/ROOT/pages/servlet/architecture.adoc

Code comments should be placed in callouts, especially when they contain formatting and links. Otherwise, it breaks the layout of the page, as you can see in this code listing:

move code comment to callout

---

web/src/main/java/org/springframework/security/web/authentication/rememberme/RememberMeAuthenticationFilter.java
web/src/main/java/org/springframework/security/web/savedrequest/SavedCookie.java

This PR solved issue for #12454 
and continue for #12455

Refactor SavedCookie for Cookie's deprecated method and fix typo in RememberMeAuthenticationFilter

---

config/src/main/java/org/springframework/security/config/annotation/web/configuration/EnableWebSecurity.java

This PR fixes the explanation in the javadoc of the `@EnableWebSecurity`, which was using a deprecated method to set up the `SecurityFilterChain` as a `@Bean`.

Update javadoc in EnableWebSecurity

---

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoder.java

When using `PublicKeyReactiveJwtDecoderBuilder` and `SecretKeyReactiveJwtDecoderBuilder`, Supports reactive exception handling
```java
// before
try {
reactiveJwtDecoder.decode(jwt)
.flatMap(...);
} catch (Exception exception) {
onError(exception);
}
```
```java
// after
reactiveJwtDecoder.decode(jwt)
.doOnError(onError)
.flatMap(...);
```

NimbusReactiveJwtDecoder support mono chain

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/AbstractAuthenticationFilterConfigurer.java

This PR fixes the typo in the AbstractAuthenticationFilterConfigurer class and corrects the use of generic type parameters in the javadoc.

fix typo and update javadoc in AbstractAuthenticationFilterConfigurer

---

web/src/main/java/org/springframework/security/web/authentication/ui/DefaultLoginPageGeneratingFilter.java

This PR has refactored the `DefaultLoginPageGeneratingFilter` class.
* Some `private static` methods have been changed to `non-static` methods.
* Changed the `initAuthFilter` method to use `instanceof pattern matching`.
* Refactored the error message extraction in the `generateLoginPageHtml` method.

Polish DefaultLoginPageGeneratingFilter

---

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSaml4LogoutRequestResolver.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSamlLogoutRequestResolver.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSaml4LogoutRequestResolverTests.java

Add RelayState Customizer to SAML Logout
Closes gh-12538

Add RelayState Customizer to SAML Logout

---

config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java
config/src/test/java/org/springframework/security/config/annotation/web/builders/HttpSecurityAddFilterTest.java

Before the fix, these methods would throw a NPE in case when the filter class passed as the second parameter, is not registered yet.
In particular, this exception can occur when mixing standard and custom DSL to register filters.
The fix doesn't change the situation that standard DSL for registration of filters cannot refer to filters that are registered via custom DSL even though those calls were done earlier.
It just provides more user-friendly error handling for this and most likely other scenarios of calls of HttpSecurity#addFilterBefore, HttpSecurity#addFilterAfter.
The error handling is implemented similarly to HttpSecurity#addFilter.
Closes gh-12637

Fix NPE in HttpSecurity#addFilterBefore, HttpSecurity#addFilterAfter

---

docs/modules/ROOT/pages/servlet/saml2/metadata.adoc
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/OpenSamlMetadataRelyingPartyRegistrationConverter.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/OpenSamlRelyingPartyRegistrationBuilderHttpMessageConverter.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistration.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistrations.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/registration/OpenSamlMetadataRelyingPartyRegistrationConverterTests.java

Preserve OpenSamlAssertingPartyDetails Instance

---

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/logout/Saml2LogoutRequest.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/authentication/logout/HttpSessionLogoutRequestRepositoryTests.java

`Saml2LogoutRequest` was not able to serialize/deserialize , changes are made to `Saml2LogoutRequest` class to made the `encoder` a transient variable , unit tests are added under `HttpSessionLogoutRequestRepositoryTests`
**previous PR #12638 created against the latest main is now closed as this fix goes under 5.8.x**

Make Saml2LogoutRequest#encoder transient

---

config/src/main/java/org/springframework/security/config/saml2/RelyingPartyRegistrationsBeanDefinitionParser.java
config/src/test/java/org/springframework/security/config/saml2/RelyingPartyRegistrationsBeanDefinitionParserTests.java

Fix entity-id ignored in RelyingPartyRegistration XML config

---

core/src/main/java/org/springframework/security/authorization/AuthorityAuthorizationManager.java
core/src/test/java/org/springframework/security/authorization/AuthorityAuthorizationManagerTests.java

There are no check for role prefix in AuthorizeHttpRequestsConfigurer#XXXrole methoids. This PR adds check for the same. Now the configuration will fail if role/s start with prefix for hasRole and hasAnyRole methods.
Closes #12581

AuthorizeHttpRequestsConfigurer#XXXrole methods should ensure the role does not begin with the role prefix

---

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/OpenSamlRelyingPartyRegistration.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistration.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/OpenSamlAuthenticationRequestResolver.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistrationTests.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/authentication/OpenSamlAuthenticationRequestResolverTests.java

Add support for AuthnRequestsSigned setting

---

docs/modules/ROOT/pages/servlet/oauth2/login/core.adoc

This PR fixes gh-12824, which currently redirects to a non-existent page. Instead, it will now redirect to [the actual page](https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/oauth2/login).

Updated core.adoc to fix Issue #12824

---

web/src/test/java/org/springframework/security/web/authentication/SimpleUrlAuthenticationSuccessHandlerTests.java

In the `onAuthenticationSuccess` method of the `SimpleUrlAuthenticationSuccessHandler`, the `clearAuthenticationAttributes` method is used to remove `AuthenticationException` objects that may be left in the session.
However, since there was no verification of whether this logic was working properly in test cases of `SimpleUrlAuthenticationSuccessHandler`, I added tests to verify it.

Add test to SimpleUrlAuthenticationSuccessHandlerTests

---

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/OpenSamlAuthenticationRequestResolver.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/registration/TestRelyingPartyRegistrations.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/authentication/OpenSamlAuthenticationRequestResolverTests.java

Add nameIdFormat processing to OpenSamlAuthenticationRequestResolver

---

docs/modules/ROOT/pages/migration/servlet/authorization.adoc

Fix SecurityWebApplicationInitializer.getSecurityDispatcherTypes example in doc
(fixes gh-12939)

Fix SecurityWebApplicationInitializer.getSecurityDispatcherTypes example in doc

---

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/metadata/OpenSamlMetadataResolver.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSamlLogoutRequestResolver.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/TestOpenSamlObjects.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSamlLogoutRequestResolverTests.java

Replace deprecated OpenSaml methods

---

web/src/main/java/org/springframework/security/web/ObservationFilterChainDecorator.java
web/src/test/java/org/springframework/security/web/ObservationFilterChainDecoratorTests.java

I tried to compile the project locally in order to test it.
But unfortunately I had the error below. And I definitely don't know how to fix it.
I would try to check open-telemetry locally if you help me to compile the project.
```
./gradlew build
> Task :buildSrc:compileJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':buildSrc:compileJava'.
> error: invalid source release: 17
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from …
```

#12811 - compressing simple class name for observation

---

config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurerAdapter.java

This PR just fixes the code sample in javadocs that errorneously uses `WebSecurity` parameter in a bean-creation method that doesn't need to have any parameters, as `WebSecurity` parameter is already provided in `WebSecurityCustomizer.customize(WebSecurity web)` functional method. Moreover, the sample doesn't even compile because of parameter names collision (the bean factory paramter and lambda parameter).
This fix could also be backported to 5.7.x branch.

Fix javadoc for migration from WebSecurityConfigurerAdapter

---

docs/modules/ROOT/pages/servlet/authentication/cas.adoc

Fix typo cas.adoc

---

core/src/main/java/org/springframework/security/authorization/method/AuthorizationAnnotationUtils.java
core/src/test/java/org/springframework/security/authorization/method/AuthorizationAnnotationUtilsTests.java

Ignore synthetic methods when checking for duplicate annotations

---

dependencies/spring-security-dependencies.gradle

Bump oauth2-oidc-sdk to 10.7.1 to update json-smart to 2.4.10
`oauth2-oidc-sdk:9.43.1` uses `json-smart-2.4.8` which is vulnerable to the following [CVE-2023-1370](https://nvd.nist.gov/vuln/detail/CVE-2023-1370)
Updated the version to `10.7.1` to use `json-smart-2.4.10` to fix the vulnerability

Address CVE-2023-1370

---

web/src/main/java/org/springframework/security/web/ObservationFilterChainDecorator.java
web/src/main/java/org/springframework/security/web/server/ObservationWebFilterChainDecorator.java
web/src/test/java/org/springframework/security/web/ObservationFilterChainDecoratorTests.java
web/src/test/java/org/springframework/security/web/server/ObservationWebFilterChainDecoratorTests.java

The tag `spring.security.reached.filter.name` is only set if a filter-name is available, otherwise the tag is omitted entirely. This leads to issues with metric-exporters that don't support dynamic tags, but rather expect tag-names of a metric to be always the same. The most prominent example is the Prometheus-exporter.
Instead of omitting the tag if no filer-name is set, a none-value is applied instead, making the tag-list consistent in all cases

Use consistent list of micrometer tags in web observation handler

---

docs/modules/ROOT/pages/servlet/integrations/websocket.adoc

Fix legacy-websocket-configuration cross-reference

---

cas/src/main/java/org/springframework/security/cas/web/CasAuthenticationFilter.java

Saving security context in CasAuthenticationFilter between requests

---

web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationFilter.java

Remove deprecated hint to use Digest Auth in favor of Basic Auth.
Closes gh-13231

Update JavaDoc of BasicAuthenticationFilter (gh-13231)

---

config/src/main/java/org/springframework/security/config/annotation/AbstractConfiguredSecurityBuilder.java
config/src/test/java/org/springframework/security/config/annotation/web/AbstractConfiguredSecurityBuilderTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfigurationTests.java

Does not apply a Configurer when disabled from another DSL

---

docs/modules/ROOT/pages/servlet/saml2/login/authentication.adoc
docs/modules/ROOT/pages/servlet/saml2/login/overview.adoc

Fix typo overview.adoc

---

.vscode/settings.json
buildSrc/src/main/groovy/io/spring/gradle/convention/AbstractSpringJavaPlugin.groovy
buildSrc/src/main/groovy/io/spring/gradle/convention/EclipsePlugin.groovy
buildSrc/src/main/resources/META-INF/gradle-plugins/io.spring.convention.eclipse.properties
config/spring-security-config.gradle

- Gradle projects contain cycles which comes from dependencies to test sources which is not a problem in gradle but eclipse metadata generation is getting confused. Thus we need settings to relax errors org.eclipse.jdt.core.circularClasspath=warning org.eclipse.jdt.core.incompleteClasspath=warning
- Additionally .classpath entries needs to be changes having without_test_code=false test=false
- Aspects end up getting source dirs `build/classes/java/main` and `build/resources/main` which never have sources. Vscode complains about that, eclipse is fine. Remove those from entries.
- In tests `htmlunit` depends on `xml-apis`. `xml-apis` are now part of jdk and eclipse complains about that. Excluse these in a gradle build.
- Both eclipse and vscode don't currently work with buildship, due to …

Make eclipse/vscode project import work

---

docs/modules/ROOT/pages/servlet/authentication/persistence.adoc

Typos in docs

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/CsrfConfigurer.java
config/src/main/java/org/springframework/security/config/http/CsrfBeanDefinitionParser.java
web/src/main/java/org/springframework/security/web/csrf/CsrfFilter.java

Remove usage of deprecated `LazyCsrfTokenRepository` from  `CsrfConfigurer.java` and  `CsrfBeanDefinitionParser.java`
as `CsrfFilter` uses `CsrfTokenRepository`.
Closes gh-13194

Remove LazyCsrfTokenRepository usage

---

core/src/main/java/org/springframework/security/authorization/method/Jsr250AuthorizationManager.java
core/src/test/java/org/springframework/security/authorization/method/Jsr250AuthorizationManagerTests.java

Creating a Draft PR for gh-12782 will move it ready for review upon receiving confirmation to work on the issue
This PR:
- Closes gh-12782
- Added missing Unit test to cover the use case when there is more than one JSR250Annotation at class level

Use AuthoritiesAuthorizationManager in Jsr250AuthorizationManager

---

config/src/main/java/org/springframework/security/config/annotation/method/configuration/MethodSecuritySelector.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/EnableCustomMethodSecurity.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfigurationTests.java

EnableMethodSecurity annotation does not get imported when defined as a meta-annotation
Closes gh-12870

Add meta-annotation support for EnableMethodSecurity

---

core/src/test/java/org/springframework/security/authentication/TestAuthentication.java
web/src/main/java/org/springframework/security/web/access/intercept/RequestMatcherDelegatingAuthorizationManager.java
web/src/test/java/org/springframework/security/web/access/intercept/RequestMatcherDelegatingAuthorizationManagerTests.java

Simplify RequestMatcherDelegatingAuthorizationManager.Builder matcher registration
Closes gh-11624

Simplify RequestMatcherDelegatingAuthorizationManager.Builder matcher registration

---

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/SupplierClientRegistrationRepository.java
oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/registration/SupplierClientRegistrationRepositoryTests.java

Closes gh-12967
Adds a `SupplierClientRegistrationRepository` to lazily retrieve `ClientRegistration`(s).
This is different from the proposed design and instead each registration can be lazily retrieved. If caching is required a `SingletonSupplier` can be used.

Add `SupplierClientRegistrationRepository`

---

docs/modules/ROOT/pages/servlet/authorization/authorize-http-requests.adoc

Hi,
this is a very very small typo fix. I just stumbled upon reading it, and thought "why not fix it real quick?".
I checked whether there are more occurrences of the same mistake within this repo, and there are none.
Feel free to ignore me ;) and thanks for the nice documentation 👍

Fix typo: you're -> your

---

web/src/main/java/org/springframework/security/web/savedrequest/SavedRequestAwareWrapper.java
web/src/test/java/org/springframework/security/web/savedrequest/SavedRequestAwareWrapperTests.java

We detected an issue in the process of handling the original request, after redirecting the Browser to the authenticated entry point: As the `SavedRequestAwareWrapper` is not exposing the content-type of the original request, Spring cannot resolve the handler method correctly, if it specifies a `consumes` parameter (see attached example: [post-redirect.zip](https://github.com/spring-projects/spring-security/files/11915298/post-redirect.zip)).
```
@PostMapping(path = "example-post", consumes = {
MediaType.APPLICATION_FORM_URLENCODED_VALUE,
MediaType.ALL_VALUE // only needed if browser has been redirected to the authentication entry point
})
public String exampleHandler() {
...
}
```

Return content-type from saved request

---

docs/modules/ROOT/pages/migration/servlet/config.adoc

Changed WebSecurityConfigurerAdapeter to WebSecurityConfigurerAdapter in Spring docs 5.8.x

Fix Adapeter to Adapter

---

config/src/main/java/org/springframework/security/config/annotation/web/builders/FilterOrderRegistration.java
core/src/main/java/org/springframework/security/authentication/AbstractAuthenticationToken.java
core/src/main/java/org/springframework/security/authentication/AnonymousAuthenticationToken.java
core/src/main/java/org/springframework/security/authentication/jaas/JaasGrantedAuthority.java
core/src/main/java/org/springframework/security/core/authority/SimpleGrantedAuthority.java
core/src/main/java/org/springframework/security/core/userdetails/User.java
ldap/src/main/java/org/springframework/security/ldap/userdetails/LdapAuthority.java
web/src/main/java/org/springframework/security/web/authentication/switchuser/SwitchUserGrantedAuthority.java
web/src/main/java/org/springframework/security/web/jaasapi/JaasApiIntegrationFilter.java

I refactored it like this
1. Using `putIfAbsent` method instead of `containsKey` and `put` method of the `Map`.
2. Using pattern matching for `instanceof`
I hope this helps improve readability.

Refactor for readability

---

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerAuthenticationManagerResolver.java
oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerReactiveAuthenticationManagerResolver.java
oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerAuthenticationManagerResolverDeprecatedTests.java
oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerAuthenticationManagerResolverTests.java
oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerReactiveAuthenticationManagerResolverDeprecatedTests.java
oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerReactiveAuthenticationManagerResolverTests.java

Close #13427
* Make `TrustedIssuerJwtAuthenticationManagerResolver` public so constructors to validate issuer with a predicate can be used.
* Makes the servlet and reactive versions a little more consistent (i.e. logging)
* Use `Set` instead of `ArrayList`; it has O(1) time complexity for look ups.

Allow JWT issuer AuthenticationManagerResolvers to accept predicate issuer validator

---

test/src/test/java/org/springframework/security/test/web/servlet/response/Gh3409Tests.java

Fix method typo `unauthenticatedNullAuthenitcation()` to `unauthenticatedNullAuthentication()`.
It seems like change for this review request was omitted: https://github.com/spring-projects/spring-security/pull/3818#discussion_r60294118.

Fix method typo in Gh3409Tests (gh-3409)

---

config/src/main/java/org/springframework/security/config/annotation/web/configuration/OAuth2ClientConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2ClientConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2LoginConfigurer.java
config/src/main/java/org/springframework/security/config/http/AuthenticationConfigBuilder.java
config/src/main/java/org/springframework/security/config/http/OAuth2AuthorizedClientManagerRegistrar.java
config/src/test/java/org/springframework/security/config/annotation/web/configuration/OAuth2AuthorizedClientManagerConfigurationTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configuration/OAuth2ClientConfigurationTests.java
config/src/test/java/org/springframework/security/config/http/OAuth2AuthorizedClientManagerRegistrarTests.java
config/src/test/resources/org/springframework/security/config/http/OAuth2AuthorizedClientManagerRegistrarTests-clients.xml
config/src/test/resources/org/springframework/security/config/http/OAuth2AuthorizedClientManagerRegistrarTests-minimal.xml
config/src/test/resources/org/springframework/security/config/http/OAuth2AuthorizedClientManagerRegistrarTests-providers.xml

This PR is the most recent iteration of design work for simplifying the configuration of the OAuth2 Client component model. The following list documents progress:
Issue gh-11783

Simplify configuration of OAuth2 Client component model

---

docs/modules/ROOT/pages/servlet/authorization/authorize-http-requests.adoc

closes gh-13728
This PR includes both of the methods suggested in the issue. Therefore, once one of them is adopted, the commits related to the other changes will be removed. Please provide your opinion on which method would be preferable.

Fix inaccurate information about permitting the FORWARD dispatcher in Kotlin

---

config/src/test/kotlin/org/springframework/security/config/annotation/method/configuration/KotlinEnableReactiveMethodSecurityNoAuthorizationManagerTests.kt
core/src/main/java/org/springframework/security/access/prepost/PrePostAdviceReactiveMethodInterceptor.java

This draft PR updates `PrePostAdviceReactiveMethodInterceptor` to utilize Framework's new support for Kotlin coroutines, along with fixing tests that began failing after this change.
Closes gh-13764
cc @jzheaux @sdeleuze

Support nested suspend calls for Kotlin coroutines

---

docs/modules/ROOT/pages/servlet/test/mockmvc/request-builders.adoc
docs/modules/ROOT/pages/servlet/test/mockmvc/result-handlers.adoc
docs/modules/ROOT/pages/servlet/test/mockmvc/result-matchers.adoc

https://github.com/spring-projects/spring-security/issues/13573
The title for some of the links is showing as Untitled
Update the corresponding doc files
[Security RequestBuilders](https://docs.spring.io/spring-security/reference/servlet/test/mockmvc/request-builders.html)
[Security ResultMatchers](https://docs.spring.io/spring-security/reference/servlet/test/mockmvc/result-matchers.html)
[Security ResultHandlers](https://docs.spring.io/spring-security/reference/servlet/test/mockmvc/result-handlers.html)
Validated it locally

Fix untitled page title in documentation

---

docs/modules/ROOT/pages/servlet/exploits/firewall.adoc

GET and POST are mentioned as allowed HTTP Methods in that example but for XML it is GET and HEAD.

Correct mentioned HTTP Method in Documentation

---

web/src/main/java/org/springframework/security/web/firewall/StrictHttpFirewall.java

Better error strings for invalid header and parameter values.
This PR was created because we have had an outstanding ticket with Cloudflare (https://support.cloudflare.com/hc/en-us/requests/2858014?page=1) for over a month where we have been trying to get to the bottom of what / who is sending an illegal header value. because StrictHttpFirewall doesn't tell us what the header name is, it's been a guessing game.
Work done: Updated exception strings to include the header / parameter name for when the value is invalid.

Improve StrictHttpFirewall error messaging

---

web/src/main/java/org/springframework/security/web/savedrequest/HttpSessionRequestCache.java
web/src/test/java/org/springframework/security/web/savedrequest/HttpSessionRequestCacheTests.java

Prior to this commit, the `ServletRequest#getParameter` method was used in order to verify if the `matchingRequestParameterName` was present in the request. That method has some side effects like interfering in the execution of the `ServletRequest#getInputStream` and `ServletRequest#getReader` method when the request is an HTTP POST (if those methods are invoked after getParameter, or vice-versa, the content won't be available). This commit makes that we only use the query string to check for the parameter, avoiding draining the request's input stream.
Closes gh-13731

Resolve The matchingRequestParameterName From The Query String

---

oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/OAuth2AuthorizationManagers.java
oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/ScopeAuthorizationManagerFactory.java
oauth2/oauth2-core/src/test/java/org/springframework/security/oauth2/core/OAuth2AuthorizationManagersTests.java

Closes #13754 Add hasScope and hasAnyScope for authorization rules

---

web/src/main/java/org/springframework/security/web/util/matcher/DispatcherTypeRequestMatcher.java
web/src/main/java/org/springframework/security/web/util/matcher/RegexRequestMatcher.java

Hello, I replaced `HttpMethod.resolve()` to `HttpMethod.valueOf()`
`HttpMethod.resolve()` is deprecated since Spring Framework 6.0.
Thank you.

Replace deprecated method

---

docs/modules/ROOT/pages/features/exploits/http.adoc

This updates references to the deprecated `server.use-forward-headers` property to the recommended `server.forward-headers-strategy` property. This also mentions the Reactive `ForwardedHeaderTransformer` alongside the `ForwardedHeaderFilter` and updates their links to point to the respective reference docs.

Update doc references for forwarded headers support

---

docs/modules/ROOT/pages/features/exploits/http.adoc

ip number does follow the ip number format, let it be 192.168.0.107

Update http.adoc: IP number does not follow IP number format

---

docs/modules/ROOT/pages/servlet/authorization/method-security.adoc

Docs custom AuthorizationManager fix

---

config/src/main/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistry.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/AbstractRequestMatcherBuilderRegistry.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/AntPathRequestMatcherBuilder.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/DispatcherServletDelegatingRequestMatcherBuilder.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/MvcRequestMatcherBuilder.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/RequestMatcherBuilder.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/RequestMatcherBuilders.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/ServletPatternRequestMatcher.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/ServletRegistrationCollection.java
config/src/test/java/org/springframework/security/config/MockServletContext.java
config/src/test/java/org/springframework/security/config/TestMockHttpServletMappings.java
config/src/test/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistryNoMvcTests.java
config/src/test/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistryTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/AbstractRequestMatcherBuilderRegistryTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurerTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/RequestMatcherBuildersTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/ServletPatternRequestMatcherTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/TestMockHttpServletMappings.java
docs/modules/ROOT/pages/servlet/authorization/authorize-http-requests.adoc

This PR extracts the logic `AuthorizeHttpRequestsConfigurer` uses to generate `RequestMatcher` instances, simplifying how `AntPathRequestMatcher` and `MvcRequestMatcher` instances are generated.
It exposes this through the `forServletPattern` DSL method.
Closes gh-13562

Add servletPath support to AuthorizeHttpRequests

---

aspects/spring-security-aspects.gradle
gradle/libs.versions.toml

Starting with version 8.4 the custom configuration to change the source directory from `src/*/aspectj` to `src/*/java` is not necessary anymore.
see https://github.com/freefair/gradle-plugins/issues/881

Update to io.freefair.aspectj 8.4

---

messaging/src/main/java/org/springframework/security/messaging/context/SecurityContextPropagationChannelInterceptor.java
messaging/src/test/java/org/springframework/security/messaging/context/SecurityContextPropagationChannelInterceptorTests.java

The `SecurityContextChannelInterceptor` currently has an ability to populate a security context with an `Authentication` from message header. But doesn't look like there is a way in the framework to populate such a header and therefore propagate context downstream the messaging flow
* Extend a `SecurityContextChannelInterceptor` to support `postReceive()` contract for context population and `afterReceiveCompletion()` to clean it up, respectively
* Optimize `setup()` function logic to not re-populate context if it already has the same `Authentication`
* Add a logic to the `preSend()` to populate header with the value from current security context if it is missed in a message
The change is driven by this Spring Integration feature: …

Propagate security context via channel interceptor

---

web/src/main/java/org/springframework/security/web/DefaultRedirectStrategy.java
web/src/main/java/org/springframework/security/web/session/RequestedUrlRedirectInvalidSessionStrategy.java
web/src/test/java/org/springframework/security/web/DefaultRedirectStrategyTests.java
web/src/test/java/org/springframework/security/web/session/SessionManagementFilterTests.java

* Makes it possible to customize the redirect strategy of `RequestedUrlRedirectInvalidSessionStrategy`, so that the servlet context path can be taken into account if desired.
* Makes the HTTP status code used by `DefaultRedirectStrategy` configurable, so that `307 Temporary Redirect` can be chosen if desired.
Closes gh-12795
Closes gh-12797

Make it possible to take servlet context path into account and ensure HTTP method is preserved on redirect to requested URL

---

core/src/main/java/org/springframework/security/core/userdetails/User.java

One field in `toString` implementation has a lower case but all others have an upper case - fix this misbehavior.

Use same case for all fields in toString

---

web/src/main/java/org/springframework/security/web/ObservationFilterChainDecorator.java
web/src/test/java/org/springframework/security/web/ObservationFilterChainDecoratorTests.java

This PR closes issue gh-13660
Issue with Micrometer having dash in it's label name, as for example prometheus does not allow dashes in metrics names.

Removed dash from observation name for since it's used as Micrometer metric

---

docs/modules/ROOT/pages/servlet/authorization/method-security.adoc

Fixed typo by changing 'please' to 'place'.

Fix typo in method-security.adoc

---

core/src/main/java/org/springframework/security/authentication/jaas/AbstractJaasAuthenticationProvider.java
core/src/main/java/org/springframework/security/authentication/jaas/AuthorityGranter.java
core/src/main/java/org/springframework/security/authentication/jaas/JaasAuthenticationProvider.java
core/src/main/java/org/springframework/security/authorization/event/AuthorizationEvent.java
core/src/main/java/org/springframework/security/core/token/KeyBasedPersistenceTokenService.java
core/src/main/java/org/springframework/security/core/userdetails/ReactiveUserDetailsPasswordService.java
core/src/test/java/org/springframework/security/authentication/UsernamePasswordAuthenticationTokenTests.java
web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationFilter.java

Found a weird reference to `BasicProcessingFilter` in the `BasicAuthenticationFilter` class. Seems to be a left-over after a renaming of the filter classes was done (commit 1286741c7c50fa7730e31852ea6fa4e03bc387ce).
While I was at it, fixed some more typos in comments in the core module.

Fix obsolete comment and typos

---

core/src/main/java/org/springframework/security/authorization/event/AuthorizationEvent.java

Updated the Javadoc comment for the `getAuthorizationDecision` method in the `AuthorizationEvent` class.
The `@return` tag in the Javadoc comment for the `getAuthorizationDecision` method was missing a description.

Update Javadoc Comments in AuthorizationEvent Class

---

docs/modules/ROOT/pages/servlet/authorization/authorize-http-requests.adoc

The example request matcher listed "/resources/**", while the explanation (3) used "/static/" instead.

Fix typo in the 'Authorizing Requests' example

---

oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/ClaimAccessor.java

This fixes a typo in the docstring for `ClaimAccessor#getClaimAsMap` that mistakenly refers to the expected type as a List instead of a Map.

Fix typo in getClaimAsMap docstring

---

docs/modules/ROOT/pages/servlet/architecture.adoc
docs/modules/ROOT/pages/servlet/authorization/architecture.adoc

add missing [tabs] fix typo in docs

---

core/src/main/java/org/springframework/security/access/hierarchicalroles/RoleHierarchyImpl.java
core/src/test/java/org/springframework/security/access/hierarchicalroles/RoleHierarchyImplTests.java
docs/modules/ROOT/pages/servlet/authorization/architecture.adoc

Create builder class to declaratively create a RoleHierarchy with a fluent API, add test. Closes #13300
gh-13300

Add RoleHierarchyBuilder

---

core/src/main/java/org/springframework/security/authorization/AuthorizationManagers.java
core/src/test/java/org/springframework/security/authorization/AuthorizationManagersTests.java

Factory methods to create AuthorizationManager with a configurable default AuthorizationDecision.
Closes gh-13085

Add AuthorizationManager factory methods

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurer.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurerTests.java
core/src/main/java/org/springframework/security/authorization/AuthorizationManagers.java
core/src/test/java/org/springframework/security/authorization/AuthorizationManagersTests.java

Add Not Support

---

config/src/main/java/org/springframework/security/config/annotation/method/configuration/Jsr250MethodSecurityConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/SecuredMethodSecurityConfiguration.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/MethodSecurityService.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/MethodSecurityServiceImpl.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfigurationTests.java

Forked and reworked from https://github.com/spring-projects/spring-security/pull/14057
Closes https://github.com/spring-projects/spring-security/issues/12783
PR includes
Automatic inclusion of any RoleHierarchy Bean into the Configurations related to Method Security

Use available RoleHierachy Bean for MethodSecurity Config

---

core/src/main/java/org/springframework/security/access/hierarchicalroles/RoleHierarchyImpl.java
core/src/test/java/org/springframework/security/access/hierarchicalroles/RoleHierarchyImplTests.java
docs/modules/ROOT/pages/servlet/authorization/architecture.adoc
docs/modules/ROOT/pages/servlet/authorization/method-security.adoc

Currenctly Hierarchical Roles requires the setter method to define the hierarchy.
```java
RoleHierarchyImpl hierarchy = new RoleHierarchyImpl();
hierarchy.setHierarchy("...");
```
This PR adds a factory method for this use case to make it easier
```java
RoleHierarchyImpl hierarchy = RoleHierarchyImpl.of("...");
```

Add a factory method for RoleHierarchyImpl

---

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java
config/src/main/kotlin/org/springframework/security/config/web/server/ServerHttpSecurityDsl.kt
config/src/main/kotlin/org/springframework/security/config/web/server/ServerSessionConcurrencyDsl.kt
config/src/main/kotlin/org/springframework/security/config/web/server/ServerSessionManagementDsl.kt
config/src/test/java/org/springframework/security/config/web/server/ServerHttpSecurityTests.java
config/src/test/java/org/springframework/security/config/web/server/SessionManagementSpecTests.java
config/src/test/kotlin/org/springframework/security/config/web/server/ServerSessionManagementDslTests.kt
core/src/main/java/org/springframework/security/core/session/InMemoryReactiveSessionRegistry.java
core/src/main/java/org/springframework/security/core/session/ReactiveSessionInformation.java
core/src/main/java/org/springframework/security/core/session/ReactiveSessionRegistry.java
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/reactive/authentication/concurrent-sessions-control.adoc
docs/modules/ROOT/pages/whats-new.adoc
web/src/main/java/org/springframework/security/web/authentication/session/SessionAuthenticationException.java
web/src/main/java/org/springframework/security/web/server/authentication/ConcurrentSessionControlServerAuthenticationSuccessHandler.java
web/src/main/java/org/springframework/security/web/server/authentication/DelegatingServerAuthenticationSuccessHandler.java
web/src/main/java/org/springframework/security/web/server/authentication/InvalidateLeastUsedServerMaximumSessionsExceededHandler.java
web/src/main/java/org/springframework/security/web/server/authentication/MaximumSessionsContext.java
web/src/main/java/org/springframework/security/web/server/authentication/PreventLoginServerMaximumSessionsExceededHandler.java
web/src/main/java/org/springframework/security/web/server/authentication/RegisterSessionServerAuthenticationSuccessHandler.java
web/src/main/java/org/springframework/security/web/server/authentication/ServerMaximumSessionsExceededHandler.java
web/src/main/java/org/springframework/security/web/server/authentication/SessionLimit.java
web/src/main/java/org/springframework/security/web/session/WebSessionStoreReactiveSessionRegistry.java
web/src/test/java/org/springframework/security/web/server/authentication/DelegatingServerAuthenticationSuccessHandlerTests.java
web/src/test/java/org/springframework/security/web/server/authentication/session/ConcurrentSessionControlServerAuthenticationSuccessHandlerTests.java
web/src/test/java/org/springframework/security/web/server/authentication/session/InMemoryReactiveSessionRegistryTests.java
web/src/test/java/org/springframework/security/web/server/authentication/session/InvalidateLeastUsedServerMaximumSessionsExceededHandlerTests.java
web/src/test/java/org/springframework/security/web/server/authentication/session/PreventLoginServerMaximumSessionsExceededHandlerTests.java
web/src/test/java/org/springframework/security/web/server/authentication/session/RegisterSessionServerAuthenticationSuccessHandlerTests.java
web/src/test/java/org/springframework/security/web/session/WebSessionStoreReactiveSessionRegistryTests.java

- https://github.com/spring-projects/spring-security/issues/13791

Max Sessions on WebFlux

---

config/src/main/kotlin/org/springframework/security/config/annotation/web/AuthorizeHttpRequestsDsl.kt
config/src/test/kotlin/org/springframework/security/config/annotation/web/AuthorizeHttpRequestsDslTests.kt
web/src/main/java/org/springframework/security/web/access/IpAddressAuthorizationManager.java
web/src/main/java/org/springframework/security/web/server/authorization/IpAddressAuthorizationManager.java

Adding DSL for hasIpAddress for WebMvc

---

docs/modules/ROOT/pages/servlet/authorization/authorize-http-requests.adoc

Minor typo in authorize HTTP requests Docs page. I changed double quotation for String value, It was single quotation. Copy and paste makes compile error.

Fix typo in Authorize HTTP Requests' Doc Page

---

docs/modules/ROOT/pages/servlet/authorization/events.adoc

Minor correction in Authorization Events documentation page text.

Fix typo in Authorization Events' Doc Page

---

config/src/main/java/org/springframework/security/config/annotation/method/configuration/EnableMethodSecurity.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/Jsr250MethodSecurityConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/SecuredMethodSecurityConfiguration.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/MethodSecurityService.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/MethodSecurityServiceImpl.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfigurationTests.java

Add order offset to @EnableMethodSecurity

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurer.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurerTests.java
core/src/test/java/org/springframework/security/authentication/TestAuthentication.java

It is a great pleasure to write first PR on Spring Security.
This PR closes gh-13256
- Implement `hasVariable` and `equalTo` to simplify request authorization path extraction.
- I wonder if this is the best way.

Simplify Request Authorization Path Extraction

---

README.adoc

CI badge link in README is outdated and always "failed" no matter CI status, so it l updated with current CI workflow badge
```
https://github.com/spring-projects/spring-security/workflows/CI/badge.svg?branch=main
```
[![CI](https://github.com/spring-projects/spring-security/actions/workflows/continuous-integration-workflow.yml/badge.svg)](https://github.com/spring-projects/spring-security/actions/workflows/continuous-integration-workflow.yml) (to-be)
```
https://github.com/spring-projects/spring-security/actions/workflows/continuous-integration-workflow.yml/badge.svg
```

Update CI workflow badge

---

docs/modules/ROOT/pages/servlet/authentication/architecture.adoc

"See the Javadoc for the [Javadoc](https://docs.spring.io/spring-security/site/docs/6.2.1/api/org/springframework/security/authentication/ProviderManager.html) class." under ProviderManager should be changed to the following:
"See the Javadoc for the [ProviderManager](https://docs.spring.io/spring-security/site/docs/6.2.1/api/org/springframework/security/authentication/ProviderManager.html) class."

fix: typo in Authentication Architecture ProviderManager

---

config/src/main/java/org/springframework/security/config/annotation/method/configuration/Jsr250MethodSecurityConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/SecuredMethodSecurityConfiguration.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfigurationTests.java

Closes [14401](https://github.com/spring-projects/spring-security/issues/14401)

set AuthorizationEventPublisher for Jsr250MethodInterceptor and SecuredMethodInterceptor

---

core/src/main/java/org/springframework/security/authorization/method/AuthorizationAnnotationUtils.java
core/src/test/java/org/springframework/security/access/annotation/RequireUserRole.java
core/src/test/java/org/springframework/security/authorization/method/AuthorizationAnnotationUtilsTests.java

This commit revises `AuthorizationAnnotationUtils` as follows.
- Removes code duplication by treating both `Class` and `Method` as `AnnotatedElement`.
- Avoids duplicated annotation searches by processing merged annotations in a single Stream instead of first using the `MergedAnnotations` API to find possible duplicates and then again searching for a single annotation via `AnnotationUtils` (which effectively performs the same search using the `MergedAnnotations` API internally).
- Uses `.distinct()` within the Stream to avoid the need for the workaround introduced in gh-13625. Note that the semantics here result in duplicate "equivalent" annotations being ignored. In other words, if `@⁠PreAuthorize("hasRole('someRole')")` is present multiple times as a meta-annotation, no exception will …

Revise `AuthorizationAnnotationUtils`

---

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/oidc/authentication/OidcIdTokenDecoderFactory.java
oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/oidc/authentication/ReactiveOidcIdTokenDecoderFactory.java
oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/oidc/authentication/OidcIdTokenDecoderFactoryTests.java
oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/oidc/authentication/ReactiveOidcIdTokenDecoderFactoryTests.java

Discussed in the mentioned issue and implemented as suggested by @jzheaux.
- Adds support for overriding WebClient passed to NimbusReactiveJwtDecoder in ReactiveOidcIdTokenDecoderFactory
- Adds support for overriding RestOperations passed to NimbusJwtDecoder in OidcIdTokenDecoderFactory
Closes: gh-14178

Support overriding WebClient/RestOperations in (Reactive)OidcIdTokenDecoderFactory

---

web/src/main/java/org/springframework/security/web/server/authentication/ServerWebExchangeDelegatingReactiveAuthenticationManagerResolver.java

In the `ServerWebExchangeDelegatingReactiveAuthenticationManagerResolver.Builder` class the JavaDoc comments mention the wrong class name. This commit fixes this.

Fix wrong class name in JavaDoc

---

config/src/main/kotlin/org/springframework/security/config/annotation/web/FormLoginDsl.kt
config/src/test/kotlin/org/springframework/security/config/annotation/web/FormLoginDslTests.kt

Add `usernameParameter` and `passwordParameter` to FormLoginDsl

---

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoder.java

Previously, the `decode` method threw a `JwtException` directly when encountering an unsupported algorithm or any exception during parsing. This commit introduces a more robust error handling mechanism. 
Now, instead of throwing exceptions directly, it returns a `Mono.error()` with a `BadJwtException` containing detailed error information. This approach provides more flexibility and allows the caller to handle errors in a more granular way, by being able to use project reactors onError functionality.
Closes gh-14467

Enhance JWT decoding error handling

---

messaging/src/main/java/org/springframework/security/messaging/handler/invocation/reactive/CurrentSecurityContextArgumentResolver.java
messaging/src/test/java/org/springframework/security/messaging/handler/invocation/reactive/CurrentSecurityContextArgumentResolverTests.java
web/src/main/java/org/springframework/security/web/method/annotation/CurrentSecurityContextArgumentResolver.java
web/src/main/java/org/springframework/security/web/reactive/result/method/annotation/CurrentSecurityContextArgumentResolver.java
web/src/test/java/org/springframework/security/web/method/annotation/CurrentSecurityContextArgumentResolverTests.java
web/src/test/java/org/springframework/security/web/reactive/result/method/annotation/CurrentSecurityContextArgumentResolverTests.java

Add argument resolver for SecurityContext

---

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/userinfo/DefaultOAuth2UserService.java
oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/userinfo/DefaultReactiveOAuth2UserService.java
oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/oidc/userinfo/OidcReactiveOAuth2UserServiceTests.java
oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/oidc/userinfo/OidcUserServiceTests.java
oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/userinfo/DefaultOAuth2UserServiceTests.java
oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/userinfo/DefaultReactiveOAuth2UserServiceTests.java

Nested username attribute in DefaultOAuth2User

---

web/src/main/java/org/springframework/security/web/util/matcher/IpAddressMatcher.java
web/src/test/java/org/springframework/security/web/util/matcher/IpAddressMatcherTests.java

Add validation IpAddressMatcher

---

core/src/main/java/org/springframework/security/authorization/method/AbstractExpressionAttributeRegistry.java
core/src/main/java/org/springframework/security/authorization/method/Jsr250AuthorizationManager.java
core/src/main/java/org/springframework/security/authorization/method/PostAuthorizeExpressionAttributeRegistry.java
core/src/main/java/org/springframework/security/authorization/method/PostFilterExpressionAttributeRegistry.java
core/src/main/java/org/springframework/security/authorization/method/PreAuthorizeExpressionAttributeRegistry.java
core/src/main/java/org/springframework/security/authorization/method/PreFilterExpressionAttributeRegistry.java
core/src/main/java/org/springframework/security/authorization/method/SecuredAuthorizationManager.java
core/src/test/java/org/springframework/security/authorization/method/Jsr250AuthorizationManagerTests.java
core/src/test/java/org/springframework/security/authorization/method/PostAuthorizeAuthorizationManagerTests.java
core/src/test/java/org/springframework/security/authorization/method/PostFilterAuthorizationMethodInterceptorTests.java
core/src/test/java/org/springframework/security/authorization/method/PreAuthorizeAuthorizationManagerTests.java
core/src/test/java/org/springframework/security/authorization/method/PreFilterAuthorizationMethodInterceptorTests.java
core/src/test/java/org/springframework/security/authorization/method/SecuredAuthorizationManagerTests.java

Closes gh-13783
Forward #14479

Spring Security annotations on subclasses support intercepting parent class methods.

---

docs/modules/ROOT/pages/servlet/authorization/authorize-http-requests.adoc

Typo: Update authorize-http-requests.adoc

---

ldap/src/main/java/org/springframework/security/ldap/authentication/ad/ActiveDirectoryLdapAuthenticationProvider.java
ldap/src/main/java/org/springframework/security/ldap/authentication/ad/DefaultActiveDirectoryAuthoritiesPopulator.java

Implemented a possibility to provide a custom `AuthoritiesPopulator` in `ActiveDirectoryLdapAuthenticationProvider`
Discussed in #4490
- I have extracted the existing implementation within `loadUserAuthorities` into a separate default AD populator, the same way it's done for non-AD LDAP AuthenticationProvider. Replaced a for with streams when collecting authorities;
- Mirrored existing constructors with a new parameter, keeping the old ones for back compatibility;
- Applied a few straightforward IDE-suggested fixes, let me know if you'd like me to revert them.
Resolves #4490

Implement providing a custom AuthoritiesPopulator in ADLdapAuthProvider

---

config/src/main/java/org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/ReactiveAuthorizationManagerMethodSecurityConfiguration.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfigurationTests.java
core/src/main/java/org/springframework/security/authorization/method/AbstractExpressionAttributeRegistry.java
core/src/main/java/org/springframework/security/authorization/method/AuthorizationAnnotationUtils.java
core/src/main/java/org/springframework/security/authorization/method/PostAuthorizeAuthorizationManager.java
core/src/main/java/org/springframework/security/authorization/method/PostAuthorizeExpressionAttributeRegistry.java
core/src/main/java/org/springframework/security/authorization/method/PostAuthorizeReactiveAuthorizationManager.java
core/src/main/java/org/springframework/security/authorization/method/PostFilterAuthorizationMethodInterceptor.java
core/src/main/java/org/springframework/security/authorization/method/PostFilterAuthorizationReactiveMethodInterceptor.java
core/src/main/java/org/springframework/security/authorization/method/PostFilterExpressionAttributeRegistry.java
core/src/main/java/org/springframework/security/authorization/method/PreAuthorizeAuthorizationManager.java
core/src/main/java/org/springframework/security/authorization/method/PreAuthorizeExpressionAttributeRegistry.java
core/src/main/java/org/springframework/security/authorization/method/PreAuthorizeReactiveAuthorizationManager.java
core/src/main/java/org/springframework/security/authorization/method/PreFilterAuthorizationMethodInterceptor.java
core/src/main/java/org/springframework/security/authorization/method/PreFilterAuthorizationReactiveMethodInterceptor.java
core/src/main/java/org/springframework/security/authorization/method/PreFilterExpressionAttributeRegistry.java
core/src/main/java/org/springframework/security/authorization/method/PrePostTemplateDefaults.java
docs/modules/ROOT/pages/servlet/authorization/method-security.adoc

Add meta-annotation annotation parameter support

---

core/src/main/java/org/springframework/security/authentication/DelegatingReactiveAuthenticationManager.java
core/src/test/java/org/springframework/security/authentication/DelegatingReactiveAuthenticationManagerTests.java

continueOnError flag has been added to DelegatingReactiveAuthenticationManager
Closes gh-14521

Add ContinueOnError Support for Failed Authentications

---

ldap/src/integration-test/java/org/springframework/security/ldap/userdetails/LdapUserDetailsManagerTests.java
ldap/src/main/java/org/springframework/security/ldap/userdetails/LdapUserDetailsManager.java

Implement customization of `rolePrefix` in `LdapUserDetailsManager`

---

config/src/main/java/org/springframework/security/config/annotation/method/configuration/AuthorizationProxyConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/Jsr250MethodSecurityConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/MethodSecuritySelector.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/SecuredMethodSecurityConfiguration.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/AuthorizationProxyConfigurationTests.java
core/src/main/java/org/springframework/security/authorization/AuthorizationAdvisorProxyFactory.java
core/src/main/java/org/springframework/security/authorization/AuthorizationProxyFactory.java
core/src/main/java/org/springframework/security/authorization/method/AuthorizationAdvisor.java
core/src/main/java/org/springframework/security/authorization/method/AuthorizationManagerAfterMethodInterceptor.java
core/src/main/java/org/springframework/security/authorization/method/AuthorizationManagerBeforeMethodInterceptor.java
core/src/main/java/org/springframework/security/authorization/method/PostFilterAuthorizationMethodInterceptor.java
core/src/main/java/org/springframework/security/authorization/method/PreFilterAuthorizationMethodInterceptor.java
core/src/test/java/org/springframework/security/authorization/AuthorizationAdvisorProxyFactoryTests.java
docs/modules/ROOT/pages/servlet/authorization/method-security.adoc
docs/modules/ROOT/pages/whats-new.adoc

Proxy arbitrary objects like so:
```java
public class Flight {
@PreAuthorize("hasAuthority('airplane:read')")
Double getAltitude() {
return 35000d;
}
}
// ...
var preAuthorize = AuthorizationManagerBeforeMethodInterceptor.preAuthorize();
var factory = new AuthorizationAdvisorProxyFactory(preAuthorize);
var flight = new Flight();
assertThatNoException().isThrownBy(flight::getAltitude);
Flight proxied = (Flight) factory.proxy(flight);
assertThatExceptionOfType(AccessDeniedException.class).isThrownBy(proxied::getAltitude);
```
For values of type `Iterator`, `Collection`, `Stream`, `Array`, `Map`, and `Optional`, the values are proxied instead of the collection. For `Class` values, `ProxyFactory#getProxyClass` is used.
Also when adding `@EnableMethodSecurity`, `AuthorizationProxyFactory` is …

Add Programmatic Proxy Support for Method Security

---

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml4AuthenticationProvider.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml4AuthenticationProviderTests.java

This fixes https://github.com/spring-projects/spring-security/issues/11725 and reflects the feedback from https://github.com/spring-projects/spring-security/pull/12818

[ISSUE-11725] Add secondary statusCode messages on error

---

core/src/main/java/org/springframework/security/authentication/AuthenticationProvider.java

"Authentication" is an interface, not a class. So, It's not correct to say 'instance of the Authentication class.

Update the documentation of AuthenticationProvider.java

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/DefaultOidcLogoutTokenValidatorFactory.java
config/src/main/java/org/springframework/security/config/web/server/DefaultOidcLogoutTokenValidatorFactory.java
oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/oidc/authentication/DefaultOidcIdTokenValidatorFactory.java
oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtValidators.java
oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/JwtValidatorsTests.java

Simplification of creation of OAuth2TokenValidator with JwtValidators defaults.
Closes gh-14831

Simplification of creation of OAuth2TokenValidator with JwtValidators defaults.

---

settings.gradle

Reverts spring-projects/spring-security#14833
Gradle Enterprise plugin version 3.17 is newer than the newest version supported by Gradle Enterprise 2023.4.6 which is 3.16. Please update to a newer version of Gradle Enterprise.

Revert "Bump com.gradle.enterprise from 3.16.2 to 3.17"

---

core/src/main/java/org/springframework/security/core/ComparableVersion.java

Changed the variable name from MAX_INTITEM_LENGTH to MAX_INT_ITEM_LENGTH to adhere to naming conventions
1. According to Java's naming convention, constant names are typically all capitalized, separated by an underscore (_) between words.
2. It increases readability.
3. MAX_INTITEM_LENGTH can be difficult to understand the meaning of a variable because the term "INTITEM" is not commonly used.

Fix Variable Naming Convention

---

config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeUserDetailsBeanManagerConfigurer.java

InitializeUserDetailsBeanManagerConfigurer  inject PasswordEncoder into DaoAuthenticationProvider constructor

---

core/src/main/java/org/springframework/security/authorization/method/AuthorizationManagerAfterMethodInterceptor.java
core/src/main/java/org/springframework/security/authorization/method/AuthorizationManagerAfterReactiveMethodInterceptor.java
core/src/main/java/org/springframework/security/authorization/method/AuthorizationManagerBeforeMethodInterceptor.java
core/src/main/java/org/springframework/security/authorization/method/AuthorizationManagerBeforeReactiveMethodInterceptor.java
core/src/main/java/org/springframework/security/authorization/method/MethodAuthorizationDeniedHandler.java
core/src/main/java/org/springframework/security/authorization/method/MethodAuthorizationDeniedPostProcessor.java
core/src/main/java/org/springframework/security/authorization/method/ThrowingMethodAuthorizationDeniedHandler.java
core/src/main/java/org/springframework/security/authorization/method/ThrowingMethodAuthorizationDeniedPostProcessor.java
core/src/test/java/org/springframework/security/authorization/method/AuthorizationManagerAfterMethodInterceptorTests.java
core/src/test/java/org/springframework/security/authorization/method/AuthorizationManagerAfterReactiveMethodInterceptorTests.java
core/src/test/java/org/springframework/security/authorization/method/AuthorizationManagerBeforeMethodInterceptorTests.java
core/src/test/java/org/springframework/security/authorization/method/AuthorizationManagerBeforeReactiveMethodInterceptorTests.java
docs/modules/ROOT/pages/servlet/authorization/method-security.adoc

Handle SpEL AuthorizationDeniedExceptions

---

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtDecoderProviderConfigurationUtils.java

This PR adds reasonable timeouts to JwtDecoderProviderConfigurationUtils and NimbusJwtDecoder.
It's fixing [Issue GH-14269](https://github.com/spring-projects/spring-security/issues/14269)
Since the `RestOperations` instance in `JwkSetUriJwtDecoderBuilder` is not static, I couldn't have used a static initializer block and had to use the following solution. I am open to suggestions if you think there is a better solution for this.

Add timeout defaults to JwtDecoders

---

docs/modules/ROOT/pages/reactive/oauth2/client/client-authentication.adoc
docs/modules/ROOT/pages/reactive/oauth2/client/core.adoc
docs/modules/ROOT/pages/reactive/oauth2/login/core.adoc
docs/modules/ROOT/pages/servlet/oauth2/client/client-authentication.adoc
docs/modules/ROOT/pages/servlet/oauth2/client/core.adoc
docs/modules/ROOT/pages/servlet/oauth2/login/core.adoc

Closes gh-14917
I've found `Spring Boot 2.x` referenced in a few more doc files other than the ones mentioned in the issue, let me know if those should not be changed and I can revert them.

Replace "Spring Boot 2.x" with "Spring Boot"

---

config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeAuthenticationProviderBeanManagerConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeUserDetailsBeanManagerConfigurer.java

Closes gh-14663
See the issue for use-case matrix.
I'd like to draw your attention to the following:
1 UserDetailsService ; `INFO` level:
```
2024-03-08T14:23:23.058+01:00  INFO 49038 --- [           main] r$InitializeUserDetailsManagerConfigurer : Global AuthenticationManager configured with UserDetailsService bean with name myUserDetailsService
```
2 UserDetailsService ; `WARN` level:
```
2024-03-08T14:25:11.644+01:00  WARN 49146 --- [           main] r$InitializeUserDetailsManagerConfigurer : Found 2 UserDetailsService beans, with names [myUserDetailsService, secondUserDetailsService]. Global Authentication Manager will not use a UserDetailsService for username/password login.
```
1 AuthenticationProvider and at least 1 UserDetailsService bean, `WARN` level:
``` …
```

Improve logging for Global Authentication

---

core/src/main/java/org/springframework/security/authorization/method/PostAuthorizeExpressionAttributeRegistry.java

Fix  MethodAuthorizationDeniedPostProcessor does not exist in java doc

---

config/src/main/java/org/springframework/security/config/authentication/PasswordEncoderParser.java
config/src/main/java/org/springframework/security/config/ldap/LdapProviderBeanDefinitionParser.java
config/src/test/java/org/springframework/security/config/authentication/PasswordEncoderParserTests.java

This PR removes the 'useBase64' parameter from createPasswordEncoderBeanDefinition. It's no longer needed, simplifying the function's interface and ensuring consistency. The PR  also removed `false` from  `createPasswordEncoderBeanDefinition` method call.

Remove useBase64 parameter

---

crypto/src/main/java/org/springframework/security/crypto/password/DelegatingPasswordEncoder.java
crypto/src/test/java/org/springframework/security/crypto/password/DelegatingPasswordEncoderTests.java

This closes gh-14880
https://github.com/spring-projects/spring-security/issues/14880

Improve PasswordEncoder Error Messaging

---

docs/modules/ROOT/pages/reactive/configuration/webflux.adoc
docs/modules/ROOT/pages/servlet/configuration/kotlin.adoc

Updates the documentation to provide a bit more explicit instruction on how to enable the Kotlin DSL. I found the existing reference to 
> import the `invoke` function
a bit less obvious then I would have thought, and despite being reasonably knowledgable, having done this thing before in the past, and having the code sample, it took me a few minutes to figure out exactly what it was referring to.

Minor Documentation update on import needed for using Kotlin DSL

---

docs/modules/ROOT/pages/servlet/authentication/passwords/digest.adoc

Changed method names and arguments in reference docs

Minor docs fix

---

docs/modules/ROOT/pages/servlet/authorization/authorize-http-requests.adoc

- Consistency: Replaced mix of tabs/spaces with spaces indentation
---
Something was mixed-up with the code example at https://docs.spring.io/spring-security/reference/servlet/authorization/authorize-http-requests.html.
Not sure if it's perfect (Java has `// ...`, Kotlin and XML don't), but it should be an improvement 😄

Fix Kotlin example in authorize-http-requests.adoc

---

web/src/main/java/org/springframework/security/web/DefaultSecurityFilterChain.java

This PR addresses issue #12218 
1. Changes the logging level of `DefaultSecurityFilterChain` from INFO to DEBUG to align with `FilterChainProxy`.
2. Logs only the class names of filters instead of their full `toString` of filter.

Adjust DefaultSecurityFilterChain Logging Level and Simplify Filter Logging

---

docs/modules/ROOT/pages/servlet/authentication/passwords/in-memory.adoc

Fix link in the In-Memory Authentication documentation

---

docs/modules/ROOT/pages/servlet/oauth2/resource-server/multitenancy.adoc

Fixed the Java example of the jwtDecoder function. The parameter called [_jwtProcessor_](https://github.com/spring-projects/spring-security/blob/752a56a9d9d88fb801fdca0e380d992fd2a75dca/docs/modules/ROOT/pages/servlet/oauth2/resource-server/multitenancy.adoc?plain=1#L421C36-L421C48) was received in the function, but in the function body and referenced the name [_processor_](https://github.com/spring-projects/spring-security/blob/752a56a9d9d88fb801fdca0e380d992fd2a75dca/docs/modules/ROOT/pages/servlet/oauth2/resource-server/multitenancy.adoc?plain=1#L422C50-L422C59), which is non-existent. The parameter in the method body has been changed to _jwtProcessor_ to match the received parameter.
This is a small correction, but I believe it optimizes the use of the example. :grin:

Fix Java example in multitenanci.adoc

---

docs/modules/ROOT/pages/servlet/test/mockmvc/setup.adoc

* Fix invalid Kotlin-syntax
* Use `lateinit` instead of allowing NullPointerExceptions.

Update Kotlin example for MockMvc and Spring Security

---

core/spring-security-core.gradle
core/src/main/java/org/springframework/security/access/expression/method/DefaultMethodSecurityExpressionHandler.java
core/src/test/kotlin/org/springframework/security/access/expression/method/DefaultMethodSecurityExpressionHandlerKotlinTests.kt
docs/modules/ROOT/pages/servlet/authorization/method-security.adoc

Closes the following issue:
- #15093
**Summary**
Adds support for Kotlin in [`DefaultMethodSecurityExpressionHandler`](https://github.com/spring-projects/spring-security/blob/64e2a2ff8b493aa0298043128b7329e2a7362e4b/core/src/main/java/org/springframework/security/access/expression/method/DefaultMethodSecurityExpressionHandler.java).
It additionally updates the documentation (both `javadoc` and `asciidoc`) to reflect the current implementation details and usage.
**Implementation details**
Attempts to mutate the state of either the `Collection` or the `Map`:
- if an `UnsupportedOperationException` is not thrown, returns the instance with its state mutated.
- if an `UnsupportedOperationException` is thrown, returns a new instance with the filtered state.
**Tests**
The original Java test …

Add Kotlin support to PreFilter and PostFilter annotations

---

config/src/main/kotlin/org/springframework/security/config/web/server/ServerHttpSecurityDsl.kt
config/src/test/kotlin/org/springframework/security/config/web/server/ServerHttpSecurityDslTests.kt

**Added `securityContextRepository` field variable to set `ServerSecurityContextRepository` in `ServerHttpSecurityDsl`.**
There is no way in `ServerHttpSecurityDsl` to **set the `ServerSecurityContextRepository` of `ServerHttpSecurity`**. So I added a field variable to set `ServerSecurityContextRepository`.

Add SecurityContextRepository to Kotlin Reactive DSL

---

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/metadata/OpenSamlMetadataResolver.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/metadata/OpenSamlSigningUtils.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/metadata/Saml2Utils.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/metadata/OpenSamlMetadataResolverTests.java

Support signing SAML metadata

---

config/src/main/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistry.java
config/src/test/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistryTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/AuthorizeRequestsTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/HttpSecuritySecurityMatchersTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/UrlAuthorizationConfigurerTests.java

Always Use Request-Level ServletContext to Evaluate Request Matcher Paths

---

web/src/main/java/org/springframework/security/web/authentication/rememberme/AbstractRememberMeServices.java
web/src/test/java/org/springframework/security/web/authentication/rememberme/AbstractRememberMeServicesTests.java

Add support remember-me cookie customization

---

config/src/main/java/org/springframework/security/config/annotation/web/builders/WebSecurity.java
config/src/test/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurationTests.java

Add support checking AnyRequestMatcher securityFilterChains

---

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml4AuthenticationProvider.java

Surrounding code appears to intend it to be at trace, not debug.

Fix level of log message.

---

docs/modules/ROOT/pages/servlet/authorization/method-security.adoc

See [section "Using Method Parameters" in the current documentation](https://docs.spring.io/spring-security/reference/servlet/authorization/method-security.html#using_method_parameters). It looks like it is supposed to list the order in which Spring tries to discover parameter names:
1. `@P`
2. `@Param`
3. `javac` `-parameters`
4. `javac` with debug symbols
However, currently it is erroneously displayed as:
1. `@P`
- `@Param`
- `javac` `-parameters`
- `javac` with debug symbols
This pull request tries to fix this.
Though please let me know if I misunderstood this, or if there is a better way to solve this.

Fix malformed list in "Using Method Parameters" documentation

---

docs/modules/ROOT/pages/servlet/authentication/events.adoc

In https://docs.spring.io/spring-security/reference/servlet/authentication/events.html#_default_event, the given example does not work, as
* in the Java case, the assignment type `AuthenticationEventPublisher` does not have the expected method `setDefaultAuthenticationFailureEvent`, but `DefaultAuthenticationEventPublisher` has.
* in both the Java and Kotlin case the class `GenericAuthenticationFailureEvent` does not exist. `AbstractAuthenticationFailureEvent` could be used instead.

Two small fixes to the Servlet's Authentication Events documentation

---

docs/modules/ROOT/pages/prerequisites.adoc

Raises the minimum version of the Java runtime for Spring Security from 8 to 17

Update prerequisites documentation with Java 17

---

docs/modules/ROOT/pages/servlet/authorization/method-security.adoc
docs/modules/ROOT/pages/servlet/saml2/login/authentication-requests.adoc
docs/modules/ROOT/pages/servlet/saml2/login/overview.adoc

Hi Team,
This pr fixes a typo in the Spring Security documentation and updates the source block roles for consistency.
- Changed `.collect(Collectors.toList()));` to `.collect(Collectors.toList());`.
- Changed `[source,java,role="secondary"]` to `[source,kotlin,role="secondary"]` in the Kotlin example code block.
Thank you.

Fix typos and formatting in documentation

---

docs/modules/ROOT/pages/servlet/oauth2/resource-server/jwt.adoc
docs/modules/ROOT/pages/servlet/oauth2/resource-server/opaque-token.adoc

Prefer usage of the Lambda DSL.
The `OAuth2ResourceServerConfigurer::opaqueToken` and `OAuth2ResourceServerConfigurer::jwt` methods are deprecated since Spring Security 6.1.
With Spring Security 6.3, it looks like both methods are not working.

Update the OAuth2 jwt and opaque Resource Server documentation

---

README.adoc

Changing URL from https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/ to https://docs.spring.io/spring-security/reference/ since the first one doesn't exist anymore.

Fixing URL on README

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OidcBackChannelLogoutAuthenticationProvider.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OidcLogoutConfigurerTests.java

Backport of the solution for #15003 to `6.2.x` .

Allow logout+jwt JWT type

---

oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/user/DefaultOAuth2User.java
oauth2/oauth2-core/src/test/java/org/springframework/security/oauth2/core/user/DefaultOAuth2UserTests.java

This commit resolves NPEs that occur in DefaultOuth2User#getName.
If the attributes have a key, but the value comes in null, the NPE occurs, and we modified the case and added a related test case.
fixes: #15338

Fix NPE when nameAttributeValue is null (#15338)

---

core/src/main/java/org/springframework/security/authentication/AuthenticationManager.java

Add @FunctionalInterface to AuthenticationManager.
AuthenticationManager is being implemented by using lambda. Therefore, It would be clear not to add more abstract functions, if @FunctionalInterface Annotation is added.
cc. https://github.com/spring-projects/spring-security/pull/15379

Add @FunctionalInterface to AuthenticationManager

---

config/src/main/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfiguration.java
config/src/test/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfigurationTests.java
docs/modules/ROOT/pages/servlet/integrations/cors.adoc

Closes [gh-15378](https://github.com/spring-projects/spring-security/issues/15378)

Restrict automatic CORS configuration to UrlBasedCorsConfigurationSource

---

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/Saml2RelyingPartyInitiatedLogoutSuccessHandler.java

This PR fixes a typo of "the the" to "the".

Remove duplicated "the" in JavaDoc

---

ldap/src/main/java/org/springframework/security/ldap/authentication/ad/ActiveDirectoryLdapAuthenticationProvider.java

Updated javadocs for `ActiveDirectoryLdapAuthenticationProvider` as discussed in #7760. Closes #7760.

Clarify url Parameter Usage in AD Provider Constructor

---

docs/modules/ROOT/pages/servlet/exploits/csrf.adoc

I fixed the explanation about HttpSessionCsrfTokenRepository class. This class loads CRSF token from and save into a session.

Correct HttpSessionCsrfTokenRepository Documentation

---

core/src/main/java/org/springframework/security/provisioning/InMemoryUserDetailsManager.java
core/src/test/java/org/springframework/security/provisioning/InMemoryUserDetailsManagerTests.java

This PR fixes issue gh-3192 by allowing `MutableUserDetails` to be stored and loaded inside the `InMemoryUserDetailsManager` instead of always wrapping it into `MutableUser`. The custom user type must implement `CredentialsContainer` in order to be returned by `loadUserByUsername()` and not transformed into `User`.
I wanted to write tests for the new cases, and I saw that methods were not previously covered so I wrote tests for all cases for `createUser()` and `loadUserByUsername()`. However, I have concerns about some tests:
`createUserWhenNotInstanceOfMutableUserDetailsThenShouldWrapIntoMutableUser` and
`createUserWhenInstanceOfMutableUserDetailsThenShouldNotWrapIntoMutableUser` can't directly access `Map<String, MutableUserDetails> users` to get the underlying user & type, so they are …

Preserve custom user type in InMemoryUserDetailsManager

---

docs/modules/ROOT/pages/servlet/authorization/authorize-http-requests.adoc

Hi together,
This PR just adjusts some code formatting for the examples while I was reading the documentation.
Best Regards,
Robert

Fix code formatting in documentation

---

config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebMvcSecurityConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/web/reactive/ServerHttpSecurityConfiguration.java
config/src/test/java/org/springframework/security/config/annotation/web/configuration/WebMvcSecurityConfigurationTests.java
config/src/test/java/org/springframework/security/config/annotation/web/reactive/ServerHttpSecurityConfigurationTests.java
messaging/src/main/java/org/springframework/security/messaging/handler/invocation/reactive/CurrentSecurityContextArgumentResolver.java
messaging/src/test/java/org/springframework/security/messaging/handler/invocation/reactive/CurrentSecurityContextArgumentResolverTests.java
web/src/main/java/org/springframework/security/web/method/annotation/CurrentSecurityContextArgumentResolver.java
web/src/main/java/org/springframework/security/web/reactive/result/method/annotation/CurrentSecurityContextArgumentResolver.java
web/src/test/java/org/springframework/security/web/method/annotation/CurrentSecurityContextArgumentResolverTests.java
web/src/test/java/org/springframework/security/web/reactive/result/method/annotation/CurrentSecurityContextArgumentResolverTests.java

Improve @CurrentSecurityContext meta-annotations

---

docs/modules/ROOT/pages/servlet/oauth2/index.adoc
oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/client/OAuth2ClientHttpRequestInterceptor.java
oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/client/RequestAttributeClientRegistrationIdResolver.java
oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/function/client/OAuth2ClientHttpRequestInterceptorTests.java

Add `RestClient` interceptor

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LoginConfigurer.java
core/src/main/java/org/springframework/security/access/method/MethodSecurityMetadataSource.java
core/src/main/java/org/springframework/security/access/prepost/PrePostInvocationAttributeFactory.java
gradle/libs.versions.toml
ldap/src/main/java/org/springframework/security/ldap/LdapUtils.java
ldap/src/main/java/org/springframework/security/ldap/userdetails/LdapUserDetailsManager.java
oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerAuthenticationManagerResolverDeprecatedTests.java
oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerReactiveAuthenticationManagerResolverDeprecatedTests.java

Supersedes gh-15596 
Backport of gh-15646

Bump io-spring-javaformat from 0.0.42 to 0.0.43

---

config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2LoginConfigurerTests.java
docs/modules/ROOT/pages/reactive/oauth2/login/logout.adoc
docs/modules/ROOT/pages/servlet/oauth2/login/logout.adoc

This contains the following changes to the OIDC logout documentation:
- replace `OidcSessionStrategy` by `OidcSessionRegistry`
- replace `ReactiveOidcSessionStrategy` by `ReactiveOidcSessionRegistry`
- fix broken/inconsistent Java code examples
- fix syntax of adoc source code blocks -- same as in https://github.com/spring-projects/spring-security/pull/15566 to avoid conflicts if that one gets merged first
Furthermore a test name was adjusted to reflect the right terminology.
- There is no `OidcSessionStrategy` in Spring Security, the demo code indicates that actually `OidcSessionRegistry` was meant

Fix OIDC Logout docs: Session Strategy vs. Registry

---

docs/modules/ROOT/pages/servlet/integrations/servlet-api.adoc

In the [```Servlet 3+ Integration```](https://docs.spring.io/spring-security/reference/6.3/servlet/integrations/servlet-api.html#servletapi-authenticate) section of the ```Servlet API Integration``` document, there is an error in the method signature. The correct method signature should be [HttpServletRequest.authenticate(HttpServletResponse)](https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#authenticate%28javax.servlet.http.HttpServletResponse%29).

Fixed typo in the Servlet API Integration documentation

---

core/src/main/java/org/springframework/security/authorization/method/PostAuthorizeExpressionAttributeRegistry.java

Fix variable targetClassToUse is not passed into the synthesize method

---

core/src/main/java/org/springframework/security/authorization/method/AuthorizationAdvisorProxyFactory.java
core/src/test/java/org/springframework/security/authorization/AuthorizationAdvisorProxyFactoryTests.java
docs/modules/ROOT/pages/servlet/authorization/method-security.adoc

Remove the need for @JsonSerialize when serializing authorization proxy objects with Jackson

---

config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeUserDetailsBeanManagerConfigurer.java

We should assume that every `UserDetailsService` is wired with configured `UserDetailsAuthenticationProvider`.
Continuation of commit 7ddc00521ed88df2086eba60d059742057b0d127

Improve warning message

---

web/src/main/java/org/springframework/security/web/savedrequest/CookieRequestCache.java
web/src/main/java/org/springframework/security/web/server/savedrequest/CookieServerRequestCache.java
web/src/test/java/org/springframework/security/web/savedrequest/CookieRequestCacheTests.java
web/src/test/java/org/springframework/security/web/server/savedrequest/CookieServerRequestCacheTests.java

Issue https://github.com/spring-projects/spring-security/issues/15204

Add cookie customizer to CookieRequestCache

---

docs/modules/ROOT/pages/servlet/authentication/events.adoc

The [AuthenticationEventPublisher](https://docs.spring.io/spring-security/site/docs/6.3.3/api/org/springframework/security/authentication/AuthenticationEventPublisher.html) interface does not provide the ```setAdditionalExceptionMappings(Map<Class<? extends AuthenticationException)``` method, and it is located in the [DefaultAuthenticationEventPublisher](https://docs.spring.io/spring-security/site/docs/6.3.3/api/org/springframework/security/authentication/DefaultAuthenticationEventPublisher.html) implementation class.

Corrected AuthenticationEventPublisher Type

---

docs/modules/ROOT/pages/reactive/integrations/observability.adoc
docs/modules/ROOT/pages/servlet/integrations/observability.adoc

In the [```Manual Configuration```](https://docs.spring.io/spring-security/reference/6.3/servlet/integrations/observability.html#observability-tracing-manual-configuration) section of the ```Servlet and Reactive Observability``` documents, the ```ObservationRegistry``` class is incorrectly written: [Type 'io. micrometer. observation. ObservationRegistry' does not have type parameters](https://javadoc.io/doc/io.micrometer/micrometer-observation/1.13.2/io/micrometer/observation/ObservationRegistry.html).

Fixed typos in the Servlet and Reactive Observability documents

---

config/src/main/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistry.java

Address unnecessary method invocation in AbstractRequestMatcherRegistry

---

config/src/main/kotlin/org/springframework/security/config/annotation/web/HttpSecurityDsl.kt
config/src/main/kotlin/org/springframework/security/config/annotation/web/OneTimeTokenLoginDsl.kt
config/src/test/kotlin/org/springframework/security/config/annotation/web/OneTimeTokenLoginDslTests.kt
docs/modules/ROOT/pages/servlet/authentication/onetimetoken.adoc

Add One-Time Token Login support to Kotlin DSL

---

core/src/main/java/org/springframework/security/access/hierarchicalroles/RoleHierarchyImpl.java
core/src/test/java/org/springframework/security/access/hierarchicalroles/RoleHierarchyImplTests.java

_[ As requested by @marcusdacoregio in this [comment](https://github.com/spring-projects/spring-security/pull/15272#issuecomment-2317889390) ]_
When defining a RoleHierarchy you can use the text format and the Builder model.
In the text format you can specify
```
ROLE_A > ROLE_B
ROLE_A > ROLE_C
```
which gives 'A' both 'B' and 'C'
The same specification in the Builder
```
RoleHierarchyImpl.withDefaultRolePrefix()
.role("A").implies("B")
.role("A").implies("C")
.build();
```
which gives 'A' only 'C'
Rootcause: doing `implies` wipes any previous specifications for the same source role.
This fixes that and makes the Builder behave the same as the text format.

Fix adding more implied roles in the RoleHierarchy Builder.

---

core/src/main/java/org/springframework/security/jackson2/AbstractUnmodifiableCollectionDeserializer.java
core/src/main/java/org/springframework/security/jackson2/UnmodifiableListDeserializer.java
core/src/main/java/org/springframework/security/jackson2/UnmodifiableSetDeserializer.java

The goal of this PR is to abstract the common logic found in UnmodifiableListDeserializer and UnmodifiableSetDeserializer to improve maintainability.
To achieve this, an abstract class AbstractUnmodifiableCollectionDeserializer has been introduced to handle shared deserialization logic.
Summary of Changes:
- Abstract Class Created:
- Introduced AbstractUnmodifiableCollectionDeserializer to centralize the common JSON deserialization logic and collection element addition.
- This abstract class uses a generic type <T> to handle various collection types such as List and Set.
- Class Refactoring:
- Refactored UnmodifiableListDeserializer and UnmodifiableSetDeserializer to extend the new abstract class.
- Moved duplicated logic into the abstract class methods, reducing redundancy and improving …

Refactor `UnmodifiableListDeserializer` and `UnmodifiableSetDeserializer` to Use `AbstractUnmodifiableCollectionDeserializer`

---

config/src/test/java/org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfigurationTests.java
core/src/main/java/org/springframework/security/authorization/method/AuthorizationAnnotationUtils.java

Annotation expression template processing should not fail on Class parameter types

---

config/src/test/java/org/springframework/security/config/annotation/web/configurers/DefaultLoginPageConfigurerTests.java
config/src/test/java/org/springframework/security/config/http/FormLoginBeanDefinitionParserTests.java
web/src/main/java/org/springframework/security/web/authentication/ui/DefaultLoginPageGeneratingFilter.java
web/src/main/java/org/springframework/security/web/authentication/ui/DefaultLogoutPageGeneratingFilter.java
web/src/main/java/org/springframework/security/web/authentication/ui/DefaultOneTimeTokenSubmitPageGeneratingFilter.java
web/src/main/java/org/springframework/security/web/authentication/ui/HtmlTemplates.java
web/src/main/java/org/springframework/security/web/server/ui/HtmlTemplates.java
web/src/main/java/org/springframework/security/web/server/ui/LoginPageGeneratingWebFilter.java
web/src/main/java/org/springframework/security/web/server/ui/LogoutPageGeneratingWebFilter.java
web/src/test/java/org/springframework/security/web/authentication/DefaultLoginPageGeneratingFilterTests.java
web/src/test/java/org/springframework/security/web/authentication/ui/DefaultLogoutPageGeneratingFilterTests.java
web/src/test/java/org/springframework/security/web/authentication/ui/DefaultOneTimeTokenSubmitPageGeneratingFilterTests.java
web/src/test/java/org/springframework/security/web/authentication/ui/HtmlTemplatesTests.java
web/src/test/java/org/springframework/security/web/server/ui/LoginPageGeneratingWebFilterTests.java
web/src/test/java/org/springframework/security/web/server/ui/LogoutPageGeneratingWebFilterTests.java

reviewer: @rwinch 
Some notes:
- ~I have not updated the tests, they still use string concatenation sometimes. I'd rather not use the templating in the tests themselves.~ Using text blocks and constants in tests.
- I have added tests that render the full document and assert equality. While they are brittle, they allow to iterate much faster by seeing what's broken.
- ~For context, checktyle / SpringLeadingWhitespace breaks when using space-indented text-blocks. There is an open issue in [spring-javaformat](https://github.com/spring-io/spring-javaformat/issues/421) ; `//@formatter:off` does not suppress the error. I have re-indented all text blocks with tabs. If we really prefer spaces, then we would need file-wide checkstyle suppressions.~ This is is Fixed in spring-javaformat 0.0.43

Use HTML templating in default UIs

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/ott/OneTimeTokenLoginConfigurer.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/ott/OneTimeTokenLoginConfigurerTests.java
web/src/main/java/org/springframework/security/web/authentication/ui/DefaultOneTimeTokenSubmitPageGeneratingFilter.java
web/src/test/java/org/springframework/security/web/authentication/ui/DefaultOneTimeTokenSubmitPageGeneratingFilterTests.java

reviewer: @marcusdacoregio 
Add the following (one commit per line):
- The OneTimeToken default submit UI uses `contextPath` in the form POST action
- Remove unused `<script>` and `<noscript>` tags in OTT submit page
- Remove unused logger in OTT Configurer
- Add OTT Configurer tests that renders the OTT request form on the default login UI

Polish OneTimeTokenLogin

---

docs/modules/ROOT/pages/servlet/authentication/logout.adoc

Corrected the title error of the sample code in [Customizing Logout Success](https://docs.spring.io/spring-security/reference/6.3/servlet/authentication/logout.html#customizing-logout-success) section of ```Handling Logouts``` document.

Correct Title in logout.adoc

---

config/spring-security-config.gradle
config/src/main/java/org/springframework/security/config/annotation/method/configuration/AuthorizationProxyConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/AuthorizationProxyDataConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/MethodSecuritySelector.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/aot/EnableMethodSecurityAotTests.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/aot/Message.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/aot/MessageRepository.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/aot/User.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/aot/UserProjection.java
core/spring-security-core.gradle
core/src/main/java/org/springframework/security/aot/hint/AuthorizeReturnObjectCoreHintsRegistrar.java
core/src/main/java/org/springframework/security/aot/hint/AuthorizeReturnObjectHintsRegistrar.java
core/src/main/java/org/springframework/security/aot/hint/SecurityHintsAotProcessor.java
core/src/main/java/org/springframework/security/aot/hint/SecurityHintsRegistrar.java
core/src/main/resources/META-INF/spring/aot.factories
core/src/test/java/org/springframework/security/aot/hint/AuthorizeReturnObjectCoreHintsRegistrarTests.java
core/src/test/java/org/springframework/security/aot/hint/AuthorizeReturnObjectHintsRegistrarTests.java
core/src/test/java/org/springframework/security/aot/hint/SecurityHintsAotProcessorTests.java
data/src/main/java/org/springframework/security/data/aot/hint/AuthorizeReturnObjectDataHintsRegistrar.java
data/src/test/java/org/springframework/security/data/aot/hint/AuthorizeReturnObjectDataHintsRegistrarTests.java
docs/modules/ROOT/pages/servlet/authorization/method-security.adoc

This API allows for hint registration based on Spring Security's infrastructural beans
There are two built-in implementations:
1. `AuthorizeReturnObjectCoreHintsRegistrar` traverses the object graph of all Spring beans for methods that use `@AuthorizeReturnObject`. It creates the initial proxy class for each of those return values. Also, it uses each return value as a launch point to find other objects that use `@AuthorizeReturnObject`.
2. `AuthorizeReturnObjectDataHintsRegistrar` traverses Spring Data repository factory beans since each repository's primary domain object is often hidden behind generic erasure. It thereafter traverses any object it finds in the same way as 1.
Any return objects that were missed by the scan can be added by the application in the following way:
```java …
```

Add Security Hint AOT Processing

---

config/src/main/java/org/springframework/security/config/annotation/method/configuration/ReactiveAuthorizationManagerMethodSecurityConfiguration.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/PrePostReactiveMethodSecurityConfigurationTests.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/ReactiveMethodSecurityService.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/ReactiveMethodSecurityServiceImpl.java
docs/modules/ROOT/pages/reactive/authorization/method.adoc

EnableReactiveMethodSecurity Supports Custom MethodSecurityExpressionHandler

---

config/src/test/java/org/springframework/security/config/annotation/web/configurers/DefaultLoginPageConfigurerTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/ott/OneTimeTokenLoginConfigurerTests.java
config/src/test/java/org/springframework/security/config/http/FormLoginBeanDefinitionParserTests.java
web/src/main/java/org/springframework/security/web/authentication/ui/DefaultLoginPageGeneratingFilter.java
web/src/test/java/org/springframework/security/web/authentication/DefaultLoginPageGeneratingFilterTests.java

Following gh-15723, default UIs had blank lines with only spaces. These get deleted by the spring-javaformat plugin. In order to avoid this behavior, an extra `\s` had been inserted in the tests. The reason for those `\s` is not obvious.
This commit cleans up the `\s` but changing the HTML templates.

Remove trailing spaces in default UIs

---

config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeAuthenticationProviderBeanManagerConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeUserDetailsBeanManagerConfigurer.java

There was a small bug with `getBeansWithName` in both `InitializeAuthenticationProviderBeanManagerConfigurer` and `InitializeUserDetailsBeanManagerConfigurer`, where we returned a list containing n copies of the same bean.
This did not have any functional impact as we only ever use the list when there is only one element in it.
---
Please merge forward to main.

Fix getBeansWithName in global authentication configurers

---

config/src/main/java/org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfiguration.java
core/src/main/java/org/springframework/security/aot/hint/PrePostAuthorizeExpressionBeanHintsRegistrar.java
core/src/main/java/org/springframework/security/aot/hint/PrePostAuthorizeHintsRegistrar.java
core/src/test/java/org/springframework/security/aot/hint/PrePostAuthorizeHintsRegistrarTests.java
docs/modules/ROOT/pages/servlet/authorization/method-security.adoc

Provide Runtime Hints for Beans used in Pre/PostAuthorize Expressions

---

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/ReactiveJwtDecoders.java

Issue: https://github.com/spring-projects/spring-security/issues/15773
Please tell me if I miss something

Simplify Casting with ReactiveJwtDecoders

---

core/src/test/java/org/springframework/security/provisioning/InMemoryUserDetailsManagerTests.java
crypto/src/main/java/org/springframework/security/crypto/password/DelegatingPasswordEncoder.java
crypto/src/test/java/org/springframework/security/crypto/password/DelegatingPasswordEncoderTests.java

I fear I might have been too slow to submit this! However, this closes gh-14880
Happy to make any changes.

Improved error message for PasswordEncoder

---

docs/modules/ROOT/pages/servlet/integrations/websocket.adoc

Updating integration websocket documentation  
Injecting ApplicationContext and AuthorizationManager is not intuitive  
AuthenticatedAuthorizationManager.authenticated() does not accept security settings

Update websocket integration docs

---

config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java

This is a follow-up to https://github.com/spring-projects/spring-security/pull/13010
At that time, existing deprecation notices were upgraded to 'for removal', yet:
1. The annotation itself was not updated to reflect 'for removal'
2. Further, they both suggest migrating to a method that is _also_ deprecated and slated for removal.
Those two issues combine to create a humorous situation where a deprecation _**warning**_ turns into a deprecation _**error**_ if you follow the advice.

Complete HttpSecurity Deprecation notices

---

core/src/main/java/org/springframework/security/core/annotation/ExpressionTemplateSecurityAnnotationScanner.java

Since `UniqueSecurityAnnotationScanner `has cached annotations internally

Polish ExpressionTemplateSecurityAnnotationScanner

---

config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/AuthenticationConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeUserDetailsBeanManagerConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/rsocket/RSocketSecurity.java
config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java
config/src/main/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/ExpressionUrlAuthorizationConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/RememberMeConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/RequestCacheConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/ServletApiConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/SessionManagementConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/X509Configurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2ClientConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2LoginConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OidcLogoutConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/ott/OneTimeTokenLoginConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LoginConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LogoutConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2MetadataConfigurer.java
config/src/main/java/org/springframework/security/config/authentication/AuthenticationManagerFactoryBean.java
config/src/main/java/org/springframework/security/config/http/GrantedAuthorityDefaultsParserUtils.java
config/src/main/java/org/springframework/security/config/method/GlobalMethodSecurityBeanDefinitionParser.java
config/src/main/java/org/springframework/security/config/method/MethodSecurityBeanDefinitionParser.java
config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java
config/src/test/java/org/springframework/security/config/web/server/CorsSpecTests.java

Closes https://github.com/spring-projects/spring-security/issues/15805

ObjectProvider over custom getBeanOrNull method

---

docs/modules/ROOT/pages/servlet/integrations/observability.adoc

I have fixed the Kotlin example code as it was not syntactically correct and did not work as expected.
Since this is a simple docs fix, I did not create a issue.
and i want this feature really https://github.com/spring-projects/spring-security/issues/15678 🙏🙏

Minor fix in Kotlin docs for noSpringSecurityObservations

---

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/ExpressionJwtGrantedAuthoritiesConverter.java
oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/ExpressionJwtGrantedAuthoritiesConverterTests.java

This helps to reduce custom code necessary to extract roles from deeply nested claims.
Fixes #15201

GH-15201 Introduce ExpressionJwtGrantedAuthoritiesConverter to extract nested authorities via SpEL expression

---

core/src/main/java/org/springframework/security/authentication/ott/InMemoryOneTimeTokenService.java
core/src/test/java/org/springframework/security/authentication/ott/InMemoryOneTimeTokenServiceTests.java

Add public InMemoryOneTimeTokenService.setClock(Clock)

---

config/src/main/java/org/springframework/security/config/annotation/web/configuration/OAuth2ClientConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/web/reactive/ReactiveOAuth2ClientConfiguration.java

Use constructor inject and use `ObjectProvider.getIfUnique` instead of list.size == 1

Polish OAuth2ClientConfiguration

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OidcBackChannelLogoutTokenValidator.java
config/src/main/java/org/springframework/security/config/web/server/OidcBackChannelLogoutTokenValidator.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OidcLogoutConfigurerTests.java
config/src/test/java/org/springframework/security/config/web/server/OidcLogoutSpecTests.java

OidcBackChannelLogoutTokenValidator should not construct when missing OIDC Provider Issuer

---

config/src/main/java/org/springframework/security/config/web/server/OidcBackChannelLogoutReactiveAuthenticationManager.java
config/src/test/java/org/springframework/security/config/web/server/OidcLogoutSpecTests.java

The OIDC back-channel spec recommends using a logout token typ `logout+jwt` (see [here](https://openid.net/specs/openid-connect-backchannel-1_0-final.html#LogoutToken)).
Support of this type was recently added [on the Servlet side](https://github.com/spring-projects/spring-security/commit/9101bf1f7d5ad5d57ebfa2df78135704cdc19b23), so backporting the same on the reactive side to 
close the gap.
Closes gh-15702

Allow logout+jwt JWT type for reactive

---

docs/modules/ROOT/pages/servlet/authentication/passwords/form.adoc
docs/modules/ROOT/pages/servlet/authentication/persistence.adoc

**`UsernamePasswordAuthenticationFilter` Definition raises confusion**
as written in the docs : "When the username and password are submitted, the `UsernamePasswordAuthenticationFilter` authenticates the username and password.", It states that `UsernamePasswordAuthenticationFilter ` is responsible for Authenticating users and populating the `SecurityContext`. instead as stated later we read : "`UsernamePasswordAuthenticationFilter` creates a `UsernamePasswordAuthenticationToken`, which is a type of [Authentication](https://docs.spring.io/spring-security/reference/servlet/authentication/architecture.html#servlet-authentication-authentication), by extracting the username and password from the HttpServletRequest instance."
I think we should change the docs so it wouldn't raise any …

Docs ->  Servlet Applications Authentication  -> Form Login & Persistence 

---

core/src/main/java/org/springframework/security/aot/hint/OneTimeTokenRuntimeHints.java
core/src/main/java/org/springframework/security/authentication/ott/JdbcOneTimeTokenService.java
core/src/main/resources/META-INF/spring/aot.factories
core/src/main/resources/org/springframework/security/core/ott/jdbc/one-time-tokens-schema.sql
core/src/test/java/org/springframework/security/aot/hint/OneTimeTokenRuntimeHintsTests.java
core/src/test/java/org/springframework/security/authentication/ott/JdbcOneTimeTokenServiceTests.java

Add support JdbcOneTimeTokenService

---

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistrations.java
oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/registration/ClientRegistrationsTests.java

This adds the `fromOidcConfiguration` method to `ClientRegistrations` to build a `ClientRegistration` from a map representation of an OpenID Provider Configuration Response.
This is useful when the OpenID Provider Configuration is not available at a well-known location, or if custom validation is needed for the issuer location (e.g. if the issuer is only reachable via a back-channel URI that is different from the issuer value in the configuration).
Example usage:
```java
RequestEntity<Void> request = RequestEntity.get(metadataEndpoint).build();
ParameterizedTypeReference<Map<String, Object>> typeReference = new ParameterizedTypeReference<>() {};
Map<String, Object> configuration = rest.exchange(request, typeReference).getBody();
// Validate configuration.get("issuer") as per in the OIDC …
```

Allow building a ClientRegistration from provided configuration

---

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java
config/src/test/java/org/springframework/security/config/web/server/OAuth2LoginTests.java

Auto config OidcReactiveOAuth2UserService When Oauth2UserService bean is Present

---

buildSrc/src/main/java/org/springframework/gradle/maven/PublishAllJavaComponentsPlugin.java
buildSrc/src/main/java/org/springframework/security/convention/versions/VerifyDependenciesVersionsPlugin.java
config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeAuthenticationProviderBeanManagerConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeUserDetailsBeanManagerConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.java
core/src/main/java/org/springframework/security/jackson2/UserDeserializer.java
core/src/main/java/org/springframework/security/jackson2/UsernamePasswordAuthenticationTokenDeserializer.java
messaging/src/main/java/org/springframework/security/messaging/util/matcher/MessageMatcher.java
oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/jackson2/JsonNodeUtils.java
oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/oidc/authentication/ReactiveOidcIdTokenDecoderFactory.java
oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistrations.java
oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/userinfo/DefaultOAuth2UserService.java
oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/userinfo/DefaultReactiveOAuth2UserService.java
oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/http/converter/OAuth2AccessTokenResponseHttpMessageConverter.java
oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/http/converter/OAuth2ErrorHttpMessageConverter.java
oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/web/reactive/function/OAuth2AccessTokenResponseBodyExtractor.java
oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtDecoderProviderConfigurationUtils.java
oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/ReactiveJwtDecoderProviderConfigurationUtils.java
oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/SpringOpaqueTokenIntrospector.java
oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/SpringReactiveOpaqueTokenIntrospector.java
rsocket/src/main/java/org/springframework/security/rsocket/util/matcher/PayloadExchangeMatcher.java
web/src/main/java/org/springframework/security/web/authentication/LoginUrlAuthenticationEntryPoint.java
web/src/main/java/org/springframework/security/web/authentication/preauth/websphere/DefaultWASUsernameAndGroupsExtractor.java
web/src/main/java/org/springframework/security/web/firewall/StrictHttpFirewall.java
web/src/main/java/org/springframework/security/web/jackson2/PreAuthenticatedAuthenticationTokenDeserializer.java

Polish diamond operator usage

---

acl/src/main/java/org/springframework/security/acls/domain/AclImpl.java
acl/src/main/java/org/springframework/security/acls/domain/DefaultPermissionFactory.java
config/src/main/java/org/springframework/security/config/http/UserDetailsServiceFactoryBean.java
core/src/main/java/org/springframework/security/access/intercept/RunAsManagerImpl.java
core/src/main/java/org/springframework/security/core/userdetails/jdbc/JdbcDaoImpl.java
ldap/src/test/java/org/apache/directory/server/core/avltree/ArrayMarshaller.java
taglibs/src/main/java/org/springframework/security/taglibs/authz/AbstractAuthorizeTag.java
taglibs/src/main/java/org/springframework/security/taglibs/authz/AccessControlListTag.java
web/src/main/java/org/springframework/security/web/FilterChainProxy.java

In the current codebase, we're using .size() == 0 to check if Lists and Maps are empty. I propose changing this to .isEmpty().
Reasons for the proposed change:
1. Improved readability: .isEmpty() more clearly expresses the intent of checking whether a collection is empty.
2. Adherence to Java Collections Framework conventions: isEmpty() is the standard method for checking if a collection is empty.
If there's a specific reason for using `size() == 0` instead of `isEmpty()`, could you please share the rationale?

Improve readibility of empty collection checks

---

config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/ott/OneTimeTokenLoginConfigurer.java
config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java
config/src/main/kotlin/org/springframework/security/config/annotation/web/HttpSecurityDsl.kt
config/src/main/kotlin/org/springframework/security/config/web/server/ServerHttpSecurityDsl.kt
config/src/main/kotlin/org/springframework/security/config/web/server/ServerOneTimeTokenLoginDsl.kt
config/src/test/java/org/springframework/security/config/annotation/web/configurers/ott/OneTimeTokenLoginConfigurerTests.java
config/src/test/java/org/springframework/security/config/web/server/OneTimeTokenLoginSpecTests.java
config/src/test/kotlin/org/springframework/security/config/annotation/web/OneTimeTokenLoginDslTests.kt
config/src/test/kotlin/org/springframework/security/config/web/server/ServerOneTimeTokenLoginDslTests.kt
docs/modules/ROOT/pages/reactive/authentication/onetimetoken.adoc
docs/modules/ROOT/pages/servlet/authentication/onetimetoken.adoc
web/src/main/java/org/springframework/security/web/server/authentication/ott/GenerateOneTimeTokenWebFilter.java
web/src/test/java/org/springframework/security/web/server/authentication/ott/GenerateOneTimeTokenWebFilterTests.java

Add Reactive One-Time Token Login Kotlin DSL Support

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/RememberMeConfigurer.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/RememberMeConfigurerTests.java
web/src/main/java/org/springframework/security/web/authentication/rememberme/RememberMeAuthenticationFilter.java
web/src/test/java/org/springframework/security/web/authentication/rememberme/RememberMeAuthenticationFilterTests.java

As described in gh-2253, the `RememberMeAuthenticationFilter` does not call the configured `SessionAuthenticationStrategy` if there is one, and therefore concurrent session control does not work properly.
This PR adapts the `RememberMeAuthenticationFilter` so that it calls the `SessionAuthenticationStrategy` on successful authentication as the `AbstractAuthenticationProcessingFilter` does. The shared `SessionAuthenticationStrategy` is then used in the `RememberMeConfigurer` to configure the filter like it is done in `FormLoginConfigurer`.
Let me know if anything is missing!

Use SessionAuthenticationStrategy for Remember-Me authentication

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurer.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurerTests.java

Fix extensibility issue since [RequestMatcherDelegatingAuthorizationManager](https://github.com/spring-projects/spring-security/blob/main/web/src/main/java/org/springframework/security/web/access/intercept/RequestMatcherDelegatingAuthorizationManager.java) is `final` and does not expose any public methods other than what is available through [AuthorizationManager](https://github.com/spring-projects/spring-security/blob/main/core/src/main/java/org/springframework/security/authorization/AuthorizationManager.java). Fixes #15948
Allows the following:
```java 
http.authorizeHttpRequests((authorize) -> authorize
.requestMatchers("/assets/**", "/logout").permitAll()
.anyRequest().permitAll().withObjectPostProcessor(new ObjectPostProcessor<AuthorizationManager<HttpServletRequest>>() {
@Override …
```

Make RequestMatcherDelegatingAuthorizationManager post-processable

---

config/src/test/java/org/springframework/security/config/annotation/web/configurers/DefaultLoginPageConfigurerTests.java

The PR aims to fix the `DefaultLoginPageConfigurerTests.loginPageWhenErrorThenDefaultLoginPageWithError()` failure given the system language is set to something else than english.
When asserting the Bad credentials login page, the expected template contains the hardcoded "Bad credentials" message.
When the system language is other than english, this test fails locally as the actual code will produce the localized version of this page.
This PR fixes the issue adding the localized message to the expected page template in order to make sure that it will match the actual response regardless the locale setting.

Fix DefaultLoginPageConfigurerTests localization failure on system language different than english

---

web/src/main/java/org/springframework/security/web/savedrequest/CookieRequestCache.java
web/src/test/java/org/springframework/security/web/savedrequest/CookieRequestCacheTests.java

Closes gh-15905
This is also aligned with `CookieServerRequestCache`
```
onErrorResume(IllegalArgumentException.class, (ex) -> Mono.empty())
```

Catch base64 decode exception

---

web/src/main/java/org/springframework/security/web/authentication/DelegatingAuthenticationConverter.java

This change is valuable since `new ArrayList<>()` and `List.of` have different behaviors, meaning that these two constructors give two different object states without saying so.
This PR aligns the two constructors.

Align DelegatingAuthenticationConverter Constructors

---

core/src/test/java/org/springframework/security/authorization/method/AuthorizationManagerAfterMethodInterceptorTests.java
core/src/test/java/org/springframework/security/authorization/method/AuthorizationManagerBeforeMethodInterceptorTests.java
core/src/test/java/org/springframework/security/authorization/method/PostFilterAuthorizationMethodInterceptorTests.java
core/src/test/java/org/springframework/security/authorization/method/PreFilterAuthorizationMethodInterceptorTests.java
ldap/src/test/java/org/springframework/security/ldap/authentication/ad/ActiveDirectoryLdapAuthenticationProviderTests.java
web/src/test/java/org/springframework/security/web/access/ExceptionTranslationFilterTests.java
web/src/test/java/org/springframework/security/web/concurrent/ConcurrentSessionFilterTests.java

Hi there,
This PR is to address [issue #14768](https://github.com/spring-projects/spring-security/issues/14768), which involves reducing repeated mock object creation in tests. 
I mistakenly closed PR #15256 and then discovered that I do not have permission to reopen it, receiving the message `this branch was force pushed or recreated.`  I'm not sure if I should reopen the original or create this new PR 
Although my issue submission mentioned 4 separate draft PRs, I combined them into this PR, since they all address the same problem.

Factor out some common object mocking in tests

---

.github/workflows/pr-build-workflow.yml

- Enable build scans on the PR workflow. Build scans should be anonymous according to our [develocity-conventions](https://github.com/spring-io/develocity-conventions?tab=readme-ov-file#anonymous-publication)
- Remove the (unmapped) `DEVELOCITY_ACCESS_KEY`

github-actions: configure PR workflow to publish anonymous build scans

---

core/src/main/java/org/springframework/security/authentication/ott/JdbcOneTimeTokenService.java

Polish insert query for JdbcOneTimeTokenService

Polish JdbcOneTimeTokenService

---

web/src/main/java/org/springframework/security/web/authentication/AbstractAuthenticationProcessingFilter.java
web/src/main/java/org/springframework/security/web/authentication/session/ConcurrentSessionControlAuthenticationStrategy.java
web/src/main/java/org/springframework/security/web/context/AbstractSecurityWebApplicationInitializer.java
web/src/main/java/org/springframework/security/web/server/header/ClearSiteDataServerHttpHeadersWriter.java
web/src/main/java/org/springframework/security/web/server/header/ContentSecurityPolicyServerHttpHeadersWriter.java
web/src/main/java/org/springframework/security/web/webauthn/api/AuthenticatorSelectionCriteria.java

Fix typo javadoc some classes

---

docs/modules/ROOT/pages/servlet/saml2/login/authentication.adoc

Currently, this method([createDefaultAssertionValidator](https://github.com/spring-projects/spring-security/blob/51c06a53faf821396fbd0f9c166c7cad19f7cbfb/saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml4AuthenticationProvider.java#L489)) of deprecated is recommended in this saml2 document. 
I have corrected this.

Fix saml2 authentication guide docs

---

config/src/main/java/org/springframework/security/config/annotation/web/builders/WebSecurity.java
web/src/main/java/org/springframework/security/web/DefaultSecurityFilterChain.java

This adds `BeanNameAware` to `DefaultSecurityFilterChain` to improve the information it can provide to logs.
A sample improved message looks like this:
> A filter chain that matches any request [DefaultSecurityFilterChain defined as 'api1' in [org.example.FilterChainConfig] matching [any request] and having filters [DisableEncodeUrl, WebAsyncManagerIntegration, SecurityContextHolder, HeaderWriter, Csrf, Logout, RequestCacheAware, SecurityContextHolderAwareRequest, AnonymousAuthentication, ExceptionTranslation, Authorization]] has already been configured, which means that this filter chain [DefaultSecurityFilterChain defined as 'api2' in [org.example.FilterChainConfig] matching [Or [Mvc [pattern='/app/**']]] and having filters [DisableEncodeUrl, WebAsyncManagerIntegration, …

Improve Error Message for Conflicting Filter Chains

---

web/src/main/java/org/springframework/security/web/server/WebFilterChainProxy.java

In reactive,use `WebFilterChain `instead of `FilterChain`

Correct class name reference in WebFilterChainProxy JavaDoc

---

saml2/saml2-service-provider/src/opensaml4Main/java/org/springframework/security/saml2/provider/service/registration/OpenSaml4AssertingPartyMetadataRepository.java
saml2/saml2-service-provider/src/opensaml4Test/java/org/springframework/security/saml2/provider/service/registration/OpenSaml4AssertingPartyMetadataRepositoryTests.java
saml2/saml2-service-provider/src/opensaml5Main/java/org/springframework/security/saml2/provider/service/registration/OpenSaml5AssertingPartyMetadataRepository.java
saml2/saml2-service-provider/src/opensaml5Test/java/org/springframework/security/saml2/provider/service/registration/OpenSaml5AssertingPartyMetadataRepositoryTests.java

Initialize OpenSAML in OpenSamlAssertingPartyMetadataRepository

---

web/src/test/java/org/springframework/security/MockPortResolver.java

This pull request simplifies the MockPortResolver class by:
* Removing unnecessary parentheses to enhance code readability.
* Adding a static final field for the "https" scheme to improve maintainability and avoid duplication.

Remove unnecessary parentheses and add static final field MockPortResolver#getServerPort

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/servlet/authentication/architecture.adoc
docs/modules/ROOT/pages/servlet/authentication/passwords/erasure.adoc
docs/modules/ROOT/pages/servlet/authentication/passwords/user-details.adoc

Improve documentation about CredentialsContainer

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/WebAuthnConfigurer.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/WebAuthnConfigurerTests.java
web/src/main/java/org/springframework/security/web/authentication/ui/DefaultResourcesFilter.java
web/src/test/java/org/springframework/security/web/authentication/ui/DefaultResourcesFilterTests.java

reviewer: @rwinch 
Use `DefaultResourcesFilter` with a proper static method for webauthn pages.
The filter is registered when:
- the default login page is used
- the default registration page is used
This means the filter may end up registered twice, which may cause a slight performance hit. We accept this tradeoff for code simplicity, since this is not intended for production workloads anyways.

Add DefaultResourcesFilter.webauthn()

---

config/src/main/java/org/springframework/security/config/annotation/rsocket/ReactiveObservationConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/web/socket/WebSocketObservationConfiguration.java
config/src/test/java/org/springframework/security/config/annotation/web/socket/WebSocketMessageBrokerSecurityConfigurationTests.java

I think we should change bean name or use `@ConditionalOnMissingBean`
Closes https://github.com/spring-projects/spring-security/issues/16011

Fix conflicting bean names between @EnableWebSecurity and @EnableWebSocketSecurity

---

config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeAuthenticationProviderBeanManagerConfigurer.java

Delay initialization AuthenticationProvider in Global Authentication

---

docs/modules/ROOT/pages/servlet/oauth2/index.adoc

The code example in the "Access Protected Resources for the Current User" -> "Configure RestClient with ClientHttpRequestInterceptor" section was incorrect. Updated the example to use the correct `OAuth2ClientHttpRequestInterceptor ` constructor and added a call to `setClientRegistrationIdResolver`. This ensures accurate usage of the API.
Closes gh-16165.

Fix OAuth2 documentation: Correct OAuth2ClientHttpRequestInterceptor usage

---

docs/modules/ROOT/pages/whats-new.adoc

This PR fixes a typo in the 'What's New' documentation. The phrase `'select the write' `has been corrected to `'select the right'` for clarity and accuracy.
The change ensures better readability and aligns with the intended meaning in the context of the documentation.
Closes gh-16178

Fix Typo in 'What's New' Documentation

---

messaging/src/main/java/org/springframework/security/messaging/context/AuthenticationPrincipalArgumentResolver.java
messaging/src/main/java/org/springframework/security/messaging/handler/invocation/reactive/AuthenticationPrincipalArgumentResolver.java
messaging/src/main/java/org/springframework/security/messaging/handler/invocation/reactive/CurrentSecurityContextArgumentResolver.java
web/src/main/java/org/springframework/security/web/method/annotation/AuthenticationPrincipalArgumentResolver.java
web/src/main/java/org/springframework/security/web/method/annotation/CurrentSecurityContextArgumentResolver.java
web/src/main/java/org/springframework/security/web/reactive/result/method/annotation/AuthenticationPrincipalArgumentResolver.java
web/src/main/java/org/springframework/security/web/reactive/result/method/annotation/CurrentSecurityContextArgumentResolver.java

Since UniqueSecurityAnnotationScanner has cached annotations internally

Remove duplicate cache in AuthenticationPrincipalArgumentResolver、and CurrentSecurityContextArgumentResolver

---

docs/modules/ROOT/pages/servlet/saml2/opensaml.adoc

- Corrected a typo in the closing dependency XML tag.
- Corrected typo in `<artifactId>` (`opensaml-saml-imple `-> `opensaml-saml-impl`).
- Excluded all `OpenSAML 4.x` dependencies.
- Removed redundant dependencies (`opensaml-core-api` and `opensaml-core-impl`) as they are transitively included in `opensaml-saml-api` and `opensaml-saml-impl`.
Closes gh-16191

Fix: Correct OpenSAML 5.x Documentation

---

config/src/main/java/org/springframework/security/config/annotation/AbstractConfiguredSecurityBuilder.java
config/src/main/java/org/springframework/security/config/annotation/SecurityConfigurerAdapter.java
config/src/main/java/org/springframework/security/config/annotation/authentication/builders/AuthenticationManagerBuilder.java
config/src/main/java/org/springframework/security/config/annotation/authentication/configurers/ldap/LdapAuthenticationProviderConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/authentication/configurers/userdetails/AbstractDaoAuthenticationConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java
config/src/main/java/org/springframework/security/config/annotation/web/builders/WebSecurity.java
config/src/main/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfiguration.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/AbstractHttpConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/ChannelSecurityConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/ExpressionUrlAuthorizationConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/UrlAuthorizationConfigurer.java

Add Deprecated ObjectPostProcessor constructor

---

config/src/main/java/org/springframework/security/config/http/AuthorizationFilterParser.java

Users that are migrating from Spring 5.x don't know that the AuthorizationManager is turned on by default in 6.x and incompatible with their existing Access Decision Manager configuration.
This improvement to the error message with help to bring their attention to the relevant option that is true by default. It will also prevent them from wasting time and looking at where they implement or wire an AuthorizationManager instance.
Closes #16193

Improve AuthorizationManager configuration error messages

---

docs/modules/ROOT/pages/features/integrations/localization.adoc
docs/modules/ROOT/pages/reactive/getting-started.adoc
docs/modules/ROOT/pages/reactive/oauth2/resource-server/bearer-tokens.adoc
docs/modules/ROOT/pages/servlet/appendix/namespace/method-security.adoc
docs/modules/ROOT/pages/servlet/authentication/rememberme.adoc
docs/modules/ROOT/pages/servlet/authentication/runas.adoc
docs/modules/ROOT/pages/servlet/authorization/method-security.adoc
docs/modules/ROOT/pages/servlet/saml2/metadata.adoc

Fix Documentation Typos

---

docs/modules/ROOT/pages/getting-spring-security.adoc

This PR consolidates the separate XML and Gradle code snippets into joint tabs within the getting-spring-security.adoc file
Issue gh-16228

Use Documentation Tags for Maven and Gradle in Getting Started

---

config/spring-security-config.gradle
config/src/integration-test/java/org/springframework/security/config/annotation/configurers/WebAuthnWebDriverTests.java

reviewer: @rwinch 
Add end-to-end tests for the webauthn registration and login, using Selenium + Chrome driver.
Chrome is the only browser supporting virtual authenticators as of today.

webauthn: add webdriver test

---

web/src/main/java/org/springframework/security/web/webauthn/management/Webauthn4JRelyingPartyOperations.java
web/src/test/java/org/springframework/security/web/webauthn/api/TestPublicKeyCredentialCreationOptions.java
web/src/test/java/org/springframework/security/web/webauthn/jackson/JacksonTests.java
web/src/test/java/org/springframework/security/web/webauthn/registration/PublicKeyCredentialCreationOptionsFilterTests.java

[The attestation option in PublicKeyCredentialCreationOptions](https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialcreationoptions-attestation) is a parameter that controls whether to request attestation statement from the security key. Currently, Spring Security Passkeys requests attestation statement by specifiy `direct` value to `attestation` option, but Spring Security Passkeys doesn't implement attestation statement verification[1]. Therefore, the requested attestation statement is not used at all.
Specifying `direct` to request attestation may trigger browsers to display additional privacy related dialog to users, so it is best to avoid specifying `direct` unnecessarily.
[1] Spring Security Passkeys uses [WebAuthnManager.createNonStrictWebAuthnManager()](https://github.com/sprin …

Avoid requesting an unnecessary attestation statement when creating a webauthn credential

---

config/src/main/kotlin/org/springframework/security/config/web/server/ServerHeadersDsl.kt
config/src/test/kotlin/org/springframework/security/config/web/server/ServerHeadersDslTests.kt

Allow configuring custom ServerHttpHeadersWriter for Kotlin DSL

---

config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeUserDetailsBeanManagerConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/authentication/configurers/userdetails/AbstractDaoAuthenticationConfigurer.java
config/src/main/java/org/springframework/security/config/authentication/AuthenticationManagerFactoryBean.java
core/src/main/java/org/springframework/security/authentication/dao/DaoAuthenticationProvider.java
docs/modules/ROOT/pages/servlet/authentication/passwords/index.adoc

This PR simplifies `DaoAuthenticationProvider` construction by moving the required members to the constructor and the optional ones to setters.
Closes gh-15973

Add UserDetailsService Constructor

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/SessionManagementConfigurer.java
config/src/main/java/org/springframework/security/config/http/HttpConfigurationBuilder.java
config/src/main/resources/org/springframework/security/config/spring-security-6.5.rnc
config/src/main/resources/org/springframework/security/config/spring-security-6.5.xsd
config/src/test/java/org/springframework/security/config/annotation/web/configurers/SessionManagementConfigurerTests.java
config/src/test/java/org/springframework/security/config/http/HttpHeadersConfigTests.java
config/src/test/resources/org/springframework/security/config/http/HttpHeadersConfigTests-DefaultsSessionManagementConcurrencyControlMaxSessions.xml
config/src/test/resources/org/springframework/security/config/http/HttpHeadersConfigTests-DefaultsSessionManagementConcurrencyControlMaxSessionsRef.xml
config/src/test/resources/org/springframework/security/config/http/HttpHeadersConfigTests-DefaultsSessionManagementConcurrencyControlWithInvalidMaxSessionsConfig.xml
docs/modules/ROOT/pages/servlet/appendix/namespace/http.adoc
web/src/main/java/org/springframework/security/web/authentication/session/ConcurrentSessionControlAuthenticationStrategy.java
web/src/main/java/org/springframework/security/web/session/SessionLimit.java
web/src/test/java/org/springframework/security/web/authentication/session/ConcurrentSessionControlAuthenticationStrategyTests.java
web/src/test/java/org/springframework/security/web/session/SessionLimitTests.java

Support Determining Max Sessions by Authentication

---

core/src/main/java/org/springframework/security/core/annotation/UniqueSecurityAnnotationScanner.java
core/src/test/java/org/springframework/security/core/annotation/UniqueSecurityAnnotationScannerTests.java

Add @AuthenticationPrincipal/@CurrentSecurityContext Interface Support for Expression Templates

---

web/src/main/java/org/springframework/security/web/aot/hint/PublicKeyCredentialUserEntityRuntimeHints.java
web/src/main/java/org/springframework/security/web/aot/hint/UserCredentialRuntimeHints.java
web/src/main/java/org/springframework/security/web/webauthn/management/JdbcPublicKeyCredentialUserEntityRepository.java
web/src/main/java/org/springframework/security/web/webauthn/management/JdbcUserCredentialRepository.java
web/src/main/resources/META-INF/spring/aot.factories
web/src/main/resources/org/springframework/security/user-credentials-schema.sql
web/src/main/resources/org/springframework/security/user-entities-schema.sql
web/src/test/java/org/springframework/security/web/aot/hint/PublicKeyCredentialUserEntityRuntimeHintsTests.java
web/src/test/java/org/springframework/security/web/aot/hint/UserCredentialRuntimeHintsTests.java
web/src/test/java/org/springframework/security/web/webauthn/api/TestCredentialRecord.java
web/src/test/java/org/springframework/security/web/webauthn/management/JdbcPublicKeyCredentialUserEntityRepositoryTests.java
web/src/test/java/org/springframework/security/web/webauthn/management/JdbcUserCredentialRepositoryTests.java

Add Support JDBC Repositories For WebAuthn

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/AbstractHttpConfigurer.java

Use `getBeanProvider `instead of `getBeanNamesForType`.

Polish AbstractHttpConfigurer 

---

docs/modules/ROOT/pages/servlet/architecture.adoc

Change deprecated FilterSecurityInterceptor to AuthorizationFilter with a link to authorization page.

Update docs to link to AuthorizationFilter instead of deprecated FilterSecurityInterceptor

---

docs/modules/ROOT/pages/servlet/oauth2/client/index.adoc

Text `OAuth 2.0 Client` does not link to page `OAuth 2.0 Client`
Reference
https://docs.spring.io/spring-security/reference/6.5-SNAPSHOT/servlet/oauth2/index.html#further-reading

Fix OAuth reference documentation typo

---

docs/modules/ROOT/pages/servlet/authentication/logout.adoc

- Fix logout code snippet for Kotlin: Corrected deleteCookies syntax
- The deleteCookies property of org.springframework.security.config.annotation.web.LogoutDsl has a private access modifier, so it cannot be used in the format deleteCookies = ""

Fix logout code snippet for Kotlin

---

docs/modules/ROOT/pages/servlet/authorization/method-security.adoc

val/var on function parameters is invalid Kotlin syntax. It has been removed quite some time ago. This change updates the method-security page to reflect that.

method-security: fix invalid Kotlin syntax

---

config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.java

Remove unused code，`webSecurityConfigurers and beanClassLoader`

Remove unused code from WebSecurityConfiguration

---

config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.java
config/src/test/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurationTests.java

Use ObjectProvider instead of @Autowired HttpSecurity because when the user provides a SecurityFilterChain bean, it will still inject HttpSecurity. Since HttpSecurity is a prototype bean, this avoids its instantiation.

Avoid unnecessary instantiation of HttpSecurity

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2LoginConfigurer.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2LoginConfigurerTests.java

Add Support OAuth2AuthorizationRequestResolver As Bean

---

docs/modules/ROOT/pages/servlet/authentication/architecture.adoc
docs/modules/ROOT/pages/servlet/authentication/persistence.adoc

Fixed grammatical mistakes/errors in the docs.

---

config/src/main/kotlin/org/springframework/security/config/annotation/web/AuthorizeHttpRequestsDsl.kt
config/src/test/kotlin/org/springframework/security/config/annotation/web/AuthorizeHttpRequestsDslTests.kt

Add support fullyAuthenticated to Kotlin DSL

---

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/oidc/web/server/logout/OidcClientInitiatedServerLogoutSuccessHandler.java
oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/oidc/web/server/logout/OidcClientInitiatedServerLogoutSuccessHandlerTests.java

Customize Redirect URI in OidcClientInitiatedServerLogoutSuccessHandler

---

web/src/main/java/org/springframework/security/web/ObservationFilterChainDecorator.java

Use spring.security prefix instead of security.security

---

core/src/main/java/org/springframework/security/core/ComparableVersion.java

Suggestion: Consider using isEmpty() instead of size() == 0
I hope this doesn’t cause any inconvenience, but I was wondering if there’s a specific reason why size() == 0 is used instead of isEmpty(). Using isEmpty() can make the code more readable and aligns with modern Java practices. It conveys the intent more clearly, improving overall clarity.
I apologize for taking your time and appreciate your consideration.

Suggest replacing size() == 0 with isEmpty() for collection check

---

docs/modules/ROOT/pages/servlet/test/mockmvc/index.adoc

Link to Test chapter of Spring Framework documentation is broken, this commit fixes it.
No GitHub issue created for this.

Fix broken link to MockMvc documentation

---

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/SpringOpaqueTokenIntrospector.java
oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/SpringReactiveOpaqueTokenIntrospector.java
oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/introspection/SpringOpaqueTokenIntrospectorTests.java
oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/introspection/SpringReactiveOpaqueTokenIntrospectorTests.java

Encode clientId and clientSecret for `OpaqueTokenIntrospector` and `ReactiveOpaqueTokenIntrospector`

---

javascript/lib/webauthn-core.js
javascript/test/webauthn-core.test.js

webauthn js should ensure allowCredentials[].id is an ArrayBuffer

---

web/src/test/java/org/springframework/security/web/authentication/ott/GenerateOneTimeTokenFilterTests.java

Added tests for GenerateOneTimeTokenFilter.

Add GenerateOneTimeTokenFilterTests

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/ott/OneTimeTokenLoginConfigurer.java
config/src/main/kotlin/org/springframework/security/config/annotation/web/OneTimeTokenLoginDsl.kt
config/src/test/java/org/springframework/security/config/annotation/web/configurers/ott/OneTimeTokenLoginConfigurerTests.java
config/src/test/kotlin/org/springframework/security/config/annotation/web/OneTimeTokenLoginDslTests.kt
core/src/main/java/org/springframework/security/authentication/ott/GenerateOneTimeTokenRequest.java
core/src/main/java/org/springframework/security/authentication/ott/InMemoryOneTimeTokenService.java
core/src/main/java/org/springframework/security/authentication/ott/JdbcOneTimeTokenService.java
docs/modules/ROOT/pages/servlet/authentication/onetimetoken.adoc
docs/modules/ROOT/pages/whats-new.adoc
web/src/main/java/org/springframework/security/web/authentication/ott/DefaultGenerateOneTimeTokenRequestResolver.java
web/src/main/java/org/springframework/security/web/authentication/ott/GenerateOneTimeTokenFilter.java
web/src/main/java/org/springframework/security/web/authentication/ott/GenerateOneTimeTokenRequestResolver.java
web/src/test/java/org/springframework/security/web/authentication/ott/DefaultGenerateOneTimeTokenRequestResolverTests.java

Add Support GenerateOneTimeTokenRequestResolver

---

settings.gradle

[issue#16322](https://github.com/spring-projects/spring-security/issues/16322)

Update settings.gradle to correct the behavior if creating a new subproject with default buildFile name

---

core/src/main/java/org/springframework/security/provisioning/InMemoryUserDetailsManager.java

Update UsernameNotFoundException message

---

web/src/main/java/org/springframework/security/web/access/HttpStatusAccessDeniedHandler.java
web/src/test/java/org/springframework/security/web/access/HttpStatusAccessDeniedHandlerTests.java

Add `HttpStatusAccessDeniedHandler`, **`AccessDeniedHandler` that sets the HTTP status code** like `HttpStatusEntryPoint`. This feature is already supported by Spring WebFlux as `HttpStatusServerAccessDeniedHandler`, but is not supported by Spring Web MVC.

Add `HttpStatusAccessDeniedHandler`

---

web/src/main/java/org/springframework/security/web/authentication/ott/DefaultGenerateOneTimeTokenRequestResolver.java

Fixed assertion in `DefaultGenerateOneTimeTokenRequestResolver`.

Fixed assertion in DefaultGenerateOneTimeTokenRequestResolver

---

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java
config/src/main/kotlin/org/springframework/security/config/web/server/ServerOneTimeTokenLoginDsl.kt
config/src/test/java/org/springframework/security/config/web/server/OneTimeTokenLoginSpecTests.java
config/src/test/kotlin/org/springframework/security/config/web/server/ServerOneTimeTokenLoginDslTests.kt
docs/modules/ROOT/pages/reactive/authentication/onetimetoken.adoc
web/src/main/java/org/springframework/security/web/server/authentication/ott/DefaultServerGenerateOneTimeTokenRequestResolver.java
web/src/main/java/org/springframework/security/web/server/authentication/ott/GenerateOneTimeTokenWebFilter.java
web/src/main/java/org/springframework/security/web/server/authentication/ott/ServerGenerateOneTimeTokenRequestResolver.java
web/src/test/java/org/springframework/security/web/server/authentication/ott/DefaultServerGenerateOneTimeTokenRequestResolverTests.java

Add Support ServerGenerateOneTimeTokenRequestResolver

---

docs/modules/ROOT/partials/servlet/oauth2/client/rest-client-access-token-response-client.adoc

In line 260, there is the mention of "=== Customizing the `WebClient`" while it should be "=== Customizing the `RestClient`"

Fix RestClient Documentation Header

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/DPoPAuthenticationConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurer.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/DPoPAuthenticationConfigurerTests.java
oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/OAuth2ErrorCodes.java
oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/DPoPProofContext.java
oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/DPoPProofJwtDecoderFactory.java
oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/DPoPProofJwtDecoderFactoryTests.java
oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/DPoPAuthenticationProvider.java
oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/DPoPAuthenticationToken.java
oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/DPoPAuthenticationProviderTests.java

This PR adds **resource server support** for [RFC 9449 OAuth 2.0 Demonstrating Proof of Possession (DPoP)](https://datatracker.ietf.org/doc/html/rfc9449).
See `DPoPAuthenticationConfigurerTests` which demonstrates how to use DPoP-bound access token authentication.

Add support for OAuth 2.0 Demonstrating Proof of Possession (DPoP)

---

core/src/main/java/org/springframework/security/authorization/method/PreAuthorizeExpressionAttributeRegistry.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/BaseOpenSamlAuthenticationProvider.java
saml2/saml2-service-provider/src/opensaml4Main/java/org/springframework/security/saml2/provider/service/registration/OpenSaml4AssertingPartyMetadataRepository.java
saml2/saml2-service-provider/src/opensaml4Test/java/org/springframework/security/saml2/provider/service/authentication/TestCustomOpenSaml4Objects.java
saml2/saml2-service-provider/src/opensaml5Main/java/org/springframework/security/saml2/provider/service/registration/OpenSaml5AssertingPartyMetadataRepository.java
saml2/saml2-service-provider/src/opensaml5Test/java/org/springframework/security/saml2/provider/service/authentication/TestCustomOpenSaml5Objects.java

Consistently NonNull annotation

---

docs/modules/ROOT/pages/features/authentication/password-storage.adoc
docs/modules/ROOT/pages/reactive/exploits/csrf.adoc
docs/modules/ROOT/pages/reactive/oauth2/resource-server/bearer-tokens.adoc

Consistently Spring Security javadocs

---

docs/modules/ROOT/pages/servlet/configuration/java.adoc

Update reference Spring Framwork links

---

config/src/test/java/org/springframework/security/config/annotation/web/configurers/DefaultLoginPageConfigurerTests.java
core/src/main/java/org/springframework/security/authentication/ProviderManager.java
web/src/main/java/org/springframework/security/web/authentication/ui/DefaultLoginPageGeneratingFilter.java
web/src/test/java/org/springframework/security/web/authentication/DefaultLoginPageGeneratingFilterTests.java

Overview,
1. Login page, now displays "Invalid Credentials" as a generic error message for any authentication failures.
2. Debug messages are provided at `ProviderManager` to check where and why the authentication has failed.
Closes [gh-16484](https://github.com/spring-projects/spring-security/issues/16473?issue=spring-projects%7Cspring-security%7C16484)

Generic error message in Log In page and debug messages

---

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtEncoder.java
oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jose/TestJwks.java
oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusJwtEncoderTests.java

Signed-off-by: douxiaofeng99 <18600127780@163.com>

Support JWK Selection Strategy in NimbusJwtEncoder

---

core/src/main/java/org/springframework/security/authentication/ott/OneTimeTokenAuthenticationProvider.java
core/src/test/java/org/springframework/security/authentication/ott/OneTimeTokenAuthenticationProviderTests.java

Add BadCredentialsException to OneTimeTokenAuthenticationProvider

---

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistrations.java
oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/registration/ClientRegistrationsTests.java
oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtDecoderProviderConfigurationUtils.java
oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/ReactiveJwtDecoderProviderConfigurationUtils.java
oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/JwtDecoderProviderConfigurationUtilsTests.java
oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/ReactiveJwtDecoderProviderConfigurationUtilsTests.java

Closes #15852
By using `UriComponentsBuilder.fromUriString` we stay in a single semantic context and do not loose information.

JwtDecoders should support issuer hostnames containing underscores

---

docs/modules/ROOT/pages/servlet/appendix/faq.adoc

Fix typo `security-api-url` attribute in `faq.adoc`

---

docs/modules/ROOT/pages/servlet/authorization/method-security.adoc

Replace @PreFilter with @Postfilter in example

Fix @PostResult example in method-security doc

---

core/src/main/java/org/springframework/security/provisioning/JdbcUserDetailsManager.java
core/src/test/java/org/springframework/security/provisioning/JdbcUserDetailsManagerTests.java

- added setUserDetailsMapper method to allow customization of UserDetails mapping using RowMapper
- added setGrantedAuthorityMapper method to allow customization of GrantedAuthority mapping using RowMapper
- unit tests for updated methods
- Closes gh-16540

Add customizable RowMappers for user details and authorities in JdbcUserDetailsManager

---

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/DelegatingOAuth2AuthorizedClientProvider.java
oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/DelegatingReactiveOAuth2AuthorizedClientProvider.java
oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/OAuth2AuthorizedClient.java
oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/authentication/OAuth2AuthenticationToken.java
oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/userinfo/DelegatingOAuth2UserService.java
oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/DefaultOAuth2AuthorizationRequestResolver.java
oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/AuthorizationGrantType.java
oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtDecoder.java
oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtEncoder.java
oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoder.java
oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/ReactiveJwtDecoder.java

Noticed one of the four oauth grant types was missing in this section of javadoc.  Included some minor grammar changes too.

Grammar Fixes in OAuth 2.0 JavaDoc

---

docs/modules/ROOT/pages/migration/oauth2.adoc
docs/modules/ROOT/pages/reactive/oauth2/resource-server/jwt.adoc
docs/modules/ROOT/pages/servlet/oauth2/resource-server/jwt.adoc
oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtTypeValidator.java
oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtValidators.java
oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java
oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoder.java
oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/JwtTypeValidatorTests.java
oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/JwtValidatorsTests.java
oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderTests.java
oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoderTests.java

Allow at+jwt, according to RFC-9068

---

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtAudienceValidator.java
oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtValidators.java
oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/JwtAudienceValidatorTests.java

Since audience is among claims that are often validated, this PR introduces `JwtAudienceValidator` to simplify such use case with `spring-security-oauth2-jose`. I've also plugged the new validator into recently introduced `at+jwt` support (thanks for that).

Introduce JwtAudienceValidator

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurer.java
config/src/main/java/org/springframework/security/config/annotation/web/configurers/PermitAllSupport.java
core/src/main/java/org/springframework/security/authorization/SingleResultAuthorizationManager.java
core/src/main/java/org/springframework/security/authorization/method/Jsr250AuthorizationManager.java
core/src/test/java/org/springframework/security/authorization/AuthorizationManagerTests.java
core/src/test/java/org/springframework/security/authorization/AuthorizationManagersTests.java
core/src/test/java/org/springframework/security/authorization/SingleResultAuthorizationManagerTests.java
messaging/src/main/java/org/springframework/security/messaging/access/intercept/MessageMatcherDelegatingAuthorizationManager.java
web/src/main/java/org/springframework/security/web/access/intercept/RequestMatcherDelegatingAuthorizationManager.java
web/src/test/java/org/springframework/security/web/access/intercept/RequestMatcherDelegatingAuthorizationManagerTests.java

Add SingleResultAuthorizationManager

---

web/src/main/java/org/springframework/security/web/webauthn/management/JdbcUserCredentialRepository.java
web/src/test/java/org/springframework/security/web/webauthn/management/JdbcUserCredentialRepositoryTests.java

Fix JdbcUserCredentialRepository Save

---

docs/modules/ROOT/pages/servlet/oauth2/login/logout.adoc

Fix Typos in OIDC Back-Channel Logout documentation 

---

web/src/main/java/org/springframework/security/web/authentication/AbstractAuthenticationTargetUrlRequestHandler.java
web/src/test/java/org/springframework/security/web/authentication/AbstractAuthenticationTargetUrlRequestHandlerTests.java

This is small polish add assertion to `setRedirectStrategy` of `AbstractAuthenticationTargetUrlRequestHandler` to prevent `NullPointnerException`.

Polish AbstractAuthenticationTargetUrlRequestHandler

---

core/src/main/java/org/springframework/security/core/annotation/UniqueSecurityAnnotationScanner.java
core/src/test/java/org/springframework/security/core/annotation/UniqueSecurityAnnotationScannerTests.java

When searching for parameter annotations, I overlooked a scenario as below:
```java
interface RemoteUserService {
void batch(@CustomParameterAnnotation("six") String... user);
}
class UserServiceImpl implements RemoteUserService {
@Override
public void batch(@CustomParameterAnnotation("seven") String... user) {
}
}
class DefaultUserService extends UserServiceImpl implements RemoteUserService {
@Override
public void batch(String... user) {
}
}
```
When I run test should be throw exception :
```java
Parameter parameter = DefaultUserService.class.getDeclaredMethod("batch", String[].class).getParameters()[0];
this.parameterScanner.scan(parameter);
```

Fixed the issue where the annotation parameter scan skipped first-level conflicts

---

saml2/saml2-service-provider/src/opensaml5Main/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml5AuthenticationProvider.java
saml2/saml2-service-provider/src/opensaml5Main/java/org/springframework/security/saml2/provider/service/authentication/logout/OpenSaml5LogoutRequestValidator.java
saml2/saml2-service-provider/src/opensaml5Main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSaml5LogoutRequestResolver.java
saml2/saml2-service-provider/src/opensaml5Main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSaml5LogoutResponseResolver.java

Fixing some typos that I found while integrating with Open SAML 5

Fix typos Open SAML 5 Javadoc referencing Open SAML 4

---

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/JdbcOAuth2AuthorizedClientService.java
oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/JdbcOAuth2AuthorizedClientServiceTests.java
web/src/main/java/org/springframework/security/web/webauthn/management/JdbcPublicKeyCredentialUserEntityRepository.java

Improve entity fetching from db

---

docs/modules/ROOT/pages/servlet/integrations/data.adoc

No need to declare the method that create a bean as a public, and no need to declare interface that extends ```PagingAndSortingRepository``` with ```@Repository```

Removed Unnecessary Code in Documentation

---

config/src/test/java/org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfigurationTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurerTests.java
core/src/main/java/org/springframework/security/authorization/event/AuthorizationDeniedEvent.java
core/src/main/java/org/springframework/security/authorization/event/AuthorizationGrantedEvent.java

Add support ResolvableTypeProvider to AuthorizationEvent

---

web/src/main/java/org/springframework/security/web/server/csrf/CsrfException.java
web/src/main/java/org/springframework/security/web/server/csrf/WebSessionServerCsrfTokenRepository.java

I fixed javadocs on WebFlux CSRF protection classes.
They wrongly have Servlet API references since they were copied from Servlet equivalents.

Fix javadocs on WebFlux CSRF classes

---

test/src/test/java/org/springframework/security/test/web/reactive/server/SecurityMockServerConfigurersTests.java
web/src/main/java/org/springframework/security/web/server/authorization/HttpStatusServerAccessDeniedHandler.java
web/src/test/java/org/springframework/security/web/server/authorization/HttpStatusServerAccessDeniedHandlerTests.java

- HttpStatusServerAccessDeniedHandler previously returned the exception message,
which could expose sensitive information.
- This PR ensures that the handler always returns a static "Access Denied" message.
- Updated HttpStatusServerAccessDeniedHandler to return a static message.
- Updated tests to verify the response body.
Closes gh-16514

Replace dynamic error message with static "Access Denied"

---

docs/modules/ROOT/pages/servlet/authentication/passwords/basic.adoc

As discussed in https://github.com/spring-projects/spring-security/issues/16103
Add a short explaination why default configuration will not send `WWW-Authenticate` header when called from javascript XHR.
@sjohnr

Explain behaviour with XMLHttpRequest on 401 response

---

docs/modules/ROOT/pages/servlet/authorization/authorize-http-requests.adoc

As discussed in https://github.com/spring-projects/spring-security/issues/12950, the request matcher pattern examples on the [Authorize HTTP Requests - Security Matchers](https://docs.spring.io/spring-security/reference/servlet/authorization/authorize-http-requests.html#security-matchers) page are incorrect:
*  `/user/**` should be `/api/user/**`
*  `/admin/**` should be `/api/admin/**`

Fix the request matcher patterns in the documentation

---

core/src/main/java/org/springframework/security/authentication/DelegatingReactiveAuthenticationManager.java
core/src/main/java/org/springframework/security/authentication/ProviderManager.java
core/src/main/java/org/springframework/security/core/AuthenticationException.java
core/src/main/java/org/springframework/security/jackson2/BadCredentialsExceptionMixin.java
core/src/test/java/org/springframework/security/authentication/DelegatingReactiveAuthenticationManagerTests.java
core/src/test/java/org/springframework/security/authentication/ProviderManagerTests.java
etc/checkstyle/checkstyle-suppressions.xml
oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerAuthenticationManagerResolver.java
oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerReactiveAuthenticationManagerResolver.java
oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerAuthenticationManagerResolverTests.java
oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerReactiveAuthenticationManagerResolverTests.java
web/src/main/java/org/springframework/security/web/access/ExceptionTranslationFilter.java
web/src/main/java/org/springframework/security/web/authentication/RequestMatcherDelegatingAuthenticationManagerResolver.java
web/src/main/java/org/springframework/security/web/server/authentication/ServerWebExchangeDelegatingReactiveAuthenticationManagerResolver.java
web/src/main/java/org/springframework/security/web/server/authorization/ExceptionTranslationWebFilter.java
web/src/test/java/org/springframework/security/web/access/ExceptionTranslationFilterTests.java
web/src/test/java/org/springframework/security/web/server/authorization/ExceptionTranslationWebFilterTests.java

- #16444 
- Store the authentication request details in the `authRequest` field of `AuthenticationException` when an authentication exception occurs.
@rwinch

Include AuthenticationRequest in AuthenticationException

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/CorsConfigurer.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/CorsConfigurerTests.java
config/src/test/kotlin/org/springframework/security/config/annotation/web/CorsDslTests.kt

Update HandlerMappingIntrospector Usage in CORS support

---

config/src/test/java/org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfigurationTests.java
core/src/main/java/org/springframework/security/authorization/method/AuthorizationAdvisorProxyFactory.java
core/src/test/java/org/springframework/security/authorization/AuthorizationAdvisorProxyFactoryTests.java

Sorting in AuthorizationAdvisorProxyFactory should be thread-safe

---

web/src/main/java/org/springframework/security/web/util/matcher/IpAddressMatcher.java
web/src/test/java/org/springframework/security/web/util/matcher/IpAddressMatcherTests.java

Closes gh-16795
Implemented the toString method based on gh-16795.
In the future, if getHostAddress() or getMaskBits() methods are introduced, the internal logic of toString may be updated to use those methods.
Fixed a formatting issue detected in build #5695 (checkFormatTest failure) and resubmitted the PR.

Add toString to IpAddressMatcher

---

core/src/main/java/org/springframework/security/authentication/dao/AbstractUserDetailsAuthenticationProvider.java

This PR adds validation for `preAuthenticationChecks` and `postAuthenticationChecks` in 
`AbstractUserDetailsAuthenticationProvider`. The primary approach is to add assertions in
the `afterPropertiesSet()` method to detect null values early in the application lifecycle.
Currently, if these checks are set to null, a `NullPointerException` is thrown during the 
authentication process, which might be difficult to troubleshoot. The early validation approach
ensures errors are detected at initialization time with a clear error message.
As an alternative, we could add null checks before invoking the `check()` methods:
```java
if (this.preAuthenticationChecks != null) {
this.preAuthenticationChecks.check(user);
}

Add not null validation for UserDetailsChecker in AbstractUserDetailsAuthenticationProvider

---

web/src/main/java/org/springframework/security/web/aot/hint/UserCredentialRuntimeHints.java
web/src/main/resources/org/springframework/security/user-credentials-schema-postgres.sql
web/src/test/java/org/springframework/security/web/aot/hint/UserCredentialRuntimeHintsTests.java

Add Support Postgres To JdbcUserCredentialRepository

---

web/src/main/java/org/springframework/security/web/server/csrf/CookieServerCsrfTokenRepository.java
web/src/test/java/org/springframework/security/web/server/csrf/CookieServerCsrfTokenRepositoryTests.java

WithHttpOnlyCookie defaults to false

---

config/src/test/java/org/springframework/security/config/annotation/web/builders/TestHttpSecurities.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/DefaultFiltersTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/NamespaceHttpCustomFilterTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/SecurityContextConfigurerTests.java
web/src/test/java/org/springframework/security/web/access/RequestMatcherDelegatingWebInvocationPrivilegeEvaluatorTests.java
web/src/test/java/org/springframework/security/web/access/TestWebInvocationPrivilegeEvaluators.java

This PR addresses issue #16604 by renaming several WebAuthn test object classes to follow the established Spring Security convention of naming test objects as Test{Object}s (plural form).
Changes
Renamed TestAuthenticatorAttestationResponse → TestAuthenticatorAttestationResponses
Renamed TestCredentialRecord → TestCredentialRecords
Renamed TestPublicKeyCredential → TestPublicKeyCredentials
Renamed TestPublicKeyCredentialUserEntity → TestPublicKeyCredentialUserEntities
Renamed TestPublicKeyCredentialRpEntity → TestPublicKeyCredentialRpEntities

Update WebAuthn Test Objects Class Names

---

crypto/src/main/java/org/springframework/security/crypto/keygen/Base64StringKeyGenerator.java

Changes
> keyLength must be greater than or equal to32
into
> keyLength must be greater than or equal to 32

Typo in Base64StringKeyGenerator exception message

---

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/OpaqueTokenIntrospector.java

Polish javadoc

---

docs/modules/ROOT/pages/servlet/configuration/kotlin.adoc

During implementation of SecurityFilterChain in kotlin, it was noticed that the documented examples for 
public final fun securityMatcher(vararg pattern: String): Unit was missing the spread operator to turn the arrayOf into a varargs

Update kotlin.adoc to add required spread operator(*)

---

crypto/src/main/java/org/springframework/security/crypto/argon2/Argon2EncodingUtils.java
crypto/src/test/java/org/springframework/security/crypto/argon2/Argon2EncodingUtilsTests.java

Parsing Argon2 params relies on `String[] parts = encodedHash.split("\\$")`. For a string beginning with a `$`, the first element of the resulting array will be empty. This is already addressed in the code, with the variable `int currentPart` being initialized with `1`. But the IllegalArgumentException message incorrectly refers to `part[0]`, which will be empty for a well-formed Argon2 string starting with `$`.
The fix is trivial in this case, just use the array index 1.
P.S. one could also check for the 0-th array element to be an empty string and throw an IllegalArgumentException if it's not. However, this requires additional domain expertise and as such goes beyond the scope.

Fix IllegalArgumentException message for unknown Argon2 types

---

docs/modules/ROOT/pages/reactive/oauth2/resource-server/opaque-token.adoc
docs/modules/ROOT/pages/servlet/oauth2/resource-server/opaque-token.adoc

the getter method is `getOpaquetoken()` not `getOpaqueToken()`
See https://github.com/spring-projects/spring-boot/blob/c6045c3111c43bd7b0f99e6c2858bfb2999e358f/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/OAuth2ResourceServerProperties.java#L51

Use proper configuration key in Opaque Token documentation

---

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistrations.java
oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/registration/ClientRegistrationsTests.java

ClientRegistrations#fromIssuerLocation should not swallow 4xx exception messages

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/WebAuthnConfigurer.java

Assertions have been added to WebAuthnConfigurer. Also some code cleanup was done.

Polish WebAuthnConfigurer

---

core/src/main/java/org/springframework/security/provisioning/JdbcUserDetailsManager.java
core/src/test/java/org/springframework/security/provisioning/JdbcUserDetailsManagerTests.java

Hello everyone,
This proposal is about tiny enhancements applied to JdbcUserDetailsManager.userExists() method.
As we do not really use an information returned by select query
`select username from users where username = ?`,
and only resultset size is important, my idea is to replace it with an ordinary `count` query.
Some pros of this approach:
* It works faster on DB side and IMO the code is more straightforward in this case, you see what's the purpose just looking on sql
* No need to create unnecessary wrappers on Java side. Currently JdbcTemplate creates a list with a one single purpose - to let the code check its size - and then it goes directly to GC. Not used for iterating over it or any modification/read operations.
* Overloaded version of queryForList() method used there is …

Improve JdbcUserDetailsManager.userExists method

---

web/src/main/java/org/springframework/security/web/csrf/CookieCsrfTokenRepository.java
web/src/test/java/org/springframework/security/web/csrf/CookieCsrfTokenRepositoryTests.java

From : https://github.com/spring-projects/spring-security/issues/14132 
Removing the Deprecated methods used in CookieServerCsrfTokenRepository.

Remove deprecated methods from CookieServerCsrfTokenRepository

---

crypto/src/main/java/org/springframework/security/crypto/encrypt/BouncyCastleAesCbcBytesEncryptor.java
crypto/src/main/java/org/springframework/security/crypto/encrypt/BouncyCastleAesGcmBytesEncryptor.java
crypto/src/test/java/org/springframework/security/crypto/encrypt/BouncyCastleAesBytesEncryptorEquivalencyTests.java

- Update AESEngine to use the default AES engine, following BouncyCastle's recommendations (see release-1-56 of changelog: https://www.bouncycastle.org/download/bouncy-castle-java/?filter=java%3Drelease-1-56).
- Migrate to the latest API 'newInstance()' method to allow removal of method level @SuppressWarnings("deprecation")
- Remove @SuppressWarnings("deprecation"), as it is not needed anymore

Address BouncyCastle's deprecated AESFastEngine usage

---

web/src/main/java/org/springframework/security/web/authentication/rememberme/AbstractRememberMeServices.java
web/src/main/java/org/springframework/security/web/firewall/FirewalledResponse.java
web/src/main/java/org/springframework/security/web/jackson2/CookieDeserializer.java
web/src/main/java/org/springframework/security/web/jackson2/SavedCookieMixin.java
web/src/main/java/org/springframework/security/web/savedrequest/SavedCookie.java
web/src/test/java/org/springframework/security/web/authentication/rememberme/AbstractRememberMeServicesTests.java
web/src/test/java/org/springframework/security/web/firewall/FirewalledResponseTests.java
web/src/test/java/org/springframework/security/web/jackson2/DefaultSavedRequestMixinTests.java
web/src/test/java/org/springframework/security/web/jackson2/SavedCookieMixinTests.java
web/src/test/java/org/springframework/security/web/savedrequest/SavedCookieTests.java

**ISSUE:** gh-16889
Removing deprecated cookie methods comment & version.
These changes partly addresses the gh-16889. To prevent review fatigue, I'll create to additional PRs.
**Note:** `CookieMixinTests` will need to be updated when the `comment` & `version` methods are removed from the Jakarta Servlet API. [PR](https://github.com/jakartaee/servlet/pull/858) to deprecate the methods.

Remove deprecated Cookie method usage

---

config/src/main/java/org/springframework/security/config/oauth2/client/CommonOAuth2Provider.java
docs/modules/ROOT/pages/reactive/oauth2/login/core.adoc
docs/modules/ROOT/pages/servlet/oauth2/login/core.adoc

Add Twitter/X to CommonOAuth2Provider
#16379

Add Twitter/X to CommonOAuth2Provider

---

web/src/main/java/org/springframework/security/web/csrf/CsrfFilter.java
web/src/main/java/org/springframework/security/web/csrf/CsrfTokenRequestAttributeHandler.java
web/src/main/java/org/springframework/security/web/csrf/CsrfTokenRequestHandler.java
web/src/main/java/org/springframework/security/web/csrf/CsrfTokenRequestHandlerLoggerHolder.java
web/src/main/java/org/springframework/security/web/csrf/XorCsrfTokenRequestAttributeHandler.java
web/src/main/java/org/springframework/security/web/server/csrf/ServerCsrfTokenRequestAttributeHandler.java
web/src/main/java/org/springframework/security/web/server/csrf/ServerCsrfTokenRequestHandler.java
web/src/main/java/org/springframework/security/web/server/csrf/ServerCsrfTokenRequestHandlerLoggerHolder.java
web/src/main/java/org/springframework/security/web/server/csrf/XorServerCsrfTokenRequestAttributeHandler.java

This PR adds trace-level logging to CSRF token handlers to improve debugging capabilities.
- Add logging to show token source (header or parameter) in `resolveCsrfTokenValue`
- Add logging to show request attribute names used in `handle` methods
- Add logging in `XorCsrfTokenRequestAttributeHandler` when token processing fails (as specifically requested in the issue)
- Apply similar logging improvements to `XorServerCsrfTokenRequestAttributeHandler` for consistency
Fixes #13626

Add logging to CsrfTokenRequestHandler implementations

---

docs/modules/ROOT/pages/servlet/saml2/login/authentication-requests.adoc
docs/modules/ROOT/pages/servlet/saml2/login/overview.adoc

As suggested in issue #12810, this PR updates the documentation to reflect the correct usage of the `assertingparty` Spring Boot auto-configuration property instead of `identityprovider`.
I also believe that the same documentation examples are missing the `registration` property; I added them in a separate commit (but I would gladly either squash the two commits, or create a separate PR entirely).

Update the docs to use assertingparty instead of identityprovider to close #12810

---

crypto/src/main/java/org/springframework/security/crypto/keygen/Base64StringKeyGenerator.java
crypto/src/test/java/org/springframework/security/crypto/keygen/Base64StringKeyGeneratorTests.java

The main purpose of this change is to essentially remove the strict 32 byte key length limit to allow developers to generate shorter Base64 strings if needed. Now, when trying to pass `keyLength < DEFAULT_KEY_LENGTH (32)` into the constructor, an exception is thrown, which is not always justified for less critical token generation tasks.
I believe that we don't need such a strict condition and we can soften the condition and just check that the key length is not less than or equal to 0.
Fix: #17012

Remove 32-byte minimum keyLength restriction in `Base64StringKeyGenerator`

---

core/src/main/java/org/springframework/security/authorization/method/NullReturningMethodAuthorizationDeniedHandler.java
core/src/test/java/org/springframework/security/authorization/method/NullReturningMethodAuthorizationDeniedHandlerTests.java

This implementation of MethodAuthorizationDeniedHandler returns null when authorization is denied.
Issue: #16705

Add NullReturningMethodAuthorizationDeniedHandler

---

core/src/main/java/org/springframework/security/provisioning/JdbcUserDetailsManager.java
core/src/test/java/org/springframework/security/provisioning/JdbcUserDetailsManagerTests.java

**Summary:**
Implements `UserDetailsPasswordService` in `JdbcUserDetailsManager` to allow password updates, controlled by a new flag.
**Changes:**
* Added `updatePassword(UserDetails user, String newPassword)` method.
* Introduced `enableUpdatePassword` boolean property (default: false) and setter `setEnableUpdatePassword(boolean)`.
* `updatePassword` method logic updated:
* If `enableUpdatePassword` is true, it updates the user's password via updateUser.
* If `enableUpdatePassword` is false, it returns the original `UserDetails` without performing any update.
* Added tests in `JdbcUserDetailsManagerTests` to verify both scenarios (`updatePasswordWhenDisabledReturnOriginalUser` and `updatePasswordWhenEnabledShouldUpdatePassword`).
Closes gh-16863

Implement UserDetailsPasswordService in JdbcUserDetailsManager

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/servlet/saml2/saml-extension-migration.adoc

This PR adds a dedicated migration guide for users transitioning from the Spring Security SAML Extension to Spring Security’s built-in SAML 2.0 support.
- Migration guide content ported from the project Wiki
- xref links to `saml2Login`, `saml2Logout`, and `saml2Metadata` reference pages
- Metadata sample added to the “Examples Matrix” section
- Navigation updated to include the new guide with clearer naming
- Other documentation refinements based on reviewer feedback
Fixes: gh-11161  
Supersedes: #17026

Add SAML 2.0 migration guide from Spring Security SAML Extension

---

docs/modules/ROOT/pages/servlet/authentication/session-management.adoc

This commit adds a documentation note explaining the importance of overriding equals() and hashCode() in custom UserDetails implementations.
The default SessionRegistryImpl in Spring Security uses an in-memory ConcurrentMap<Object, Set<String>>, Map<String,SessionInformation> to associate principals with sessions. If a custom UserDetails class does not properly override equals() and hashCode(), user sessions may not be tracked or matched correctly.
I believe this helps developers avoid subtle session management issues when implementing custom authentication logic.
Reference: org.springframework.security.core.session.SessionRegistryImpl

Advise overriding equals() and hashCode() in UserDetails implementations

---

config/src/main/java/org/springframework/security/config/web/server/OidcBackChannelLogoutWebFilter.java
config/src/main/java/org/springframework/security/config/web/server/OidcBackChannelServerLogoutHandler.java

A couple of classes in the webflux module used the `jakarta.servlet` module class to specify statuses, which in a way makes us dependent on them and that is wrong. In my fix I used `org.springframework.http.HttpStatus`
Fixes: #17125

Use HttpStatus in back-channel logout filters

---

web/src/main/java/org/springframework/security/web/jackson2/SwitchUserGrantedAuthorityMixIn.java
web/src/main/java/org/springframework/security/web/jackson2/WebJackson2Module.java
web/src/test/java/org/springframework/security/web/jackson2/SwitchUserGrantedAuthorityMixInTests.java

This PR moves the SwitchUserGrantedAuthorityMixIn annotations  into WebJackson2Module instead of WebServlet Jackson2Module to fix the deserialization problem of SwitchUserGrantedAuthority in Webflux.
Fixes https://github.com/spring-projects/spring-security/issues/17041

Fix the problem of not deserializing SwitchUserGrantedAuthority in Webflux

---

config/src/main/java/org/springframework/security/config/annotation/method/configuration/AuthorizationProxyWebConfiguration.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/AuthorizationProxyConfigurationTests.java
core/src/main/java/org/springframework/security/aot/hint/AuthorizeReturnObjectHintsRegistrar.java
core/src/main/java/org/springframework/security/authorization/AuthorizationProxyFactory.java
core/src/main/java/org/springframework/security/authorization/method/AuthorizationAdvisorProxyFactory.java
core/src/test/java/org/springframework/security/authorization/AuthorizationAdvisorProxyFactoryTests.java

Overview
---
This pull request updates the AuthorizationProxyFactory interface to make its proxy method generic, ensuring that it returns the same type as the input object. 
The following changes are included:
- Refactored AuthorizationProxyFactory.proxy to use generics (<T> T proxy(T object)).
- Removed redundant casts from production and test code that are no longer necessary due to the type-safe proxy method.
<br>
Related
---
ISSUE: #16706 
<br>
Note
---
I’m aware that the issue is currently labeled with status: waiting-for-triage, which indicates that the final design direction may not be settled yet. This PR reflects my current understanding of the issue and is intended as a starting point for further discussion.
If this approach does not align with the intended direction, please …

Make AuthorizationProxyFactory.proxy generic 

---

config/src/main/java/org/springframework/security/config/annotation/method/configuration/AuthorizationProxyWebConfiguration.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfigurationTests.java

Exceptions for Authorized Objects should propagate when returned from a Controller

---

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtTimestampValidator.java
oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/JwtTimestampValidatorTests.java

I implemented ```required``` parameter in ```JwtTimestampValidator```, ```JwtIssuerValidator``` and ```JwtAudienceValidator```. I left the function of the original constructors untouched. In the original implementation successful validation was returned even if timestamps, issues or audience claims were missing. So this way previous API, implementations are not breaking. With my changes it is possible now to specify more strict specification, to tell if the given claim is mandatory to present and indiate it with failed validation if the claim is missing.
This is the feature indicated in #17004

JwtTimestampsValidator can require exp and nbf claims

---

oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/endpoint/OAuth2AuthorizationRequest.java
oauth2/oauth2-core/src/test/java/org/springframework/security/oauth2/core/endpoint/OAuth2AuthorizationRequestTests.java
oauth2/oauth2-core/src/test/java/org/springframework/security/oauth2/core/endpoint/TestOAuth2AuthorizationRequests.java

Add Equals and HashCode methods for better comparison.

---

config/src/main/java/org/springframework/security/config/annotation/method/configuration/AuthorizationProxyDataConfiguration.java
config/src/test/java/org/springframework/security/config/annotation/method/configuration/PrePostMethodSecurityConfigurationTests.java

Support Spring Data container types for AuthorizeReturnObject

---

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java
oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderTests.java

We want to increase the cache-ttl of the NimbusJwtDecoder respectively the underlying JWKSource. Furthermore we want to use the refresh-ahead caching of JWKSource.
The com.nimbusds.jose.jwk.source.JWKSourceBuilder provides a lot of features to customize how jwks are cached / update etc. but currently there is no way to customize it.
The implemented possiiblity to customiz the used JWKSourceBuilder in NimbusJwtDecoder allows to use all features from JWKSourceBuilder.

Add possibility to customize JwkSource of NimbusJwtDecoder

---

docs/modules/ROOT/pages/migration/servlet/oauth2.adoc
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/Saml2AuthenticationTokenConverter.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/Saml2AuthenticationTokenConverterTests.java

I think we can define `Boolean shouldInflate` and method `decode` will be added
```java
if (this.shouldInflate == null) {
this.shouldInflate = HttpMethod.GET.matches(request.getMethod());
}
```
If not, this will break `Saml2LoginBeanDefinitionParserTests` and `Saml2AuthenticationTokenConverterTests`
```text
Saml2LoginBeanDefinitionParserTests > authenticateWhenCustomAuthnRequestRepositoryThenUses() FAILED
org.mockito.exceptions.verification.WantedButNotInvoked at Saml2LoginBeanDefinitionParserTests.java:323
Saml2LoginBeanDefinitionParserTests > authenticateWhenAuthenticationResponseValidThenAuthenticate() FAILED
java.lang.AssertionError at Saml2LoginBeanDefinitionParserTests.java:213
Saml2LoginBeanDefinitionParserTests > authenticateWhenAuthenticationResponseValidThenAuthenticationSuccessE …
```

Remove GET request support from Saml2AuthenticationTokenConverter

---

config/src/test/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LogoutConfigurerTests.java
config/src/test/java/org/springframework/security/config/http/Saml2LogoutBeanDefinitionParserTests.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/core/Saml2ErrorCodes.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/BaseOpenSamlLogoutResponseResolver.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/Saml2LogoutRequestFilter.java
saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/Saml2LogoutResponseResolver.java
saml2/saml2-service-provider/src/opensaml4Main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSaml4LogoutResponseResolver.java
saml2/saml2-service-provider/src/opensaml4Test/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSaml4LogoutResponseResolverTests.java
saml2/saml2-service-provider/src/opensaml5Main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSaml5LogoutResponseResolver.java
saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/authentication/logout/Saml2LogoutRequestFilterTests.java

solves https://github.com/spring-projects/spring-security/issues/14635

Send saml logout response even when validation errors happen

---

docs/modules/ROOT/pages/servlet/appendix/database-schema.adoc

docs: match the database schema with https://github.com/spring-projects/spring-security/blob/6.5.0/docs/modules/ROOT/pages/servlet/authentication/passwords/jdbc.adoc

Fix users schema documentation

---

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationProvider.java
oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationProviderTests.java

Add `Assert.notNull` validation in `JwtAuthenticationProvider.authenticate()` to ensure the authentication token returned by `jwtAuthenticationConverter` is not null.
While the `JwtAuthenticationConverter.convert()` method typically returns a valid `AbstractAuthenticationToken`, there's no explicit null check before accessing the token's properties. This could potentially lead to a `NullPointerException`  if:
- Custom converter implementations return null
- Unexpected edge cases occur during token conversion
- External factors affect the conversion process
- Added `Assert.notNull(token, "token cannot be null")` validation
- Added comprehensive test to verify the null check behavior
- New test passes and verifies proper exception handling
- All existing tests continue to pass
- No breaking …

Add null check for authentication token in JwtAuthenticationProvider

---

config/src/main/java/org/springframework/security/config/websocket/WebSocketMessageBrokerSecurityBeanDefinitionParser.java

This PR refactors the class matching logic for CSRF token handshake interceptor registration in `MessageSecurityPostProcessor`.
- Replaces multiple `else-if` conditions checking `beanClassName` with a single `Set<String>` lookup
- Introduces `CSRF_HANDSHAKE_HANDLER_CLASSES` as a static, final, and immutable constant using `Collections.unmodifiableSet(...)`
- Preserves existing behavior while improving readability and maintainability
- Keeps import statements explicit (avoids wildcard imports)
- Removes duplicate string checks
- Prevents potential copy-paste errors
- Makes it easier to extend or maintain the list of supported handshake handler classes
Let me know if further refinement or test adjustments are needed.

Simplify Websocket Csrf Processor XML Configuration

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2LoginConfigurer.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2LoginConfigurerTests.java

fix 6.4 -> 6.5 class cast issue / relax type constraint

OAuth2Login DSL should support post-processing AuthenticationProvider implementations

---

buildSrc/build.gradle
buildSrc/src/main/groovy/security-kotlin.gradle
config/spring-security-config.gradle
config/src/test/kotlin/org/springframework/security/config/web/server/ServerX509DslTests.kt
core/spring-security-core.gradle
docs/spring-security-docs.gradle
docs/src/test/kotlin/org/springframework/security/kt/docs/features/integrations/rest/configurationwebclient/ServerWebClientHttpInterfaceIntegrationConfiguration.kt
docs/src/test/kotlin/org/springframework/security/kt/docs/reactive/authentication/reactivex509/X509ConfigurationTests.kt
gradle/libs.versions.toml

Update to Kotlin 2.2

---

web/src/main/java/org/springframework/security/web/csrf/CsrfFilter.java

Update toString() method in DefaultRequiresCsrfMatcher to better reflect its logic during trace-level logging. 
The current log message was ambiguous:
"Did not protect against CSRF since request did not match CsrfNotRequired [TRACE, HEAD, GET, OPTIONS]"
Now it clearly shows:
"Did not protect against CSRF since request did not match IsNotHttpMethod [TRACE, HEAD, GET, OPTIONS]"
Closes gh-17250

Improve logging clarity in CsrfFilter

---

config/src/main/java/org/springframework/security/config/authentication/AbstractUserDetailsServiceBeanDefinitionParser.java
config/src/main/java/org/springframework/security/config/authentication/AuthenticationProviderBeanDefinitionParser.java
config/src/test/java/org/springframework/security/config/annotation/authentication/AuthenticationManagerBuilderTests.java
config/src/test/java/org/springframework/security/config/annotation/authentication/NamespaceAuthenticationProviderTests.java
config/src/test/java/org/springframework/security/config/annotation/authentication/configuration/AuthenticationConfigurationTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/RememberMeConfigurerTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configurers/ServletApiConfigurerTests.java
config/src/test/resources/org/springframework/security/config/http/MiscHttpConfigTests-Sec750.xml
core/src/main/java/org/springframework/security/authentication/dao/DaoAuthenticationProvider.java
core/src/test/java/org/springframework/security/authentication/dao/DaoAuthenticationProviderTests.java
core/src/test/java/org/springframework/security/provisioning/InMemoryUserDetailsManagerTests.java
docs/modules/ROOT/pages/servlet/authentication/passwords/index.adoc
itest/context/src/integration-test/resources/filter-chain-performance-app-context.xml

Remove deprecated elements from DaoAuthenticationProvider

---

config/src/main/java/org/springframework/security/config/annotation/AbstractConfiguredSecurityBuilder.java
config/src/test/java/org/springframework/security/config/annotation/web/AbstractConfiguredSecurityBuilderTests.java
config/src/test/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfigurationTests.java
config/src/test/java/org/springframework/security/config/http/customconfigurer/CustomHttpSecurityConfigurerTests.java

Remove AbstractConfiguredSecurityBuilder apply method

---

config/src/main/java/org/springframework/security/config/annotation/AbstractConfiguredSecurityBuilder.java
config/src/test/java/org/springframework/security/config/annotation/web/AbstractConfiguredSecurityBuilderTests.java

Support add nested security configurers during builder initialization

---

web/src/main/java/org/springframework/security/web/servlet/util/matcher/PathPatternRequestMatcher.java

Closes [gh-17584](https://github.com/spring-projects/spring-security/issues/17584)

Use final values in equals and hashCode

---

config/src/main/java/org/springframework/security/config/annotation/method/configuration/DeferringMethodInterceptor.java
config/src/main/java/org/springframework/security/config/annotation/method/configuration/MethodSecurityAdvisorRegistrar.java
config/src/main/java/org/springframework/security/config/web/PathPatternRequestMatcherBuilderFactoryBean.java
config/src/main/java/org/springframework/security/config/web/server/OAuth2ErrorEncoder.java
config/src/test/java/org/springframework/security/config/annotation/web/reactive/WebFluxSecurityConfigurationTests.java
config/src/test/java/org/springframework/security/config/http/MiscHttpConfigTests.java
config/src/test/java/org/springframework/security/config/method/MethodSecurityBeanDefinitionParserTests.java
core/src/test/java/org/springframework/security/authorization/AuthorizationAdvisorProxyFactoryTests.java
core/src/test/java/org/springframework/security/authorization/ReactiveAuthorizationAdvisorProxyFactoryTests.java
etc/checkstyle/checkstyle.xml
saml2/saml2-service-provider/src/opensaml4Test/java/org/springframework/security/saml2/provider/service/authentication/TestCustomOpenSaml4Objects.java
saml2/saml2-service-provider/src/opensaml5Main/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml5AuthenticationProvider.java
saml2/saml2-service-provider/src/opensaml5Test/java/org/springframework/security/saml2/provider/service/authentication/TestCustomOpenSaml5Objects.java

Correct `@NonNull` and `@Nullable` package name

---

web/src/main/java/org/springframework/security/web/util/matcher/IpAddressMatcher.java
web/src/test/java/org/springframework/security/web/util/matcher/IpAddressMatcherTests.java

I think we won't lose anything if we make the regex in the matcher class more strict.
Closes: gh-17499

Make stricter IP format check in `IpAddressMatcher`

---

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OidcBackChannelLogoutHandler.java
config/src/main/java/org/springframework/security/config/http/FilterChainMapBeanDefinitionDecorator.java
config/src/main/java/org/springframework/security/config/http/HttpSecurityBeanDefinitionParser.java
config/src/main/java/org/springframework/security/config/websocket/WebSocketMessageBrokerSecurityBeanDefinitionParser.java
config/src/test/java/org/springframework/security/SpringSecurityCoreVersionSerializableTests.java
config/src/test/java/org/springframework/security/config/http/HttpHeadersConfigTests.java

This PR includes
- Add diamond operator

Apply missing diamond operators

---

core/src/main/java/org/springframework/security/core/annotation/ExpressionTemplateSecurityAnnotationScanner.java
core/src/main/java/org/springframework/security/core/annotation/ExpressionTemplateValueProvider.java
core/src/test/java/org/springframework/security/core/annotation/ExpressionTemplateSecurityAnnotationScannerTests.java

Implements a simple mechanism for providing custom expression template values from enums used in expression templates.
Closes gh-17447

Add ExpressionTemplateValueProvider

---

config/src/test/java/org/springframework/security/config/SecurityNamespaceHandlerTests.java

Removes "shameless class coverage stats boosting" code that created
meaningless anonymous class instances just to increase coverage metrics.
Replaces with proper tests that validate BeanIds and Elements constants
are accessible and not empty.
**Changes:**
- Removed shameless coverage comment and anonymous class instantiations
- Added meaningful constant validation tests
- Improved test quality while maintaining coverage

Replace "shameless coverage code" in SecurityNamespaceHandlerTests with meaningful tests

---

core/src/main/java/org/springframework/security/authentication/AuthenticationTrustResolver.java
core/src/main/java/org/springframework/security/authentication/AuthenticationTrustResolverImpl.java

Since `AuthenticationTrustResolver` can handle null arguments (this is also stated in the implementation of this interface), we should mark these arguments as `@Nullable`.
Closes: gh-17764

Annotate AuthenticationTrustResolver methods with `@Nullable`

---

web/src/main/java/org/springframework/security/web/authentication/UsernamePasswordAuthenticationFilter.java

Rename DEFAULT_ANT_PATH_REQUEST_MATCHER to DEFAULT_PATH_REQUEST_MATCHER to reflect PathPatternRequestMatcher usage instead of legacy Ant pattern terminology.
This PR improves code clarity by fixing a misleading variable name in `UsernamePasswordAuthenticationFilter` and removing outdated terminology.
The current variable `DEFAULT_ANT_PATH_REQUEST_MATCHER` incorrectly suggests that Ant pattern matching is being used, when the actual implementation uses `PathPatternRequestMatcher`. This naming inconsistency can confuse developers reading the code.
Rename the variable to `DEFAULT_PATH_REQUEST_MATCHER` to:
- Accurately reflect the `PathPatternRequestMatcher` implementation
- Remove misleading references to legacy Ant pattern terminology
- Improve code readability and maintainability
- Rename …

Fix misleading variable name in authentication filter

---

web/src/main/java/org/springframework/security/web/ObservationFilterChainDecorator.java
web/src/test/java/org/springframework/security/web/FilterChainProxyTests.java

Fixes https://github.com/spring-projects/spring-security/issues/12610
---
As I see from my research, the bug happens only in the real servlet environment, supposedly because of HttpServletResponse.sendError(), I didn't manage to reproduce it via mockMvc.
Tomcat creates a new HttpServletRequest in case error, which is related to "/error" path, which will be served by ErrorController.
Fortunately, request attributes are copied from the original request to the "/error"-related one, so we can put the ObservationView into the original request in order to extract this ObservationView from "/error"-related request and create a new parent observation with a given parent ObservationView. The last ObservationView propagates TraceContext to the new Observation so we have the same traceId.
--- …

Fix traceId discrepancy in case error in servlet web

---

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java
oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderTests.java

Add `discoverJwsAlgorithms()` in `NimbusJwtDecoder`

---

config/src/integration-test/java/org/springframework/security/config/annotation/rsocket/AnonymousAuthenticationITests.java
config/src/main/java/org/springframework/security/config/annotation/rsocket/RSocketSecurity.java

Adding anonymous interceptor hardcoded to `RSocketSecurity#payloadInterceptors` and is added anyway. I think you should add an option to disable adding anonymous interceptor.
I think the most logical way is to add a flag, as in our case I did. I also added a method `disableAnonymous` which sets the field to true and we no longer add the anonymous interceptor.
Fixes: #17132

Add option to disable anonymous authentication in `RSocketSecurity`

---

web/src/main/java/org/springframework/security/web/servlet/util/matcher/PathPatternRequestMatcher.java
web/src/test/java/org/springframework/security/web/servlet/util/matcher/PathPatternRequestMatcherTests.java

Fix double-slash when basePath is root
