web/src/main/java/org/springframework/security/web/access/DelegatingAccessDeniedHandler.java
Modify typo in variable name of `DelegatingAccessDeniedHandler`.
Please review this PR.
I have signed and agree to the terms of the Spring Individual Contributor License Agreement.
https://jira.spring.io/browse/SEC-2840
=> SEC-2840: Modify typo in DelegatingAccessDeniedHandler

core/src/main/java/org/springframework/security/authentication/AnonymousAuthenticationProvider.java, core/src/main/java/org/springframework/security/authentication/TestingAuthenticationToken.java
=> Unused import

samples/ldap-xml/src/main/webapp/WEB-INF/classes/users.ldif
Format of the dn was incorrect. Looks like a bad copy/paste.
=> Fixed incorrect dn.

web/src/main/java/org/springframework/security/web/csrf/CsrfFilter.java
I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement
=> SEC-3164 Optimization in DefaultRequiresCsrfMatcher

web/src/main/java/org/springframework/security/web/context/support/SecurityWebApplicationContextUtils.java
I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.
=> SEC-3158 findRequiredWebApplicationContext() compatibility with spring framework 4.1

docs/manual/src/docs/asciidoc/_includes/test.adoc
target class is org.springframework.security.test.context.support.WithSecurityContextTestExecutionListener
=> fix typo in doc

config/src/main/resources/org/springframework/security/config/spring-security-3.1.rnc, config/src/main/resources/org/springframework/security/config/spring-security-3.1.xsd, config/src/main/resources/org/springframework/security/config/spring-security-3.2.rnc, config/src/main/resources/org/springframework/security/config/spring-security-3.2.xsd, config/src/main/resources/org/springframework/security/config/spring-security-4.0.rnc, config/src/main/resources/org/springframework/security/config/spring-security-4.0.xsd, config/src/main/resources/org/springframework/security/config/spring-security-4.1.rnc, config/src/main/resources/org/springframework/security/config/spring-security-4.1.xsd
…xsd, spring-security-4.0.xsd
Fixes #3229
[x] I have signed the CLA
=> Fix typo in xsd

config/src/main/java/org/springframework/security/config/annotation/web/builders/FilterComparator.java, config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java, config/src/test/groovy/org/springframework/security/config/annotation/web/configurers/NamespaceHttpCustomFilterTests.groovy
=> Add HttpSecurity.addFilterAt

config/src/test/groovy/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfigurationTests.groovy
=> Add SpEL Bean reference test

crypto/src/test/java/org/springframework/security/crypto/encrypt/BouncyCastleAesBytesEncryptorEquivalencyTest.java
Tests would fail in cases where JCE unlimited strength was available but
GCM wasn't, like on JDK7.
=> Skip tests when AesBytesEncryptor can't be created in CBC or GCM mode.

docs/manual/src/docs/asciidoc/index.adoc
Correction to xml configuration for AuthenticationPrincipalArgumentResolver in reference doc.
Fixes gh-3771
=> Correction to xml configuration for AuthenticationPrincipalArgumentResolver

config/src/main/java/org/springframework/security/config/annotation/web/configurers/SessionManagementConfigurer.java, config/src/test/groovy/org/springframework/security/config/annotation/web/configurers/NamespaceSessionManagementTests.groovy
Allow configuring the InvalidSessionStrategy in Java Configuration.
Fixes gh-3371
=> Add Java Configuration InvalidSessionStrategy

docs/manual/src/docs/asciidoc/index.adoc
=> Add What's new in 4.1 RC2

web/src/main/java/org/springframework/security/web/csrf/CookieCsrfTokenRepository.java, web/src/test/java/org/springframework/security/web/csrf/CookieCsrfTokenRepositoryServlet3Tests.java, web/src/test/java/org/springframework/security/web/csrf/CookieCsrfTokenRepositoryTests.java
=> CookieCsrfTokenRepository supports HttpOnly

web/src/main/java/org/springframework/security/web/util/OnCommittedResponseWrapper.java
possible fix for #3842 
I have not signed the CLA yet, if it is necessary for this small fix please let me know.
=> Improve GC for OnCommittedResponseWrapper

docs/manual/src/docs/asciidoc/index.adoc
Replace remaining authorizeUrls with authorizeRequests
Fixes gh-3875
=> authorizeUrls -> authorizeRequests

config/src/main/java/org/springframework/security/config/annotation/web/configurers/HttpBasicConfigurer.java, config/src/test/groovy/org/springframework/security/config/annotation/web/configurers/ExceptionHandlingConfigurerTests.groovy, config/src/test/groovy/org/springframework/security/config/annotation/web/configurers/LogoutConfigurerTests.groovy
=> Logout is 204 for XMLHttpRequest

web/src/main/java/org/springframework/security/web/servlet/util/matcher/MvcRequestMatcher.java
Remove unused method MvcReqestMatcher.getMvcPattern
=> Remove unused MvcReqestMatcher.getMvcPattern

docs/manual/src/docs/asciidoc/_includes/test.adoc
@SpringExecutionListeners -> @SpringTestExecutionListeners
=> Fix Reference (test.adoc) Typo

docs/manual/src/docs/asciidoc/index.adoc
removed outdated description and linked directly to java configuration sample applications
=> Linked to java configuration sample applications

docs/manual/src/docs/asciidoc/index.adoc
I've polished "What's new in Spring Security 4.2" on reference docs.
Please review.
=> Polishing doc

docs/manual/src/docs/asciidoc/index.adoc
Fix some typo in documentation.
=> Update index.adoc - Typos

web/src/main/java/org/springframework/security/web/header/writers/ReferrerPolicyHeaderWriter.java
I've polished some cords at the `ReferrerPolicyHeaderWriter`.
Please review.
gh-4110
=> Polishing the ReferrerPolicyHeaderWriter

acl/src/test/java/org/springframework/security/acls/domain/AclAuthorizationStrategyImplTests.java
This PR simply removes dead code in `AclAuthorizationStrategyImplTests`.
=> Remove dead code in AclAuthorizationStrategyImplTests

docs/manual/src/docs/asciidoc/_includes/test.adoc, docs/manual/src/docs/asciidoc/_includes/websocket.adoc, docs/manual/src/docs/asciidoc/index.adoc
Fix typo errors in various `*.adoc` files.
=> Fix doc typo

web/src/main/java/org/springframework/security/web/savedrequest/HttpSessionRequestCache.java
I've polished JavaDoc comment.
Issue: gh-4130
=> Add since version in javadoc

gradle/boot-sample.gradle
=> Fix warning from spring-boot plugin

README.adoc
Fixes gh-4154.
Please, see GitHub issue #4154 for the motivation.
=> Update required JDK version to JDK8

.travis.yml, core/spring-security-core.gradle
=> Build Leverages tests-configuration plugin

config/src/main/java/org/springframework/security/config/annotation/web/configurers/HeadersConfigurer.java
=> Fix JavaDoc for HeadersConfigurer

webflux/src/main/java/org/springframework/security/web/server/authorization/DelegatingReactiveAuthorizationManager.java, webflux/src/main/java/org/springframework/security/web/server/util/matcher/AndServerWebExchangeMatcher.java, webflux/src/main/java/org/springframework/security/web/server/util/matcher/OrServerWebExchangeMatcher.java, webflux/src/main/java/org/springframework/security/web/server/util/matcher/PathMatcherServerWebExchangeMatcher.java, webflux/src/main/java/org/springframework/security/web/server/util/matcher/ServerWebExchangeMatcher.java, webflux/src/main/java/org/springframework/security/web/server/util/matcher/ServerWebExchangeMatchers.java, webflux/src/test/java/org/springframework/security/web/server/authorization/DelegatingReactiveAuthorizationManagerTests.java, webflux/src/test/java/org/springframework/security/web/server/util/matcher/AndServerWebExchangeMatcherTests.java, webflux/src/test/java/org/springframework/security/web/server/util/matcher/OrServerWebExchangeMatcherTests.java, webflux/src/test/java/org/springframework/security/web/server/util/matcher/PathMatcherServerWebExchangeMatcherTests.java, webflux/src/test/java/org/springframework/security/web/server/util/matcher/ServerWebExchangeMatchersTests.java
=> ServerWebExchangeMatcher returns Mono<MatchResult>

config/src/main/java/org/springframework/security/config/web/server/AuthorizeExchangeBuilder.java, webflux/src/main/java/org/springframework/security/web/server/authorization/DelegatingReactiveAuthorizationManager.java, webflux/src/main/java/org/springframework/security/web/server/util/matcher/ServerWebExchangeMatcherEntry.java, webflux/src/test/java/org/springframework/security/web/server/authorization/DelegatingReactiveAuthorizationManagerTests.java
=> Add ServerWebExchangeMatcherEntry

docs/manual/src/docs/asciidoc/index.adoc
To fix WARNING displayed in Travis CI job log:
> :docs:manual:asciidoctorasciidoctor: WARNING: index.adoc: line 988: no callouts refer to list item 1
=> [Doc] add missing callout

README.adoc
=> Update Minimum Versions

core/src/main/java/org/springframework/security/core/SpringSecurityMessageSource.java
=> Small typo in Javadoc

core/src/main/java/org/springframework/security/provisioning/InMemoryUserDetailsManager.java
=> Add InMemoryUserDetailsManager(UserDetails... users)

config/src/test/java/org/springframework/security/config/annotation/web/reactive/EnableWebFluxSecurityTests.java
=> Fix EnableWebFluxSecurityTests

docs/manual/src/docs/asciidoc/index.adoc
Update to remove extra Ldap Authentication Section Header
=> Update to remove extra Header

web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationEntryPoint.java
```
s/ExceptionTraslationFilter/ExceptionTranslationFilter
```
=> fix JavaDoc typo on `BasicAuthenticationEntryPoint`

crypto/src/main/java/org/springframework/security/crypto/password/Pbkdf2PasswordEncoder.java
=> Polishing the Pbkdf2PasswordEncoder's javadoc

core/src/main/java/org/springframework/security/jackson2/UsernamePasswordAuthenticationTokenDeserializer.java, core/src/test/java/org/springframework/security/jackson2/UsernamePasswordAuthenticationTokenMixinTests.java
=> Fix UsernamePasswordAuthenticationTokenMixin to handle null credentials/details

acl/src/test/java/org/springframework/security/acls/afterinvocation/AclEntryAfterInvocationCollectionFilteringProviderTests.java, acl/src/test/java/org/springframework/security/acls/afterinvocation/AclEntryAfterInvocationProviderTests.java, core/src/main/java/org/springframework/security/provisioning/JdbcUserDetailsManager.java, core/src/test/java/org/springframework/security/access/hierarchicalroles/RoleHierarchyImplTests.java, core/src/test/java/org/springframework/security/access/method/DelegatingMethodSecurityMetadataSourceTests.java, etc/checkstyle/checkstyle.xml, messaging/src/test/java/org/springframework/security/messaging/access/intercept/ChannelSecurityInterceptorTests.java, web/src/test/java/org/springframework/security/web/FilterChainProxyTests.java, web/src/test/java/org/springframework/security/web/servletapi/SecurityContextHolderAwareRequestFilterTests.java
This PR adds Checkstyle `EmptyStatementCheck` module and aligns code with it.
=> Apply Checkstyle EmptyStatementCheck module

config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java
Hi, there is a typo in java doc.
Please, review it.
Thanks
=> Typo in java doc

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2LoginConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/SecurityConfigurerAdapterTests.java, config/src/test/java/org/springframework/security/config/method/Contact.java, core/src/test/java/org/springframework/security/core/context/SecurityContextImplTests.java, samples/javaconfig/webflux-form/src/main/java/sample/ThymeleafConfig.java, samples/xml/dms/src/main/java/sample/dms/Directory.java, web/src/main/java/org/springframework/security/web/access/expression/DelegatingEvaluationContext.java, web/src/main/java/org/springframework/security/web/csrf/LazyCsrfTokenRepository.java, web/src/main/java/org/springframework/security/web/header/writers/HpkpHeaderWriter.java, web/src/main/java/org/springframework/security/web/header/writers/HstsHeaderWriter.java, web/src/main/java/org/springframework/security/web/server/header/HttpHeaderWriterWebFilter.java, web/src/test/java/org/springframework/security/web/PortResolverImplTests.java
This PR removes explicit `super()` calls.
=> Remove explicit super() calls

samples/javaconfig/webflux-form/spring-security-samples-javaconfig-webflux-form.gradle
Just a small polish, noticed while looking at #4939
=> Remove duplicate dependency

config/src/main/java/org/springframework/security/config/annotation/web/reactive/EnableWebFluxSecurity.java, config/src/test/java/org/springframework/security/config/annotation/web/reactive/EnableWebFluxSecurityTests.java, config/src/test/java/org/springframework/security/config/annotation/web/reactive/ServerHttpSecurityConfigurationBuilder.java, config/src/test/java/org/springframework/security/config/users/ReactiveAuthenticationTestConfiguration.java, core/src/main/java/org/springframework/security/authentication/UserDetailsRepositoryReactiveAuthenticationManager.java, core/src/test/java/org/springframework/security/authentication/ReactiveUserDetailsServiceAuthenticationManagerTests.java, docs/manual/src/docs/asciidoc/index.adoc, samples/javaconfig/hellowebflux-method/src/main/java/sample/SecurityConfig.java, samples/javaconfig/hellowebflux/src/main/java/sample/HelloWebfluxSecurityConfig.java, samples/javaconfig/hellowebfluxfn/src/main/java/sample/HelloWebfluxFnSecurityConfig.java, samples/javaconfig/webflux-form/src/main/java/sample/WebfluxFormSecurityConfig.java
This PR renames `userDetailsRepository` to `userDetailsService` to align with its type.
=> Rename userDetailsRepository to userDetailsService

gradle/dependency-management.gradle
=> Upgrade Nimbus JOSE + JWT to 5.5

core/src/test/java/org/springframework/security/authentication/dao/DaoAuthenticationProviderTests.java
This PR polishes `DaoAuthenticationProviderTests`, mainly trying to align class names with its interface name.
=> Polish DaoAuthenticationProviderTests

gradle/dependency-management.gradle, gradle/wrapper/gradle-wrapper.properties
=> Update to Gradle 4.6

core/src/main/java/org/springframework/security/jackson2/BadCredentialsExceptionMixin.java, core/src/main/java/org/springframework/security/jackson2/CoreJackson2Module.java, core/src/test/java/org/springframework/security/jackson2/BadCredentialsExceptionMixinTests.java
Changes related to issue https://github.com/spring-projects/spring-session/issues/1013 and  #4370 
It's my first pull request.
Don't hesitate to tell me if I miss something.
=> Add the BadCredentialsExceptionMixin

gradle.properties
=> Update to Spring Boot 2.0.0.RELEASE

core/src/main/java/org/springframework/security/access/hierarchicalroles/RoleHierarchyImpl.java, core/src/test/java/org/springframework/security/access/hierarchicalroles/RoleHierarchyImplTests.java
=> Support whitespace characters using RoleHierarchyImpl

config/src/main/java/org/springframework/security/config/oauth2/client/oidc/OidcConfigurationProvider.java
See  gh-5355
I've done a small polishing.
=> Polishing the OidcConfigurationProvider

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java
This exposes JwtConfigurer#decoder as well as makes the configurer
look in the application context for a bean of type JwtDecoder.
Fixes: gh-5519
=> User-Specified JwtDecoder

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java
This exposes #authenticationEntryPoint(), #accessDeniedHandler, on
the Resource Server DSL.
With these, a user can customize the error responses when a bearer
token request fails.
Fixes: gh-5497
=> Bearer Token Exception Handling Configuration

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderJwkSupport.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderJwkSupportTests.java
This commit captures and remaps the exception that Nimbus throws
when a PlainJWT is presented to it.
While the surrounding classes are likely only used today by the
oauth2Login flow, since they are public, we'll patch them at this
point for anyone who may be using them directly.
Fixes: gh-5457
=> Close Nimbus Information Leak

acl/src/test/java/org/springframework/security/acls/jdbc/EhCacheBasedAclCacheTests.java, cas/src/test/java/org/springframework/security/cas/authentication/CasAuthenticationProviderTests.java, config/src/test/java/org/springframework/security/config/FilterChainProxyConfigTests.java, core/src/test/java/org/springframework/security/access/intercept/RunAsManagerImplTests.java, core/src/test/java/org/springframework/security/authentication/jaas/SecurityContextLoginModuleTests.java, oauth2/oauth2-core/src/test/java/org/springframework/security/oauth2/core/ClaimAccessorTests.java, openid/src/test/java/org/springframework/security/openid/OpenIDAuthenticationProviderTests.java, taglibs/src/test/java/org/springframework/security/taglibs/authz/AuthenticationTagTests.java, web/src/test/java/org/springframework/security/web/authentication/SimpleUrlAuthenticationSuccessHandlerTests.java, web/src/test/java/org/springframework/security/web/authentication/preauth/AbstractPreAuthenticatedProcessingFilterTests.java
This PR replaces `isEqualTo(null)` with `isNull()`.
=> Replace isEqualTo(null) with isNull()

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationConverter.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationProvider.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtReactiveAuthenticationManager.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationConverterTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationProviderTests.java
Exposes ability to specify strategy for converting Jwt into an
Authentication, specifically in JwtAuthenticationProvider.
Fixes: gh-5629
=> Jwt -> Authentication Conversion

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/HeaderSpecTests.java, web/src/main/java/org/springframework/security/web/server/header/FeaturePolicyServerHttpHeadersWriter.java, web/src/test/java/org/springframework/security/web/server/header/FeaturePolicyServerHttpHeadersWriterTests.java
=> Add reactive support for Feature-Policy security header

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/DefaultClientCredentialsTokenResponseClient.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/OAuth2AuthorizationGrantRequestEntityUtils.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/OAuth2ClientCredentialsGrantRequestEntityConverter.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/DefaultClientCredentialsTokenResponseClientTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/OAuth2ClientCredentialsGrantRequestEntityConverterTests.java
=> Re-factor DefaultClientCredentialsTokenResponseClient

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2ResourceServerSpecTests.java
This makes the AuthenticationManager used by the OAuth2 Resource
Server configurable, focusing at this point on the Jwt use case.
Fixes: gh-5750
=> AuthenticationManager for OAuth2ResourceServerSpec

config/src/main/java/org/springframework/security/config/annotation/web/configurers/X509Configurer.java, config/src/test/groovy/org/springframework/security/config/annotation/web/configurers/NamespaceHttpX509Tests.groovy, config/src/test/groovy/org/springframework/security/config/annotation/web/configurers/X509ConfigurerTests.groovy
This PR fixes #5771(Allow PrincipalExtractor to be customized) issue.
=> Allow PrincipalExtractor to be customized

docs/manual/src/docs/asciidoc/_includes/test/method.adoc
=> Fix Code Format in Reference

core/src/main/java/org/springframework/security/access/annotation/Secured.java
=> Fix truncated javadoc for Secured

core/src/main/java/org/springframework/security/provisioning/JdbcUserDetailsManager.java
=> Remove unnecessary concatenation of sql in JdbcUserDetailsManager

web/src/main/java/org/springframework/security/web/header/HeaderWriterFilter.java, web/src/test/java/org/springframework/security/web/header/HeaderWriterFilterTests.java
HeaderWriterFilter wraps request dispatcher so it can write security
headers before the include occurs.
Fixes: gh-5499
=> Write Security Headers Before Servlet Include

config/src/main/java/org/springframework/security/config/annotation/web/configurers/RequestCacheConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/RequestCacheConfigurerTests.java
=> Register NullRequestCache When Disabled

ldap/src/main/java/org/springframework/security/ldap/userdetails/LdapUserDetailsMapper.java
Fix small typo in exception message
=> Fix typo in exception message

gradle/dependency-management.gradle
=> Update to nimbus-jose-jwt:6.3

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java
Fixes problems with documentation of AnonymousAuthentication
in ServerHttpSecurity
Fixes: gh-6327
=> Fixes Documentation Problem

docs/manual/src/docs/asciidoc/_includes/servlet/authorization/architecture.adoc
=> cconfigured -> configured

gradle/dependency-management.gradle
Update version of nimbus-jose-jwt from 6.5.1 to 6.7.
Fixes: gh-6459
=> Update to nimbus-jose-jwt:6.7

docs/manual/src/docs/asciidoc/_includes/servlet/architecture/overview.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/architecture/xml.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/hello/boot.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/hello/index.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/hello/java-configuration.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/hello/xml-configuration.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/index.adoc
Editing pass plus merge
Rob made new content in the about directory. I edited that content. Then Rob made minor tweaks in two of those files. I merged those tweaks and edited one of them ("samples applications" needed to be "sample applications"). Now we're caught up.
=> Gh 2567 rewrite docs

samples/boot/webflux-form/spring-security-samples-boot-webflux-form.gradle, samples/javaconfig/form/spring-security-samples-javaconfig-form.gradle, samples/javaconfig/helloworld/spring-security-samples-javaconfig-helloworld.gradle, samples/javaconfig/jdbc/spring-security-samples-javaconfig-jdbc.gradle, samples/javaconfig/ldap/spring-security-samples-javaconfig-ldap.gradle, samples/xml/contacts/spring-security-samples-xml-contacts.gradle, samples/xml/helloworld/spring-security-samples-xml-helloworld.gradle, samples/xml/insecure/spring-security-samples-xml-insecure.gradle, samples/xml/jaas/spring-security-samples-xml-jaas.gradle, samples/xml/ldap/spring-security-samples-xml-ldap.gradle
We have performed some polish on your URLs. We do not follow redirects to avoid expanding intentionally shorter URLs (i.e. URL shortened URLs)
These URLs were fixed successfully.
| HTTP URL | Result URL | HTTPS Result | HTTP Result | Count |
| --- | --- | --- | --- | --- |
| http://www.apache.org/licenses/LICENSE-2.0 | https://www.apache.org/licenses/LICENSE-2.0 | HttpResponse(httpStatus = 200 OK) | null | 10 |
=> Polish URLs

docs/manual/src/docs/asciidoc/_includes/servlet/web/websocket.adoc
=> Fix a typo

web/src/main/java/org/springframework/security/web/firewall/FirewalledResponse.java
#6731 Improves the performance of checking headers for new lines.
=> Issue #6731 improve performance of checking headers

gradle/wrapper/gradle-wrapper.properties
Updated Gradle version to 5.3.1. 
Fixes gh-6745.
=> Update Gradle version to 5.3.1

Gemfile, Gemfile.lock, README.markdown, _config.yml, _includes/download_widget.md, _sample-pages/project.html, _sample-pages/project_group.html, bootstrap/css/bootstrap-select.css, bootstrap/js/bootstrap-select.js, bootstrap/js/bootstrap.js, css/main.css.css, font-awesome/css/font-awesome-ie7.css, font-awesome/css/font-awesome.css, js/backbone.js, js/jquery.js, js/test/SpecRunner.html, js/test/lib/support/mock-ajax.js, js/test/spec/QuickStartWidgetSpec.js, js/underscore.js
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were unable to be fixed. Please review them to see if they can be manually resolved.
([https](https://erik.eae.net/archives/2007/07/27/18.54.15/) result SSLHandshakeException).
([https](https://javascript.nwbox.com/IEContentLoaded/) result SSLHandshakeException).
([https](https://blindsignals.com/index.php/2009/07/jquery-delay/) result SSLHandshakeException).
These URLs were fixed, but the https status was not OK. However, the https status was the same as the http request or http redirected to an https URL, so they were migrated. Your review is recommended.
https://fontawesome.com?from=io …
=> URL Cleanup

docs/manual/src/docs/asciidoc/_includes/preface/whats-new.adoc
=> Fix Broken Documentation Link

samples/boot/oauth2resourceserver-multitenancy/README.adoc, samples/boot/oauth2resourceserver-multitenancy/src/integration-test/java/sample/OAuth2ResourceServerApplicationITests.java, samples/boot/oauth2resourceserver-multitenancy/src/main/java/sample/OAuth2ResourceServerSecurityConfiguration.java
=> Fix OAuth2 multitenancy sample

.gitignore
fixes https://github.com/spring-projects/spring-security/issues/6859
=> Git ignore .attach_pid* files

Jenkinsfile, gradle/dependency-management.gradle
=> Update to Reactor Dysprosium-M1

gradle/dependency-management.gradle
=> Update to Spring 5.2.0.M2

config/src/main/java/org/springframework/security/config/annotation/web/configurers/AbstractAuthenticationFilterConfigurer.java
=> Fix JavaDoc for defaultSuccessUrl

Jenkinsfile
We need to wait to merge this PR until the ssh issue between jenkins and the docs server is repaired. Thus, I've made it a Draft PR to make sure we don't accidentally merge it and break the build.
Fixes: gh-6929
=> Reinstate docs and schema deployments

config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java
=> Fix HttpSecurity Javadoc for jee() method

docs/manual/src/docs/asciidoc/_includes/preface/modules.adoc
=> Updates modules.adoc (typo fix)

core/src/main/java/org/springframework/security/access/hierarchicalroles/RoleHierarchy.java
=> FIX #6954(RoleHierarchy Comments are misleading)

Jenkinsfile
=> Jenkins build performs git clean

web/src/main/java/org/springframework/security/web/authentication/UsernamePasswordAuthenticationFilter.java
=> Add @Nullable to UsernamePasswordAuthenticationFilter

crypto/src/main/java/org/springframework/security/crypto/bcrypt/BCrypt.java, crypto/src/main/java/org/springframework/security/crypto/password/AbstractPasswordEncoder.java, crypto/src/main/java/org/springframework/security/crypto/password/PasswordEncoderUtils.java, crypto/src/main/java/org/springframework/security/crypto/password/Pbkdf2PasswordEncoder.java, crypto/src/main/java/org/springframework/security/crypto/password/StandardPasswordEncoder.java, crypto/src/main/java/org/springframework/security/crypto/scrypt/SCryptPasswordEncoder.java, web/src/main/java/org/springframework/security/web/authentication/rememberme/TokenBasedRememberMeServices.java
=> Use MessageDigest.isEqual() where possible

config/src/main/java/org/springframework/security/config/annotation/SecurityConfigurer.java
=> Changed docs to reflect that init should apply configurers

docs/manual/src/docs/asciidoc/_includes/servlet/preface/java-configuration.adoc
This is my first pull request. It's trivial so I didn't create a branch. It's not explicitly stated in the guidelines if it's needed. Thanks
=> Fixed typo in documentation.

config/src/main/java/org/springframework/security/config/Customizer.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/HeadersConfigurer.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/HttpBasicConfigurer.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/SessionManagementConfigurer.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2LoginConfigurer.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurer.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/openid/OpenIDLoginConfigurer.java, config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, config/src/test/java/org/springframework/security/config/web/server/HttpsRedirectSpecTests.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2ClientSpecTests.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2LoginTests.java, config/src/test/java/org/springframework/security/config/web/server/OAuth2ResourceServerSpecTests.java, docs/manual/src/docs/asciidoc/_includes/reactive/cors.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/headers.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/oauth2/login.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/oauth2/resource-server.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/redirect-https.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/webflux.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/x509.adoc, samples/boot/oauth2resourceserver-static/src/main/java/sample/OAuth2ResourceServerSecurityConfiguration.java, samples/boot/webflux-form/src/main/java/sample/WebfluxFormSecurityConfig.java, samples/boot/webflux-x509/src/main/java/sample/WebfluxX509Application.java, web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationEntryPoint.java
=> Remove exceptions from lambda security configuration

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtTimestampValidator.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationProvider.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionAuthenticationProvider.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionReactiveAuthenticationManager.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/BearerTokenAuthenticationEntryPoint.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/access/BearerTokenAccessDeniedHandler.java, web/src/main/java/org/springframework/security/web/header/writers/HstsHeaderWriter.java
=> Fix javadoc

.editorconfig, CONTRIBUTING.md, build.gradle, config/src/test/java/org/springframework/security/config/annotation/web/configurers/HeadersConfigurerTests.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/RememberMeConfigurerTests.java, core/src/site/site.xml, ldap/src/integration-test/java/org/springframework/security/ldap/SpringSecurityLdapTemplateITests.java, ldap/src/integration-test/java/org/springframework/security/ldap/search/FilterBasedLdapUserSearchTests.java, ldap/src/integration-test/java/org/springframework/security/ldap/userdetails/LdapUserDetailsManagerTests.java, samples/xml/contacts/src/main/webapp/WEB-INF/spring.tld
See: https://travis-ci.org/spring-projects/spring-security/builds/570999589#L1514-L1525
=> Use UTF-8 for compilation

build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Update to Gradle 5.6.1

config/spring-security-config.gradle, config/src/main/java/org/springframework/security/config/annotation/web/configuration/OAuth2ImportSelector.java, config/src/main/java/org/springframework/security/config/annotation/web/configuration/OAuth2ResourceServerConfiguration.java, config/src/test/java/org/springframework/security/config/annotation/web/configuration/OAuth2ResourceServerConfigurationTests.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/reactive/function/client/ServletBearerExchangeFilterFunction.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/TestBearerTokenAuthentications.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/web/reactive/function/client/ServletBearerExchangeFilterFunctionTests.java
=> Bearer WebClient Filter Authentication Propagation

samples/boot/oauth2resourceserver/src/test/java/sample/OAuth2ResourceServerControllerTests.java, test/src/main/java/org/springframework/security/test/web/reactive/server/SecurityMockServerConfigurers.java, test/src/main/java/org/springframework/security/test/web/servlet/request/SecurityMockMvcRequestPostProcessors.java, web/src/main/java/org/springframework/security/web/csrf/CsrfFilter.java, web/src/main/java/org/springframework/security/web/server/csrf/CsrfWebFilter.java, web/src/test/java/org/springframework/security/web/csrf/CsrfFilterTests.java, web/src/test/java/org/springframework/security/web/server/csrf/CsrfWebFilterTests.java
=> Mock Jwt Disables CSRF

acl/src/main/java/org/springframework/security/acls/jdbc/JdbcAclService.java
Just a simple comment fix no one but code-readers will see.
=> Fixed typo in comment

oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/ClientCredentialsOAuth2AuthorizedClientProviderTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/PasswordOAuth2AuthorizedClientProviderTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/RefreshTokenReactiveOAuth2AuthorizedClientProviderTests.java
Fixes gh-7511
Co-authored-by: Isaac Cummings <josh.cummings+zac@gmail.com>
=> Add Clock Skew Tests

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationProvider.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationProviderTests.java
Fixes gh-7514
https://github.com/spring-projects/spring-security/issues/7514
=> We will not validate IP addresses as part of assertion validation

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistration.java
Minor docs fix to reference the correct variable in the sample code.
=> Fix variable reference in sample code

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationRequestFilter.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationRequestFilterTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/servlet/filter/TestSaml2SigningCredentials.java
Fix https://github.com/spring-projects/spring-security/issues/7640
=> Remove empty relay state from redirect url

crypto/src/test/java/org/springframework/security/crypto/bcrypt/BCryptTests.java
Replace test vectors with a list of test objects to improve readability/maintainability
=> Improve unit test maintainability

docs/manual/src/docs/asciidoc/_includes/servlet/oauth2/oauth2-resourceserver.adoc
=> Fix var typo and code readability

config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2LoginConfigurer.java
=> Typo in doc

ldap/src/integration-test/java/org/springframework/security/ldap/server/UnboundIdContainerLdifTests.java, ldap/src/integration-test/resources/test-server-malformed.txt, ldap/src/main/java/org/springframework/security/ldap/server/UnboundIdContainer.java
=> Load default LDIF file from classpath in "unboundid" mode

web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationFilter.java, web/src/test/java/org/springframework/security/web/authentication/www/BasicAuthenticationFilterTests.java
Fix #7835 including unit tests
=> Set credentials charset of authentication converter

core/src/main/java/org/springframework/security/access/expression/SecurityExpressionRoot.java
=> Remove unwanted code

settings.gradle
[Here's a build scan](https://github.com/wilkinsona/spring-security/pull/new/gradle-enterprise-plugin-3.2) for a local build using the new version of the plugin.
=> Upgrade to Gradle Enterprise Plugin 3.2

config/src/main/kotlin/org/springframework/security/config/web/servlet/HttpSecurityDsl.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/HttpSecurityDslTests.kt
=> Add addFilterAfter and addFilterBefore to Kotlin DSL

config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java
=> Fix typo in Javadoc of ServerHttpSecurity#hasAuthority

web/src/main/java/org/springframework/security/web/FilterChainProxy.java
=> Fix example in javadoc of FilterChainProxy

docs/manual/src/docs/asciidoc/_includes/about/index.adoc
Renamed Preface Section of docs to Introduction
=> Rename Preface to Introduction

crypto/src/main/java/org/springframework/security/crypto/encrypt/AesBytesEncryptor.java, crypto/src/test/java/org/springframework/security/crypto/encrypt/AesBytesEncryptorTests.java
=> AesBytesEncryptor constructor that uses secret key

docs/articles/src/docbook/codebase-structure.xml, docs/guides/src/docs/asciidoc/form-javaconfig.asc, docs/guides/src/docs/asciidoc/helloworld-boot.asc, docs/manual/src/docs/asciidoc/_includes/about/exploits/csrf.adoc, docs/manual/src/docs/asciidoc/_includes/reactive/exploits/csrf.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/appendix/faq.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/appendix/namespace.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/cas.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/unpwd/digest.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/unpwd/in-memory.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authorization/secure-objects.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/exploits/csrf.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/integrations/jsp-taglibs.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/integrations/localization.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/integrations/mvc.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/integrations/servlet-api.adoc
=> Fixed typos in documentation

core/src/main/resources/org/springframework/security/messages_zh_TW.properties
Align with commit f7b33da5775d2bef504c1671a83a52e48759d13b.
=> Update Traditional Chinese translation.

samples/boot/saml2login/README.adoc
@pivotal-issuemaster This is an Obvious Fix
=> Fixing typo in SAML 2.0 Sample README

docs/manual/src/docs/asciidoc/_includes/about/authentication/password-storage.adoc, docs/manual/src/docs/asciidoc/_includes/about/exploits/headers.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/architecture/security-filter-chain.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/architecture/provider-manager.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authentication/unpwd/in-memory.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authorization/acls.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authorization/expression-based.adoc, docs/manual/src/docs/asciidoc/_includes/servlet/authorization/secure-objects.adoc
Hi,
This pull request simply fixes a few typos found reading the manual. Great stuff by the way, thanks for this great learning material !
Have a nice day.
=> Fix a few typos in the documentation

.github/workflows/pr-build-workflow.yml
Updates pipeline to run for PRs to all base branches
=> Update pipeline to run for PRs to all branches

config/src/main/kotlin/org/springframework/security/config/web/servlet/FormLoginDsl.kt
Just fixed a miswritten comment.
=> fix miswritten comment of FormLoginDsl.kt

core/src/main/java/org/springframework/security/core/SpringSecurityCoreVersion.java
=> Add try-with-resources to close stream

core/src/main/java/org/springframework/security/authentication/AbstractUserDetailsReactiveAuthenticationManager.java, core/src/test/java/org/springframework/security/authentication/UserDetailsRepositoryReactiveAuthenticationManagerTests.java, web/src/main/java/org/springframework/security/web/access/ExceptionTranslationFilter.java, web/src/main/java/org/springframework/security/web/authentication/preauth/x509/SubjectDnX509PrincipalExtractor.java, web/src/main/java/org/springframework/security/web/authentication/rememberme/AbstractRememberMeServices.java, web/src/test/java/org/springframework/security/web/access/ExceptionTranslationFilterTests.java, web/src/test/java/org/springframework/security/web/authentication/preauth/x509/SubjectDnX509PrincipalExtractorTests.java, web/src/test/java/org/springframework/security/web/authentication/rememberme/AbstractRememberMeServicesTests.java
=> Implement MessageSourceAware where missing

README.adoc
Similar to: https://github.com/spring-projects/spring-boot/pull/24640
=> Add Revved up by Gradle Enterprise badge to README

settings.gradle
=> Update Gradle Enterprise Gradle Plugin

docs/manual/src/docs/asciidoc/_includes/servlet/authentication/unpwd/jdbc.adoc
https://github.com/spring-projects/spring-security/issues/9481
=> Fix missing return in example

config/src/main/kotlin/org/springframework/security/config/web/server/ServerHttpSecurityDsl.kt
=> Fix typo in ServerHttpSecurityDsl Javadoc

.github/workflows/continuous-integration-workflow.yml, .github/workflows/pr-build-workflow.yml
=> Stop CI Jobs on Forks

saml2/saml2-service-provider/core/src/main/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistration.java
=> Update SAML JavaDoc to reference specification

web/src/main/java/org/springframework/security/web/authentication/logout/CookieClearingLogoutHandler.java, web/src/test/java/org/springframework/security/web/authentication/logout/CookieClearingLogoutHandlerTests.java
=> Properly clean cookies with context path after logout

config/src/test/kotlin/org/springframework/security/config/web/server/ServerCsrfDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/server/ServerFormLoginDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/server/ServerHttpBasicDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/server/ServerJwtDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/server/ServerLogoutDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/server/ServerOAuth2ClientDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/server/ServerOAuth2LoginDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/server/ServerOAuth2ResourceServerDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/server/ServerRequestCacheDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/server/ServerX509DslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/CsrfDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/HttpBasicDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/LogoutDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/OAuth2ClientDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/OAuth2ResourceServerDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/RememberMeDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/RequiresChannelDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/SessionManagementDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/X509DslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/oauth2/client/AuthorizationCodeGrantDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/oauth2/login/AuthorizationEndpointDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/oauth2/login/RedirectionEndpointDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/oauth2/login/TokenEndpointDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/oauth2/login/UserInfoEndpointDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/oauth2/resourceserver/JwtDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/oauth2/resourceserver/OpaqueTokenDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/session/SessionConcurrencyDslTests.kt
This pull requests migrate kotlin tests from java mockito to mockk within the config folder.  
Closes gh-9785
=> migrate kotlin tests from java mockito to mockk

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/OAuth2AuthorizationGrantRequestEntityUtils.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveAuthorizationCodeTokenResponseClient.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveClientCredentialsTokenResponseClient.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/WebClientReactivePasswordTokenResponseClient.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveRefreshTokenTokenResponseClient.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/OAuth2ClientCredentialsGrantRequestEntityConverterTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveClientCredentialsTokenResponseClientTests.java
=> URL encode client credentials

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistrations.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/registration/ClientRegistrationsTests.java
=> Remove validation for unsupported grant types

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistrations.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/registration/ClientRegistrationsTests.java
=> Handle missing authorization endpoint uri

dependencies/spring-security-dependencies.gradle, docs/manual/spring-security-docs-manual.gradle, docs/manual/src/docs/asciidoc/_includes/servlet/architecture/filters.adoc, gradle.properties
=> Use springFrameworkVersion properties in docs links

docs/guides/spring-security-docs-guides.gradle, docs/manual/spring-security-docs-manual.gradle, gradle.properties
=> Update docs to point to minor version branches

oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/endpoint/DefaultMapOAuth2AccessTokenResponseConverter.java, oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/endpoint/MapOAuth2AccessTokenResponseConverter.java, oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/http/converter/OAuth2AccessTokenResponseHttpMessageConverter.java, oauth2/oauth2-core/src/test/java/org/springframework/security/oauth2/core/endpoint/DefaultMapOAuth2AccessTokenResponseConverterTests.java
=> Remove wildcard from generics in converter

config/src/main/kotlin/org/springframework/security/config/web/servlet/FormLoginDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/servlet/OAuth2LoginDsl.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/FormLoginDslTests.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/OAuth2LoginDslTests.kt
Opened to address existing issues from `ideal-for-contribution` backlog: gh-9837 and gh-9838
=> AuthenticationDetailsSource for OAuth2 and Form Login Kotlin DSL

docs/manual/src/docs/asciidoc/_includes/servlet/oauth2/oauth2-client.adoc
=> Update deprecated usage in reference docs

config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LoginConfigurer.java
Improve OpenSAML Version Check
Closes gh-10077
=> Improve OpenSAML Version Check

cas/src/main/java/org/springframework/security/cas/web/CasAuthenticationFilter.java, core/src/main/java/org/springframework/security/access/intercept/AbstractSecurityInterceptor.java, core/src/main/java/org/springframework/security/core/Authentication.java, core/src/main/java/org/springframework/security/core/context/GlobalSecurityContextHolderStrategy.java, core/src/main/java/org/springframework/security/core/context/InheritableThreadLocalSecurityContextHolderStrategy.java, core/src/main/java/org/springframework/security/core/context/ListeningSecurityContextHolderStrategy.java, core/src/main/java/org/springframework/security/core/context/SecurityContextChangedEvent.java, core/src/main/java/org/springframework/security/core/context/SecurityContextChangedListener.java, core/src/main/java/org/springframework/security/core/context/SecurityContextHolder.java, core/src/main/java/org/springframework/security/core/context/ThreadLocalSecurityContextHolderStrategy.java, core/src/main/java/org/springframework/security/provisioning/JdbcUserDetailsManager.java, core/src/test/java/org/springframework/security/core/context/SecurityContextHolderTests.java, remoting/src/main/java/org/springframework/security/remoting/rmi/ContextPropagatingRemoteInvocation.java, web/src/main/java/org/springframework/security/web/access/ExceptionTranslationFilter.java, web/src/main/java/org/springframework/security/web/authentication/AbstractAuthenticationProcessingFilter.java, web/src/main/java/org/springframework/security/web/authentication/AnonymousAuthenticationFilter.java, web/src/main/java/org/springframework/security/web/authentication/logout/SecurityContextLogoutHandler.java, web/src/main/java/org/springframework/security/web/authentication/preauth/AbstractPreAuthenticatedProcessingFilter.java, web/src/main/java/org/springframework/security/web/authentication/rememberme/RememberMeAuthenticationFilter.java, web/src/main/java/org/springframework/security/web/authentication/switchuser/SwitchUserFilter.java, web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationFilter.java, web/src/main/java/org/springframework/security/web/authentication/www/DigestAuthenticationFilter.java, web/src/main/java/org/springframework/security/web/servletapi/HttpServlet3RequestFactory.java
Applications can add a listener by doing:
```java
SecurityContextHolder.addListener((event) -> logger.info("security context changed"));
```
=> Add SecurityContextHolder#addListener

docs/manual/src/docs/asciidoc/_includes/servlet/appendix/proxy-server.adoc
=> Update a broken link to Spring Boot documentation

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java
@pivotal-cla This is an Obvious Fix
=> Closes gh-10222. Added exception to error message

messaging/src/main/java/org/springframework/security/messaging/context/AuthenticationPrincipalArgumentResolver.java, messaging/src/main/java/org/springframework/security/messaging/handler/invocation/reactive/AuthenticationPrincipalArgumentResolver.java, messaging/src/test/java/org/springframework/security/messaging/context/AuthenticationPrincipalArgumentResolverTests.java, messaging/src/test/java/org/springframework/security/messaging/handler/invocation/reactive/AuthenticationPrincipalArgumentResolverTests.java, web/src/main/java/org/springframework/security/web/method/annotation/AuthenticationPrincipalArgumentResolver.java, web/src/main/java/org/springframework/security/web/reactive/result/method/annotation/AuthenticationPrincipalArgumentResolver.java, web/src/test/java/org/springframework/security/web/method/annotation/AuthenticationPrincipalArgumentResolverTests.java, web/src/test/java/org/springframework/security/web/reactive/result/method/annotation/AuthenticationPrincipalArgumentResolverTests.java
=> Allow AuthenticationPrincipal argument type to be primitive

docs/modules/ROOT/pages/servlet/oauth2/oauth2-client.adoc
=> Document authentication helper method in WebClient integration

docs/modules/ROOT/pages/servlet/oauth2/oauth2-client.adoc
=> Document parameters converter in oauth2 client servlet docs

aspects/spring-security-aspects.gradle, build.gradle
Version 6.3.0 aligns with the used Gradle 7.3
fixes #10492
=> Update aspectj-plugin to 6.3.0

docs/modules/ROOT/pages/servlet/oauth2/resource-server/multitenancy.adoc
#10505 Fixed jwtDecoder(JWTProcessor jwtProcessor, OAuth2TokenValidator<Jwt> jwtValidator)
=> #10505 Fixed jwtDecoder example code

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/OAuth2AuthorizedClientProviderBuilder.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/ReactiveOAuth2AuthorizedClientProviderBuilder.java
=> Update clockSkew javadoc according to implementation

settings.gradle
=> Bump up Gradle enterprise plugin to 3.7.2

docs/modules/ROOT/pages/reactive/oauth2/client/authorization-grants.adoc, docs/modules/ROOT/pages/reactive/oauth2/client/index.adoc, docs/modules/ROOT/pages/reactive/oauth2/login/advanced.adoc, docs/modules/ROOT/pages/reactive/oauth2/login/core.adoc
=> Fix Reactive OAuth2 Kotlin DSL examples

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/OpenSamlAssertingPartyMetadataConverter.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/OpenSamlRelyingPartyRegistrationBuilderHttpMessageConverter.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistrations.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/registration/OpenSamlAssertingPartyMetadataConverterTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistrationsTests.java, saml2/saml2-service-provider/src/test/resources/test-entitiesdescriptor.xml
=> Add EntitiesDescriptor Support

.github/workflows/release-next-version.yml, build.gradle, buildSrc/src/main/java/org/springframework/gradle/github/milestones/GitHubMilestoneApi.java, buildSrc/src/main/java/org/springframework/gradle/github/milestones/GitHubMilestoneNextReleaseTask.java, buildSrc/src/main/java/org/springframework/gradle/github/milestones/GitHubMilestoneNextVersionDueTodayTask.java, buildSrc/src/main/java/org/springframework/gradle/github/milestones/GitHubMilestonePlugin.java, buildSrc/src/main/java/org/springframework/gradle/github/milestones/Milestone.java, buildSrc/src/main/java/org/springframework/gradle/github/milestones/NextVersionYml.java, buildSrc/src/test/java/org/springframework/gradle/github/milestones/GitHubMilestoneApiTests.java
Add Gradle task that calculates the next release milestone based on the current version and check if it is due today.
The second step in the workflow is only a placeholder.
Issue gh-10451
Issue gh-10455
=> Add workflow that triggers release on due date

docs/modules/ROOT/pages/servlet/integrations/data.adoc
Related GitHub issue
[gh-10827](https://github.com/spring-projects/spring-security/issues/10827)
Purposed changes
- add Kotlin examples for Spring Data Integration of servlet application
=> add Kotlin examples for Spring Data Integration of servlet application

docs/modules/ROOT/pages/features/integrations/cryptography.adoc
gh-10910
- edit declaration of `PasswordEncoder` interface of Cryptography section (documentation)
=> Edit declaration of PasswordEncoder interface of Cryptography section

.github/workflows/continuous-integration-workflow.yml
=> Update CI process to create GitHub releases with release notes

.github/workflows/continuous-integration-workflow.yml
=> Add missing output and checkout

.github/workflows/continuous-integration-workflow.yml
=> Do not run CI on tags

buildSrc/src/main/java/org/springframework/security/convention/versions/UpdateProjectVersionPlugin.java, buildSrc/src/main/java/org/springframework/security/convention/versions/UpdateToSnapshotVersionTask.java
=> Add gradle task for updating to next development version

docs/modules/ROOT/pages/servlet/oauth2/resource-server/bearer-tokens.adoc
=> Fix typo in reference documentation

.github/workflows/antora-generate.yml, .github/workflows/continuous-integration-workflow.yml, .github/workflows/deploy-reference.yml, .github/workflows/pr-build-workflow.yml, .github/workflows/release-next-version.yml
=> Add gradle-build-action to GitHub Actions pipelines

config/src/main/kotlin/org/springframework/security/config/web/servlet/HttpSecurityDsl.kt, config/src/main/kotlin/org/springframework/security/config/web/servlet/SecurityContextDsl.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/SecurityContextDslTests.kt
Add Security Context Dsl
- tests based on `SecurityContextConfigurerTests`
- security config dsl 
Closes gh-11039
=> Security Context Dsl

config/src/main/kotlin/org/springframework/security/config/web/servlet/AuthorizeHttpRequestsDsl.kt, config/src/test/kotlin/org/springframework/security/config/web/servlet/AuthorizeHttpRequestsDslTests.kt, docs/modules/ROOT/pages/servlet/authorization/authorize-http-requests.adoc
=> Add shouldFilterAllDispatcherTypes to Kotlin DSL

config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/ChannelSecurityConfigurerTests.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/HttpSecurityRequestMatchersTests.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/UrlAuthorizationConfigurerTests.java
=> Fix mvcMatchers overriding previous paths

core/src/main/java/org/springframework/security/authorization/AuthorityAuthorizationManager.java
Consider replacing an inner loop with Set of authority strings in AuthorityAuthorizationManager
Closes gh-11188
=> Consider replacing an inner loop with Set of authority strings in AuthorityAuthorizationManager

core/src/main/java/org/springframework/security/authorization/AuthorityAuthorizationManager.java
Refers https://github.com/spring-projects/spring-security/issues/11188#issuecomment-1121701811
=> Polish gh-11188

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/jackson2/Saml2PostAuthenticationRequestMixin.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/jackson2/Saml2RedirectAuthenticationRequestMixin.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/AbstractSaml2AuthenticationRequest.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2PostAuthenticationRequest.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/Saml2RedirectAuthenticationRequest.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/Saml2AuthenticationTokenConverter.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/jackson2/Saml2PostAuthenticationRequestMixinTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/jackson2/Saml2RedirectAuthenticationRequestMixinTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/jackson2/TestSaml2JsonPayloads.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/Saml2AuthenticationTokenConverterTests.java
=> Add relyingPartyRegistrationId to AbstractSaml2AuthenticationRequest

docs/modules/ROOT/pages/reactive/test/method.adoc, docs/modules/ROOT/pages/reactive/test/web/setup.adoc, docs/modules/ROOT/pages/servlet/test/method.adoc, docs/modules/ROOT/pages/servlet/test/mockmvc/setup.adoc
Update Junit5 annotations in documentation
- replace Before with BeforeEach
- replace RunWith with ExtendWith
Issue spring-projects gh-10934
=> Update Junit5 annotations in documentation

core/src/main/java/org/springframework/security/authorization/AuthorityAuthorizationManager.java, core/src/test/java/org/springframework/security/authorization/AuthorityAuthorizationManagerTests.java
Added `roleHierarchy` field to `AuthorityAuthorizationManager`
that defaults to `NullRoleHierarchy` along with setter method to override.
Closes gh-11304
=> Add RoleHierarchy to AuthorityAuthorizationManager

docs/modules/ROOT/pages/servlet/authentication/passwords/digest.adoc
=> Fix title render issue of Digest Authentication document

oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/oidc/OidcUserInfo.java
=> Change phoneNumberVerified with type Boolean

.github/workflows/release-scheduler.yml, .github/workflows/update-scheduled-release-version.yml, build.gradle, buildSrc/src/main/java/org/springframework/gradle/github/release/DispatchGitHubWorkflowTask.java, buildSrc/src/main/java/org/springframework/gradle/github/release/GitHubActionsApi.java, buildSrc/src/main/java/org/springframework/gradle/github/release/GitHubReleasePlugin.java, buildSrc/src/main/java/org/springframework/gradle/github/release/WorkflowDispatch.java, buildSrc/src/test/java/org/springframework/gradle/github/release/GitHubActionsApiTests.java, buildSrc/src/test/java/org/springframework/gradle/github/release/GitHubReleaseApiTests.java
=> Add workflow for scheduling releases on maintenance branches

settings.gradle
=> Update Gradle Enterprise plugin

docs/modules/ROOT/pages/servlet/authorization/authorize-http-requests.adoc
=> Fix method call example on documentation

oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderTests.java
=> Fix typo on NimbusJwtDecoderTests

config/src/main/resources/org/springframework/security/config/spring-security-6.0.xsd, config/src/test/resources/org/springframework/security/config/method-security.xml
Issue gh-11328
Issue gh-11353
Issue gh-11365
=> Use relative schema location for tests

docs/modules/ROOT/pages/features/authentication/password-storage.adoc
=> "Well-Know" should be "Well-Known"

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationRequestFilter.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/Saml2LogoutRequestFilter.java, saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/Saml2RelyingPartyInitiatedLogoutSuccessHandler.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationRequestFilterTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/authentication/logout/Saml2LogoutRequestFilterTests.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/authentication/logout/Saml2RelyingPartyInitiatedLogoutSuccessHandlerTests.java
=> Add hash-based Content-Security-Policy for SAML pages

config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/EnableGlobalAuthentication.java, config/src/main/java/org/springframework/security/config/annotation/web/WebSecurityConfigurer.java, config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java, config/src/main/java/org/springframework/security/config/annotation/web/builders/WebSecurity.java, config/src/main/java/org/springframework/security/config/annotation/web/configuration/EnableWebSecurity.java, config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/AbstractAuthenticationFilterConfigurer.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/DefaultLoginPageConfigurer.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/FormLoginConfigurer.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/HeadersConfigurer.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/RememberMeConfigurer.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/X509Configurer.java
=> Remove references to WebSecurityConfigurerAdapter

docs/modules/ROOT/pages/getting-spring-security.adoc
- <dependencyManagement> to dependencyManagement
- pom.xml to build.gradle
Sorry...there were some problems just now. I resubmitted PR
=> Modify words

config/src/main/java/org/springframework/security/config/annotation/web/configurers/CsrfConfigurer.java, config/src/main/java/org/springframework/security/config/http/CsrfBeanDefinitionParser.java, config/src/main/resources/org/springframework/security/config/spring-security-5.8.rnc, config/src/main/resources/org/springframework/security/config/spring-security-5.8.xsd, config/src/test/java/org/springframework/security/config/annotation/web/configuration/DeferHttpSessionJavaConfigTests.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/CsrfConfigurerTests.java, config/src/test/java/org/springframework/security/config/http/CsrfConfigTests.java, config/src/test/resources/org/springframework/security/config/http/CsrfConfigTests-WithRequestAttrName.xml, config/src/test/resources/org/springframework/security/config/http/DeferHttpSessionTests-Explicit.xml, docs/modules/ROOT/pages/servlet/appendix/namespace/http.adoc, web/src/main/java/org/springframework/security/web/csrf/CsrfAuthenticationStrategy.java, web/src/main/java/org/springframework/security/web/csrf/CsrfFilter.java, web/src/main/java/org/springframework/security/web/csrf/CsrfTokenRequestAttributeHandler.java, web/src/main/java/org/springframework/security/web/csrf/CsrfTokenRequestProcessor.java, web/src/main/java/org/springframework/security/web/csrf/CsrfTokenRequestResolver.java, web/src/test/java/org/springframework/security/web/csrf/CsrfAuthenticationStrategyTests.java, web/src/test/java/org/springframework/security/web/csrf/CsrfFilterTests.java, web/src/test/java/org/springframework/security/web/csrf/CsrfTokenRequestProcessorTests.java
=> Add new interfaces for CSRF request processing

antora-playbook.yml
Include RC versions when building docs site.
=> build and publish RC versions

.github/actions/publish-docs.sh
Fail the script if one of the commands in the script fails.
=> propagate exit code in publish-docs script

core/src/main/java/org/springframework/security/authorization/AuthorizationManagers.java, core/src/test/java/org/springframework/security/authorization/AuthorizationManagersTests.java
=> Simplify AuthorizationManager composition

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/DefaultOAuth2AuthorizationRequestResolver.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/InvalidClientRegistrationIdException.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/OAuth2AuthorizationRequestRedirectFilter.java
=> Reduce severity of invalid registrationId to warn

build.gradle
Apply Gradle's base plugin to add clean task.
=> apply base plugin to add clean task (docs-build branch)

docs/modules/ROOT/pages/migration.adoc
=> Document how to opt-in for SHA256 in RememberMe

docs/modules/ROOT/pages/servlet/oauth2/resource-server/opaque-token.adoc
=> Fix typo on opaque-token.adoc

lib/antora/extensions/version-fix.js
* look for number instead of string
=> fix the version fix for 5.6.0-RC1

docs/modules/ROOT/pages/migration.adoc
=> Register FilterChainProxy for All Dispatcher Types Migration Steps

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/Saml2MetadataFilter.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/Saml2MetadataFilterTests.java
=> Use UTF-8 in Saml2MetadataFilter response writer

config/src/test/java/org/springframework/security/config/annotation/web/configurers/HttpSecurityObservationTests.java, config/src/test/java/org/springframework/security/config/http/HttpConfigTests.java, core/src/main/java/org/springframework/security/authentication/AuthenticationObservationConvention.java, core/src/main/java/org/springframework/security/authorization/AuthorizationObservationConvention.java, core/src/main/java/org/springframework/security/authorization/ExpressionAuthorizationDecision.java, core/src/main/java/org/springframework/security/core/context/ObservationSecurityContextChangedListener.java, core/src/test/java/org/springframework/security/core/context/ObservationSecurityContextChangedListenerTests.java, web/src/main/java/org/springframework/security/web/ObservationFilterChainDecorator.java, web/src/main/java/org/springframework/security/web/server/ObservationWebFilterChainDecorator.java
=> Polish Span and Meter Names

core/src/main/java/org/springframework/security/authorization/AuthoritiesAuthorizationManager.java, core/src/main/java/org/springframework/security/authorization/AuthorityAuthorizationManager.java, core/src/main/java/org/springframework/security/core/authority/AuthorityUtils.java, core/src/test/java/org/springframework/security/authorization/AuthoritiesAuthorizationManagerTests.java, core/src/test/java/org/springframework/security/authorization/AuthorityAuthorizationManagerTests.java, core/src/test/java/org/springframework/security/core/authority/AuthorityUtilsTests.java
=> Add Authority String AuthorizationManager

core/src/main/java/org/springframework/security/authorization/ExpressionAuthorizationDecision.java
=> Fix Javadoc since tag for class ExpressionAuthorizationDecision

core/src/main/java/org/springframework/security/access/expression/SecurityExpressionRoot.java
Consider replacing SecurityExpressionRoot.AuthenticationSupplier with SingletonSupplier
Closes gh-12487
=> Consider replacing SecurityExpressionRoot.AuthenticationSupplier with SingletonSupplier

build.gradle, lib/antora/templates/per-branch-antora-playbook.yml
Note that this PR depends on https://github.com/spring-io/antora-ui-spring/pull/62
=> upgrade Asciidoctor Tabs, the Antora Gradle plugin, and Node.js

.github/workflows/deploy-docs.yml
=> Update to spring-io/spring-gradle-build-action@v2

lib/antora/templates/per-branch-antora-playbook.yml
- declare atlas extension as package
- declare release line extension as package
- enable release line extension by default
- configure atlas extension, but do not enable by default
=> prime atlas extension for use in playbook template

.github/workflows/continuous-integration-workflow.yml
Signed-off-by: jongwooo <jongwooo.han@gmail.com>
Reopen #12449
=> chore: Use cache in continuous-integration-workflow.yml

config/src/main/java/org/springframework/security/config/annotation/web/configurers/SessionManagementConfigurer.java, config/src/test/java/org/springframework/security/config/annotation/web/configurers/SessionManagementConfigurerTests.java
=> #12579: SessionManagementFilter should used configured SecurityContextRepository

docs/modules/ROOT/pages/migration/servlet/authentication.adoc
=> Fix typo in Authentication Migrations page

core/src/main/java/org/springframework/security/authorization/AuthorizationManager.java
Simple typo fix on AuthorizationManager
=> Fix javadox typo

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/OpenSamlMetadataAssertingPartyDetailsConverter.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistrationsTests.java, saml2/saml2-service-provider/src/test/resources/test-federated-metadata.xml, saml2/saml2-service-provider/src/test/resources/test-metadata-without-idp.xml
=> Ignore SPSSODescriptor elements

docs/modules/ROOT/pages/servlet/authentication/passwords/form.adoc
=> Fix broken links in form login section

config/src/main/kotlin/org/springframework/security/config/annotation/web/FormLoginDsl.kt, config/src/test/kotlin/org/springframework/security/config/annotation/web/FormLoginDslTests.kt
Fixes https://github.com/spring-projects/spring-security/issues/12552
=> Add disable to FormLoginDsl

config/src/test/java/org/springframework/security/test/web/servlet/RequestCacheResultMatcher.java
=> fix typo in RequestCacheResultMatcher

docs/modules/ROOT/pages/servlet/authentication/session-management.adoc
This PR Fixes #12850, by changing two code blocks.
=> Fix documentation code block bug

web/src/main/java/org/springframework/security/web/util/matcher/RequestMatchers.java, web/src/test/java/org/springframework/security/web/util/matcher/RequestMatchersTests.java
This PR implements the improvement described in gh-12751.
The added test cases verify that compilation succeeds.
=> Add factory class for RequestMatcher composition

CONTRIBUTING.adoc
Closes gh-12925
Closes gh-6094
This new format takes a lot of inspiration from [Spring Framework's contribution guidelines](https://github.com/spring-projects/spring-framework/blob/main/CONTRIBUTING.md).
=> Revisit Contribution Guidelines

docs/modules/ROOT/pages/migration/servlet/session-management.adoc, docs/modules/ROOT/pages/servlet/authentication/logout.adoc, docs/modules/ROOT/pages/servlet/authentication/session-management.adoc
=> Improve Docs by mentioning that Empty SecurityContext should be saved

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml4AuthenticationProvider.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml4AuthenticationProviderTests.java
=> Don't use raw xml saml authentication request for response validation

docs/modules/ROOT/pages/servlet/authentication/passwords/form.adoc
=> Fix invalid link in ref doc

saml2/saml2-service-provider/src/opensaml3Main/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationProvider.java, saml2/saml2-service-provider/src/opensaml4Main/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml4AuthenticationProvider.java
=> Debug message in OpenSamlAuthenticationProviders is never logged

docs/modules/ROOT/pages/migration/servlet/authorization.adoc
AuthorizationMangers -> AuthorizationManagers
=> Fix typo in authorization.adoc

web/src/main/java/org/springframework/security/web/savedrequest/SimpleSavedRequest.java
=> Assert is missing object. It was useless before Spring Framework 6.1 and will not compile on 6.1

config/src/main/java/org/springframework/security/config/http/OAuth2ClientBeanDefinitionParser.java, config/src/main/java/org/springframework/security/config/http/OAuth2ClientBeanDefinitionParserUtils.java, config/src/main/java/org/springframework/security/config/http/OAuth2LoginBeanDefinitionParser.java, config/src/main/java/org/springframework/security/config/http/OAuth2ResourceServerBeanDefinitionParser.java, config/src/main/java/org/springframework/security/config/oauth2/client/ClientRegistrationsBeanDefinitionParser.java, config/src/test/java/org/springframework/security/config/doc/SpringSecurityXsdParser.java, core/src/main/java/org/springframework/security/jackson2/SecurityJackson2Modules.java, core/src/test/java/org/springframework/security/provisioning/JdbcUserDetailsManagerTests.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/oidc/userinfo/OidcUserRequestUtils.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/oidc/userinfo/OidcUserService.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/userinfo/DefaultReactiveOAuth2UserService.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/OAuth2AuthorizationCodeGrantFilter.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/method/annotation/OAuth2AuthorizedClientArgumentResolver.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/reactive/function/client/ServerOAuth2AuthorizedClientExchangeFilterFunction.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/reactive/function/client/ServletOAuth2AuthorizedClientExchangeFilterFunction.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveClientCredentialsTokenResponseClientTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/jackson2/OAuth2AuthenticationTokenMixinTests.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoder.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/NimbusOpaqueTokenIntrospector.java, rsocket/src/test/java/org/springframework/security/rsocket/authentication/AuthenticationPayloadInterceptorTests.java, rsocket/src/test/java/org/springframework/security/rsocket/metadata/BasicAuthenticationDecoderTests.java, web/src/main/java/org/springframework/security/web/FilterInvocation.java, web/src/main/java/org/springframework/security/web/savedrequest/CookieRequestCache.java
Hi, I replaced some deprecated methods.
This doesn't want to be a full cleansing of every single deprecated methods of course, I just tried to replace the simple cases where a logically equivalent alternative was present.
Also I didn't consider some cases because #12569 is already covering them.
Bye!
=> Replace deprecated methods

cas/src/main/java/org/springframework/security/cas/web/CasAuthenticationFilter.java
=> Use SecurityContextHolderStrategy in CasAuthenticationFilter

docs/modules/ROOT/pages/servlet/oauth2/resource-server/bearer-tokens.adoc
=> Fix Bearer Token RestTemplate Support example

docs/modules/ROOT/pages/servlet/authentication/session-management.adoc
=> Fix minor typo in docs

docs/modules/ROOT/pages/servlet/authentication/rememberme.adoc
=> Closes #11450 - Add Java beans configuration for Remmember Me Docs

antora-playbook.yml, lib/antora/templates/per-branch-antora-playbook.yml
=> Update to antora-ui-spring 0.3.5

antora-playbook.yml, lib/antora/templates/per-branch-antora-playbook.yml
=> Update to antora-ui-spring 0.3.6

docs/modules/ROOT/pages/servlet/authentication/logout.adoc
=> Fix grammar on logout page of the docs

docs/modules/ROOT/pages/servlet/integrations/websocket.adoc
In Kotlin, the wildcard type is represented by *, so the code has been updated to replace ? with *.
Additionally, a ">" character was missing and has been added to correct the code.
=> Replace wildcard type ? with * in Kotlin and fix typo in Spring docs

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/jackson2/Saml2LogoutRequestMixin.java, saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/jackson2/Saml2LogoutRequestMixinTests.java
=> Saml2LogoutRequestMixin relayState property should be binding

saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/metadata/OpenSamlMetadataResolver.java
=> Allow OpenSamlMetadataResolver to also render un-pretty printed metadata content

oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/ClaimAccessor.java, oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JoseHeader.java
Replace all occurrences of `Assert.isTrue\((\w+)\s?!=\s?null\s*,` with `Assert.notNull($1,`.
=> Check for null value with the appropriate assertion method

docs/modules/ROOT/pages/servlet/authentication/logout.adoc
=> Update logout.adoc: Replace Directives with Directive

oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/SpringOpaqueTokenIntrospector.java, oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/SpringReactiveOpaqueTokenIntrospector.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/introspection/SpringOpaqueTokenIntrospectorTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/introspection/SpringReactiveOpaqueTokenIntrospectorTests.java
=> Add a custom converter in SpringOpaqueTokenIntrospector

docs/modules/ROOT/pages/servlet/authorization/architecture.adoc
Add missing method call in authorization docs
=> Add missing method call in docs

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java, oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoderTests.java
Caught ParseExcepetion, dropped nimbus error message, and replace with Malformed header.
=> Dropped Nimbus Error Message gh 13730

core/src/main/java/org/springframework/security/core/userdetails/UserDetails.java, test/src/test/java/org/springframework/security/test/context/showcase/CustomUserDetails.java
=> Add default implementations in UserDetails

docs/modules/ROOT/pages/servlet/oauth2/resource-server/multitenancy.adoc
Closes gh-14229
Improves the example code for issuer validation in the case of multitenancy.
=> Improve Multitenancy Issuer Validator example

web/src/main/java/org/springframework/security/web/util/matcher/IpAddressMatcher.java
=> Enhance IpAddressMatcher performance

docs/modules/ROOT/pages/servlet/authentication/rememberme.adoc
I changed 'unecessarily' to 'unnecessarily'.
=> Typo: Update rememberme.adoc

docs/modules/ROOT/pages/servlet/authentication/anonymous.adoc
I changed 'instancesthat' to 'instances that'
=> Typo: Update anonymous.adoc

config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LogoutConfigurer.java
=> Saml2 LogoutFilter Should Come Before Common LogoutFilter

config/src/main/java/org/springframework/security/config/annotation/web/HttpSecurityBuilder.java, config/src/main/java/org/springframework/security/config/annotation/web/builders/FilterOrderRegistration.java
=> Fix security filter sort in javadoc

config/src/main/java/org/springframework/security/config/annotation/web/configurers/LogoutConfigurer.java
=> Remove duplicate setSecurityContextHolderStrategy

web/src/main/java/org/springframework/security/web/firewall/StrictHttpFirewall.java, web/src/test/java/org/springframework/security/web/firewall/StrictHttpFirewallTests.java
=> Allow tab in HTTP header values.

web/src/main/java/org/springframework/security/web/server/authentication/DelegatingServerAuthenticationConverter.java, web/src/test/java/org/springframework/security/web/server/authentication/DelegatingServerAuthenticationConverterTests.java
=> Add DelegatingServerAuthenticationConverter

oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/TokenExchangeOAuth2AuthorizedClientProvider.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/TokenExchangeReactiveOAuth2AuthorizedClientProvider.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/DefaultTokenExchangeTokenResponseClient.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/TokenExchangeGrantRequest.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/TokenExchangeGrantRequestEntityConverter.java, oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveTokenExchangeTokenResponseClient.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/TokenExchangeOAuth2AuthorizedClientProviderTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/TokenExchangeReactiveOAuth2AuthorizedClientProviderTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/DefaultTokenExchangeTokenResponseClientTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/TokenExchangeGrantRequestEntityConverterTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/TokenExchangeGrantRequestTests.java, oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveTokenExchangeTokenResponseClientTests.java, oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/AuthorizationGrantType.java, oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/endpoint/OAuth2ParameterNames.java
=> Add support for OAuth 2.0 Token Exchange Grant

web/src/main/java/org/springframework/security/web/server/authentication/AuthenticationWebFilter.java
=> Improve logging in AuthenticationWebFilter

docs/modules/ROOT/pages/reactive/oauth2/client/authorization-grants.adoc
This (reactive) page is currently out of sync with the Servlet page. This pull request aims to ensure alignment between both pages.
=> Synchronize Reactive Page with Servlet Page for Consistency

core/src/main/java/org/springframework/security/authorization/AuthenticatedReactiveAuthorizationManager.java
=> fix docs error in AuthenticatedReactiveAuthorizationManager

README.adoc
=> Fix incorrect links

core/src/main/java/org/springframework/security/authentication/AbstractAuthenticationToken.java
Use instanceof Pattern Matching
=> Use instanceof Pattern Matching

settings.gradle
=> Conditionally Add Conventions Plugin

oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtDecoder.java
=> Fix typo in JwtDecoder

docs/modules/ROOT/pages/reactive/configuration/webflux.adoc
Fixed minor typo in import note which leaded to compilation error in Kotlin.
=> Docs: Fix import for reactive example with Kotlin DSL

config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LoginConfigurer.java, core/src/main/java/org/springframework/security/access/method/MethodSecurityMetadataSource.java, core/src/main/java/org/springframework/security/access/prepost/PrePostInvocationAttributeFactory.java, gradle/libs.versions.toml, ldap/src/main/java/org/springframework/security/ldap/LdapUtils.java, ldap/src/main/java/org/springframework/security/ldap/userdetails/LdapUserDetailsManager.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerAuthenticationManagerResolverDeprecatedTests.java, oauth2/oauth2-resource-server/src/test/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerReactiveAuthenticationManagerResolverDeprecatedTests.java
Supersedes gh-15598
Backport of gh-15646
=> Bump io-spring-javaformat from 0.0.42 to 0.0.43

docs/modules/ROOT/pages/reactive/integrations/cors.adoc, docs/modules/ROOT/pages/servlet/integrations/cors.adoc
=> Update CORS document

oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/endpoint/OAuth2AuthorizationRequest.java, oauth2/oauth2-core/src/test/java/org/springframework/security/oauth2/core/endpoint/OAuth2AuthorizationRequestTests.java
=> fix additionalParameters array parameter of OAuth2AuthorizationRequest causes the authorizationRequestUri to be incorrect

web/src/main/java/org/springframework/security/web/server/savedrequest/WebSessionServerRequestCache.java
```diff
-createDefaultRequestMacher
+createDefaultRequestMatcher
```
=> Fix typo of createDefaultRequestMacher in WebSessionServerRequestCache

web/src/main/java/org/springframework/security/web/authentication/ui/DefaultOneTimeTokenSubmitPageGeneratingFilter.java
Update javaDoc for DefaultOneTimeTokenSubmitPageGeneratingFilter
=> Update javaDoc for DefaultOneTimeTokenSubmitPageGeneratingFilter

core/src/main/java/org/springframework/security/core/token/KeyBasedPersistenceTokenService.java
Replaces the method call to fix Issue #15889.
=> Replace Date().getTime() method with System.currentTimeMillis()

core/src/main/java/org/springframework/security/authorization/AuthorizationEventPublisher.java
Add @FunctionalInterface to AuthorizationEventPublisher
=> Add @FunctionalInterface to AuthorizationEventPublisher

docs/modules/ROOT/pages/reactive/oauth2/resource-server/index.adoc
=> Fix typo in oauth2 resource server documentation

web/src/main/java/org/springframework/security/web/aot/hint/WebMvcSecurityRuntimeHints.java, web/src/test/java/org/springframework/security/web/aot/hint/WebMvcSecurityRuntimeHintsTests.java
=> Add RuntimeHints for webauthn Javascript resource

docs/modules/ROOT/pages/servlet/authorization/method-security.adoc, docs/modules/ROOT/pages/servlet/exploits/csrf.adoc
=> Polish Dark Mode for CSRF and Method Security diagrams

config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeUserDetailsBeanManagerConfigurer.java
Related to #16050
As the [comments ](https://github.com/spring-projects/spring-security/pull/16050#issuecomment-2469417774)said
=> Do not eagerly construct UserDetailsService bean in Global Authentication

web/src/main/java/org/springframework/security/web/session/HttpSessionEventPublisher.java
=> Add @inheritDoc to sessionIdChanged method

config/src/main/kotlin/org/springframework/security/config/annotation/web/WebAuthnDsl.kt
Fixed typo in WebAuthnDsl javadoc.
=> Fixed typo in WebAuthnDsl

config/src/main/java/org/springframework/security/config/annotation/web/configurers/ott/OneTimeTokenLoginConfigurer.java
Use the `getBeanProvider. getIfUnique(default)`method directly
=> Polish OneTimeTokenLoginConfigurer

config/src/main/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurer.java, config/src/main/java/org/springframework/security/config/annotation/web/configurers/PermitAllSupport.java
- Renamed PERMIT_ALL_AUTHORIZATION_MANAGER to snake_case style
- Introduced AUTHORIZATION_DECISION for reuse
=> Refactor authorization manager variable naming

docs/modules/ROOT/pages/servlet/architecture.adoc
=> Fix ordering for security filter configuration

core/src/main/java/org/springframework/security/core/annotation/ExpressionTemplateSecurityAnnotationScanner.java, core/src/test/java/org/springframework/security/core/annotation/ExpressionTemplateSecurityAnnotationScannerTests.java
=> Method Security templates support use deep non-aliased attributes

docs/modules/ROOT/pages/servlet/oauth2/resource-server/multitenancy.adoc, docs/modules/ROOT/pages/servlet/saml2/login/overview.adoc
Fix typo and inline code formatting in documentation.
=> Fix typo and inline code formatting in documentation

core/src/main/java/org/springframework/security/authorization/method/AuthorizeReturnObjectMethodInterceptor.java
Use `authorizationProxyFactory` as message prompt
=> Use correct message prompt in AuthorizeReturnObjectMethodInterceptor constructor

.github/workflows/codeql.yml
=> Explicitly disable the default codeql setup

web/src/main/java/org/springframework/security/web/authentication/preauth/x509/X509PrincipalExtractor.java
=> Add FunctionalInterface To X509PrincipalExtractor

web/src/test/java/org/springframework/security/web/authentication/preauth/x509/SubjectDnX509PrincipalExtractorTests.java
Fix Typo In SubjectDnX509PrincipalExtractorTests
=> Fix Typo In SubjectDnX509PrincipalExtractorTests

docs/modules/ROOT/pages/servlet/authentication/x509.adoc
=> Remove duplicate lines from X.509 documentation

docs/modules/ROOT/pages/servlet/authentication/logout.adoc
=> Correct method name in document

web/src/main/java/org/springframework/security/web/DefaultSecurityFilterChain.java
Change import from reactor.util.annotation.NonNull to org.springframework.lang.NonNull
#16572
=> Change NonNull import from reactor to spring

web/src/main/java/org/springframework/security/web/server/savedrequest/WebSessionServerRequestCache.java
- Remove unused method and unnecessary `this` keyword because `logger` is declared `static final`
- Update javadoc
=> Cleanup code

config/src/main/java/org/springframework/security/config/oauth2/client/CommonOAuth2Provider.java, config/src/test/java/org/springframework/security/config/oauth2/client/CommonOAuth2ProviderTests.java
=> Add test and update Javadoc `CommonOAuth2Provider`

web/src/main/java/org/springframework/security/web/authentication/UsernamePasswordAuthenticationFilter.java
Remove the redundant punctuation marks in the comments.
=> Remove the redundant punctuation marks in the comments

config/src/main/java/org/springframework/security/config/annotation/method/configuration/AuthorizationProxyWebConfiguration.java
=> Publishing a default TargetVisitor should not override Spring MVC support

config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java
=> Update HttpSecurity javadoc to use authorizeHttpRequests

web/src/main/java/org/springframework/security/web/webauthn/management/Webauthn4JRelyingPartyOperations.java, web/src/test/java/org/springframework/security/web/webauthn/management/Webauthn4jRelyingPartyOperationsTests.java
This PR includes:
- Specific generic types
- Remove redundant null check
- Fix typos in test case
=> Polish Webauthn4JRelyingPartyOperations

config/src/main/java/org/springframework/security/config/SecurityNamespaceHandler.java, config/src/test/java/org/springframework/security/config/SecurityNamespaceHandlerTests.java
=> Simplify error message for unsupported Security XSD versions

core/src/main/java/org/springframework/security/core/annotation/ExpressionTemplateSecurityAnnotationScanner.java, core/src/main/java/org/springframework/security/core/annotation/ExpressionTemplateValueProvider.java
=> Polish javadoc
